apps/zotonic_core/src/models/m_identity.erl, apps/zotonic_mod_ratelimit/src/mod_ratelimit.erl
There is a timing difference between checking a password for valid usernames and invalid usernames.
The timing difference can be used to find valid usernames.
This change adds a timer around the pw check to make all pw checks about 300msec.
=> core: add timer on pw checks against timing attacks for finding valid usernames

modules/mod_ratelimit/mod_ratelimit.erl, src/models/m_identity.erl
There is a timing difference between checking a password for valid usernames and invalid usernames.
The timing difference can be used to find valid usernames.
This change adds a timer around the pw check to make all pw checks about 300msec.
=> core: add timer on pw checks against timing attacks for finding valid usernames (0.x)

modules/mod_video/mod_video.erl
Fix an issue with video preview if the archive directory has a space in its filename.
=> mod_video: escape filename for ffmpeg preview cmd (0.x)

modules/mod_base/controllers/controller_file.erl
Adds `default-src 'none'` to the Content-Security-Policy header for downloads/views of user uploaded files.
=> mod_base: more restrictive CSP header in controller_file (0.x)

apps/zotonic_mod_base/src/controllers/controller_file.erl
This makes displaying user uploaded content even more restrictive than the previous `sandbox` solution.
=> mod_base: set the CSP for files to: default-src 'none'; sandbox

modules/mod_authentication/controllers/controller_logoff.erl, modules/mod_authentication/controllers/controller_logon.erl, modules/mod_base/controllers/controller_user_agent_select.erl, modules/mod_translation/controllers/controller_language_set.erl, src/support/z_context.erl
This adds a check on all `p` and `page` arguments of various controllers to ensure that the redirect is a redirect to a local URL.
This does not break code that is redirecting within the site.
After review the code in master should also be checked and the `z_context:site_url/2` routine converted for master.
=> Filter the redirect args of logon/logoff to ensure that it is a local redirect

apps/zotonic_mod_authentication/src/controllers/controller_logoff.erl
The redirect url was checked to be a local url, so this check is mostly to ensure proper percent encoding,
=> mod_authentication: ensure that logoff redirect url is sanitized.

apps/zotonic_mod_base/priv/templates/_pager.tpl, apps/zotonic_mod_base/src/scomps/scomp_base_pager.erl
The `...` in the pager looks clickable, but has the URL `#`, which can affect some search forms.
This changes the `...` into a clickable URL that is the last page nr + 1.
See also #3120
=> mod_base: make the ... in the page clickable.

apps/zotonic_core/src/markdown/markdown.erl, apps/zotonic_core/src/markdown/z_html2markdown.erl, apps/zotonic_core/src/markdown/z_markdown.erl
This fixes a problem with UTF-8 characters in certain positions and removes obsolete string functions.
=> core: adapt markdown for utf8 and modern string functions.

apps/zotonic_mod_editor_tinymce/priv/lib/js/tinymce-5.10.2/tiny-init.js, apps/zotonic_mod_editor_tinymce/priv/lib/js/tinymce-5.10.2/tinymce/plugins/zanchor/plugin.min.js
This add the `zanchor` plugin to make anchor tags (`<a name="foo">`).
The `zanchor` is an adapted version of `anchor` where `id` has been replaced with `name`.
This because the Zotonic sanitizer removes `id` attributes but keeps `name` attributes.
=> mod_editor_tinymce: add zanchor plugin

modules/mod_base/scomps/scomp_base_pager.erl, modules/mod_base/templates/tablet/_pager.tpl
Add link to pager ellipsis to conveniently skip forward or backward, in response to findings during zotonic upgrade
testing: Although the ellipsis entries in the pager are marked as disabled in the current version, if you click on it,
it resets the pager to the first page.
Checking on `sep` maintains backward compatibility in the pager template, though I would say the that the form
`{undefined, sep}` doesn't occur anymore after this patch.
Also, the cases of IsEstimate are probably collapsed because the total number currently always is an estimate?
This seems to go wrong (no ellipsis to the right where we would expect one in the case where there still are next pages) now; this should probably go into a separate issue.
=> mod_base: Pager ellipsis link (0.x)

modules/mod_authentication/mod_authentication.erl
The parameter order for a call to `m_identity:set_by_type/5` was incorrect.
=> mod_authentication: Fix parameter order in call to identity set by type

apps/zotonic_core/src/support/z_logger_formatter.erl
In the logger, if a string contained non Latin-1 characters then the string was displayed as a binary.
This changes that behavior to show all strings that are valid unicode as strings.
=> core: in logger show unicode binaries as strings

apps/zotonic_core/src/support/z_memo.erl, apps/zotonic_core/src/support/z_tags.erl, apps/zotonic_mod_import_csv/src/mod_import_csv.erl
This addresses [the issue mentioned on Slack](https://erlanger.slack.com/archives/C0SEMDD36/p1665592350066809), i.e. doc chunk generation with `rebar3 ex_doc` not working as expected. I'm not including `rebar3_ex_doc` in `rebar.config`, but the patch I tested with is just:
```
diff --git a/rebar.config b/rebar.config
index efd2bb3af..d117d883b 100644
--- a/rebar.config
+++ b/rebar.config
@@ -33,3 +33,5 @@
% no_return
]}
]}.
+
+{project_plugins, [rebar3_ex_doc]}.
```
=> Fix -include{,_lib} attributes to unbreak doc chunk generation

.github/workflows/publish.yml
Add option to manually publish the current version to Hex.
This is needed for cases where the automatic publish is not triggered.
=> workflows: add manual trigger for publish workflow

apps/zotonic_mod_admin/priv/templates/_admin_overview_list.tpl
This adds a column with the publication_start date to the admin overview list table.
=> mod_admin: add column published-on to overview list table

apps/zotonic_mod_translation/priv/templates/_html_head_translation.tpl, apps/zotonic_mod_translation/src/models/m_translation.erl
Set the x-default language to the `en` version, if available.
This used to be `x-none` (no language) resulting in an URL without language code.
But Google wouldn't index the page without language code, as all those pages have a canonical with language code.
The idea is to direct "other languages" Google users to the `en` version and have them select a translation from there.
=> mod_translation: change x-default url to use 'en'

apps/zotonic_mod_base/src/controllers/controller_static_pages.erl
Fix a problem where controller_static_pages did not accept the `{files, ...}` root option.
=> zotonic_mod_base: fix for controller_static_pages with {files, ...} root

apps/zotonic_mod_admin_frontend/priv/lib/js/modules/admin-frontend.js, apps/zotonic_mod_admin_frontend/priv/templates/_admin_frontend_edit.tpl, apps/zotonic_mod_admin_frontend/src/mod_admin_frontend.erl
This allows to make links like: `/edit/1234#edit_id=456&tab=sometab`
This opens the editor for 456 (with tree 1234) and selects the given tab.
=> mod_admin_frontend: support linking to specific tab in edit page

src/db/z_db.erl, src/support/z_datamodel.erl, src/support/z_file_entry.erl, src/support/z_module_manager.erl, src/support/z_notifier.erl
Some queries and processes didn't have their lager metadata set.
This made it harder to see which site any message belonged to.
Also add info message when a module/site's datamodel is installed.
=> core: ensure that lager metadata is set for spawned processes and queries

src/support/z_search.erl
This fixes a problem where the search crashed if `undefined` was passed for the page length.
=> core: in search allow undefined for pagelen. Issue #3171

apps/zotonic_mod_seo_sitemap/src/models/m_seo_sitemap.erl
Fix #3157
Resources with a `website` and `is_website_redirect` are redirecting on page visit and should not be in the sitemap.
This updates excludes such resources from the sitemap.
=> mod_seo_sitemap: exclude resources with a redirect from sitemap.

modules/mod_search/support/search_query.erl, src/models/m_edge.erl, src/support/z_search.erl
This helps the query optimizer to analyze the query.
=> core: in sql use 'any' instead of 'select unnest'

apps/zotonic_mod_video_embed/src/mod_video_embed.erl
Fixes a problem with fetching the video id from illegal vimeo links
=> mod_video_embed: fix a problem where embed could crash on illegal vimeo links

apps/zotonic_core/src/models/m_edge.erl, apps/zotonic_core/src/support/z_search.erl, apps/zotonic_mod_acl_user_groups/src/support/acl_user_groups_checks.erl, apps/zotonic_mod_admin_category/src/mod_admin_category.erl, apps/zotonic_mod_admin_predicate/src/mod_admin_predicate.erl, apps/zotonic_mod_search/src/support/search_query.erl
This helps the query planner analyzing the query.
=> core: use SQL 'any' instead of 'unnest'

apps/zotonic_mod_survey/src/mod_survey.erl
This fixes a problem with pre-filling answers using the user's properties.
=> mod_survey: set answer_user_id to user if not editing existing answer

apps/zotonic_mod_authentication/priv/lib/js/zotonic.auth-ui.worker.js
This fixes a problem where 2FA enabled accounts could not reset their password.
After the new password was entered the view changed to logon, making it impossible to reset the password.
=> mod_authentication: fix a problem with pw reset for 2FA enabled accounts

apps/zotonic_core/src/models/m_media.erl
Fixes an issue where mod_clamav could crash on m_media insert calls with a string as filename.
=> core: ensure that the media filename is always a binary

apps/zotonic_mod_wires/priv/lib/js/apps/zotonic-wired.js, doc/ref/actions/action_typeselect.rst
Fix #3192 3192
Removes the two character limit on type select searches. As a result, previously found resources are removed when there is no input.
=> mod_wires: Remove 2 char limit on typeselect search

apps/zotonic_mod_admin/priv/templates/blocks/_admin_edit_block_li_header.tpl, apps/zotonic_mod_admin/priv/templates/blocks/_admin_edit_block_li_text.tpl, apps/zotonic_mod_base/src/filters/filter_trans_filter_filled.erl, apps/zotonic_mod_base/src/filters/filter_translation.erl, apps/zotonic_mod_survey/priv/templates/_admin_block_test_feedback.tpl, apps/zotonic_mod_survey/priv/templates/_admin_survey_edit_email_text.tpl, apps/zotonic_mod_survey/priv/templates/_admin_survey_edit_feedback.tpl, apps/zotonic_mod_survey/priv/templates/blocks/_admin_edit_block_li_survey_button.tpl, apps/zotonic_mod_survey/priv/templates/blocks/_admin_edit_block_li_survey_category.tpl, apps/zotonic_mod_survey/priv/templates/blocks/_admin_edit_block_li_survey_country.tpl, apps/zotonic_mod_survey/priv/templates/blocks/_admin_edit_block_li_survey_hidden.tpl, apps/zotonic_mod_survey/priv/templates/blocks/_admin_edit_block_li_survey_likert.tpl, apps/zotonic_mod_survey/priv/templates/blocks/_admin_edit_block_li_survey_long_answer.tpl, apps/zotonic_mod_survey/priv/templates/blocks/_admin_edit_block_li_survey_matching.tpl, apps/zotonic_mod_survey/priv/templates/blocks/_admin_edit_block_li_survey_multiple_choice.tpl, apps/zotonic_mod_survey/priv/templates/blocks/_admin_edit_block_li_survey_narrative.tpl, apps/zotonic_mod_survey/priv/templates/blocks/_admin_edit_block_li_survey_short_answer.tpl, apps/zotonic_mod_survey/priv/templates/blocks/_admin_edit_block_li_survey_thurstone.tpl, apps/zotonic_mod_survey/priv/templates/blocks/_admin_edit_block_li_survey_truefalse.tpl, apps/zotonic_mod_survey/priv/templates/blocks/_admin_edit_block_li_survey_upload.tpl, apps/zotonic_mod_survey/priv/templates/blocks/_admin_edit_block_li_survey_yesno.tpl, doc/ref/filters/filter_trans_filter_filled.rst, doc/ref/filters/filter_translation.rst, doc/ref/filters/translation/index.rst
This fixes an issue with displaying texts using the construct `foo[lang_code]` where `foo` will be assumed to be resource uri if it is a binary.
=> mod_base: add filter translation

apps/zotonic_mod_search/src/support/search_query.erl
* mod_search: fix sorting for custom pivot
Fix #[3198]
Prepend "pivot_" to table name instead of column name
=> mod_search: fix sorting for custom pivot (#3198)

apps/zotonic_mod_admin/priv/templates/_admin_edit_content_date_range.tpl, apps/zotonic_mod_admin/priv/templates/_admin_edit_content_pub_period.tpl, apps/zotonic_mod_admin/priv/templates/_admin_edit_sidebar_parts.tpl, apps/zotonic_mod_admin/priv/templates/_edit_date.tpl, apps/zotonic_mod_l10n/priv/templates/_admin_edit_content_timezone.tpl
This adds a panel with which the page's `tz` property can be edited.
This also makes the `_edit_date.tpl`  time zone aware.
=> mod_admin: Add optional editing of the page's time zone

apps/zotonic_mod_admin/priv/templates/_admin_edit_content_advanced.tpl, apps/zotonic_mod_admin/src/controllers/controller_admin_edit.erl, apps/zotonic_mod_base/src/controllers/controller_page.erl, apps/zotonic_mod_base/src/filters/filter_urldecode.erl, doc/ref/filters/filter_urldecode.rst, doc/ref/filters/filter_urlencode.rst, doc/ref/filters/urls/index.rst
This could happen if a resource has a page path with a space (encoded as %20). The reconstitution of the page path did not account for non url-safe characters.
=> mod_base: Fix an issue where controller_page could enter in a redirect loop.

apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_core/src/install/z_install.erl, apps/zotonic_core/src/install/z_install_update.erl, apps/zotonic_core/src/support/z_module_indexer.erl, apps/zotonic_mod_admin/priv/templates/_admin_edit_content_advanced.tpl, apps/zotonic_mod_search/src/support/search_query.erl, doc/developer-guide/search.rst, doc/ref/notifications/notification/meta-search_query.rst, doc/ref/notifications/notification/meta-search_query_term.rst, doc/ref/notifications/notification/search_query_term.rst, doc/ref/notifications/other.rst
Add the resource property `is_unfindable`
This can be used to hide pages from search queries.
For this to work the query must add the term `is_findable`
Also add support for custom query terms using the notification `#search_query_term{}`.
This observer must return either `undefined`, the empty list, or a `search_sql_term{}` record.
=> mod_search: add is_unfindable and custom query terms

modules/mod_acl_user_groups/support/acl_user_groups_checks.erl, modules/mod_search/support/search_query.erl
Also use '= true/false' for is_published checks, as that helps with picking the correct index values
=> mod_acl_user_groups: use psql 'any' instead of nested query (0.x)

apps/zotonic_mod_search/src/support/search_query.erl
The wrong table was linked.
Added extra logging to notify if a filter term could not be added.
=> mod_search_query: fix a problem with filtering facets

apps/zotonic_mod_admin_identity/priv/templates/email_admin_new_user.tpl, apps/zotonic_mod_admin_identity/src/actions/action_admin_identity_dialog_user_add.erl, apps/zotonic_mod_mailinglist/src/models/m_mailinglist.erl
This fixes a problem where sending the user-creation email might be too early with the propagation of the new user details.
This is fixed by moving the email outside the transaction.
Also modify the new-user-email for the case the new user does not have access to the admin.
=> mod_admin: better user create email, fix race condition

apps/zotonic_mod_admin/priv/templates/_admin_edit_content_address.tpl, apps/zotonic_mod_admin/priv/templates/_admin_edit_content_note.tpl, apps/zotonic_mod_admin/priv/templates/_admin_edit_content_note_inner.tpl, apps/zotonic_mod_admin/priv/templates/_admin_edit_header.tpl, apps/zotonic_mod_admin/priv/templates/_admin_edit_sidebar_parts.tpl, apps/zotonic_mod_admin/priv/templates/_dialog_admin_rsc_note.tpl, apps/zotonic_mod_admin/src/mod_admin.erl, apps/zotonic_mod_admin/src/models/m_admin_note.erl, apps/zotonic_mod_mailinglist/priv/templates/_admin_edit_sidebar.tpl, apps/zotonic_mod_mailinglist/src/support/z_mailinglist_recipients.erl, doc/ref/models/model_admin_note.rst
This adds a notes field to the admin that is only visible for admin users that can edit the resource.
Also add an optional mailinglist opt-out flag.
=> mod_admin: add admin notes; mailinglist opt out

apps/zotonic_core/src/smtp/z_email.erl, apps/zotonic_mod_acl_user_groups/src/support/acl_user_groups_checks.erl
This fixes an issue where an email needed to be sent using sudo permission.
=> core: allow send to recipient-id email address if recipient is visible.

apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_mod_acl_user_groups/src/support/acl_user_groups_checks.erl, doc/ref/notifications/acl.rst, doc/ref/notifications/notification/acl_user_groups_modify.rst, doc/ref/notifications/notification/meta-acl_user_groups_modify.rst
This adds the option to dynamically add user groups, for example if an user has some sort of subscription or followed a special link.
=> mod_acl_user_groups: add notification to update an user's user groups on lookup

apps/zotonic_mod_mailinglist/priv/templates/_admin_mailing_status_overview.tpl
Only the default pagelen of 20 mailinglists were shown when sending a mailing.
=> mod_mailinglist: fix an issue where not all mailinglists were shown on the mailing page.

apps/zotonic_core/src/support/z_pivot_rsc_job.erl
This fixes an issue where the pivot process could insert a repivot for an event due to the even having a due date. If this due date was in the past then the pivot could re-insert an immediate pivot request for the resource it was already pivoting. Thus ending in a pivot loop.
=> core: Fix an issue where the pivot could loop on some events

apps/zotonic_core/src/db/z_db.erl, apps/zotonic_core/src/models/m_edge.erl
Previously those functions only accepted resource ids, not names.
Also add more specs to the m_edge routines.
=> core: in m_edge be more flexible about subject/object

apps/zotonic_core/src/support/z_pivot_rsc.erl, apps/zotonic_mod_admin/priv/templates/_admin_status_update_pivot_count.tpl, apps/zotonic_mod_admin/src/models/m_admin.erl
This is fixed by making a distinction between the 'backlog' pivots and the scheduled pivots.
=> mod_admin: fix a problem where scheduled re-pivots disabled the button 'Rebuild search indices'

modules/mod_admin_identity/dispatch/admin_dispatch, modules/mod_admin_identity/templates/_admin_edit_content_address_email.person.tpl, modules/mod_admin_identity/templates/_admin_edit_sidebar.person.tpl
This limits access to user info data in admin templates to users with mod_admin_identity usage rights.
=> mod_admin_identity: Require module use rights to view user info data

apps/zotonic_core/src/models/m_modules.erl, apps/zotonic_core/src/support/z_module_manager.erl, apps/zotonic_mod_admin_modules/priv/templates/admin_modules.tpl, apps/zotonic_mod_filestore/priv/templates/admin_filestore.tpl
Add `z_module_manager:mod_info/1` to obtain information about a module.
Show version of modules in admin/modules list.
After this has been merged we can port it back to the 0.x
=> mod_admin_modules: show version of modules in modules overview

apps/zotonic_mod_translation/src/filters/filter_translate.erl, apps/zotonic_mod_translation/test/mod_translation_tests.erl, doc/ref/filters/filter_translate.rst, doc/ref/filters/filter_translation.rst, doc/ref/filters/filter_translations.rst, doc/ref/filters/strings/index.rst
Filter to translate texts using the translations in the .po file.
=> mod_translation: add translate filter

apps/zotonic_core/src/models/m_rsc_update.erl, apps/zotonic_core/src/models/m_search.erl, apps/zotonic_core/src/support/z_search.erl, apps/zotonic_core/src/support/z_search_terms.erl, apps/zotonic_mod_search/src/support/search_query.erl
Fix #3232 
Fixes an issue where using the `cat_exact` query term could result in an error.
Fixes an issue where custom query terms could crash the search.
=> mod_search: fix cat_exact and more robust against errors in queries

apps/zotonic_core/src/models/m_rsc_import.erl
When importing a resource the `name` was passed to the `m_rsc:rid/2` routine, which could then match local authoritative resources.  With the correct options and access rights this could result overwriting locally defined resources with the newly imported resource.
=> core: Fix for importing resources where unique name was used to find resources

src/support/z_module_manager.erl
This fixes an issue where in-memory caches could get corrupted due to a rollback during scheme install.
Fixes #3164
=> core: flush caches if rollback happens during module schema install.

modules/mod_admin/models/m_admin_status.erl, modules/mod_admin/templates/admin.tpl, modules/mod_admin_modules/controllers/controller_admin_module_manager.erl, modules/mod_admin_modules/templates/_admin_modules_down_warning.tpl, modules/mod_admin_modules/templates/admin_modules.tpl
Fix #3045
Show a warning on the admin dashboard and modules pages when modules are not running.
=> mod_admin_modules: add warning if not all modules are running.

apps/zotonic_mod_video/src/support/z_video_preview.erl
The preview generation would crash because the dimensions of the video could not be fetched.
=> mod_video: fix a problem where preview generation would crash on audio-only videos.

doc/requirements.txt
[Alabaster](https://github.com/bitprophet/alabaster) is the default theme of Sphinx.
It is installed by Sphinx.
In alabaster version 0.7.13 the requirement for Sphinx 1.6 or higher was added.
Apparently Sphinx 1.5.3 doesn't fix the version of the default installed theme.
=> docs: fix build of docs

apps/zotonic_mod_seo/priv/templates/_html_head_seo.tpl, apps/zotonic_mod_translation/priv/templates/_html_head_seo.tpl, apps/zotonic_mod_translation/priv/templates/_html_head_translation.tpl, apps/zotonic_mod_translation/src/mod_translation.erl, apps/zotonic_mod_translation/src/models/m_translation.erl
* Add "/" as the x-default to the hreflang-cluster of the homepage
* Set canonical of "/" to itself instead of the translated language version
* Remove "noindex"-setting from "/"
https://hreflang.org/redirects-canonicals-cause-hreflang-problems/
=> mod_translation: better SEO handling of x-default language

doc/requirements.txt, modules/mod_seo/templates/_html_head_seo.tpl, modules/mod_translation/templates/_html_head_translation.tpl
When a page has translations, then noindex is set for the missing translations.
This to prevent "duplicate page" notifications from Google et al.
This change disables this behavior for the home page.
=> mod_seo: do not set home page to noindex on missing languages (0.x)

apps/zotonic_core/src/csv/z_csv_writer.erl
This fixes an issue with exports to "simple" CSV files where postal codes are prefixed with a `'` character.
Not all CSV import routines handle these quoted values well.
=> core: in z_csv_writer, do not escape all fields starting with a digit

apps/zotonic_core/src/models/m_search.erl
If there were no query arguments in the path then the `qargs` option was automatically added.
Now only add this if there is no payload (which contains query arguments).
=> core: in m_search only add qargs if the payload is empty

apps/zotonic_mod_survey/priv/templates/_admin_survey_editor_results.tpl, apps/zotonic_mod_survey/priv/templates/_dialog_survey_link_person.tpl, apps/zotonic_mod_survey/priv/templates/_dialog_survey_link_person_new.tpl, apps/zotonic_mod_survey/src/mod_survey.erl, apps/zotonic_mod_survey/src/models/m_survey.erl, apps/zotonic_mod_survey/src/support/survey_admin.erl, apps/zotonic_mod_survey/src/support/survey_schema.erl, doc/ref/modules/mod_survey.rst
In the survey results editor we now show which user submitted the survey (if any).
There is also an option to create a new `person` using the entered answers or link to an existing person based on the entered email address, name or address.
=> mod_survey: in survey results editor show user and allow to link or create new person

src/support/z_search.erl
Fixes an issue where passing `undefined` for offset or limit gives an _arith_ error.
=> z_search: default pagelen for undefined limit

apps/zotonic_mod_search/src/support/search_query.erl, doc/developer-guide/search.rst
This adds support for some ACL modules that use the visible_for property.
=> mod_search: add search term to filter on visible_for property

apps/zotonic_mod_wires/src/actions/action_wires_form_reset.erl
This fixes an issue where tinymce forms were not reset using the reset action.
=> mod_wires: use form reset from zotonic-wired.js

apps/zotonic_mod_admin/priv/templates/_admin_query_preview.tpl, apps/zotonic_mod_admin/src/controllers/controller_admin_edit.erl, apps/zotonic_mod_mailinglist/priv/templates/_admin_edit_content.mailinglist.tpl, apps/zotonic_mod_mailinglist/src/models/m_mailinglist.erl, apps/zotonic_mod_survey/priv/templates/_admin_survey_editor_results.tpl, apps/zotonic_mod_survey/priv/templates/_admin_survey_results_charts.tpl, apps/zotonic_mod_survey/priv/templates/_admin_survey_results_tab.tpl, apps/zotonic_mod_survey/priv/templates/_dialog_survey_mailinglist.tpl, apps/zotonic_mod_survey/src/mod_survey.erl, apps/zotonic_mod_survey/src/support/survey_admin.erl
This adds an option in the "results" tab of a survey to add all survey participants to a mailinglist.
The mailinglist can be newly created or an existing mailinglist.
=> mod_survey: option to add survey participants to mailing list

apps/zotonic_mod_mailinglist/src/models/m_mailinglist.erl
Fixes the email normalization when checking if an email address is subscribed.
=> mod_mailinglist: fix email normalization in recipient_status/3

shell.nix
This is used in zotonic-0.x/zotonic/src/scripts/helpers/zotonic_setup
=> Add ps to shell.nix

shell.nix
This allows the Nix package set used in `shell.nix` to be overridden.
=> Allow the nix package set to be overridden

apps/zotonic_mod_base/src/scomps/scomp_base_pager.erl
For search pages with a resource having a `page_path` but without a special dispatch rule the `page` dispatch rule could be generated for the numbered pages.
This fixes the issue and will use the `page_url` property for generating the page URLs if the dispatch rule is `page`.
=> mod_base: fix an issue in pager scomp where wrong page URLs could be generated

rebar.config.lock
This fixes an issue with the z_url_metadata where for some Youtube pages no metadata could be fetched due to the head of those pages being longer than 256KB.
=> Upgrade z_stdlib to 69e81d (0.x)

modules/mod_base/scomps/scomp_base_pager.erl
For search pages with a resource having a page_path but without a special dispatch rule the page dispatch rule could be generated for the numbered pages.
This fixes the issue and will use the page_url property for generating the page URLs if the dispatch rule is page.
0.x version of #3294
=> mod_base: fix an issue in page scomp where a wrong URL could be generated (0.x)

apps/zotonic_core/src/models/m_edge.erl, apps/zotonic_core/src/support/z_edge_log_server.erl
Two changes:
* Ensure edge log server gets polled after edge sequence changes
* Deduplicate edge change MQTT notifications
=> m_edge: flush edge log after edge seq changes

apps/zotonic_core/src/support/z_lib_include.erl, doc/ref/tags/tag_lib.rst
This PR adds `defer` argument to the `lib` tag.
The `defer` first will download the script file and then wait for HTML parsing. In other words, the script will execute after `domInteractive` and before `domContentLoaded` events.
**NOTE**
The `async` argument was changed to always set also the defer, as specified by the [W3 documentation](https://www.w3.org/TR/2011/WD-html5-20110525/scripting-1.html#attr-script-async):
> The [defer](https://www.w3.org/TR/2011/WD-html5-20110525/scripting-1.html#attr-script-defer) attribute may be specified even if the [async](https://www.w3.org/TR/2011/WD-html5-20110525/scripting-1.html#attr-script-async) attribute is specified, to cause legacy Web browsers that only support [defer](https://www.w3.org/TR/2011/WD-html5-20110525/scripting-1.html#attr-script-de …
=> Add defer argument to lib tag

apps/zotonic_core/src/support/z_crypto.erl, apps/zotonic_core/src/support/z_media_tag.erl, apps/zotonic_core/src/support/z_render.erl, apps/zotonic_core/src/support/z_utils.erl, apps/zotonic_core/src/support/z_validation.erl, apps/zotonic_mod_acl_user_groups/src/models/m_acl_rule.erl, apps/zotonic_mod_auth2fa/src/models/m_auth2fa.erl, apps/zotonic_mod_auth2fa/src/support/z_auth2fa_qrcode_demo.erl, apps/zotonic_mod_authentication/src/controllers/controller_authentication.erl, apps/zotonic_mod_authentication/src/models/m_authentication.erl, apps/zotonic_mod_base/src/filters/filter_pickle.erl, apps/zotonic_mod_facebook/src/mod_facebook.erl, apps/zotonic_mod_wires/src/scomps/scomp_wires_draggable.erl, apps/zotonic_mod_wires/src/scomps/scomp_wires_droppable.erl, apps/zotonic_mod_wires/src/scomps/scomp_wires_sortable.erl, apps/zotonic_mod_wires/src/scomps/scomp_wires_sorter.erl, apps/zotonic_mod_wires/src/support/z_transport.erl
The postback payloads and image URLs were signed using md5.
As that algorithm has known weaknesses this changes it to hmac-sha256. 
The encoding is also changed from hex to base64url.
Old image URLs will be invalid after this change. Unless the image URL only uses a mediaclass, in which case the URL is still valid as there isn't a signature in those URLs.
=> core: change the signature algorithm for payloads to hmac-sha256

modules/mod_cookie_consent/lib/js/z.cookie_consent.js
This allows strict frontend frameworks like Elm to replace the `<script>` with some other element and still have it work. Ideally, we would use a `<template>` instead of a `<script>`, but that also causes problems in Elm at the moment: https://github.com/elm/virtual-dom/issues/185
=> Make mod_cookie_consent selector slightly more general

apps/zotonic_mod_base/priv/lib/js/modules/z.dialog.js, doc/ref/actions/action_dialog.rst
This PR adds the `keyboard` option to prevent dialog closing by pressing the escape key.
Reference: https://getbootstrap.com/docs/4.4/components/modal/#options
=> Add keyboard to dialog options

apps/zotonic_mod_search/src/support/search_facet.erl
Changed type from "float" to "double precision" when creating
search_facet table as this is what postgresql returns.
Fixes comparison error at search_facet table creation due to mismatch  between search_facet "native" type (float) and sql column type (double precision). 
Tested by adding .._float type to facet.tpl template and successfully generating table with double precision column.
=> mod_search: Fix mismatch between sql and facet float type

modules/mod_logging/mod_logging.erl
This removes logging of the pool usage to the db log.
Especially on slow(er) databases we can expect a lot of db pool messages.
If the pool is really exhausted then we will see crashing queries.
=> mod_logging: be less vocal about the database pool usage (0.x)

src/models/m_rsc_update.erl
Do not throw an exception, as this expectation should be programmatically handled.
=> core: on rsc update error for expected version, return error (0.x)

apps/zotonic_core/src/support/z_fetch.erl
The "args" are encoded as a query string for 'get' requests.
Also support various content types for the payload.
=> core: support query arguments for z_fetch with method get

apps/zotonic_mod_translation/src/mod_translation.erl, apps/zotonic_mod_wires/priv/lib/js/apps/zotonic-wired.js
Fix #2347
When you don't use the url rewrite method to change the language, zotonic relies on the `z.lang` cookie. This cookie was not changed when a language switch is made. 
I updated the `z_reload` function from `zotonic-wired.js` to also change the language cookie when the language switch happens.
=> Change the language setting by changing the z.lang cookie setting

apps/zotonic_mod_l10n/priv/templates/_l10n_timezone_options.tpl
Removed unused `with` in timezone select template. This confused me quite a bit as I assumed the template used `id` instead of `timezone`.
=> mod_l10n: Remove unused `with` tag

src/db/z_db.erl, src/support/z_pivot_rsc.erl
On a race condition a duplicate task could be inserted.
This makes the error less vocal and returns the id of the task that already exists.
=> core: on insert of duplicate task, handle error more gracefully (0.x)

GNUmakefile, apps/zotonic_launcher/src/command/zotonic_release.erl, apps/zotonic_mod_admin/src/models/m_admin_status.erl
Fix #3329
Instead of running the command to install bash completions, which can fail when you are not a bash user and can be mistaken to be a compilation failure. Show a reassuring message containing the version number when the build is done.
```
$ make
/rebar3  compile
===> Verifying dependencies...
...
...
===> Compiling zotonic_mod_admin_config
===> Compiling zotonic_mod_custom_redirect
===> Compiling zotonic_mod_ssl_letsencrypt
Zotonic 1.0.0-rc.15 [Erlang/OTP 26.0-rc1] was successfully compiled
```
**Note** The bash completions are not installed automatically now.
=> Added a otp and zotonic version number message to make all

apps/zotonic_core/src/models/m_identity.erl
The expires should be reset if the username/pw is reset.
=> core: on reset password als reset identity expires date

src/models/m_rsc_update.erl
Old values might be in the process dictionary cache, which might result in a repeated try with out of date values.
If an expectation fails, then flush the cached resource to force an update from the database.
=> core: on rsc update expect error, flush resource cache

apps/zotonic_mod_admin/priv/templates/_admin_edit_content_address.tpl, apps/zotonic_mod_admin/priv/templates/admin_status.tpl, apps/zotonic_mod_admin/src/filters/filter_temporary_rsc.erl, apps/zotonic_mod_admin_predicate/priv/templates/_admin_edit_content.predicate.tpl
- Set `is_temporary` for resources that are still temporary, reset after an hour if resource has been updated
- Add billing address to address edit form
- Add `is_insert_before` checkbox to predicate edit page
=> mod_admin: filter temporary_rsc set is_temporary (and other changes)

apps/zotonic_mod_base/src/filters/filter_sort.erl, doc/ref/filters/filter_sort.rst
Fix #3351
Add sorting of lists of maps to the sort filter
=> base: sort filter can now sort lists of maps

apps/zotonic_core/src/models/m_rsc_update.erl
This fixes an issue where a process repeatedly trying to update a resource because the process has cached an out-of-date version of the resource.
=> core: on rsc update expect error, flush cache

apps/zotonic_core/src/models/m_rsc_update.erl, apps/zotonic_core/src/support/z_datetime.erl
Use sensible defaults if 'undefined' dates are passed to the publication date range.
- ST_JUTTEMIS for publication_end
- 1970-01-01 for publication_start
=> core: allow update of publication_start and _end with 'undefined'

.github/workflows/dialyzer.yml, .github/workflows/elvis.yml, .github/workflows/publish.yml, .github/workflows/test.yml
v2 is using a deprecated node version
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> ci: use git checkout@v3

apps/zotonic_core/include/zotonic.hrl, apps/zotonic_core/include/zotonic_deprecated.hrl, apps/zotonic_core/include/zotonic_wired.hrl, apps/zotonic_core/src/support/z_multipart_parse.erl
The wired events will be deprecated, but not soon.
=> core: move the wired record definitions to a separate include file

src/models/m_rsc_update.erl, src/support/z_acl.erl
The ACL cache now gets flushed after a resource update. Whether a resource is visible or not depends on the `is_published` property (and possibly other's if a site does custom ACL) which may change with an update.
=> Flush ACL cache on resource update

apps/zotonic_core/src/models/m_rsc_update.erl, apps/zotonic_core/src/support/z_acl.erl
=> core: flush ACL cache on resource update

modules/mod_acl_user_groups/models/m_acl_rule.erl
This allows acl rules with a string like `<<"view,update">>` in the `actions` prop to be inserted through the `m_acl_rule:insert` function.
=> Allow inserting acl rules with action strings

modules/mod_acl_user_groups/support/acl_user_groups_checks.erl
The documentation gives [an example](https://zotonic.com/docs/1752/mod_acl_user_groups) for deny rules where permissions on a specific collaboration group are denied with a deny ACL rule, but this does not actually work.
The reason is that the function for checking if there was an ACL rule that grants permissions for all collaboration groups did not check if one was excluded by a deny rule.
Deny rules for collaboration groups still work a bit differently from deny rules on specific categories, though.
Deny rules on specific categories work for all child user groups, while deny rules on specific collaboration groups only work if the rule that grants access is in the same user group.
=> Fix deny rules for specific collaboration groups (0.x)

apps/zotonic_core/src/support/z_pivot_rsc.erl
Fix #3372
When the task queue process receives a task queue, it triggers another poll. By doing this other due tasks are run more quickly.
=> core: Trigger a poll when  task_done is received

apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_core/src/db/z_db_pgsql.erl, apps/zotonic_core/src/install/z_install_update.erl, apps/zotonic_mod_admin/priv/templates/_admin_edit_content_address.tpl, apps/zotonic_mod_survey/src/mod_survey.erl, doc/ref/notifications/acl.rst, doc/ref/notifications/notification/acl_collab_groups_modify.rst, doc/ref/notifications/notification/meta-acl_collab_groups_modify.rst, doc/ref/notifications/notification/meta-survey_is_allowed_results_download.rst, doc/ref/notifications/notification/meta-survey_is_submit.rst, doc/ref/notifications/notification/meta-survey_result_header.rst, doc/ref/notifications/notification/meta-survey_result_row.rst, doc/ref/notifications/notification/meta-survey_submit.rst, doc/ref/notifications/notification/survey_result_header.rst, doc/ref/notifications/notification/survey_result_row.rst, doc/ref/notifications/survey.rst
Add a notification on survey submit.
This enables the survey module to integrate with payment modules or other dynamic handling modules.
Also some small logging changes in the core.
=> mod_survey: add notifications on survey submit

apps/zotonic_mod_survey/src/models/m_survey.erl, apps/zotonic_mod_survey/src/support/survey_admin.erl
Fix a problem where the survey results could not be sorted on a column.
This changes the return value of:
* `m_survey:get_results/3`
* `m_survey:get_results_sorted/3`
To enable the type checks by Dialyzer.
=> mod_survey: fix results sorted on a column

apps/zotonic_core/src/support/z_media_tag.erl, apps/zotonic_core/src/support/z_mediaclass.erl
This adds:
* functions to fetch all mediaclasses defined in a site or module
* z_media_tag:attributes/3 function to fetch all the attributes that would be added to a image tag
Note that this changes the mediaclass index, a hot-code upgrade can't be done.
=> core: add fetch of mediaclasses per module and media tag attributes

apps/zotonic_mod_mailinglist/src/models/m_mailinglist.erl
An error in a filter caused non-admin users to not see their subscriptions.
=> mod_mailinglist: fix a problem with listing subscriptions for unsubscribe

apps/zotonic_core/src/models/m_identity.erl, apps/zotonic_mod_admin_identity/priv/templates/_admin_identity_email.tpl
Also add a max-width to the email-entry input box.
This brings the 'Add' button better into view.
=> core: add extra 'is_email_verified' api call for other users/ids

apps/zotonic_core/src/support/z_context.erl, apps/zotonic_core/src/support/z_dispatcher.erl
Fix #3383
Adds the function `is_hostname_redirect_configured/1` to the context to check if the current site always wants redirects to the preferred hostname.
When this is not the case and an absolute url is requested from a context with a request, the hostname of the request is used as hostname to create an absolute url with.
=> core: Do not generate absolute urls from the preferred hostname when redirect is false

apps/zotonic_mod_seo_sitemap/priv/templates/_admin_edit_content_seo_extra.tpl, apps/zotonic_mod_seo_sitemap/src/models/m_seo_sitemap.erl
Previously the priority and the changefreq was set per category only.
This adds the same options for a single page.
=> mod_seo_sitemap: add option to set priority and changefreq per page

apps/zotonic_mod_admin/priv/templates/_admin_edit_content_person.tpl, apps/zotonic_mod_base/src/filters/filter_escapejs.erl
The escapejs returns a list, which is now interpreted as a string with unicode characters, instead of a utf8 byte stream.
=> mod_base: fix a problem with js_escape and utf8 texts

apps/zotonic_mod_survey/priv/templates/_admin_survey_settings_tab.tpl, apps/zotonic_mod_survey/priv/templates/_survey_question_page.tpl, apps/zotonic_mod_survey/priv/templates/survey.tpl
The `survey_is_disabled` flag was already available in the 0.x but not present as a choice in the settings for 1.x.
This adds this option and some feedback, it also allows editors to still proceed with the survey.
=> mod_survey: make the survey_is_disabled flag available

apps/zotonic_core/priv/translations/zotonic.pot, apps/zotonic_core/src/models/m_rsc_gone.erl, apps/zotonic_mod_backup/priv/templates/admin_backup_deleted.tpl, apps/zotonic_mod_backup/src/controllers/controller_admin_backup_revision.erl, apps/zotonic_mod_backup/src/models/m_backup_revision.erl
Also delete the rsc_gone row after recovery of a resource.
=> mod_backup: show follow up id in list of deleted pages

apps/zotonic_mod_oembed/src/support/oembed_providers.erl
Add spotify to the list of oembed providers.
See also #3403
=> mod_oembed: add support for spotify

src/support/z_mediaclass.erl
Validate mediaclasses have simple names.
This fixes a problem where invalid URLs for the file storage could be generated.
=> core: validate mediaclass names

apps/zotonic_core/src/install/z_install_update.erl
Tried to migrate from version 0.34.0 to master , couldn't start the site due to missing fki_comment_persistent_id index. Added a check for the existence of an index
When trying to rename the fki_comment_persistent_id index in the comment table, added an index check.
=> core: z_install_update checking index before renaming

apps/zotonic_core/src/smtp/z_email_embed.erl, apps/zotonic_core/src/support/z_media_data.erl
Fix a problem where sending a mailing could result in invisible images if the images were not public and the option to not embed images was set.
Fixed by always embedding non public images (if their size is below the threshold of 1MB).
=> core: force embed of non-public images in emails

apps/zotonic_core/src/models/m_rsc_update.erl, apps/zotonic_core/src/support/z_media_preview.erl, apps/zotonic_core/test/z_media_preview_tests.erl
This adds a tinymce option to better combine ("deconstruct") the image sequence in a single animated image file.
Also a small fix to better flush caches on a rsc update.
=> core: optimize resized animated gif images

apps/zotonic_core/src/models/m_edge.erl, apps/zotonic_core/src/models/m_rsc.erl
This adds POST and DELETE handling to the `rsc` ~and `edge`~ models.
Note: remove m_edge changes, as #3395 is a more complete solution
=> core: add m_post and m_delete handlers to rsc model

apps/zotonic_core/src/support/z_render.erl, apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/less/dialog-new-connect.less, apps/zotonic_mod_admin/priv/lib/css/zotonic-admin.css, apps/zotonic_mod_admin/priv/templates/_action_dialog_connect.tpl, apps/zotonic_mod_admin_frontend/priv/templates/_admin_frontend_tinymce_init.tpl, apps/zotonic_mod_base/priv/lib-src/less/z.modal.less, apps/zotonic_mod_base/priv/lib/css/z.modal.css, apps/zotonic_mod_base/priv/lib/js/modules/z.dialog.js, apps/zotonic_mod_editor_tinymce/priv/lib/js/tinymce-5.10.2/tiny-init.js, apps/zotonic_mod_editor_tinymce/priv/lib/js/tinymce-5.10.2/tinymce/plugins/zlink/plugin.min.js, apps/zotonic_mod_editor_tinymce/priv/lib/js/tinymce-5.10.2/tinymce/plugins/zmedia/plugin.min.js, apps/zotonic_mod_editor_tinymce/priv/lib/js/tinymce-5.10.2/z_editor.js, apps/zotonic_mod_editor_tinymce/priv/templates/_editor.tpl, apps/zotonic_mod_editor_tinymce/src/mod_editor_tinymce.erl, apps/zotonic_mod_wires/priv/lib/js/apps/zotonic-wired.js, apps/zotonic_mod_wires/src/actions/action_wires_confirm.erl, apps/zotonic_mod_wires/src/actions/action_wires_dialog_close.erl, doc/ref/actions/action_alert.rst, doc/ref/actions/action_confirm.rst, doc/ref/actions/action_dialog.rst, doc/ref/actions/action_dialog_close.rst, doc/ref/actions/action_dialog_open.rst
This adds two distinct things:
* A `level` for dialogs, allowing opening dialogs from dialogs
* An option to select a editor configuration per tinyMCE editor, in addition to the global `tinyInit`
=> Multi-level dialogs and multiple tinyMCE configs

apps/zotonic_mod_survey/src/mod_survey.erl, apps/zotonic_mod_survey/src/questions/survey_q_button.erl, apps/zotonic_mod_survey/src/questions/survey_q_category.erl, apps/zotonic_mod_survey/src/questions/survey_q_country.erl, apps/zotonic_mod_survey/src/questions/survey_q_hidden.erl, apps/zotonic_mod_survey/src/questions/survey_q_likert.erl, apps/zotonic_mod_survey/src/questions/survey_q_long_answer.erl, apps/zotonic_mod_survey/src/questions/survey_q_matching.erl, apps/zotonic_mod_survey/src/questions/survey_q_multiple_choice.erl, apps/zotonic_mod_survey/src/questions/survey_q_narrative.erl, apps/zotonic_mod_survey/src/questions/survey_q_page_break.erl, apps/zotonic_mod_survey/src/questions/survey_q_short_answer.erl, apps/zotonic_mod_survey/src/questions/survey_q_stop.erl, apps/zotonic_mod_survey/src/questions/survey_q_thurstone.erl, apps/zotonic_mod_survey/src/questions/survey_q_truefalse.erl, apps/zotonic_mod_survey/src/questions/survey_q_upload.erl, apps/zotonic_mod_survey/src/questions/survey_q_yesno.erl
Pass the id of the survey to the `answer/4` function of the survey answer modules.
This makes it possible to check if an user is allowed to answer this kind of questions.
**NOTE** Existing question handling modules must be updated.
=> mod_survey: pass the survey-id to the question answer routines

apps/zotonic_mod_search/src/support/search_query.erl, doc/developer-guide/search.rst
Add a special language search code `z_language` which is mapped to the current Context language.
Also support searching for more than one language in stored queries:
```
cat='news'
sort=-publication_start
language=[en,z_language]
```
=> mod_search: support searching for the current z_language in stored queries

apps/zotonic_mod_admin_frontend/priv/templates/_admin_frontend_edit.tpl, apps/zotonic_mod_admin_frontend/priv/templates/_admin_frontend_tinymce_overrides_js.tpl
This will add a specific overrides template for the admin frontend edit. Also it removes the is_editor_include so the overrides are taken into account.
=> [admin_frontend] Add override specific template for frontend admin

apps/zotonic_core/src/support/z_search.erl, apps/zotonic_mod_base/src/scomps/scomp_base_pager.erl
If page 1000 of a search result with 100 pages was rendered then a pager with pages 999 and below could be rendered.
This prevents this situation by better estimating the number of pages on an empty search result and rendering a minimal pager with a link to page 1 for pages beyond the number of pages in the search result.
=> core: fix a problem where a pager with more pages than result pages could be rendered

apps/zotonic_mod_search/src/support/search_query.erl
Fix a problem where the following search did not work:
```
https://example.test:8443/api/model/search/get?cat=musician&facet.first_letter=C
```
This is because `facet.first_letter` is mapped to a map:
```erlang
#{ <<"facet">> => #{ <<"first_letter">> => <<"C">> } }
```
And the search routines do not recognize the search term `facet`, as normally it is `facet.facetname`.
This is solve by pickup up the map-value and then performing an `AND` query over all the facets mentioned in the map value.
=> mod_search: allow facet term with map as argument

doc/ref/models/model_site.rst
Fix #881
Removed unused session_expire_1 and session_expire_n from the documentation.
=> docs: Removed session_expire_1 and session_expire_n from documentation.

apps/zotonic_mod_search/src/support/search_query.erl, doc/developer-guide/search.rst
Add `hasanysubject` search term, which is the same as `hasanyobject` but then for subjects.
=> mod_search: add 'hasanysubject' search term

apps/zotonic_core/src/support/z_mqtt_sessions_runtime.erl, apps/zotonic_mod_ratelimit/src/mod_ratelimit.erl, apps/zotonic_mod_ratelimit/src/models/m_ratelimit.erl
This fixes an issue where repeated, successful logons could trigger a rate limit restriction.
This is fixed by deleting the ratelimit history for the username (and device) after a successful logon.
Also let MQTT use the `z_auth:logon/2` instead of `z_acl:logon/2` so that the correct events are triggered and the user is checked for being published.
Fixes #3442
=> Clear ratelimit history for username after successful logon. 

apps/zotonic_core/src/support/z_search.erl, apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/less/bootstrap-overrides.less, apps/zotonic_mod_admin/priv/lib/css/zotonic-admin.css, apps/zotonic_mod_admin/priv/templates/_admin_overview_list.tpl, apps/zotonic_mod_admin_identity/priv/templates/_admin_overview_list_page1.tpl, apps/zotonic_mod_base/src/filters/filter_round_significant.erl, apps/zotonic_mod_mailinglist/priv/templates/_admin_overview_list_page1.tpl, apps/zotonic_mod_mailinglist/src/models/m_mailinglist.erl
This moves the identity match to the identity module and adds a list of mailinglists subscriptions.
Also small fixes for the `round_significant` filter and the search result `is_total_estimated` flag if a result is empty.
=> Add option to include extra templates on first page of admin_overview lists

apps/zotonic_mod_base/src/controllers/controller_page.erl
This changes the behavior of controller_page:
- Redirect to the page_url if the current request is canonical and the request-path is not matching the page_url
- For "gone" pages and non primary paths, use a permanent redirect instead of temporary
These changes should make bots carry over the page-scoring of old or alternative URLs to the new URL.
A redirect hell is circumvented by adding a `no-cache` caching directive, also modern browsers do check the source of a permanent redirect if they detect a redirect loop using their cached redirects.
~Possible problem is having a `/` in your templates, that will redirect upon first visit to the language variant (for example `/en/`).  This is cached (for a minute), so a next click on that link after a language switch might not redirect to the …
=> base/seo: let controller_page redirect permanently to the preferred or new page-url

apps/zotonic_mod_authentication/src/mod_authentication.erl, apps/zotonic_mod_base/src/scomps/scomp_base_pager.erl, apps/zotonic_mod_search/src/support/search_query.erl
- Fix a problem with connecting accounts using OAuth2 between Zotonic servers
- Fix a problem where pager scomp would crash if an `undefined` search result was given
- Fix a problem where searching on the text `id:somename` would result in a SQL error due to a missing operator
=> Misc fixes, OAuth, pager, search on id

apps/zotonic_mod_menu/src/filters/filter_menu_ids.erl, apps/zotonic_mod_menu/src/filters/filter_menu_rsc.erl, apps/zotonic_mod_menu/src/mod_menu.erl, apps/zotonic_mod_seo/src/support/seo_breadcrumb.erl, doc/ref/filters/filter_menu_ids.rst, doc/ref/filters/filter_menu_rsc.rst, doc/ref/filters/menu/index.rst, doc/ref/validators/validator_json.rst
Adds:
- Filter to return all ids in a menu
- Edges from a menu to all resources in a menu (`hasmenupart`). Filled on pivot of a menu resource.
- Predicate to attach a menu to a resource (`hasmenu`)
The above is used to provide all breadcrumbs of a resource, following through the `haspart` and `hasmenupart` subjects of a resource.
=> mod_seo: return all menu paths of an id

modules/mod_base/dispatch/dispatch, modules/mod_base/templates/security.txt.tpl, priv/zotonic.config.in, src/models/m_site.erl
Add the `/.well-known/security.txt` file to the core.
See also https://securitytxt.org
The values are looked up using the following configuration order:
1. Site configs:
* `site.security_email`
* `site.security_url`
* `site.security_policy_url`
* `site.security_hiring_url`
* `site.security_expires`
2. Special unique page names, to optionally add information to the site:
* `page_security_contact`
* `page_security_policy`
* `page_security_hiring`
3. Global configs:
* `security_email`
* `security_url`
* `security_policy_url`
* `security_hiring_urll`
4. Email property of the admin, used for security_email (if visible by anonymous).
If the `site.security_expires` config is not set then the default expires is a month in the future.
A site specific `security.txt` can be defined by adding the …
=> core: add security.txt support

apps/zotonic_core/src/models/m_rdf.erl, apps/zotonic_mod_seo/src/models/m_seo.erl
This ensures that the JSON+LD in the head section is rendered as the anonymous user, as the JSON+LD is meant for search engines they shouldn't have access to private properties. This also prevents scripts in the browser to see those private properties reflected in the JSON+LD page data.
Also fix an issue with unescaping date values.
=> seo: render rdf summary as anonymous

apps/zotonic_mod_admin_identity/priv/templates/_admin_overview_list_page1.tpl
The rows were not clickable, fix this.
=> mod_admin_identity: make rows in found identities clickable

apps/zotonic_core/src/models/m_identity.erl, apps/zotonic_mod_admin_identity/priv/templates/_admin_edit_basics_user.tpl, apps/zotonic_mod_admin_identity/priv/templates/_admin_edit_sidebar_identity_live.tpl, apps/zotonic_mod_admin_identity/priv/templates/admin_users.tpl, apps/zotonic_mod_admin_identity/src/actions/action_admin_identity_dialog_set_username_password.erl
This prevents the admin user to log in using an username_pw identity.
Only the configured admin password and username 'admin' can be used to logon the admin using an username/pw combo.
Also hide the UI to set an username_pw for the admin.
=> mod_authentication: prevent admin to be able to log in using an username_pw identity

apps/zotonic_mod_seo/src/support/seo_breadcrumb.erl
As the homepage is not in the main menu it does not have a breadcrumb.
This adds a breadcrumb containing itself.
=> mod_seo: let the homepage have a breadcrumb of itself

apps/zotonic_mod_seo/src/support/seo_breadcrumb.erl
The partof-trail and the menu trail could be the same.
=> Prevent duplicate trails

apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_core/src/support/z_pivot_rsc_job.erl, apps/zotonic_mod_base/priv/templates/pivot/pivot.tpl
Fixes a problem where the surname was not pivoted due to an error in the default pivot.tpl template.
Also adds better handling of ``#custom_pivot`` notification results and more documentation for this notification.
=> Fix pivot of surname, better handling of custom_pivot

apps/zotonic_mod_admin/src/support/z_admin_media_discover.erl
This fixes an issue with importing URLs like `https://sculpture-network.org/en/event/50639/xv.-international-forum-in-málaga`  (note the á character)
=> mod_admin: fix an issue with importing URLs containing multibyte characters

apps/zotonic_core/src/support/z_mqtt.erl
This fixes an issue where passing an atom for a MQTT topic could crash the topic mapping.
Now an atom is assumed to be the unique name of a resource and a mapping from the resource to a resource id is tried.
=> core: accept atoms as topics, assume to be unique names

apps/zotonic_core/src/models/m_rdf.erl
This fixes an issue where creation, publication and modification dates were not acceptable properties for the old base type `Thing` and types like `Person`.
=> core: add CreativeWork as base type to most JSON-LD descriptions

apps/zotonic_mod_survey/priv/templates/blocks/_admin_edit_block_li_survey_category.tpl, apps/zotonic_mod_survey/priv/templates/blocks/_admin_edit_block_li_survey_truefalse.tpl
This would cause these radio buttons to behave as a single group, removing the value from one block if it was selected in another block.
=> mod_survey: fix a problem where radio buttons had the same 'name' in different blocks

apps/zotonic_mod_seo/src/support/seo_breadcrumb.erl
This fixes a problem where a wrong menutrail could be returned for sites without a page called `page_home` or `home` but that do have a `main_menu`.
=> mod_seo: fix a problem with the menu trail if there is no home page

apps/zotonic_core/src/db/z_db.erl, apps/zotonic_core/src/models/m_media.erl, apps/zotonic_core/src/models/m_rsc.erl, apps/zotonic_filehandler/src/zotonic_filehandler_mappers.erl, apps/zotonic_mod_admin/src/actions/action_admin_delete_rsc.erl, apps/zotonic_mod_filestore/src/mod_filestore.erl, apps/zotonic_mod_search/src/support/search_query.erl
- More logging in media handling and db queries
- Better resilience against errors during file duplication
- Up the mod_filestore version to force upgrades when upgrading from 0.x
- Accept atom z_language as language code in queries
- Support Taskfile when handling lib-src changes
=> Misc fixes

apps/zotonic_mod_seo/priv/templates/_seo_admin_preview_json_ld.tpl
Fix a problem where crafted content could result in JSON-LD for SEO editing that was not properly escaped.
=> mod_seo: escape json-ld shown for editing

apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_core/src/models/m_rsc_import.erl, apps/zotonic_mod_backup/priv/templates/_dialog_backup_upload.tpl, apps/zotonic_mod_backup/src/backup_rsc_upload.erl, apps/zotonic_mod_backup/src/controllers/controller_admin_backup.erl
This adds support to import a JSON file with the content of the rsc export API.
The imported file replaces the resource.
=> mod_backup: support import of JSON rsc export files using mod_backup admin panel

src/support/z_exec.erl, src/support/z_media_preview.erl
Add a special version of the `os:cmd/1` function with a timeout.
This fixes an issue where a hanging convert command could prevent other convert commands from running.
Needs and additional zotonic 1.x version, where we are using `exec` for running commands.
=> core: add timeout to ImageMagick convert commands (0.x)

apps/zotonic_mod_search/src/mod_search.erl
There was an ambiguous `id` in the SQL query if a resource-id was excluded.
=> mod_search: Fix a problem where match_objects might result in an SQL error

apps/zotonic_core/src/support/z_exec.erl, apps/zotonic_core/src/support/z_media_preview.erl, apps/zotonic_mod_video/src/mod_video.erl, apps/zotonic_mod_video/src/support/z_video_convert.erl, apps/zotonic_mod_video/src/support/z_video_info.erl, apps/zotonic_mod_video/src/support/z_video_preview.erl
This fixes an issue where the ImageMagick `convert` command could hang on some image files.
=> core: add timeouts to convert and ffmpeg commands

src/erlydtl/erlydtl_runtime.erl
Support:
* `@value` lookup on a value (ie. binary, number, atom) returns that value
* the first index of a value is the value, this support looking up values where the value might be a list
* a key into a value returns `undefined`
This is also more compatible with the 1.x value lookup and makes it easier for path-lookups in JSON data.
=> Better value lookup for linked-data lookup paths (0.x)

apps/zotonic_mod_acl_user_groups/src/support/acl_user_groups_checks.erl
Fix a problem where checking for being the group-manager failed for non-logged-on users.
=> mod_acl_user_groups: fix a problem in checking for collab group manager

apps/zotonic_core/include/zotonic.hrl, apps/zotonic_core/src/i18n/z_trans.erl, apps/zotonic_mod_translation/src/support/translation_scan.erl
`?__("...", Context)` expressions inside an 'if' were not collected.
Also fix an issue where the translation lookup of a missing string could result in returning a string instead of binary.
Adds the `?___("some text", Context)` (triple underscore) macro to fetch all translations of a string. This is useful for places where a `#trans{}` record is needed.
=> mod_translation: fix an issue where translations in an 'if' were not found.

apps/zotonic_mod_translation/priv/templates/_dialog_language_copy.tpl
This was caused by a class changing names, which prevented the copy routine of finding the correct language tabs.
=> mod_admin: fix an issue where in the admin-edit a language could not be copied

src/support/z_context.erl
Remove the `x-xss-protection` header.
Issue #3519
=> core: remove the x-xss-protection header (0.x)

apps/zotonic_core/src/support/z_context.erl
Remove the `x-xss-protection` header from the default security headers.
=> core: remove x-xss-protection header. Fix #3519

apps/zotonic_mod_survey/priv/templates/email_survey_result.tpl, apps/zotonic_mod_survey/priv/templates/survey_results_printable.tpl
Keep linebreaks and escape the answers in the email and the printable version of results.
=> mod_survey: Keep linebreaks in answers of survey

apps/zotonic_mod_survey/priv/templates/_survey_start.tpl, apps/zotonic_mod_survey/priv/templates/_survey_start_button.tpl, apps/zotonic_mod_survey/priv/templates/survey.tpl
Add option to the survey page to automatically start the survey by adding `?autostart=1` to the survey URL.
=> mod_survey: add option for survey autostart via query arg

apps/zotonic_mod_seo/priv/templates/admin_seo.tpl, apps/zotonic_mod_seo/src/support/seo_jsonld_webpage.erl
Add the option to hide the search action from the Website `schema:potentialAction`. This is needed for sites without a search page, but with a `search` dispatch rule.
=> mod_seo: add option to hide the JSON-LD search action

apps/zotonic_mod_backup/priv/templates/admin_backup.tpl, apps/zotonic_mod_backup/src/mod_backup.erl
Add the option to make daily database-only backups, also if there isn't a filestore enabled.
=> mod_backup: add option to make daily db-only backups

apps/zotonic_mod_search/src/mod_search.erl, apps/zotonic_mod_search/src/support/search_query.erl
Make the text search weight config more flexible.
Also tune the default weights for better relevance of search results.
Issue #3522
=> mod_search: tune text search weight config

apps/zotonic_mod_base/priv/lib/js/modules/z.dialog.js
This ensures the backdrop is also removed. With `dialogRemove` this was not the case.
=> mod_zotonic_wires: use different function to close dialog

apps/zotonic_core/src/support/z_utils.erl
In OTP 26.1 and 27 the values +0.0 and -0.0 are different.
Don't use `===` and pattern matching to compare with 0.0.
=> OTP 26.1/27 compat with +/-0.0

apps/zotonic_mod_admin_frontend/priv/templates/_admin_frontend_edit.tpl, apps/zotonic_mod_translation/priv/templates/_translation_edit_languages.tpl, apps/zotonic_mod_wires/src/support/z_transport.erl
Small fixes in:
* z_transport for unknown delegates
* frontend edit for forms
* simplify looping over languages in languages select edit panel
=> Small fixes - edit - z_transport

apps/zotonic_mod_backup/priv/templates/admin_backup.tpl, apps/zotonic_mod_backup/priv/templates/admin_backup_revision.tpl, apps/zotonic_mod_backup/src/mod_backup.erl, apps/zotonic_mod_backup/src/models/m_backup_revision.erl, doc/ref/modules/mod_backup.rst
Add a simple periodic cleanup of the revision log.
Revisions are deleted after 18 months.
This can be changed using the config `mod_backup.revision_retention_period`
For the cleanup of person data (GDPR) we will need a shorter period.
This will be done in a separate pull request.
=> mod_backup: periodic cleanup of revisions

apps/zotonic_mod_search/src/mod_search.erl
Fix #3561 
Adapted the autocomplete query so it does not return unfindable resource ids.
=> mod_search: Make sure the autocomplete search does not return unfindable resources

apps/zotonic_mod_base/src/controllers/controller_id.erl
These resources are gone and have an explicit new location.
Use a permanent redirect, just like controller_page is doing.
=> mod_base: set controller_id redirect to permanent for gone resources

apps/zotonic_core/priv/translations/zotonic.pot, apps/zotonic_core/src/support/z.erl, apps/zotonic_core/src/support/z_exec_browser.erl, apps/zotonic_launcher/src/command/zotonic_cmd_chrome.erl, apps/zotonic_launcher/src/command/zotonic_cmd_open.erl, doc/ref/cli/index.rst
This lets the site open command use the default browser on Safari.
The secure-open uses Chrome, as it needs special command line options only available to Chrome.
=> core: on macOS let z:open/1 open in the default browser

apps/zotonic_core/src/support/z_acl.erl
Make it possible to type: `z_acl:sudo(sitename)` instead of `z_acl:sudo(z:c(sitename))`.
=> core: add convenience function z_acl:sudo(sitename)

apps/zotonic_core/src/models/m_config.erl, apps/zotonic_mod_admin_config/priv/templates/admin_config.tpl, apps/zotonic_mod_admin_config/src/controllers/controller_admin_config.erl, apps/zotonic_mod_filestore/priv/templates/admin_filestore.tpl
Issue #3590 
Not a complete solution yet to #3590, this pull request:
* Only show first three chars in /admin/config for values considered a secret
* The `is_secret` is for now set by checking the config key name for `secret`, `key` or `password`
* Some exemptions to this name matching are hard coded (`s3key`, `password_min_length`)
* The filestore password is shown as a password input, hiding the password from plain sight for "shoulder surfers".
This doesn't add any security to leaking secrets to people with access to the admin. We might want to add something that the user's password must have been recently entered, and if not force a password entry before editing a config value.
=> mod_admin_config: hide secrets from direct view

apps/zotonic_core/src/support/z_context.erl, apps/zotonic_mod_admin/priv/templates/_action_dialog_connect_tab_find.tpl, apps/zotonic_mod_mqtt/src/scomps/scomp_mqtt_live.erl
Problem was that the `pagelen` was not passed, so it defaulted to max 20 keywords per category.
=> mod_admin: fix a problem where in the keyword connect dialog not all keywords were shown

apps/zotonic_mod_base/src/controllers/controller_static_pages.erl, apps/zotonic_mod_base/src/mod_base.erl
Better handling of files in the `priv/templates/static/` directory.
Any file or template placed in there is served automatically.
It is possible to add language variations by adding directories with the language code as directory name.
=> mod_base: better handling of 'static' directory in templates dir

apps/zotonic_core/src/models/m_rsc_update.erl, doc/ref/filters/filter_media_for_language.rst
Only allow valid languages for the medium_language.
=> core: check medium_language on rsc update, fix doc

apps/zotonic_mod_survey/include/survey.hrl, apps/zotonic_mod_survey/src/mod_survey.erl, apps/zotonic_mod_survey/src/models/m_survey.erl
Make acl checks for hard coded checks which regulated access to survey results.
This makes it possible to extend the functionality of the survey module with custom forms where another module can regulate access to the answers. E.g. public accessible filled in viewing of results.
=> mod_survey: Make proper acl checks of hard coded access checks

apps/zotonic_mod_wires/src/support/z_transport.erl
=> core: fix a problem where the query arg order was reversed

apps/zotonic_mod_admin_modules/priv/templates/admin_modules.tpl, apps/zotonic_mod_admin_modules/src/controllers/controller_admin_module_manager.erl, apps/zotonic_mod_admin_modules/src/mod_admin_modules.erl
Add a small button in the module overview to re-install a module's schema and data.
=> mod_admin_modules: add button to re-install a module's datamodel

apps/zotonic_core/src/models/m_predicate.erl, apps/zotonic_mod_admin/priv/templates/_action_dialog_connect_tab_find.tpl
Fix a problem in the connection checklists where some categories would not be displayed if the category was a sub-category of another possible object category.
=> mod_admin: fix connect dialog for predicates with checklists

doc/ref/filters/filter_media_for_language.rst, doc/ref/filters/resource_lists/index.rst, modules/mod_admin/actions/action_admin_dialog_media_upload.erl, modules/mod_admin/actions/action_admin_dialog_new_rsc.erl, modules/mod_admin/mod_admin.erl, modules/mod_admin/support/z_admin_refers.erl, modules/mod_admin/templates/_action_dialog_connect.tpl, modules/mod_admin/templates/_action_dialog_connect_tab_depictions.tpl, modules/mod_admin/templates/_action_dialog_connect_tab_find.tpl, modules/mod_admin/templates/_action_dialog_connect_tab_find_results.tpl, modules/mod_admin/templates/_action_dialog_connect_tab_new.tpl, modules/mod_admin/templates/_action_dialog_edit_basics.media.tpl, modules/mod_admin/templates/_action_dialog_media_upload_tab_upload.tpl, modules/mod_admin/templates/_action_dialog_media_upload_tab_url.tpl, modules/mod_admin/templates/_action_dialog_new_rsc_tab.tpl, modules/mod_admin/templates/_admin_edit_media.tpl, modules/mod_admin/templates/_edit_medium_language.tpl, modules/mod_admin/templates/admin_overview.tpl, modules/mod_admin/templates/admin_status.tpl, modules/mod_base/filters/filter_media_for_language.erl, modules/mod_editor_tinymce/templates/_editor.tpl, modules/mod_oembed/mod_oembed.erl, modules/mod_oembed/templates/_media_upload_panel.tpl, modules/mod_video_embed/mod_video_embed.erl, modules/mod_video_embed/templates/_media_upload_panel.tpl, src/models/m_rsc_update.erl
Support for `medium_language` property and the `media_for_language` filter.
Also:
- a medium item added to a tinyMCE body is not automatically added as a depiction; and
- for all media embedded in body or other properties a `refers` connection is added.
=> mod_admin: add support for medium_language  (adapted from master)

apps/zotonic_mod_search/src/support/search_query.erl
This fixes a problem where the rewrite of the `match_object`  into `match_object_ids` would crash.
=> mod_search: fix a crash in the match_object_ids query term handling

apps/zotonic_core/src/support/z_search_terms.erl, apps/zotonic_mod_search/src/support/search_query.erl
Make the match_object into a nested query so that is also works in `anyof` clauses.
Change the representation of 'none' query term results.
=> Fix a problem with mapping of 'none' query results in nested queries.

apps/zotonic_mod_admin/priv/templates/_admin_edit_blocks.tpl, apps/zotonic_mod_admin/src/mod_admin.erl
Fix two issues:
* Crash when unpacking the language due to values being binary
* Problem with passing the currently selected edit languages
=> mod_admin: fix a problem with adding blocks in the admin

apps/zotonic_mod_admin/priv/templates/admin_status.tpl, apps/zotonic_mod_menu/priv/templates/_admin_status.tpl, apps/zotonic_mod_menu/src/mod_menu.erl
Previously the menu-contains was tracked on pivot.
This gives a problem if there is a long pivot queue and the menu refers to dependent items.
Then the not-connected check could happen before the menu-contains edges were added.
Also add a button in the admin to set all 'hasmenupart' connections.
=> mod_menu: track the menu-contains on rsc update

apps/zotonic_mod_acl_user_groups/src/mod_acl_user_groups.erl
Remove an unused function. Switching user_id is now done differently.
=> mod_acl_user_groups: Remove unused function

apps/zotonic_mod_search/src/mod_search.erl
Fix #3614 
Make the prevnext search compatible with the new query arg format.
=> mod_search: fix a crash in the nextprev search

apps/zotonic_mod_authentication/priv/dispatch/dispatch
Error in the dispatch file, was `noindex` should be `seo_noindex`
=> mod_authentication: correct seo noindex flag for auth dispatch rules

apps/zotonic_core/src/db/z_db.erl, apps/zotonic_mod_backup/src/mod_backup.erl, apps/zotonic_mod_backup/src/models/m_backup_revision.erl
Add an extra revision with type 'D' on deletion of a resource.
Also insert this new type 'D' revisions on upgrade of the mod_backup.
This fixes an issue where the retention period was not counted after the delete but after the last save. That could result in too soon deletion of resources that were not recently edited.
=> mod_backup: save revision on rsc deletion

apps/zotonic_mod_search/src/support/search_query.erl
If a query arg `facet.foo=bar` is mapped to the search terms then it becomes:
```erlang
#{
<<"facet">> => #{
<<"foo">> => <<"bar">>
}
}
```
This is then mapped to a query term with term `facet`, which is not recognized by the search builder.
This PR fixes that by interpreting a `map` value for the `facet` term to be a filter in facet values.
=> mod_search: fix a problem with unpacked filter and facet query args

apps/zotonic_mod_admin/priv/templates/_action_dialog_edit_basics.tpl, apps/zotonic_mod_admin/src/actions/action_admin_dialog_edit_basics.erl, apps/zotonic_mod_admin/src/actions/action_admin_dialog_new_rsc.erl, apps/zotonic_mod_admin/src/mod_admin.erl, apps/zotonic_mod_editor_tinymce/priv/lib/js/tinymce-5.10.2/tinymce/plugins/zmedia/plugin.min.js, apps/zotonic_mod_editor_tinymce/priv/templates/_tinymce_dialog_zmedia_props.tpl, apps/zotonic_mod_editor_tinymce/priv/templates/_tinymce_media_preview.tpl, apps/zotonic_mod_image_edit/priv/templates/_admin_edit_media_button.tpl, apps/zotonic_mod_wires/priv/lib/js/apps/zotonic-wired.js, doc/ref/actions/action_overlay_open.rst
This adds an option to edit an image directly from the tinyMCE editor.
Also add a `refers` at the moment a new media is added to tinyMCE or an embedded page block.
This prevents problems with tracking dependent images whilst the page is not yet saved.
=> mod_admin: track embedded page refs during edit. Add image edit to media properties

apps/zotonic_launcher/src/command/zotonic_cmd_addsite.erl
This fixes an issue where the default hostname might have a `_` characters, which is not valid for hostnames.
=> zotonic_launcher: with addsite, ensure hostname is valid

apps/zotonic_core/src/models/m_category.erl, apps/zotonic_mod_admin/priv/templates/_action_dialog_edit_basics.tpl, apps/zotonic_mod_admin/src/mod_admin.erl
This fixes a problem where the category filters did not work when passing a list of category ids for the `cat` search filter.
This does remove the possibility to use strings (as list) for the category filter.
=> core: simplify flatten search cats, do no consider strings-as-list

apps/zotonic_mod_search/src/mod_search.erl
Fix #3631
Remove the query which simply returns all possible resources with a specific category.
=> Don't return all possible resources of cat when no text is given

apps/zotonic_core/src/support/z_search_props.erl, apps/zotonic_mod_admin/priv/templates/admin_media.tpl, apps/zotonic_mod_admin/priv/templates/admin_overview.tpl
Fix #3634 
all should now be passed as an atom instead of a string due to stricter search parameter checks.
=> mod_search: all must be passed as a tuple

apps/zotonic_core/src/models/m_rsc_update.erl
The visible_for was not forced to an integer, which could result in SQL type errors.
=> core: fix a problem with type conversion for the visible_for property value

apps/zotonic_core/src/support/z_media_identify.erl
HEIC and MJS are not present in the mime types app.
=> core: add mime type mappings for .heic and .mjs

apps/zotonic_mod_admin/priv/templates/_action_dialog_edit_basics.tpl, apps/zotonic_mod_base/priv/lib/js/modules/z.forminit.js, apps/zotonic_mod_image_edit/priv/templates/_admin_edit_media_button.tpl, apps/zotonic_mod_image_edit/priv/templates/_image_edit_button.tpl, apps/zotonic_mod_mqtt/src/scomps/scomp_mqtt_live.erl
Decouple the image edit button from the mod_admin.
Fix for forminit if a select has multiple options with same value.
Fix for passing query args in live scomp.
=> mod_image_edit: decouple image edit button. Small misc fixes

apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_mod_translation/src/models/m_translation.erl, apps/zotonic_mod_translation/src/support/translation_translate.erl
This adds support for a translation API which will be used to translate texts in the admin.
The API calls (with a notification) pluggable translation services.
=> mod_translation: add support for translation services

apps/zotonic_core/src/models/m_rsc_update.erl
In `update_transaction_fun_insert(#rscupd{id = insert_rsc}../5` the special value `self` is expected as an atom, while in `update_transaction_fun_insert(#rscupd{id = Id}../5` it is matched as binary. Using binaries helps with handling of input via API, so to be consistent the match on `self` should be on `<<"self">>`.
Regarding backward compatibility, I am not sure this won't break anything, though it did break in vivo without the change.
=> [core] Self is passed as a binary instead of an atom now

modules/mod_admin/support/z_admin_refers.erl
A missing order by made the "ensure refers" routine skip existing resources.
=> mod_admin: fix a problem in ensure-refers where not all resources were checked

apps/zotonic_mod_mailinglist/priv/templates/_mailinglist_subscribe_form.tpl, apps/zotonic_mod_mailinglist/priv/templates/_scomp_mailinglist_subscribe.tpl, apps/zotonic_mod_mailinglist/src/scomps/scomp_mailinglist_mailinglist_subscribe.erl
This fixes a problem where having multiple forms for the same mailing would result in duplicate element ids on the page. That would give problems with the handling of the error and done feedback messages.
=> mod_mailinglist: allow multiple subscribe forms for the same mailinglist

apps/zotonic_mod_translation/priv/templates/_dialog_rsc_language.tpl, apps/zotonic_mod_translation/priv/templates/_translation_edit_languages.tpl
Add an option to overwrite existing translations with new translations.
This can be useful if the original source text(s) have been extensively edited.
=> mod_admin: add translate overwrite option

apps/zotonic_mod_translation/priv/templates/_translation_status.tpl, apps/zotonic_mod_translation/src/models/m_translation.erl, apps/zotonic_mod_translation/src/support/translation_translate_rsc.erl, apps/zotonic_mod_translation/test/mod_translation_translate_rsc_tests.erl
Add some routines to add a translation or remove a translation from a resource.
This makes it possible to manage translations without opening the resource in the admin edit page.
=> mod_translation: add routines to add or remove translations from resources

apps/zotonic_mod_fileuploader/priv/lib/js/zotonic.fileuploader.worker.js, doc/ref/modules/mod_fileuploader.rst
This PR adds a `start_topic` option to the `fileuploader` worker.
The motivation is that I could not get the upload name using the `zotonic.fileuploader.worker.js`, so I could not get the status or cancel the upload.
I also fixed a bug in line 199 of the worker where the `response_topic` came from an inexistent `msg` object.
=> fileuploader: Add start_topic option

apps/zotonic_core/src/smtp/z_email_server.erl
Fix #3481 
If SSL is requested then use TLS and set the TLS options for the secure transmission.  Also default to port 587 for secure transmission.
=> core: set tls options for secure transmission on OTP26

apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/scss/_base.scss, apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/scss/_dialog-new-connect.scss, apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/scss/_thumbnails.scss, apps/zotonic_mod_admin/priv/lib/css/zotonic-admin.css, apps/zotonic_mod_admin/priv/templates/_action_dialog_connect_tab_find_results_item.tpl, apps/zotonic_mod_admin/priv/templates/_action_dialog_new_rsc_tab_find_results.tpl, apps/zotonic_mod_admin/priv/templates/_action_dialog_new_rsc_tab_find_results_item.tpl, apps/zotonic_mod_admin/priv/templates/_rsc_preview.tpl, apps/zotonic_mod_admin/priv/templates/admin_media.tpl, apps/zotonic_mod_admin/priv/templates/mediaclass.config, apps/zotonic_mod_base/priv/templates/pivot/_main_text.tpl
Fix #3657 
This makes it possible to search a document by filename.
=> mod_admin: index the medium filename and show it on the connect list items

modules/mod_oembed/mod_oembed.erl, modules/mod_oembed/support/oembed_client.erl
Remove the oembed_client process. The process was not restarted when it crashes, as the dummy module catches exits. 
As regulation can also be done using a _jobs_ regulator (if needed) this middle man process is not needed. Now we just do a direct oembed lookup for every request in the request context/process.
=> mod_oembed: remove the oembed_client process (0.x)

src/models/m_media.erl
Downloads could be incomplete due to an unexpected closed socket.
Check the size of the downloaded file against the value of the returned content-length header.
See also #3678
=> core: check size of downloaded file after media download (0.x)

apps/zotonic_filewatcher/src/zotonic_filewatcher_beam_reloader.erl, apps/zotonic_filewatcher/src/zotonic_filewatcher_fswatch.erl, apps/zotonic_filewatcher/src/zotonic_filewatcher_inotify.erl, apps/zotonic_filewatcher/src/zotonic_filewatcher_monitor.erl, apps/zotonic_filewatcher/src/zotonic_filewatcher_sup.erl
This fixes a problem where the file watcher would stop working of inotify or fswatch is installed but has problems running.
=> filewatcher: fallback to monitor if inotify or fswatch is encountering  problems

apps/zotonic_core/src/support/z_fetch.erl, apps/zotonic_core/src/support/z_media_identify.erl, apps/zotonic_mod_admin/src/mod_admin.erl
Also remove a debug statement.
=> core: catch json decode errors on fetch. Add mime type mapping for .eml files.

apps/zotonic_mod_admin_identity/src/actions/action_admin_identity_dialog_set_username_password.erl, apps/zotonic_mod_authentication/priv/lib/js/zotonic.auth-ui.worker.js
This fixes a problem where we could not generate a link to the "password forgotten" page where the user's email address would be prefilled.
Also do not pass the password to the new-user email template to prevent that it can be added.
=> mod_authentication: allow to pass email to the password reminder form.

apps/zotonic_core/src/smtp/z_email_server.erl
Fix #3686
Remove the TLS options and optionally reset to port 25.
=> Fix a problem where SMTP would not fall back to plain text on port 25

apps/zotonic_core/src/smtp/z_email_server.erl, apps/zotonic_core/src/support/z_config.erl, apps/zotonic_launcher/priv/config/zotonic.config.in, doc/developer-guide/email.rst
Check various configs to determine the port to use for plain text email fallback.
@seannaswell Can you have a look at this?  I think the logic is ok.
=> core: Improve smtp plaintext port determination

apps/zotonic_launcher/bin/zotonic
This fixes an issue where `epmd` could be listening on an 'outside' public port and disclosing information.
As Zotonic runs per default only as a single node, we can safely restrict epmd to only listen on the loopback interface.
=> zotonic_laucher: Restrict epmd to listen only on the loopback interface

doc/developer-guide/dispatch-rules.rst
The word "controller" is missing in the third paragraph.
=> Add missing word controller

apps/zotonic_launcher/bin/zotonic
On Ubuntu the local server name is set to `127.0.1.1` in the /etc/hosts file.
Listen on both 127.0.0.1 and 127.0.1.1 to ensure that epmd is reachable.
=> zotonic_launcher: fix a problem with epmd listen address in Ubuntu

apps/zotonic_core/src/i18n/z_language.erl, apps/zotonic_core/src/models/m_media.erl, apps/zotonic_core/src/models/m_rsc_update.erl, apps/zotonic_mod_admin/priv/templates/admin_base.tpl, apps/zotonic_mod_admin/src/actions/action_admin_dialog_media_upload.erl, apps/zotonic_mod_translation/src/mod_translation.erl, apps/zotonic_mod_translation/src/models/m_translation.erl
Do not do language detection on texts smaller than 10 chars (bytes).
Do not set RTL on admin ui depending on the content, follow the UI language.
Use the root name of a media item for its default title.
Add and fix some specs.
=> mod_translation: translation detection - rtl fix

apps/zotonic_core/src/support/z_datetime.erl, apps/zotonic_core/src/support/z_utils.erl, apps/zotonic_mod_admin/priv/templates/_admin_overview_filter_panel.tpl, apps/zotonic_mod_search/src/support/search_query.erl, doc/developer-guide/search.rst, doc/ref/modules/mod_search.rst
Add the term `ongoing_on` to check for events on the given absolute or relative time.
Also small cleanup of z_datetime relative time code.
=> mod_search: add 'ongoing_on' search term

apps/zotonic_mod_base/src/controllers/controller_api.erl
This fixes a problem where an API could return a detailed map in an error, but the error reason gets mapped to a generic error message.
=> mod_base: if API model call return error map, then return error map as JSON

src/install/z_install.erl, src/install/z_installer.erl
Add a key on `category_id`.
This was missing in the 0.x datamodel.
=> core: ensure that there is a key on category_id

cloud-init/config.d/ports.yml, cloud-init/zotonic-cloudinit.yml
Tested with Ubuntu 22
Changes:
- Add EPMD listen ports to `/etc/environment`
- Use `kerl` to install erlang
- Add erlang select using `kerl` to `/etc/profile`
- Add max inotify file watches config
- Add `wkhtmltopdf` - which is used by some modules for PDF generation
=> Adapt cloudinit for Ubuntu 22

apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_core/src/models/m_search.erl, apps/zotonic_core/src/support/z_search.erl, apps/zotonic_mod_search/src/support/search_facet.erl
If the `is_count_rows` option is passed to the search model then the number of rows is returned instead of the rows.
The option `properties` now also supports `o.predicate` and `s.predicate`.
=> core: add search option 'is_count_rows' and option to fetch objects as properties

apps/zotonic_mod_oembed/src/mod_oembed.erl
Previously the OEmbed information is takes as-is and used for fetching the preview image.
This works well, unless the provider changed their URLs for the preview images.
In those cases we can loose the preview image of the OEmbed.
This fixes the issue be retrying the OEmbed. If it succeed then the newly returned JSON is taken.
If the new OEmbed request fails then the imported JSON is used.
=> mod_oembed: fix a problem where importing an oembed resource could result in a missing preview image

doc/developer-guide/dispatch-rules.rst, doc/developer-guide/templates.rst
Fix a few small typo's in the dispatch-rules and templates docs.
=> Fix typos in dispatch-rules and templates files

apps/zotonic_core/src/support/z_sanitize.erl
Add sanitisation to the media items. If no permission/not visible return an empty space.
=> Sanitise media items

apps/zotonic_launcher/bin/zotonic
Fix #3725
The default EPMD ip address was set to 127.0.0.1 and 127.0.1.1.
The ip address 127.0.1.1 is not available on macOS, which prevented Zotonic to start with the error message:
```
Protocol 'inet_tcp': register/listen error: econnrefused
```
=> Fix an issue where epmd could not be started on non-Linux machines

apps/zotonic_mod_custom_redirect/src/mod_custom_redirect.erl, apps/zotonic_mod_custom_redirect/src/models/m_custom_redirect.erl
This fixes a problem where the redirect rules were only shown if the user has admin rights.
The correct right is `use.mod_custom_redirect`
=> mod_custom_redirect: fix a problem where the redirect rules were not shown.

apps/zotonic_core/src/db/z_db.erl, apps/zotonic_core/src/models/m_rsc_update.erl, apps/zotonic_core/src/support/z_pivot_rsc.erl, apps/zotonic_listen_smtp/src/zotonic_listen_smtp_receive.erl, apps/zotonic_mod_oauth2/src/models/m_oauth2_service.erl
Changes:
* Handle deadlock errors if the transaction fun return a deadlock error tuple (instead of a throw).
* Do not crash if rsc_update encountered a deadlock, instead return a deadlock error
* Simpler insert of ids in rsc pivot queue
* Export email parsing functions
* Prepare for OpenID support
=> core: misc fixes - especially deadlock handling and pivot insert

apps/zotonic_core/src/support/z_props.erl, apps/zotonic_core/src/support/z_search_props.erl, apps/zotonic_mod_search/src/support/search_facet.erl, apps/zotonic_mod_search/src/support/search_query.erl
Fix for using `<>` as prefix operator in search values.
Fix for using `~` when defining multiple qargs search terms with the same name.
=> mod_search: fix for using ~ char in qargs names; fix for prefix operators in values

apps/zotonic_core/src/install/z_install.erl, apps/zotonic_core/src/install/z_install_update.erl, apps/zotonic_core/src/support/z_pivot_rsc.erl, apps/zotonic_core/src/support/z_pivot_rsc_job.erl, apps/zotonic_mod_admin/priv/templates/_admin_status_update_pivot_count.tpl, apps/zotonic_mod_admin/priv/templates/admin_status.tpl
This fixes a problem where the pivot log updates could give lock errors due to the parallel rsc updates and edge changes.
=> core: replace rsc pivot queue with pivot log

apps/zotonic_core/src/support/z_cowmachine_middleware.erl, apps/zotonic_core/src/support/z_media_identify.erl, apps/zotonic_mod_base/src/controllers/controller_id.erl
This enables URLs like:
* `https://example.com/id/123.json`
* `https://example.com/id/123.html`
The extension is mapped to a mime type and replaces the `accept` header used for content negotiation.
=> mod_base: let controller_id accept an extension on the id for content negotation

apps/zotonic_mod_seo/priv/templates/_html_head_seo.tpl
This allows an overruling template to pass a custom `seo_depiction` for the `og:image` tag.
=> mod_seo: allow to set the seo_depiction to a custom value

apps/zotonic_core/src/support/z_context.erl, apps/zotonic_core/src/support/z_pivot_rsc_job.erl, apps/zotonic_mod_base/src/filters/filter_date.erl, apps/zotonic_mod_base/src/filters/filter_date_range.erl, apps/zotonic_mod_search/src/support/search_query.erl, apps/zotonic_mod_zotonic_site_management/priv/skel/blog/priv/templates/_sidebar.tpl, apps/zotonic_mod_zotonic_site_management/priv/skel/blog/priv/templates/archives.tpl, doc/developer-guide/search.rst, doc/ref/filters/filter_date.rst, doc/ref/filters/filter_date_range.rst, doc/ref/modules/mod_search.rst
This makes some changes to the way "all day" date ranges are pivoted.
The problem was:
* Date is in CET and all day
* Pivot is stored in UTC (without date conversion)
* Search for date in CET doesn't return the resource, as it is shifted one (or two for CEST) hours.
Solution:
* Pivot the "all day" date_start and date_end shifted from the resource timezone to UTC.
This pull request changes the behavior for pivoting (and searching) the "all day" date ranges.
Now the date for all-day date ranges is stored as if that date is in the timezone stored with the resource.
This timezone is in the `tz` property and will default to the timezone of the editor creating the resource.
If the `tz` property is not set, then the default Zotonic timezone is used.
Note that the way the date itself is stored in …
=> core: pivot all-day dates assuming the timezone of the resource

apps/zotonic_mod_admin/priv/templates/_admin_status_task_queue.tpl, apps/zotonic_mod_admin/src/mod_admin.erl
Adds a button in /admin/status to delete all tasks for a certain module/function pair.
=> mod_admin: add task delete button to admin

.github/workflows/dialyzer.yml, apps/zotonic_core/src/zotonic_core.app.src, apps/zotonic_launcher/src/command/zotonic_cmd_etop.erl
Small fixes for Dialyzer on OTP-26
Change CI to use OTP 26.2
=> Use OTP-26 for Dialyzer CI

apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/scss/_menu.scss, apps/zotonic_mod_admin/priv/lib/css/zotonic-admin.css
Fixes an issue where the caret is sometimes aligned below the menu item on Safari 17.4.1 on macOS
=> mod_admin: fix for menu alignment in Safari 17.4 on macOS

apps/zotonic_core/src/support/z_pivot_rsc_job.erl, apps/zotonic_mod_logging/src/models/m_log_email.erl
The "quick" pivot was handling the correction correctly, the slower "real" pivot didn't
Now open ended and open started date ranges are correctly pivoted.
=> Pivot end st juttemis fix

apps/zotonic_mod_zotonic_site_management/priv/templates/addsite.tpl
Modify the admin -> addsite page to accept the Postgres username 'dbuser' that is compatible with cloud database account names, such as 'supabase'. 
- [✔️] documentation updated
- [❎] tests added
- [✔️] no BC breaks
=> chore: allow postgres cloud db user like supabase with '.'

apps/zotonic_core/src/db/z_db.erl, apps/zotonic_core/src/install/z_install_data.erl, apps/zotonic_core/src/install/z_install_reinstall.erl, apps/zotonic_core/src/support/z_config_files.erl, apps/zotonic_core/src/support/z_sites_config.erl, apps/zotonic_launcher/src/zotonic_launcher_config.erl
Add function to drop the database schema and reinstall.
This can be used later to add reinstall of a backup.
=> core: add drop/reinstall of schema, small refactor of site config handling

apps/zotonic_mod_filestore/src/mod_filestore.erl, apps/zotonic_mod_filestore/src/support/filestore_request.erl
Certain S3 compatible stores are not able to store filenames with a '(' or ')' character in them.
Replace these characters with `--` on upload.
=> mod_filestore: fix an issue where remote filestore would not accept a parenthesis in filename

apps/zotonic_core/src/install/z_install.erl, apps/zotonic_core/src/install/z_install_update.erl, apps/zotonic_core/src/models/m_media.erl, apps/zotonic_core/src/support/z_media_gif.erl, apps/zotonic_core/src/support/z_media_identify.erl, apps/zotonic_core/src/support/z_media_preview.erl, apps/zotonic_core/src/support/z_media_tag.erl, apps/zotonic_core/src/support/z_mqtt_sessions_runtime.erl, apps/zotonic_mod_admin/priv/templates/_admin_edit_media.tpl
Animated GIF images get huge fast if they are upsized.
This prevents resizing to GIF beyond many pixels, blowing up memory by ImageMagick convert.
Big GIFs (h * w * frames) are now served as-is if a resized URL is requested.
GIFs with H * W * Frames larger than > 500 * 500 * 50 (= 12.5M) pixels are served as-is if their resized images is requested as GIF
=> core: restrict the size of (animated) gif images

apps/zotonic_mod_search/src/support/search_query.erl
Simple extra search terms for the default search query model.
=> mod_search: add search terms created_after/before and modified_after/before

apps/zotonic_core/src/i18n/z_language.erl, apps/zotonic_mod_base/src/filters/filter_trans_languages.erl, doc/ref/filters/filter_trans_languages.rst, doc/ref/filters/translation/index.rst
Add a filter to list all languages of a `#trans{}` translation record.
=> mod_translation: add filter trans_languages

apps/zotonic_core/src/support/z_mqtt_sessions_runtime.erl, apps/zotonic_core/src/support/z_replay_token.erl, apps/zotonic_core/src/support/z_site_services_sup.erl, apps/zotonic_mod_authentication/src/support/z_authentication_tokens.erl
This adds a unique token to session cookies. The token is invalidated if a user logs off.
Invalidated tokens are registered for the lifetime of sessions.
=> core/auth: ensure that a session token is invalidated upon logoff

apps/zotonic_mod_base/priv/lib/js/modules/z.forminit.js
This adds an event handler so that when a 'input' element of type 'reset' is used, then an 'input' event is sent to the form as well. This effectively makes it so that on reset the form is updated as if one had re-setted all its input field manually.
=> Add form reset event handler to update the form

apps/zotonic_mod_filestore/src/mod_filestore.erl, apps/zotonic_mod_filestore/src/models/m_filestore.erl
This fixes a problem where some paths with additional image operations become longer than the current max 255 characters.
=> mod_filestore: up the db tables path length to 500 characters

apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_mod_mailinglist/priv/templates/_dialog_mailing_page.tpl, apps/zotonic_mod_mailinglist/src/actions/action_mailinglist_dialog_mailing_page.erl, apps/zotonic_mod_mailinglist/src/actions/action_mailinglist_mailing_page_test.erl, apps/zotonic_mod_mailinglist/src/mod_mailinglist.erl, apps/zotonic_mod_mailinglist/src/models/m_mailinglist.erl, apps/zotonic_mod_mailinglist/src/support/z_mailinglist_schema.erl
This adds two options:
1. Only email recipients iff their preferred language matches the translations of the mailed page
2. An option to easily reset the mailing stats to send a mailing multiple times
=> mod_mailingslist: add option to only mail recipients matching languages with mailed page

apps/zotonic_mod_base/priv/lib/js/modules/z.forminit.js
This PR builds on #3775 by:
- moving the forced submit function to the widget's init
- adding the ability to prevent certain input fields from resetting, by adding a `data-skip-reset` attribute to them
=> Form resetting: add ignorable inputs

apps/zotonic_mod_logging/priv/lib/js/zotonic-log-ui.js, apps/zotonic_mod_wires/priv/lib/js/apps/zotonic-wired.js
Refactor unload event to pagehide event, this works better with the bfcache. Source: https://web.dev/articles/bfcache?utm_source=lighthouse&utm_medium=devtools#never_use_the_unload_event.
=> JS: refactor unload to pagehide for better compatibility with bfcache

apps/zotonic_core/src/support/z_sites_manager.erl
Problem: `z_sites_manager` can keep track of sites' configurations overrides (see `get_site_config_overrides/1` and
`put_site_config_overrides/2`),
However, in contrast with Zotonic v0.x, when gethering a site's config (with `get_site_config/1`), these aren't actually taken into account.
Solution: modify the implementation of `get_site_config` to apply the configuration overrides.
=> core: Utilize site configuration overrides

apps/zotonic_core/src/support/z_tags.erl, apps/zotonic_mod_wires/src/scomps/scomp_wires_button.erl, doc/ref/scomps/scomp_button.rst
Ensure that buttons with tag `a` have a `href` attribute.
Add it as an optional parameter for the `{% button %}` scomp.
Also make the default `Submit` text translatable.
Fix #3784
=> mod_wires: add optional href attribute for button with tag 'a'

apps/zotonic_mod_wires/priv/lib/js/apps/zotonic-wired.js
This will avoid uploading from input elements with the type `"file"` that have the `nosubmit` class (consistently with the other types of input elements).
=> Skip file inputs with the nosubmit class

apps/zotonic_mod_fileuploader/src/support/z_fileuploader.erl
Add a log entry when a fileuploader is ready, also report KB/sec upload speed.
=> mod_fileuploader: report upload speed

Dockerfile.dev, docker-compose.yml, docker/Dockerfile.dev, docker/docker-entrypoint.sh, docker/rebar.config, start-docker.sh
This fixes an issue where the Docker image could not be run on macOS due to UID/GID mapping of directories.
Also build the image in-situ, which removes the need of maintaining it on Docker hub.
=> docker: fix an issue with docker uid/gid on macOS

apps/zotonic_core/src/support/z_search.erl
On a `count(*)` we shouldn't allow any `qsort` clauses.
Remove the resulting `order` when `is_count_rows` option is set.
=> core: remove order-by when counting rows

apps/zotonic_mod_search/src/mod_search.erl, apps/zotonic_mod_search/src/support/search_query.erl, doc/developer-guide/search.rst, doc/ref/modules/mod_search.rst
This adds a `predicate` option to the `match_objects` query term.
Example:
```
%{
term: "match_objects",
value: id,
predicate: [ "subject", "author" ]
}
```
=> mod_search: add 'predicate' option to match_objects query term

apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_core/src/models/m_identity.erl, apps/zotonic_mod_authentication/priv/templates/_logon_login_form_fields.tpl, apps/zotonic_mod_authentication/priv/templates/logon_error/message.user_external.tpl, apps/zotonic_mod_authentication/src/controllers/controller_authentication.erl, apps/zotonic_mod_authentication/src/models/m_authentication.erl, doc/ref/models/model_copyright.rst, doc/ref/modules/mod_copyright.rst, doc/ref/notifications/auth.rst, doc/ref/notifications/notification/auth_identity_types.rst, doc/ref/notifications/notification/identity_update_done.rst, doc/ref/notifications/notification/meta-auth_identity_types.rst, doc/ref/notifications/notification/meta-auth_validated.rst, doc/ref/notifications/notification/meta-identity_password_match.rst, doc/ref/notifications/notification/meta-identity_update_done.rst, doc/ref/notifications/notification/meta-identity_verification.rst, doc/ref/notifications/notification/meta-identity_verified.rst, doc/ref/notifications/notification/meta-mailinglist_mailing.rst, doc/ref/notifications/notification/meta-mailinglist_message.rst, doc/ref/notifications/user.rst
Adds notification: `#identity_update_done{}`
Adds error message if external authentication is forced.
=> Add notification if identity is changed. Add error message for forced external logons.

apps/zotonic_core/src/models/m_config.erl, apps/zotonic_mod_cron/src/mod_cron.erl, apps/zotonic_mod_development/priv/templates/admin_development.tpl, apps/zotonic_mod_development/src/mod_development.erl, apps/zotonic_mod_logging/src/mod_logging.erl, apps/zotonic_mod_logging/src/models/m_log.erl, apps/zotonic_mod_logging/src/support/logging_logger_handler.erl, apps/zotonic_mod_logging/src/support/z_logging_logger_handler.erl, apps/zotonic_mod_wires/priv/lib/js/apps/zotonic-wired.js
Add an option to log the erlang console log to the browser console.
All log events for the current site, or generic events without a `site` in the metadata are sent to the browser's console log.
This is turned on by default if the environment is `development` and the class `environment-development` is set on the html tag.
For non development sites it can be turned on by an admin on the `admin/development` page.
=> mod_logging/mod_development: add logging to the browser console

apps/zotonic_core/src/smtp/z_email_server.erl, apps/zotonic_mod_admin_config/priv/templates/admin_config_email.tpl
Fix #3490 
Add a configuration to allow sending email to specific email addresses and domains, even if an email override is set.
=> email: add config site.email_override_exceptions to allow specific email addresses if an override is set

apps/zotonic_mod_authentication/src/controllers/controller_authentication.erl, apps/zotonic_mod_ratelimit/priv/templates/_admin_status.tpl, apps/zotonic_mod_ratelimit/src/mod_ratelimit.erl, apps/zotonic_mod_ratelimit/src/models/m_ratelimit.erl
Fix an issue where trying to set a complex-enough password could trigger a rate limit exclusion.
Also ensure that the external pw complexity checks are done on pw change.
=> mod_authentication: ensure pw complexity check is outside ratelimit

apps/zotonic_mod_auth2fa/priv/templates/admin_auth2fa_config.tpl, apps/zotonic_mod_auth2fa/src/mod_auth2fa.erl
Make the per-user-group 2FA setting level 3.
Forcing a 2FA code on logon.
=> mod_auth2fa: make the 'forced' per ug level 3

apps/zotonic_mod_acl_user_groups/src/support/admin_acl_rules_rsc.erl
This fixes a problem where a site ACL observer allows extra permissions, but the content group select in the resource create dialogs did not reflect those extra content group options.
=> mod_acl_user_groups: use notification to check which content groups can be used for a category insert

apps/zotonic_mod_copyright/priv/templates/_admin_edit_sidebar.tpl, apps/zotonic_mod_copyright/priv/templates/_copyright.tpl, apps/zotonic_mod_copyright/src/models/m_copyright.erl
Use the rights name for storage, which is compatible with previous systems.
=> mod_copyright: use name to store rights, support lookup by url

apps/zotonic_core/src/support/z_fetch.erl
Small fix for language option.
=> core: fix default options for z_fetch

apps/zotonic_launcher/src/command/zotonic_command.erl, apps/zotonic_launcher/src/command/zotonic_command_nodename.erl
Fixes an issue where the Erlang distribution would open a port listening on all IP addresses when using a SNAME.
Instead of the local hostname we will add 'localhost' as the hostname part.
This also fixes issues with machines that change names (like sometimes happens on macOS) and with Ubuntu where the hostname is per default mapped to 127.0.1.1
Issue #3826
=> zotonic_launcher: use '@localhost' for default SNAME for shortnames listen on 127.0.0.1

apps/zotonic_launcher/src/zotonic_launcher.app.src, apps/zotonic_mod_admin/priv/templates/_admin_status_alert.tpl, apps/zotonic_mod_admin/priv/templates/_admin_system_status.tpl, apps/zotonic_mod_admin/priv/templates/admin.tpl, apps/zotonic_mod_admin/src/models/m_admin_status.erl
Add an alert that the system memory is running low and shows more system memory status.
=> Add os memory status

apps/zotonic_mod_fileuploader/src/support/z_fileuploader.erl
By pre-allocating all the space for the to-be-uploaded file we prevent a problem with running out of space during the file upload but instead can signal the disk space problem before the uploading starts.
=> mod_fileuploader: pre-allocate uploaded file to prevent enospace during uploads

modules/mod_base/controllers/controller_file.erl
This fixes an issue where the `x-robots-tag` was set but subsequently not returned in the response headers.
=> mod_base: fix an issue where for file requests the x-robots-tag was not returned in the response headers

apps/zotonic_mod_l10n/src/mod_l10n.erl, apps/zotonic_mod_translation/src/mod_translation.erl
Set the `z.tz` and `z.lang` cookies with `SameSite=Lax` for additional security.
=> Set z.tz and z.lang cookkies to SameSite Lax

apps/zotonic_core/src/smtp/z_email_server.erl
This fixes a semantic problem where with 'ssl' we really meant "use starttls".
Now we can connect using SMTP and issue a STARTTLS command to upgrade the connection.
This also fixes problems with SSL options during connect on OTP26+ when 'smtp_ssl' was defined in the zotonic.config for a smtp relay.
=> zotonic_core: map config 'smtp_ssl' to '{tls, always}'

apps/zotonic_core/src/support/z_media_import.erl, apps/zotonic_mod_admin/src/support/z_admin_media_discover.erl, apps/zotonic_mod_oembed/src/support/oembed_client.erl
Fixes #3852 
This works around the problem that Vimeo returns 429 errors on fetching their pages.
If the URL metadata fetcher returns a 429 error then we retry with a faked import record. If this import does return import candidates then those are returned, otherwise the original 429 error is returned.
In case of Vimeo it turns out that the OEmbed API endpoint does not return a 429 error, so the `mod_oembed` can return correct embed information for Vimeo.
It would be nicer if `mod_video_embed` could also handle this, as it does return cleaner embed code. For the moment this seems a good solution.
=> zotonic_core: fix a problem where Vimeo could not be embedded due to 429 errors

apps/zotonic_mod_translation/priv/templates/_translation_edit_languages.tpl
This fixes a problem where the translation scripts could fill in the wrong translations if the input name was repeated in multiple blocks.
This is fixed by restricting the context in which the src text of the text should be present.
=> mod_translation: fix a problem with translating texts in repeating blocks

apps/zotonic_core/src/models/m_media.erl, apps/zotonic_core/src/support/z_media_import.erl, apps/zotonic_core/src/support/z_sanitize.erl, apps/zotonic_mod_admin/src/support/z_admin_media_discover.erl
This allows to import URLs like with non-escaped UTF8 characters in the path, query or fragment.
=> core: clean up URLs for media import

apps/zotonic_core/src/smtp/z_email.erl, apps/zotonic_core/src/smtp/z_email_server.erl
The CSP nonce is needed to style tags in emails when previewing emails in the browser.
We don't need to have a CSP nonce when sending emails, but we have to ensure that one is set to that the templates render without a warning that the CSP nonce is not set.
=> core: ensure that the csp-nonce is set when sending emails

apps/zotonic_mod_admin/src/models/m_admin_status.erl
There is fix on its way:
https://github.com/erlang/otp/pull/8776
=> mod_admin: disable memory warning till OTP has been fixed

apps/zotonic_core/src/support/z_media_import.erl, apps/zotonic_mod_oembed/src/mod_oembed.erl
This fixes a problem where for Soundcloud embeds the first option would be an image, and the second option the actual embed.
Example Soundcloud URL for testing:
https://soundcloud.com/ublpodcast/hoe-contractarbeiders-het-surinaamse-slavernijsysteem-voortzetten?utm_source=clipboard&utm_campaign=wtshare&utm_medium=widget&utm_content=https%253A%252F%252Fsoundcloud.com%252Fublpodcast%252Fhoe-contractarbeiders-het-surinaamse-slavernijsysteem-voortzetten
=> mod_oembed: change prio of 'document' embeds

priv/sites/zotonic_status/models/m_sitemodule.erl, priv/sites/zotonic_status/templates/_sites.tpl
Proof of concept for discussing whether it would be good to have an indication of site module status in the status overview.
Use case is any server with a lot of sites, to quickly be able to see whether any site modules happen to not have started or have stopped due to e.g. a maintenance restart.
=> [zotonic_status] Module health status

modules/mod_editor_tinymce/filters/filter_is_supported_version.erl, modules/mod_editor_tinymce/templates/_editor.tpl
_Note: this is a fix for Zotonic-0.x_
Problem: It can happen that the configured version of the editor is not available and no template can be included.
This can happen with misconfigurations but also with time: a version that used to be available can become unsupported and updating the mod_editor_tinymce would break the editor on such a website.
Solution: Make selecting the template to include more robust and default to the newest version when the configured one can't be used. Additionally, log a warning when this happens.
=> Make tinymce default to newest when the configured version is unsupported

apps/zotonic_core/src/support/z_module_indexer.erl, apps/zotonic_core/src/support/z_module_manager.erl, apps/zotonic_core/src/support/z_template.erl, apps/zotonic_mod_search/src/mod_search.erl, apps/zotonic_mod_search/src/support/search_facet.erl
When creating the pivot facet table, the current site module _must_ be running.
=> mod_search: ensure all modules and site is running before (re)creating the facet table

apps/zotonic_core/src/db/z_db_pgsql.erl, apps/zotonic_core/src/models/m_rsc.erl, apps/zotonic_core/src/support/z_acl.erl, apps/zotonic_mod_base/src/controllers/controller_http_error.erl
If a SQL error occurs, then the request process was killed by the SQL connection worker before it could return a 500 error.
This is flxed by not killing the request process.
Also the error view of the specific error was fixed in that the stack trace is removed from the error.
The rsc model is changed to return `enoent` for rsc ids outside the 1..maxint4 range of the database. This gives better error handling when such a rsc id is requested.
=> core: fix an issue where a SQL error did not return http 500 error

apps/zotonic_mod_import_csv/src/support/import_csv.erl
Fixes importing resources via csv tables.
Values are now read as binaries. They where skipped during mapping, but values from the row should have been concatenated.
=> Fix importing csv values. Values are now binaries

apps/zotonic_mod_wires/priv/lib/js/apps/zotonic-wired.js, apps/zotonic_mod_wires/src/actions/action_wires_event.erl
Cause was the tightened CSP settings, which prohibited the evaluation of the z_submit_action data attribute. This is fixed by making the attribute a function and evaluating the function.
=> mod_wires: fix eval a problem where wired form submit actions were not evaluated

apps/zotonic_core/include/zotonic_log.hrl, apps/zotonic_core/src/db/z_db.erl
This corrects the types used with the z_db routines, which were too strict.
Also opens the zlog to user defined log notifications.
=> core: more relaxes z_db:insert/update/delete type for id. Extend zlog type

apps/zotonic_mod_cookie_consent/priv/lib/js/z.cookie_consent.js
Problem: once cookies are accepted, the cookie_consent mod replaces script tags that required consent with a new tag that gets executed. However, if there was a nonce set up for the CSP headers this isn't carried over, which results in a failure to run the script with the default 'script-src' CSP directive.
Solution: modify the replacing code to add the nonce.
=> zotonic_mod_cookie_consent: carry nonce on script replacement

apps/zotonic_core/src/support/z_template_compiler_runtime.erl
Fix a problem where the template render could crash on displaying an illegal date.
=> core: catch date formatting exception for value representations

modules/mod_email_status/mod_email_status.erl, modules/mod_email_status/templates/_email_status_view.tpl, src/smtp/z_email_receive.erl
- Blocking an email address now also blocks receiving email from that email address
- Allow users with `use.mod_email_status` permission to block email addresses
=> mod_email_status: allow block of incoming email

include/zotonic_notifications.hrl, modules/mod_email_status/mod_email_status.erl, modules/mod_email_status/models/m_email_status.erl, src/smtp/z_email_receive.erl, src/smtp/z_email_server.erl
Make a distinction between blocked and bouncing.
If blocked then do not send and do not receive.
If bouncing then do not send.
This back-ports code from master (1.x) to 0.x
=> smtp: check if email address is ok before sending email (0.x)

apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_core/src/smtp/z_email_server.erl, apps/zotonic_mod_email_status/src/mod_email_status.erl
This makes a distinction between blocked and bouncing email addresses.
Never send email to blocked and/or bouncing email addresses.
This used to be the case before `#email_is_blocked` notification started to only check for blocked status. As is needed by the email receive routines.
=> core: check if recipient is ok before sending email

apps/zotonic_listen_smtp/src/zotonic_listen_smtp_receive.erl
Automatically forwarded emails retain the original `To` but don't have the blocked email address as the `From`.
On receive, also check the `To` for a blocked email address.
=> smtp: on receive block, also check 'to' header

apps/zotonic_mod_wires/priv/lib/js/apps/zotonic-wired.js
Typo, wrong variable.
Add console message if `z_script_nonce` is not set and a fallback to `eval` is tried.
=> mod_wires: fix fallback to js eval

apps/zotonic_mod_search/src/support/search_facet.erl, apps/zotonic_mod_search/src/support/search_query.erl
This fixes a problem where a faceted search would not return the searched facet if the result set was empty.
Not having the searched facet in the facet values causes the select boxes to exclude the facet from their options. If combined with a non-faceted search that excludes the searched for facet value, then the select box will reset to empty. This will mess up the search question in live search boxes.
This problem is fixed by ensuring the searched facet value is present with a count of 0.
Only facet searches with the equal or non-equal operator are considered.  And from those only facets with a 'count', excluding range and other possible facets.
=> mod_search: in faceted search, ensure the searched facet value is present

apps/zotonic_core/src/models/m_rsc_gone.erl, apps/zotonic_mod_backup/priv/templates/_admin_backup_widget_config_export_panel.tpl, apps/zotonic_mod_backup/priv/templates/admin_backup_revision.tpl, apps/zotonic_mod_backup/src/models/m_backup_revision.erl, doc/ref/modules/mod_backup.rst
This is a follow-up to #3546 covering the point:
> For the cleanup of person data (GDPR) we will need a shorter period.
Specifically, this adds (configurable) periods to:
1. delete revisions of active user's resources (defaults to 90 days);
2. delete all revisions of users that have been deleted for some time (defaults to 30 days);
=> mod_backup: stricter periodic cleanup of revisions for users

apps/zotonic_core/src/support/z_auth.erl, apps/zotonic_core/src/support/z_mqtt_sessions_runtime.erl, apps/zotonic_mod_authentication/priv/templates/_dialog_session_close.tpl, apps/zotonic_mod_authentication/priv/templates/sessions.tpl, apps/zotonic_mod_authentication/src/controllers/controller_authentication.erl, apps/zotonic_mod_authentication/src/mod_authentication.erl, apps/zotonic_mod_authentication/src/support/z_authentication_tokens.erl
Fixes a problem where the session-id of a logging-off MQTT session is changed (because it was still connected by the client) and created a dummy session entry in the sessions overview.
Also add some more explanation about what the sessions overview shows.
=> mod_authentication: better session invalidation and explanation

priv/sites/zotonic_status/models/m_sitemodule.erl, priv/sites/zotonic_status/zotonic_status.erl, src/support/z_sites_manager.erl
If site modules crash after a zotonic upgrade or server restart they will get restarted by the site manager. The check runs once every 10 minutes.
Logs a debug message on check and a warning on any unhealthy module it finds and is about to restart.
As suggested in https://github.com/zotonic/zotonic/pull/3864 (PR on site module health indicators).
=> zotonic_status: Automatically restart site modules if needed

apps/zotonic_mod_mailinglist/src/models/m_mailinglist.erl, doc/ref/modules/mod_mailinglist.rst
Add a model call to display the number of subscribers to a mailinglist. When the user is able to see the mailinglist, this value can be retrieved.
`{{ m.mailinglist.count_recipients[id] }}`
=> Add a way to display the number of subscribers to a mailinglist

start-docker.sh
Fix the docker compose start command, as docker changed it.
=> docker: change docker start command. Fix #3904

apps/zotonic_core/src/markdown/markdown.erl, apps/zotonic_core/src/models/m_rsc_update.erl, apps/zotonic_core/src/smtp/z_email_server.erl, apps/zotonic_core/src/support/z_file_entry.erl, apps/zotonic_core/src/support/z_jsxrecord.erl, apps/zotonic_core/src/support/z_logger_formatter.erl, apps/zotonic_core/src/support/z_module_manager.erl, apps/zotonic_core/src/support/z_mqtt_sessions_runtime.erl, apps/zotonic_core/src/support/z_pivot_rsc.erl, apps/zotonic_core/src/support/z_pivot_rsc_task_job.erl, apps/zotonic_core/src/support/z_proc.erl, apps/zotonic_core/src/support/z_props.erl, apps/zotonic_core/src/support/z_site_startup.erl, apps/zotonic_core/src/support/z_site_sup.erl, apps/zotonic_core/src/support/z_sites_dispatcher.erl, apps/zotonic_launcher/src/zotonic.erl, apps/zotonic_listen_mqtt/src/zotonic_listen_mqtt_handler.erl, apps/zotonic_mod_acl_user_groups/src/mod_acl_user_groups.erl, apps/zotonic_mod_acl_user_groups/src/support/admin_acl_rules.erl, apps/zotonic_mod_admin/priv/templates/_admin_edit_content_address.tpl, apps/zotonic_mod_admin/src/support/admin_rsc_diff.erl, apps/zotonic_mod_admin_merge/src/mod_admin_merge.erl, apps/zotonic_mod_backup/src/mod_backup.erl, apps/zotonic_mod_import_wordpress/src/mod_import_wordpress.erl, apps/zotonic_mod_ssl_letsencrypt/src/support/z_letsencrypt.erl, apps/zotonic_mod_survey/src/support/survey_schema.erl, apps/zotonic_mod_tkvstore/src/mod_tkvstore.erl, apps/zotonic_notifier/src/zotonic_notifier_worker.erl
* fixes an issue in markdown-to-html where it could crash on certain inputs
* allow maps with atoms for rsc updates
* use proc_lib to spawn processes, for better logging
* restrict depth of certain logged terms with the default logger formatter
* copy logger metadata to certain spawned processes
=> Misc. fixes. Better logging. Use proc_lib for spawn.

apps/zotonic_mod_seo/priv/templates/_html_head_seo.tpl
Fixes the inclusion of the googletagmanager script by adding a nonce, which [seems to have gone unnoticed](https://github.com/zotonic/zotonic/commit/e462f0c23e57b7eb9c7500b17f7533b15b567534#diff-361930818af91d41f4fca965e9a2e1d8116d030f8ffa2af22d60a8af2e5cf864R52) in #2870
=> Add nonce to googletagmanager's script

apps/zotonic_core/src/csv/z_csv_writer.erl, apps/zotonic_mod_mailinglist/src/controllers/controller_mailinglist_export.erl
Fix #3903
Fix a problem where exporting addresses of a mailinglist could crash.
Add the preferred language of the recipient to the export.
=> mod_mailinglist: fix a problem when exporting mailinglist recipients

apps/zotonic_mod_admin/priv/templates/_admin_edit_content.query.tpl, apps/zotonic_mod_admin/priv/templates/_admin_edit_header.tpl, apps/zotonic_mod_admin/priv/templates/_admin_overview_list.tpl, apps/zotonic_mod_admin/priv/templates/_admin_status_alert.tpl, apps/zotonic_mod_admin/priv/templates/_admin_system_content_warning.tpl, apps/zotonic_mod_admin/priv/templates/admin_media.tpl
If an item is protected then it can't be deleted.
This can be confusing.
Show a lock icon on protected resources, so it is clear that they can't be deleted.
Ref #3923
=> mod_admin: add lock icon after title of protected resources

apps/zotonic_core/src/support/z_logger_formatter.erl
Sometimes log messages are so long that the initial spot of the log is not visible in the terminal history. This truncates values to 1000 characters, so that most information is visible, but the log message is not too long.
=> core: truncate output values of logger

apps/zotonic_mod_base/src/controllers/controller_page.erl
The `Last-Modified` header of resource pages was not set. Let the page controller return this modification date.
The template controller typically renders many non-resource related content, so do not set the last-modified header for these pages.
=> mod_base: let controller_page set the last-modified header

rebar.config.lock
Makes the filezcache tables public to prevent a problem with deleting entries.
=> Upgrade filezcache to 2.2.0 (0.x version)

src/models/m_rsc_update.erl
Fixed by checking if the resource exists before proceeding with the update.
=> core: fix a problem where updating a non-existing resource could result in a crash (0.x)

src/support/z_pivot_rsc.erl
This can happen on sites with a high frequency of (parallel) updates.
Fix by not locking the table and making the transaction faster by having less sql queries.
=> core: fix a problem where the pivot queue could give locking errors (0.x)

apps/zotonic_core/src/support/z_datetime.erl, apps/zotonic_mod_oauth2/src/models/m_oauth2_service.erl
This gives extra feedback if there are problems with the access token exchange for Auth2 logon services.
=> mod_oauth2: add extra logging on oauth redirect

apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_mod_auth2fa/src/mod_auth2fa.erl, apps/zotonic_mod_authentication/src/mod_authentication.erl, apps/zotonic_mod_base/src/controllers/controller_page.erl, apps/zotonic_mod_oauth2/priv/lib/js/zotonic.oauth.worker.js, apps/zotonic_mod_oauth2/src/models/m_oauth2_service.erl
Fix a problem where the 2FA module would require setting a 2FA passcode on which the auth modules crashed because that error was unexpected.
Fixed by letting the 2FA module only return the passcode error on authentication using username_pw.
=> mod_oauth2: fix a problem with oauth logon crashing on required 2FA

apps/zotonic_mod_authentication/priv/lib/js/zotonic.auth.worker.js
This could happen in Chrome when using the back/forward cache and an user was known in the sessionStorage.
=> mod_authentication: fix a problem where the page was sometimes not reloaded with the logged in user

apps/zotonic_mod_admin_frontend/priv/templates/_admin_frontend_edit.tpl, apps/zotonic_mod_admin_frontend/priv/templates/page_admin_frontend_edit.tpl
TinyMCE was loaded on every page edit using `<script src=...>` tags.
This gave CSP errors.
Only loading TinyMCE on the main page fixes the CSP errors.
=> mod_admin_frontend: fix an issue where tinymce could throw csp errors

apps/zotonic_core/src/support/z_search_props.erl
Fix #3943
Removes the `page` and `pagelen` args from the list.
=> core: Remove page and pagelen args from the list

apps/zotonic_core/src/models/m_media.erl, apps/zotonic_mod_filestore/src/mod_filestore.erl
If a preview was added to the medium record after the medium was generated, then the filestore module was not notified of the new file.
These missing preview files would only be uploaded if all files would be queued for upload to the filestore.
This affected especially embeds where the preview as asynchronously downloaded after creation of the medium record, such as Youtube and Vimeo embeds.
=> core: fix a problem where some media previews were not uploaded to the filestore

apps/zotonic_mod_l10n/src/support/l10n_country2iso.erl, apps/zotonic_mod_l10n/src/support/l10n_iso2country.erl
Add mapping of different countries or country names with typos to ISO codes.
Add lookup of iso to country names in different languages.
Add Westbank and Gaza to iso/country table.
=> mod_l10n: improve country to iso mapping

docker-compose.yml
Fix #3951
The `version` declaration for docker-compose is deprecated: https://dev.to/pradumnasaraf/stop-versioning-your-docker-compose-file-1f41
=> #3951 Update docker-compose.yml - remove version as it is deprecated

apps/zotonic_mod_admin/priv/templates/_admin_status_alert.tpl
Problem: SSL configuration warnings in the admin status are misreported when the user is not an admin.
When 'm.admin_status.is_ssl_application_configured' is rendered for a non-admin, the result is 'undefined' which is in turn negated to 'true' by a 'not', meaning that the warning always appears for these users.
Solution: Only show warnings in the admin panel to admin users.
=> Show admin warnings only to admin users

apps/zotonic_core/src/support/z_sites_dispatcher.erl
When redirecting to the primary hostname, first check if there is a redirect set for that hostname (and path) by the site.
This allows a hostalias to redirect to a specific page (or other URL).
=> core: check for non-primary hosts if redirect is defined

apps/zotonic_core/src/db/z_db.erl, apps/zotonic_core/src/db/z_db_table.erl, apps/zotonic_core/src/support/z_pivot_rsc.erl, apps/zotonic_core/test/z_db_tests.erl, apps/zotonic_mod_filestore/src/models/m_filestore.erl, apps/zotonic_mod_oauth2/src/models/m_oauth2_consumer.erl, apps/zotonic_mod_search/src/support/search_facet.erl
This makes it possible to add or remove facets or pivot table columns without rebuilding the facet or pivot table.
=> core: add z_db:alter_table/3 to alter a table according to a list of column defs

apps/zotonic_core/src/support/z_search_props.erl, apps/zotonic_mod_search/src/support/search_facet.erl, apps/zotonic_mod_search/src/support/search_query.erl
Fix for two main issues:
* If for a term an operator was passed without a value then the term was not considered empty
* If 0-count facets would be expanded to include the searched-for term, then the query terms from the qargs were not considered
=> mod_search: fix an issue where faceted search might not set the empty facets

apps/zotonic_mod_admin/src/validators/validator_admin_hasedge.erl, apps/zotonic_mod_wires/priv/lib/js/apps/zotonic-wired.js, apps/zotonic_mod_wires/priv/lib/js/modules/livevalidation-1.3.js, doc/ref/validators/validator_hasedge.rst
This fixes an issue where the form submit did not always wait for the evaluation of the sync validations.
The new `hasedge` validator can be used to check if an edge has been added. The connections are often not input fields so this check can now be done differently by using an hidden input element.
Fixed async submit in combination with Zotonic postbacks. Added extra classes: `if-has-validated`, `if-has-error`,
`if-form-validated` and `if-form-error`. They are used to hide/show messages on field (within a `.form-group`) or the
form level (within a `form`).
Example:
```django
<div class="form-group"> 
<input type="hidden" id="check-author" value="author">
{% validate id="check-author"
type={hasedge id=id minimum=1}
only_on_submit
%}
<p class="if-has-error" style="display: none">{_ You …
```
=> Refactor submit with async validators. Add async 'hasedge' validator.

apps/zotonic_core/src/support/z_tags.erl
Fix #3586
Ensure that the generated tag is `<img ..>` and not `<img ... />`
=> core: remove trailing slash from generated img tag

apps/zotonic_mod_wires/priv/lib/js/apps/zotonic-wired.js
This fixes a problem where declarations from one _eval_ leak to another _eval_.
For example variables, defined with `let a = 1;` will given an error if defined twice.
The new local context is created by adding `{ ... }` around the javascript expression.
This restores the way the old `eval()` worked before the security tightening.
=> mod_wired: ensure a local context for the js eval function

apps/zotonic_core/src/markdown/markdown.erl, apps/zotonic_core/src/markdown/z_html2markdown.erl, apps/zotonic_core/test/z_markdown_tests.erl
This is in preparation for embedding markdown as module documentation.
Not supported right now is triple-quoted-code blocks within indented lists.
To do:
Typical RST generated HTML:
```
<div class="highlight-django notranslate"><div class="highlight"><pre><span></span><span class="x">&lt;div class="form-group"&gt; &lt;!-- form-group has class "has-error" if validation fails --&gt;</span>
<span class="x">    &lt;input type="hidden" id="check-author" value="author"&gt;</span>
<span class="x">    </span><span class="cp">{%</span> <span class="k">validate</span> <span class="nv">id</span><span class="o">=</span><span class="s2">"check-author"</span>
<span class="nv">type</span><span class="o">={</span><span class="nv">hasedge</span> <span class="nv">id</span><span class="o">=</span><span …
```
=> core: add simple markdown support for triple and quadruple quoted code blocks

apps/zotonic_mod_admin/priv/templates/_admin_edit_block_addblock.tpl, apps/zotonic_mod_admin/priv/templates/_admin_edit_block_li.tpl, apps/zotonic_mod_admin/priv/templates/_admin_edit_blocks.tpl, apps/zotonic_mod_admin/priv/templates/blocks/_admin_edit_block_li_header.tpl, apps/zotonic_mod_admin/priv/templates/blocks/_admin_edit_block_li_text.tpl, apps/zotonic_mod_admin/src/mod_admin.erl, doc/ref/tags/tag_autoescape.rst, doc/ref/tags/tag_block.rst, doc/ref/tags/tag_cache.rst, doc/ref/tags/tag_comment.rst, doc/ref/tags/tag_extends.rst, doc/ref/tags/tag_if.rst, doc/ref/tags/tag_ifequal.rst, doc/ref/tags/tag_ifnotequal.rst, doc/ref/tags/tag_overrules.rst
This fixes an issue where there is confusion between template blocks and page blocks.
See discussion #3955 
The documentation needs to be adapted separately, for example when we cleanup the documentation (and move the reference docs into the erlang modules).
We settled on _page block_ and not on _page section_ to prevent miscommunication between developers (who see the term _blocks_ in their code) and end-users/project-managers (who would see _section_, which is then confusing).
In the documentation we need to consistently use the term _page block_ and _template block_ to disambiguate the meaning of the word _block_.
=> mod_admin: in the UI, rename 'block' to 'page block'

apps/zotonic_core/src/markdown/z_html2markdown.erl, apps/zotonic_core/test/z_markdown_tests.erl
This fixes a problem where HTML-to-Markdown could crash on tables with certain (non-)UTF8 data in the text.
=> core: fix a problem where html2markdown could crash on certain tables

apps/zotonic_core/src/markdown/z_html2markdown.erl, apps/zotonic_core/src/smtp/z_email.erl, apps/zotonic_core/src/smtp/z_email_server.erl
If an email was sent with a reply-to address that omits the domain then a reply-to header with the value `foo` could be encoded as `foo <@example.com>`
This fixes it by changing the email split function and adding extra checks in the email encoding functions for the reply-to and from headers.
=> core: fix an issue where when sending emails the reply-to address could be wrongly encoded

apps/zotonic_core/src/models/m_media.erl, apps/zotonic_core/src/support/z_datetime.erl, apps/zotonic_core/src/support/z_media_import.erl, apps/zotonic_core/src/support/z_sanitize.erl, apps/zotonic_mod_admin/src/support/z_admin_media_discover.erl
Allow supplying a "data:" url for downloading medium entry files.
Also a small fix for some date time calculation with a year before 0.
=> core: allow download of media files using data urls

apps/zotonic_mod_email_status/src/models/m_email_status.erl
This fixes an issue where erroneous email addresses could be sent to again after more than two years.
=> mod_email_status: keep error addresses to prevent resending

apps/zotonic_mod_ssl_letsencrypt/src/filters/filter_is_letsencrypt_valid_hostname.erl, apps/zotonic_mod_translation/src/mod_translation.erl
Fix an issue where the self-ping could redirect because it was prefixed with the language code.
=> mod_translation: ensure .well-known and .zotonic URLs do not get a language code prefixed

apps/zotonic_listen_smtp/src/zotonic_listen_smtp_receive.erl
Many emails use tables for formatting.
Those tables should be ignored when creating the text version of emails.
=> smtp: do not format MD tables for received emails

apps/zotonic_core/src/support/z_context.erl, apps/zotonic_mod_wires/priv/lib/js/apps/zotonic-wired.js
This fixes an issue with old Safari (14 and earlier) where the auth exchange with the server can not be started and thus no interactivity would be possible.
This is caused by not being able to load the Auth web worker.
We now signal this issue and show a growl message if after 10 seconds the started auth worker is still not registered.
For now this message is only in English.
Also part of this merge:
* Remove `*` from the `z_context:get_q_all_noz/1` query args  (now compatible with the map version)
* Add `wss:` to the default CSP connect-src, for older Safari browsers
=> mod_wires: signal user if they are having difficulties with authentication

apps/zotonic_mod_wires/priv/lib/js/apps/zotonic-wired.js
This fixes an issue where opening the bridge to the "opener" window would result in a security exception and stop the wires initialization code.
=> mod_wires: fix an issue with bridging to opener if opened from another site

apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_listen_smtp/src/zotonic_listen_smtp_receive.erl
Just to make the email receive easier (and safer) to use.
=> smtp: add some extra typedefs for email receive

apps/zotonic_core/src/support/z_search.erl, apps/zotonic_listen_smtp/src/zotonic_listen_smtp_receive.erl, apps/zotonic_mod_base/src/controllers/controller_api.erl, apps/zotonic_mod_base/src/filters/filter_from_json.erl, doc/ref/filters/filter_from_json.rst, doc/ref/filters/variables/index.rst
The `from_json` filter parses a JSON string and returns the (structured) value for further use in the template.
The search option `is_single_page` prevents further fetching of the next pages, which is used to estimate the number of results for the query. Instead it only fetches one additional row so that the `next` flag of the search result van be set.
=> Add filter from_json.  Add option is_single_page to search

apps/zotonic_core/src/install/z_install.erl, apps/zotonic_core/src/install/z_install_update.erl, apps/zotonic_core/src/support/z_pivot_rsc.erl
This adds a `priority` field to the pivot queue.
Re-pivots are inserted with priority 2, normal pivots with 1, and quick-to-be-done with priority 0.
=> core: add priority to the pivot queue

apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_listen_smtp/src/zotonic_listen_smtp_receive.erl, apps/zotonic_mod_email_relay/src/mod_email_relay.erl
Ensure that the status message for email relay is a binary.
Fix type of status message in `#email_failed` notification.
Make email receive more robust against email addresses.
=> mod_email_status: ensure binary utf8 status message

apps/zotonic_mod_mailinglist/src/mod_mailinglist.erl, apps/zotonic_mod_mailinglist/src/models/m_mailinglist.erl
This fixes a problem where uploading a CSV file with recipients to a mailinglist could result in an SQL error.
=> mod_mailinglist: fix an issue with uploading recipients to mailinglist

apps/zotonic_core/src/models/m_site.erl, apps/zotonic_core/src/support/z_sites_manager.erl, apps/zotonic_mod_admin/priv/templates/admin_status.tpl, apps/zotonic_mod_admin/src/actions/action_admin_admin_tasks.erl
This adds a button in the admin/status to reload the configuration of the site.
After the configuration has been reloaded, the dispatcher will also be requested to update so that any changed domain names are registered.
=> core: add function to reload the site configuration

apps/zotonic_mod_wires/priv/lib/js/apps/zotonic-wired.js
This makes it easier to fix some issues with the login and password reset if the path is missing.
=> mod_wires: warn in console for missing data cotonic path

apps/zotonic_core/src/support/z_config.erl, apps/zotonic_launcher/priv/config/zotonic.config.in, apps/zotonic_listen_smtp/src/zotonic_listen_smtp.erl
If an email proxy is used in front of Zotonic then STARTTLS is not needed.
This makes it possible to disable the STARTTLS extension for the whole Zotonic server.
=> smtp: add option smtp_starttls to optionally disable smtp receive starttls extension

cloud-init/zotonic-cloudinit.yml
Newer OTP version for building servers
=> cloudinit: update to OTP27.2

priv/sites/zotonic_status/models/m_sitemodule.erl, priv/sites/zotonic_status/zotonic_status.erl
This improves the detection of crashed modules, because it looks at the id of the processes fired up for the respective site modules.
=> zotonic_status: Use whereis for detection of crashed site modules

docker/Dockerfile.dev, docker/docker-entrypoint.sh
The `sass` command is not available on Alpine Linux.
Switch to de Debian image to be able to use `sass`.
This gives a better development environment.
Also fix an issue with the security directory not being placed in docker-data.
=> Docker: use debian base image

apps/zotonic_core/priv/translations/zotonic.pot, apps/zotonic_launcher/src/command/zotonic_cmd_pot.erl, apps/zotonic_mod_translation/src/mod_translation.erl
Adds the two commands:
* bin/zotonic pot zotonic
* bin/zotonic pot [sitename]
This makes it easier to generate all pot files.
=> zotonic_launcher: add command to generate pot files

apps/zotonic_mod_seo/priv/templates/admin_seo.tpl, apps/zotonic_mod_seo_sitemap/priv/templates/_admin_seo.tpl, apps/zotonic_mod_seo_sitemap/src/mod_seo_sitemap.erl
This makes it easier for SEO people to administrate the sitemap.
=> mod_seo: add sitemap rebuild button to seo settings page

apps/zotonic_mod_filestore/priv/templates/admin_filestore.tpl
List European alternative block storage providers.
Make clear that Google and Amazon are USA based.
=> mod_filestore: list European S3 alternatives

apps/zotonic_core/include/zotonic_file.hrl, apps/zotonic_core/src/support/z_media_cleanup_server.erl, apps/zotonic_core/src/support/z_proc.erl, apps/zotonic_mod_filestore/src/mod_filestore.erl, apps/zotonic_mod_filestore/src/models/m_filestore.erl, apps/zotonic_mod_filestore/src/support/filestore_admin.erl, apps/zotonic_mod_filestore/src/support/filestore_request.erl, apps/zotonic_mod_filestore/src/support/filestore_uploader.erl
Fix #3726 
Before deleting a file from the filestore, check if the service url matches with the location to be deleted.
This fixes an issue where files on a service that is not configured could be deleted if the credentials were valid for that service as well.
=> mod_filestore: only delete files if service url matches

apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_core/src/support/z_context.erl, apps/zotonic_mod_seo/priv/templates/_html_head_seo.tpl, apps/zotonic_mod_seo/src/mod_seo.erl, doc/ref/models/model_email_relay.rst, doc/ref/notifications/email.rst, doc/ref/notifications/notification/content_security_header.rst, doc/ref/notifications/notification/email_is_recipient_ok.rst, doc/ref/notifications/notification/meta-auth_postcheck.rst, doc/ref/notifications/notification/meta-content_security_header.rst, doc/ref/notifications/notification/meta-email_failed.rst, doc/ref/notifications/notification/meta-email_is_recipient_ok.rst, doc/ref/notifications/notification/meta-email_received.rst, doc/ref/notifications/other.rst
Also, for Google trackers amend the CSP headers and update the GTM javascript to be aware of the nonce.
=> core: add `#content_security_header` notification to modify the CSP

apps/zotonic_core/src/models/m_modules.erl, apps/zotonic_core/src/support/z_module_manager.erl, apps/zotonic_mod_admin_modules/priv/templates/admin_modules.tpl, apps/zotonic_mod_mailinglist/priv/templates/_scomp_mailinglist_subscribe.tpl, apps/zotonic_mod_search/src/support/search_facet.erl
This fixes an issue where the facets would not be updated if there is a module in `stopped` state, even if that module is not activated.
Also add a table to the admin/modules with all modules that are activated but not present.
=> mod_search: fix facet check for active modules

apps/zotonic_core/src/support/z_lib_include.erl, apps/zotonic_mod_editor_tinymce/priv/templates/tinymce-4.9.3/_editor.tpl, apps/zotonic_mod_editor_tinymce/priv/templates/tinymce-5.10.2/_editor.tpl, apps/zotonic_mod_seo/priv/templates/_html_head_seo.tpl, apps/zotonic_mod_seo/src/mod_seo.erl
Fix an issue with the nonce on GTM tracking tags.
If (and only if) GTM is enabled then the `'strict-dynamic'` option is added to `script-src` CSP.
If this is done then _all_ script tags need a CSP nonce attribute.
So we add now the nonce to `lib` generated script tags and to the tinymce script tags.
Other tags in other modules need to be changed by hand (if they have manual script tags).
Also add `id` attributes to the GTM and GTAG script tags, these can be used in the GTM tag manager configuration.
=> mod_seo: tune gtm code for nonce

apps/zotonic_mod_seo/priv/templates/admin_seo.tpl, apps/zotonic_mod_seo/src/mod_seo.erl
GTM allows to inject or add custom code to a site.
This adds an option to let the user explicitly accept the risk of doing so.
If this checkbox is checked _and_ the GTM tracking code is filled in, then the `'strict-dynamic'` policy is added to the site's `script-src` CSP.
=> mod_seo: for gtm, add option to accept risk of custom code

apps/zotonic_core/src/models/m_acl.erl, apps/zotonic_core/src/support/z_acl.erl, apps/zotonic_core/src/support/z_auth.erl, apps/zotonic_mod_authentication/src/mod_authentication.erl
This adds an ACL check for testing if a user is allowed to switch to another user.
Also adds `m.acl.sudo_user` to check the original user account the user used to log on.
=> auth: ACL support for switching users (and back)

apps/zotonic_mod_admin/priv/templates/_admin_edit_sidebar_parts.tpl
It could be useful to be able to extend the side panel in the admin.
At the moment I'm working on a analytics module for zotonic, and want to add a panel displaying the number of views / # unique sessions and unique users visiting a resource.
(needs some styling)
At the moment it is not possible to add a panel like this. This PR makes it possible.
=> Add the possibility to expand the admin sidepanel

apps/zotonic_core/src/db/z_db_pgsql.erl, apps/zotonic_core/src/support/z_module_sup.erl, apps/zotonic_core/src/support/z_sites_sup.erl, apps/zotonic_core/src/zotonic_core.erl, apps/zotonic_filehandler/src/zotonic_filehandler_app.erl, apps/zotonic_filewatcher/src/zotonic_filewatcher_app.erl, apps/zotonic_launcher/src/zotonic_launcher_app.erl
This fixes a problem where if an essential application crashes the Erlang node keeps on running without that application. 
The solution is to make the applications permanent, which on application failure will crash the Erlang node. The node will then be restarted by `heart`.
Sites and modules are started as temporary apps.
=> Fix a problem where a crashed application does not restart Zotonic

apps/zotonic_core/src/models/m_identity.erl, apps/zotonic_core/src/support/z_config.erl, apps/zotonic_launcher/priv/config/zotonic.config.in
Add the config `ip_allowed_admin` to (optionally) restrict the IP addresses the admin user can logon from.
=> Add config ip_allowed_admin to restrict admin access

src/support/z_session.erl
Fix persistent id, set if undefined. If empty list then persistent id is not yet set.
Found when submitting mod_survey as anonymous user. The persistent id was empty, this created the entries to not be shown in the admin interface because they are grouped by user, which was impossible with a empty persistent id.
=> Fix persistent id, set if undefined

apps/zotonic_mod_admin/priv/templates/admin_base.tpl, apps/zotonic_mod_authentication/priv/lib/js/zotonic.auth.worker.js
This fixes an issue where in-flight zotonic-auth fetch calls could interfere with each other when executed in parallel.
Examples when this could happen are with a bit slower connections and switching users.
Also fix an issue where the colonic-pathname-search attribute was not set in the admin.
=> mod_authentication: prevent race conditions when polling auth api

apps/zotonic_mod_search/src/support/search_query.erl, apps/zotonic_mod_search/test/mod_search_db_tests.erl
If rows are counted, then the sort terms are removed.
If a SQL argument is only used in the sort term, then too many arguments are supplied and PostgreSQL will complain about the type of the over-supplied argument.
This is now fixed by not supplying extra arguments (the ranking behavior) when counting rows.
=> mod_search: fix a problem where counting rows could result in a SQL error

apps/zotonic_core/src/models/m_rsc_import.erl
This fixes an issue where if a pages was imported, and it contained a video reference in a body text, then the depiction of that video was not imported.
This issue is fixed by importing embedded media in the same manner as other referenced resources.
=> core: fix an issue where on import video depictions were not copied

apps/zotonic_mod_admin_identity/priv/templates/_identity_password.tpl, apps/zotonic_mod_authentication/src/validators/validator_authentication_acceptable_password.erl, doc/ref/validators/validator_acceptable_password.rst
This fixes an issue where the username could not be changed because the allowed password check didn't accept an empty password.
=> mod_identity: fix an issue where the username could not be changed. Fix #4068

apps/zotonic_launcher/src/zotonic_launcher_config.erl
Fix an issue where start site could crash if multiple config files are present.
=> Fix an issue with reading multiple config files

apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_core/src/db/z_db.erl, apps/zotonic_core/src/install/z_install.erl, apps/zotonic_core/src/install/z_install_update.erl, apps/zotonic_core/src/models/m_media.erl, apps/zotonic_core/src/support/z_file_locate.erl, apps/zotonic_core/src/support/z_media_archive.erl, apps/zotonic_core/src/support/z_media_cleanup_server.erl, apps/zotonic_launcher/priv/config/zotonic.config.in, apps/zotonic_mod_backup/priv/templates/_admin_backup_diff.tpl, apps/zotonic_mod_backup/priv/templates/_admin_backup_list.tpl, apps/zotonic_mod_backup/priv/templates/_dialog_backup_revert_confirm.tpl, apps/zotonic_mod_backup/priv/templates/admin_backup_deleted.tpl, apps/zotonic_mod_backup/priv/templates/admin_backup_revision.tpl, apps/zotonic_mod_backup/src/controllers/controller_admin_backup_revision.erl, apps/zotonic_mod_backup/src/mod_backup.erl, apps/zotonic_mod_backup/src/models/m_backup_revision.erl, apps/zotonic_mod_filestore/priv/templates/admin_filestore.tpl, apps/zotonic_mod_filestore/src/models/m_filestore.erl, apps/zotonic_mod_filestore/src/support/filestore_config.erl
Add a weekly backup to the schedule.
The Sunday backup is now replaced with a weekly backup.
We keep the last 5 weekly backups.
The weekly backups are numbered `-w0`...`w4` and their week number is calculated using the Gregorian days of the current date.
The old `-7` dump is removed after a week and will not be made again (as on Sundays we now make a weekly backup).
To do:
- Recover missing dependent
- Recover incoming (referring) edges
=> mod_backup: add weekly, edge and medium backups

apps/zotonic_core/src/models/m_rsc.erl
Problem: `pivot_geocode_qhash` can be any binary, including one that is not valid UTF8, and attempting to export the resource/property (via 'controller_api', for example) causes an error in the encoders, which attempt to interpret it as a binary string.
Solution: As the for most other `pivot` properties, this can be excluded from the rsc get (it's still accessible as a DB column).
@mworrell this is the PR following up our discussion earlier.
It seem to be working fine, but I'm not sure if anything depends on this property being there, so let me know if you think a TODO for later is better instead.
=> Exclude 'pivot_geocode_qhash' from rsc raw gets

apps/zotonic_mod_filestore/src/models/m_filestore.erl
Uses a high (10 minutes) timeout on the bigint column update, as that can be a long-running operation.
=> mod_filestore: use high timeout in ensure_size_bigint

apps/zotonic_core/src/support/z_expression.erl, apps/zotonic_core/src/support/z_render.erl, apps/zotonic_mod_base/src/filters/filter_merge_tags.erl, apps/zotonic_mod_base/src/filters/filter_render.erl, apps/zotonic_mod_base/test/base_filter_tests.erl, doc/ref/filters/filter_merge_tags.rst, doc/ref/filters/filter_render.rst, doc/ref/filters/html/index.rst, doc/ref/filters/strings/index.rst
Add two filters:
- `render` renders a template
- `merge_tags` replaces tags in a text with values
Examples:
```django
{% include "hallo.tpl" name="_name.tpl"|render:%{ id: someid }  %}
```
```django
{{ id.body|merge_tags:%{ id: m.acl.user } }}
```
Where the body could be something like:
```html
<p>Hello {{ name_first }},</p>
```
TODO:
=> mod_base: Add filters 'render' and 'merge_tags'

apps/zotonic_mod_survey/priv/templates/email_survey_result.tpl
This will check if a block is a survey_stop so it wont print the name in the results email.
=> Survey: Add extra parameter to exclude survey_stop from printing answer

apps/zotonic_mod_translation/priv/templates/_dialog_new_rsc_extra.tpl
Adds a select box to the rsc-new dialog tab to force a language when creating a page in the admin.
Per default the language is selected automatically.
=> mod_translation: option to set language in rsc creation dialog

.github/workflows/docs.yml, apps/zotonic_core/src/db/z_db_pgsql.erl, apps/zotonic_core/src/db/z_db_pool.erl, apps/zotonic_core/src/models/m_site.erl, apps/zotonic_core/src/smtp/z_email_server.erl, apps/zotonic_core/src/support/z.erl, apps/zotonic_core/src/support/z_crypto.erl, apps/zotonic_core/src/support/z_expression.erl, apps/zotonic_core/src/support/z_module_manager.erl, apps/zotonic_core/src/support/z_mqtt_sessions_runtime.erl, apps/zotonic_core/src/support/z_pivot_rsc.erl, apps/zotonic_core/src/support/z_site_sup.erl, apps/zotonic_core/src/support/z_sites_config.erl, apps/zotonic_core/src/support/z_sites_dispatcher.erl, apps/zotonic_core/src/support/z_utils.erl, apps/zotonic_launcher/src/command/zotonic_cmd_backup.erl, apps/zotonic_launcher/src/command/zotonic_cmd_config.erl, apps/zotonic_mod_authentication/src/models/m_authentication.erl, apps/zotonic_mod_backup/src/actions/action_backup_backup_start.erl, apps/zotonic_mod_backup/src/backup.hrl, apps/zotonic_mod_backup/src/controllers/controller_admin_backup.erl, apps/zotonic_mod_backup/src/mod_backup.erl, apps/zotonic_mod_backup/src/models/m_backup.erl, apps/zotonic_mod_backup/src/support/backup_create.erl, apps/zotonic_mod_backup/src/support/backup_file_crypto.erl, apps/zotonic_mod_backup/src/support/backup_restore.erl, apps/zotonic_mod_base/src/filters/filter_merge_tags.erl, apps/zotonic_mod_email_relay/src/mod_email_relay.erl, apps/zotonic_mod_filestore/src/mod_filestore.erl, doc/ref/modules/mod_backup.rst
Add a restore option for backups.
If a site runs with environment `backup` then it will periodically download backup files from the filestore.
After a backup is downloaded, then the SQL file dump of the newest backup will be used to replace the current schema of the site.
A hash is added to the backup files to check for integrity.
TODO:
=> Backup restore and replication

apps/zotonic_core/src/support/z_expression.erl, apps/zotonic_core/src/support/z_sanitize.erl, apps/zotonic_core/test/z_sanitize_tests.erl, apps/zotonic_mod_base/src/filters/filter_merge_tags.erl
Remove HTML comments if they contain a `<` or `>` character.
This to protect faulty HTML editors.
Fix for `name_full` rendering with the `merge_tags` filter.
=> core: stricter HTML sanitizier. Fix for merge_tags filter.

apps/zotonic_listen_smtp/src/zotonic_listen_smtp.erl
This fixes an issue with disabling session_tickets:
```
2025-05-08 11:02:51 INFO <0.1851.0> [gen_smtp_server_session:handle_request/2:903] ▸ text="SSL handshake failed : {options,incompatible,\
[{anti_replay,'100k'},\
{session_tickets,disabled}]}" 
```
=> smtp: remove ssl listen anti_replay option

apps/zotonic_core/src/smtp/z_email_server.erl, apps/zotonic_mod_email_status/src/models/m_email_status.erl
Fix #4089 
Fix an issue where after some non-recoverable errors the mail system still would retry delivery.
Fix an issue where email blocked by Zotonic email-status are logged as errors.
Fix an issue where email not sent because of the sender would be logged as error with the recipient.
=> smtp: fix issues with retries on some non recoverable email errors

apps/zotonic_core/src/support/z_expression.erl, apps/zotonic_mod_authentication/priv/lib/js/zotonic.auth.worker.js, apps/zotonic_mod_authentication/priv/templates/_logon_login_form.tpl, apps/zotonic_mod_authentication/priv/templates/_logon_login_form_fields.tpl, apps/zotonic_mod_authentication/src/controllers/controller_authentication.erl, apps/zotonic_mod_authentication/src/mod_authentication.erl
Better support for "1-click logon" using password managers like 1Password.
This is done by ensuring that the password, username and one-time passcode fields are present (but hidden) when entering the username.
=> mod_authentication: better support for password managers

apps/zotonic_mod_admin/src/actions/action_admin_link.erl, apps/zotonic_mod_admin/src/actions/action_admin_unlink.erl
This removes the growl message after the connection has been made.
It can be re-added by adding an action to the argument list.
=> mod_admin: remove growl message after making a connection, use the actions instead

apps/zotonic_mod_authentication/priv/templates/_logon_box_view.tpl, apps/zotonic_mod_authentication/priv/templates/_logon_login_extra.tpl
In the second step, if the username is known, show only the options for that username.
Hide the social logins and other extra options.
Also ensure that the error div is always present, so that the HTML-template-patching goes well if it is added.
=> mod_authentication: add extra login options in step 2 of login

apps/zotonic_core/src/install/z_install.erl, apps/zotonic_core/src/install/z_install_update.erl, apps/zotonic_core/src/models/m_rsc.erl, apps/zotonic_core/src/models/m_rsc_gone.erl, apps/zotonic_core/src/models/m_rsc_update.erl, apps/zotonic_core/src/support/z_pivot_rsc_job.erl, apps/zotonic_core/test/m_rsc_db_tests.erl, apps/zotonic_mod_admin/priv/templates/_action_dialog_connect_tab_find_results.tpl, apps/zotonic_mod_admin/priv/templates/_admin_edit_content_advanced.tpl, apps/zotonic_mod_admin/priv/templates/_admin_overview_list.tpl, apps/zotonic_mod_admin/src/controllers/controller_admin_edit.erl, apps/zotonic_mod_backup/src/support/backup_create.erl, apps/zotonic_mod_base/src/validators/validator_base_page_path_unique.erl, apps/zotonic_mod_oauth2/priv/templates/_dialog_oauth2_app_token_new.tpl, apps/zotonic_mod_oauth2/priv/templates/admin_oauth2_apps_tokens.tpl, apps/zotonic_mod_search/priv/templates/search_view.tpl, apps/zotonic_mod_search/src/support/search_query.erl, apps/zotonic_mod_translation/priv/templates/_translation_status.tpl, doc/ref/validators/validator_name_unique.rst, doc/ref/validators/validator_page_path_unique.rst
This replaces the `page_path` binary with a translatable page_path.
The database column is now a pivot column with an character varying array.
TODO:
=> core: make the page_path translatable

apps/zotonic_mod_admin/priv/templates/_admin_edit_content_pub_period.tpl
Added a block around org_pubdate so we can overrule this on apps_user level.
=> Mod_admin: Add block around org_pubdate, so we can overrule

apps/zotonic_mod_menu/src/mod_menu.erl, apps/zotonic_mod_survey/priv/templates/email_survey_result.tpl
The answers were already escaped by the prepare routines.
The title of the new menu item was given as-is from the source rsc, and then escaped again when inserting the new rsc.
=> Fix an issue where html characters were double escape in survey answer emails and when copying menu items

apps/zotonic_core/src/i18n/z_gettext_compile.erl
This removes the relatives paths and bases the filenames on the module or site names.
With this change pot merges should be simpler.
=> core: shorten filenames in generated pot files

apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_core/src/behaviours/zotonic_observer.erl, apps/zotonic_core/src/support/z_dropbox.erl, apps/zotonic_mod_import_csv/src/mod_import_csv.erl, apps/zotonic_mod_import_csv/src/support/import_csv.erl, apps/zotonic_mod_video/src/mod_video.erl
Keep the last handled dropbox file in files/handled, delete after two weeks.
This makes it possible to check the content of recently imported files.
=> core: keep last handled dropbox files in files/handled

apps/zotonic_mod_base/src/filters/filter_replace_args.erl, apps/zotonic_mod_base/test/base_filter_tests.erl
Fix `replace_args` filter, where the input contains unicode characters.
Instead of using `z_convert:to_binary/1`, `unicode:characters_to_list/1` should be used.
=> base: Fix replace_args filter where the input string contains unicode characters

apps/zotonic_core/src/support/z_config.erl, apps/zotonic_launcher/priv/config/zotonic.config.in, apps/zotonic_listen_smtp/src/zotonic_listen_smtp.erl
Add Zotonic configuration option `smtp_listen_size` to set the max size of received emails.
The default will be 20MB.
This overrules the default size of 10MB in gen_smtp.
=> smtp: add config 'smtp_listen_size' to set the max size of received e mails

apps/zotonic_core/src/support/z_controller_helper.erl, apps/zotonic_mod_base/src/controllers/controller_page.erl, apps/zotonic_mod_base/src/controllers/controller_template.erl
This fixes an issue where controller_template used a 303 and omitted cache/vary headers if it was redirecting from (say) `/` to `/en/`
=> core: let controller_template use a 308 when redirecting to language-specific URLs

apps/zotonic_core/include/zotonic.hrl, apps/zotonic_core/src/models/m_rsc.erl, apps/zotonic_core/src/support/z_dispatcher.erl, apps/zotonic_core/src/support/z_lib_include.erl, apps/zotonic_core/src/support/z_sites_dispatcher.erl, doc/technotes/dispatch-and-resources.md
This allows for dispatch rules like:
```erlang
{foo, page_foo, controller_template, [ ... ]}
```
Here the path is defined as _the page path property of page_foo_.
If a URL is generated for `foo` then the `page_url` of the resource `page_foo` is taken.
Assuming `page_foo` has a `page_path` defined, then matching that page path will use the `foo` dispatch rule.
This allows for multi-lingual page paths that should render with specific controllers or controller options (eg. templates).
Also remove the gen_server when generating page urls, instead use an ets table.
This should make the url generation more efficient, especially on many parallel requests.
=> core: support resource name for dispatch paths

apps/zotonic_core/src/support/z_utils.erl, apps/zotonic_mod_acl_user_groups/priv/templates/_admin_catcg.tpl, apps/zotonic_mod_acl_user_groups/priv/templates/_admin_category_dropdown.tpl, apps/zotonic_mod_acl_user_groups/priv/templates/_admin_content_group_dropdown.tpl, apps/zotonic_mod_acl_user_groups/priv/templates/_admin_edit_basics_user_extra.tpl, apps/zotonic_mod_acl_user_groups/priv/templates/_admin_edit_visible_for.tpl, apps/zotonic_mod_acl_user_groups/src/support/admin_acl_rules.erl, apps/zotonic_mod_acl_user_groups/src/support/admin_acl_rules_rsc.erl, apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/scss/_buttons.scss, apps/zotonic_mod_admin/priv/templates/_action_dialog_change_category.tpl, apps/zotonic_mod_admin/priv/templates/_admin_edit_content_acl.tpl, apps/zotonic_mod_admin/priv/templates/_admin_edit_content_publish.tpl
This fixes an issue where ACL collaboration groups could not be selected when connecting or quick-editing resources.
Manually exclude the following special categories:
- category;
- predicate;
- content group;
- ACL user group.
Allow other categories from the meta category.
On the new-rsc tab, pre-select the cat select if there is only a single enabled category.
In general: add class `.buttons` to fix a problem with wrapping buttons that do not have space.
This might be a generic thing for any element that contains more than a single button, for now it is just the class `.buttons` on the wrapping element.
=> Fix an issue with selecting ACL collaboration groups when creating or editing resources

apps/zotonic_mod_translation/priv/templates/_admin_headeritem.tpl
This makes it easier to change the `_language_switch.tpl` for the frontend pages without affecting the admin.
=> mod_translation: make specific lang switch menu for mod_admin

apps/zotonic_core/src/models/m_rsc_update.erl
If a resource was duplicated, then the resource dates were converted again using the timezone of the resource.
=> Fix an issue where timezone conversions where applied when duplicating resources

apps/zotonic_core/src/models/m_rsc_update.erl, apps/zotonic_mod_admin/src/controllers/controller_admin_edit.erl, apps/zotonic_mod_admin_frontend/priv/templates/_admin_frontend_edit.tpl
Changed the timezone determination of rsc updates to the following order:
1. 'tz' option in options
2. 'tz' value in update props
3. 'default_tz' option in options
4.  'tz' property of resource
5.  timezone of context.
This fixes an issue in the frontend admin edit where dates are shown in the user's context but the
update actually uses the timezone of the resource.
=> core: fix an issue with timezone conversions in frontend admin edit

apps/zotonic_mod_cron/src/mod_cron.erl, doc/ref/modules/mod_cron.rst
Adds the possibility to schedule regular events via mod_cron. This makes it possible to run module specific tasks on regular time intervals. When the module stops, the tasks are automatically cancelled.
=> Add possibility to schedule regular jobs via mod_cron

apps/zotonic_core/src/support/z_mqtt_sessions_runtime.erl
Fix the wrong site name being checked for admin privileges when subscribing to `$SYS/site/<some site>` and allow the zotonic_site_status admin to subscribe to all `$SYS` topics
Fixes the logic for subscribing over MQTT to  `$SYS/site/<sitename>` for the zotonic admin user. Additionally, allows that admin user to subscribe to all `$SYS` topics.
=> Adjust MQTT admin subscription permissions to $SYS

apps/zotonic_launcher/src/command/zotonic_cmd_resetratelimit.erl
This adds a `resetratelimit` command to allow resetting the rate limiter from the commandline or a script.
I find myself surprisingly often running into the rate limiter, and resetting it is a bit of a chore and seemingly impossible to do with `zotonic rpc`, making it difficult to automate. This command lets an administrator do so from the commandline, or automate it using shell scripts.
Example usage:
```
marco@zotonic:~/zotonic$ bin/zotonic resetratelimit zotonic_site_status
ok
marco@zotonic:~/zotonic$ bin/zotonic resetratelimit test
Error: No such site
```
=> Add `resetratelimit` command, to reset the rate limiter for a site

apps/zotonic_core/src/i18n/z_trans.erl
Fixes a crash where a trans tuple is passed together with the context.
When a trans tuple is passed together with the context, get the languages from the context and use that to pick the right translation.
Fixes this crash.
```erlang
z_trans:trans(m_rsc:p(1, title, Context), Context).
** exception error: no function clause matching z_trans:find_first({context,undefined,undefined,
...
````
=> Fixes a crash when a trans tuple is passed with the context

apps/zotonic_core/src/models/m_req.erl, apps/zotonic_core/src/support/z_mqtt_sessions_runtime.erl
For MQTT requests we set the `peer_ip` in the context.
As we also use the `peer` we should derive the `peer` from the `peer_ip` if the `peer_ip` is set in the context.
=> core: in m_req, if the 'peer_ip' is set in the context then derive the 'peer' from there

apps/zotonic_core/priv/translations/zotonic-language.pot, apps/zotonic_core/src/i18n/z_language.erl, apps/zotonic_core/src/i18n/z_language_data.erl, apps/zotonic_mod_admin/priv/templates/_admin_translation_tabs.tpl, apps/zotonic_mod_translation/priv/templates/_dialog_new_rsc_extra.tpl, apps/zotonic_mod_translation/priv/templates/_dialog_rsc_language.tpl, apps/zotonic_mod_translation/src/filters/filter_language_sort_localized.erl, apps/zotonic_mod_translation/src/mod_translation.erl, apps/zotonic_mod_translation/src/models/m_translation.erl, doc/ref/filters/filter_language_sort.rst, doc/ref/filters/filter_language_sort_localized.rst, doc/ref/filters/translation/index.rst
This translates the language names in the tabs and translate dialogs into the current interface language.
This solves a problem where editors have a problem discerning some languages they are not familiar with. Eg. Persian vs Arabic.
A new pot file is generated from the language data: `apps/zotonic_core/priv/translations/zotonic-language.pot`.
This pot file can be used to translate the language names.
=> mod_admin: show language tabs in current language, sort by shown language names

apps/zotonic_mod_acl_user_groups/priv/templates/_admin_acl_rule_row_collab.tpl, apps/zotonic_mod_acl_user_groups/priv/templates/_admin_acl_rule_row_rsc.tpl, apps/zotonic_mod_acl_user_groups/priv/templates/_admin_acl_rules_list_header.tpl, apps/zotonic_mod_acl_user_groups/priv/templates/_dialog_acl_rule_edit.tpl, apps/zotonic_mod_acl_user_groups/src/mod_acl_user_groups.erl, apps/zotonic_mod_acl_user_groups/src/models/m_acl_rule.erl, apps/zotonic_mod_acl_user_groups/src/support/acl_user_group_rebuilder.erl, apps/zotonic_mod_acl_user_groups/src/support/acl_user_groups_checks.erl, apps/zotonic_mod_acl_user_groups/src/support/acl_user_groups_rules.erl
This PR modifies the `zotonic_mod_acl_user_groups` module to support visibility in rules, which is used to allow/restrict permissions on resources depending on the value of their `visible_for` property.
For example, let's imagine that one has a platform for moderated publishing of `article`s, where the desired outcome is that:
1. there are many teams (`acl_collaboration_group`s) where people collaborate on writing
2. articles can have 3 different states (`visible_for` values): "draft", "preview" or "shared"
3. any registered user can write (`insert`) new "draft" articles in teams (`acl_collaboration_group`s) that they are a member of
4. users can edit their own articles, but only if they are still "draft"s
5. users can add (`link`) comments to any "draft" article in their teams, …
=> ACL: add support for visibility levels in rules

apps/zotonic_core/src/support/z_config.erl, apps/zotonic_core/src/zotonic_core_sup.erl, apps/zotonic_launcher/priv/config/zotonic.config.in
Add a configuration to limit the number of media resizers that can run in parallel to something else than the default 3.
Issue #4158
=> core: add configuration for max ImageMagick resized jobs

apps/zotonic_core/src/support/z_file_entry.erl, apps/zotonic_core/src/support/z_file_locate.erl, apps/zotonic_core/src/support/z_file_mtime.erl, apps/zotonic_filewatcher/src/zotonic_filewatcher_monitor.erl, apps/zotonic_mod_filestore/src/support/filestore_request.erl, apps/zotonic_mod_filestore/src/support/filestore_uploader.erl
Adding the 'raw' option makes file_info requests faster.
Also ensure that timestamps are universal.
Relevant discussion is here:
https://erlangforums.com/t/cowboy-2-13-0-performance-bottleneck-at-8-7k-rps-on-erlang-28-0-2/5004/9
=> Optimize file_info calls by adding the 'raw' option

apps/zotonic_core/src/markdown/z_html2markdown.erl
Fixed by better trimming of the texts in elements.
=> core: html2markdown fix an issue where space after a code tag could get lost

README.md, doc/developer-guide/getting-started.rst, docker-compose.yml, docker/docker-entrypoint.sh, start-podman.sh
Allow containerization in Podman:
- add script `./start-podman.sh` to start Zotonic in a Podman container
- convert relative paths of Docker images to absolute (as required by Podman)
- grant root privileges to the `zotonic` user when running in Podman  -- Docker does that by default
- update documentation
=> new: allow containerization in Podman

modules/mod_translation/mod_translation.erl
This fixes an issue where having an unknown pref_language could result in a crash.
=> mod_translation: ignore unknown pref_language (0.x)

apps/zotonic_mod_base/priv/templates/_html_head_cotonic.tpl
The final connect (on failure) does not have a language code. The pre-connect does have one.
Ensure that both do not have a language code.
This is easier for proxy configuration.
=> mod_base: ensure that the MQTT websocket preconnect path does not have a language

apps/zotonic_mod_admin/priv/templates/_admin_edit_content_date_range.tpl, apps/zotonic_mod_admin/priv/templates/_edit_date.tpl
This fixes an issue where the "date is all day" could not be selected in the admin on Safari.
If the checkbox was checked, then the hidden time inputs gave an error. This is fixed by setting the time inputs to 'disabled' if they are hidden.
=> mod_admin: fix an issue where date-is-all-day could not be selected on Safari
