src/support/emqtt_auth_zotonic.erl
When to use a mqtt client to connect onto emqtt broker of zotonic, it would crash as below:
[error] Supervisor emqtt_client_sup had child at module undefined at <0.933.0> exit with reason {{function_clause,[{wrq,req_qs,[undefined],[{file,"src/wrq.erl"},{line,130}]},{z_context,ensure_qs,1,[{file,"src/support/z_context.erl"},{line,638}]},{z_session,ensure_page_session,1,[{file,"src/support/z_session.erl"},{line,247}]},{z_auth,logon,2,[{file,"src/support/z_auth.erl"},{line,100}]},{z_auth,logon_pw,3,[{file,"src/support/z_auth.erl"},{line,71}]},{emqtt_auth_zotonic,check,2,[{file,"src/support/emqtt_auth_zotonic.erl"},{line,45}]},{emqtt_auth,handle_call,3,[{file,"src/emqtt_auth.er..."},...]},...]},...} in context child_terminated
It due to the fake context created by map_user_site/1, then in …
=> mqtt client connection auth issue

priv/zotonic.config.in, src/install/z_installer.erl
I'd much prefer if Zotonic left my database alone if it's not to its liking, this allows to set that so by setting dbcreate and dbinstall to false in the global config file. Defaults are to both create and install whatever needed.
=> Allow configuration of db creation and installation

modules/mod_admin/templates/_rsc_item.tpl
I can remember that this worked before, but I don’t understand how. Anyway, this seems to fix the old behaviour.
=> Fix page block links

src/scripts/helpers/zotonic_setup
So I can put i in /run where it belongs
=> Allow to override pidfile location with env var

modules/mod_survey/filters/filter_survey_prepare_matching.erl
split_marker/2 previously did not handle &#; entities (typically with a single quote ').
Rewrote the function to properly skip &#.
=> Handle &# entities when splitting markers

modules/mod_signup/templates/_signup.tpl, modules/mod_signup/templates/_signup_box.tpl, modules/mod_signup/templates/_signup_form.tpl
Signup didn’t work when using the modal dialog, probably because delegate was not supplied. This PR sets the delegate and makes it configurable.
=> Fix modal signup

CONTRIBUTORS, modules/mod_admin/actions/action_admin_dialog_new_rsc.erl, modules/mod_admin/templates/_action_dialog_new_rsc_tab.tpl
This allows users to pass objects variable to dialog_new_rsc action to be able to save object, predicate pairs at creation time, such as assigning current user as author.
=> Fix dialog_new_rsc action to save [object, predicate] pairs

modules/mod_admin/actions/action_admin_dialog_new_rsc.erl
Changed Objects to proplists:get_all_values(object, Args).
This will allow calling the action like below ...
{% button text="New Topic"
action={ dialog_new_rsc
cat='topic'
tabs_enabled = ["new"]
nocatselect = "true"
redirect = `topics`
object = [m.acl.user, `author`]
object = [421, `subject`]
}
%}
This also fixes and introduced bug when 'objects' was not presented.  Around line 91 of the action
[m_edge:insert(Id, Pred, m_rsc:rid(Object, Context), Context) || [Object, Pred] <- Objects]
would crap out and break the stream.  The rsc would save, but the subsequent actions would fail, ie close_dialog etc.
=> mod_admin:  action_admin_dialog_new_rsc fix

modules/mod_authentication/templates/_logon_modal.tpl
Would be great if this made it into 0.13. :wink:
Didn’t add the param to the `{% with %}` section because it didn’t add much in my opinion. If you prefer, I can add it in.
=> Allow post-login redirect to be passed to logon modal

src/zotonic_compile.erl
Previously, `include_lib()` had to point to a (relative) path. With this fix, you can just do `include_lib("module_name/include/include_name.hrl")` and it will work no matter where your sites_dir and modules_dir are located.
=> Make module and site includes path-independent

modules/mod_admin/templates/_action_dialog_connect_tab_find_results.tpl
Open admin (connection) dialogs now throws a JS error. This is because `dialogReposition()` was removed from the public API in ad6ff53. Anyway, it does not need to be called anymore, as the dialog is already repositioned when opening it.
/cc @ArthurClemens
=> Fix opening admin dialog by removing call to dialogReposition()

modules/mod_import_csv/mod_import_csv.erl
There is a small typo inside this file which checks if user is allowed to use mod_import_cvs, this should be mod_import_csv.
=> Typo inside is_allowed check mod_import_csv.erl

src/scripts/helpers/zotonic_setup
The default locations are not appropriate for all platforms and situations, so allow setting the configuration directory using an environment variable ZOTONIC_CONFIG_DIR. 
Note: if the required files are not available there, Zotonic will fail to start (which is the expected behaviour for me at least; starting with the wrong config may be harmful to your environment.)
=> Allow overriding the configuration file location

modules/mod_export/mod_export.erl
It seems search params have changed (`query_id` instead of `id`), so exporting a query threw an error.
=> Fix query export

modules/mod_authentication/templates/_logon_modal.tpl
_signup_config.tpl is part of mod_signup. When that module is disabled, an "[info] include: could not find template "_signup_config.tpl" message is printed. Apparently, even though the include is within an if case that is never reached, Zotonic still tries to find the template. Making the include optional fixes that.
=> Fix template not found error

doc/ref/modules/mod_signup.rst, modules/mod_signup/mod_signup.erl
We have added a config key for content group so we can decide in which content groups new users are placed.
=> Added config key for content group when user registers

modules/mod_mqtt/mod_mqtt.erl
there is no encoder fun of the mqtt payload published by pubzub(via mod_mqtt.erl).  There would an error, when an external mqtt client connects to zotonic emqtt broker and subscribes to a topic to which the pubzub published.
=> add a encoder fun for the external mqtt client

modules/mod_video/mod_video.erl
ffprobe can return UTF-8 JSON that is then interpreted in os:cmd and returned as a string with unicode characters. z_convert:to_binary is simply iolist_to_binary for lists and does not work with integers > 255.
Not sure z_convert:to_binary/1 should not be fixed instead.
=> Fix issue with ffprobe returning unicode text

modules/mod_base/lib/js/modules/livevalidation-1.3.js
Removed has-error class because styling of bootstrap broke when the whole form has a has-error class. Has-error class are only place on the form-group divs
Fixes #1124.
=> removed has-error class from form

modules/mod_base/controllers/controller_api.erl
This error would cause the controller_api unable to function.  It complains like below error:
(reason {{case_clause,<<"something">>},[{controller_api,allowed_methods,2,[{file,".../zotonic/modules/mod_base/controllers/controller_api.erl"},{line,65}]}
=> Duplicated Variable 'Module' in controller_api

doc/developer-guide/modules.rst, doc/developer-guide/notifications.rst
I found some errors in the documentation as I was reading about zotonic and decided to help improve them.
=> doc: Fix minor errors in documentation

doc/ref/configuration/site-configuration.rst, priv/zotonic.config.in, src/models/m_identity.erl, src/support/z_config.erl
Often the admin password for development sites is "admin".
It happens quite often that these sites are exposed to the Internet, which risks total access to the server.
This merge request adds a IP address whitelist for IP addresses that are allowed to use the password "admin" for logging into a site using the "admin" account.
There is a new Zotonic configuration in the `zotonic.config`:
```
%%% IP whitelist, used for accessing sites with a default "admin" password
%% {ip_whitelist, "127.0.0.0/8,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,::1,fd00::/8"},
```
Per default the local loopback interface and local network addresses are whitelisted.
=> Add a whitelist of IP addresses that can use the default 'admin' password to login into sites.

modules/mod_acl_user_groups/support/acl_user_groups_checks.erl
When content_group_id is not passed on insert, the insert fails when the user has no permissions to insert anything in any category *except* on a category where he is a collaboration group of.
With this fix, the content group id will be set to the first collaboration group where the user has insert rights on.
=> mod_acl_user_groups: Fix permission issue

modules/mod_admin_identity/templates/email_identity_verify.tpl, modules/mod_authentication/templates/email_password_reset.tpl, modules/mod_mailinglist/templates/email_mailinglist_confirm.tpl, modules/mod_mailinglist/templates/email_mailinglist_welcome.tpl, modules/mod_signup/templates/email_verify.tpl
* Fix the URL by making it absolute.
* Also use use_absolute_url where possible in other e-mail templates.
=> mod_admin_identity: Fix verification e-mail URL

modules/mod_base/scomps/scomp_base_button.erl, modules/mod_base/scomps/scomp_base_inplace_textbox.erl, modules/mod_base/scomps/scomp_base_lazy.erl, modules/mod_base/tests/mod_admin_tests.erl, modules/mod_email_receive/models/m_email_receive_recipient.erl, modules/mod_instagram/support/instagram_api.erl, modules/mod_linkedin/controllers/controller_linkedin_authorize.erl, modules/mod_mailinglist/models/m_mailinglist.erl, modules/mod_mqtt/scomps/scomp_mqtt_live.erl, modules/mod_search/support/search_query.erl, modules/mod_signup/mod_signup.erl, modules/mod_survey/models/m_survey.erl, modules/mod_survey/support/survey_admin.erl, modules/mod_video/mod_video.erl, src/erlydtl/erlydtl_compiler.erl, src/models/m_identity.erl, src/smtp/z_email_embed.erl, src/smtp/z_email_receive_server.erl, src/smtp/z_email_server.erl, src/support/z_ids.erl, src/support/z_pivot_rsc.erl, src/support/z_search.erl, src/support/z_session.erl, src/support/z_session_manager.erl, src/support/z_transport.erl, src/support/z_utils.erl, src/tests/erlydtl/erlydtl_tests_init.erl, src/zotonic_sup.erl
Removes a potential bottleneck by changing z_ids from a gen_server into a stateless module.
Improves the randomness by using crypto:strong_random_bytes/1.
Changes the return type of several functions from string to binary, in accordance with the general move to binary.
Makes the necessary changes in the modules that call functions in z_ids to deal with the new return type.
Solves #1150 (Refactor z_ids module).
=> core: Refactor z_ids module.

doc/developer-guide/deployment/env.rst, doc/developer-guide/deployment/privilegedports.rst, doc/ref/configuration/site-configuration.rst, doc/ref/modules/mod_ssl.rst, doc/ref/modules/mod_ssl_self_signed.rst, include/zotonic_notifications.hrl, modules/mod_ssl/mod_ssl.erl, modules/mod_ssl_self_signed/mod_ssl_self_signed.erl, src/support/z_config.erl, src/zotonic_sup.erl
This PR makes it possible to serve https for virtual sites.
Fixes issues:
https://github.com/zotonic/zotonic/issues/706, https://github.com/zotonic/zotonic/issues/364
and has support to implement:
https://github.com/zotonic/zotonic/issues/1218
Requirement is erlang 17 and higher. Erlang > 18.1 recommended.
=> Zotonic SNI support

doc/cookbook/index.rst, doc/cookbook/task-queue.rst, doc/developer-guide/modules.rst, doc/ref/notifications.rst
It’s a great feature (of course, Erlang helps here :wink:), so let’s document it.
Fix #1262.
=> Document the task queue

Dockerfile
Zotonic master now requires Erlang 18.
Fix #1294.
=> docker: Install Erlang 18

modules/mod_seo/templates/_html_head.tpl
To use the User ID feature, the user will need to set it up from the Google Analytics backend.
https://support.google.com/analytics/answer/3123666?hl=en
Fixes #1249
=> Switch to universal analytics using async method

modules/mod_base/controllers/controller_api.erl, src/support/z_sitetest.erl
Build was broken in a0820fe65e64b8c491026d09140d911081176d97.
=> core: Fix xref failures

modules/mod_survey/templates/blocks/_admin_edit_block_li_survey_thurstone.tpl, modules/mod_survey/templates/blocks/_block_view_survey_thurstone.tpl
The explanation text in the thurstone survey blocks is placed after the
input elements. This is inconsistent with the other block types that
place the explanation text immediately after the label (prompt).
This change results in more consistent admin and view appearance of
surveys.
=> Inconsistent text placement in thurstone block

modules/mod_admin/templates/_admin_edit_content_publish.tpl, modules/mod_admin/templates/_admin_edit_content_publish_view.tpl, modules/mod_admin/templates/_admin_view_types.tpl, modules/mod_base/controllers/controller_id.erl, modules/mod_base/filters/filter_content_type_label.erl, modules/mod_base/filters/filter_content_type_urls.erl
Adds a view dropdown menu with an allincluded template so modules can add specific content types that they serve. This solves two problems:
* users want a ‘view’ button without the ‘save’, so they don’t change the last updated timestamp or accidentally update other data
* users want an easy way to acccess alternative views for the page. 
Fix https://github.com/driebit/ginger/issues/49.
=> admin: Add view dropdown menu

modules/mod_admin/mod_admin.erl
Fixes:
```
zotonic_1   | 08:33:40.909 [error] Stack: [{m_predicate,name_to_id_check,2,[{file,"src/models/m_predicate.erl"},{line,139}]},{m_edge,get_id,4,[{file,"src/models/m_edge.erl"},{line,146}]},{mod_admin,do_link_unlink,6,[{file,"/opt/zotonic/modules/mod_admin/mod_admin.erl"},{line,342}]},{mod_admin,event,2,[{file,"/opt/zotonic/modules/mod_admin/mod_admin.erl"},{line,261}]},{z_transport,incoming_with_session,2,[{file,"src/support/z_transport.erl"},{line,256}]},{z_transport,incoming_msgs,2,[{file,"src/support/z_transport.erl"},{line,193}]},{z_transport,incoming,2,[{file,"src/support/z_transport.erl"},{line,161}]},{controller_websocket,websocket_message,3,[{file,"modules/mod_base/controllers/controller_websocket.erl"},{line,108}]}]
```
Broken in 0.19.0 (3c21de8a). 
@mworrell Please …
=> admin: Fix inline links

src/scripts/helpers/zotonic_setup
At some point someone thought it was a good idea to fix non-linux compatibility by using perl to do an in-place find-and-replace. Unfortunately that of course brings with it a dependency on perl which is not always available in minimal environments.
This patch re-replaces perl with sed and I believe does so in a POSIX-compatible way.
=> Remove perl dependency

modules/mod_base/controllers/controller_file.erl
Inline content-disposed PDFs no longer render because of the Content-Security-Policy header recently added to `controller_file`. See for instance https://tudelft.openresearch.net/image/2016/8/8/ri_2016_minor_calendar_q1.pdf. This fixes that by allowing browser PDF plugins to render the file.
=> mod_base: Fix Content-Security-Policy for inline PDFs

modules/mod_authentication/mod_authentication.erl, modules/mod_authentication/templates/__template_structure.txt, modules/mod_authentication/templates/admin_authentication_services.tpl, modules/mod_authentication/translations/es.po, modules/mod_authentication/translations/et.po, modules/mod_authentication/translations/fr.po, modules/mod_authentication/translations/nl.po, modules/mod_authentication/translations/pl.po, modules/mod_authentication/translations/ru.po, modules/mod_authentication/translations/tr.po, modules/mod_authentication/translations/zh.po, modules/mod_linkedin/mod_linkedin.erl, modules/mod_twitter/mod_twitter.erl
Rename 'App Keys and Authentication Services' to 'External Services'.
It's part of the Authentication menu, so we can be more concise.
=> mod_authentication: Rename menu to 'External Services'

modules/mod_translation/mod_translation.erl, modules/mod_translation/support/translation_scan.erl
Added support for the new template_compiler translation format. It is necessary to merge [this pull request](https://github.com/zotonic/template_compiler/pull/8) before this one.
=> Fix: fix .pot generation for .erl and .tpl files 

modules/mod_import_csv/dispatch/dispatch, modules/mod_import_csv/mod_import_csv.erl, modules/mod_import_csv/templates/_admin_import.tpl, modules/mod_import_csv/templates/_admin_import_button.tpl, modules/mod_import_csv/templates/_admin_status.tpl, modules/mod_import_csv/translations/nl.po, modules/mod_import_csv/translations/pl.po, modules/mod_import_csv/translations/ru.po, modules/mod_import_csv/translations/tr.po, modules/mod_import_csv/translations/zh.po
Fix #1350.
* Don't require use mod_admin_config permission, but only check use mod_import_csv.
* Create separate 'Import content' page with a menu entry under 'Content'.
* Remove 'Import CSV' button from the Status page.
* Add Dutch translation.
=> mod_import_csv: Move CSV import to Content menu

modules/mod_acl_user_groups/tests/mod_acl_user_groups_tests.erl, modules/mod_search/support/search_query_notify.erl, modules/mod_search/tests/mod_search_db_tests.erl, priv/sites/testsandbox/config, priv/sites/testsandbox/tests/testsandbox_basic_tests.erl, src/models/tests/m_rsc_db_tests.erl, src/models/tests/m_rsc_import_db_tests.erl, src/scripts/zotonic-runtests, src/tests/z_acl_tests.erl, src/tests/z_sanitize_tests.erl
* Make sure all tests are run with runtests, including db_tests.
* Fix previously excluded tests that now failed.
* Start minimum number of modules on testsandbox and remove mod_acl_adminonly
from modules list.
=> tests: Include db_tests in testrun (#1393)

src/support/z_acl.erl
Remove the `rid`, which was added in #1357, for keeping BC. 
Fix #1398.
Decided not to remove the recently added `is_atom` check in [acl_user_groups_checks](https://github.com/zotonic/zotonic/blob/master/modules/mod_acl_user_groups/support/acl_user_groups_checks.erl#L197) because (as far as I can see) it does not cause a BC break. @mmzeeman What do you think?
=> core: Remove rid from maybe_allowed

include/zotonic_notifications.hrl, modules/mod_acl_user_groups/mod_acl_user_groups.erl, modules/mod_acl_user_groups/support/acl_user_groups_checks.erl, src/support/z_acl.erl
Fixes #1403 
Also: if an user is member of a collab group, then the user can also see unpublished content.
The #acl_is_owner{} notification makes it possible to flexibly define the concept of content ownership.
=> mod_acl_user_groups: make the is_owner check a notification.

doc/ref/modules/mod_oembed.rst, modules/mod_oembed/mod_oembed.erl, modules/mod_oembed/support/oembed_client.erl, modules/mod_oembed/templates/_admin_authentication_service.tpl, src/models/tests/m_identity_tests.erl, src/support/z_sanitize.erl
Optionally add the embed.ly api key to the oembed request.=
=> Add optional embedly authentication

Dockerfile, docker/docker-entrypoint.sh, docker/zotonic.config
docker: Fix duplicate config files
* Because make was run before creating the config files, Zotonic generated default config files in   the default locations, that then became used  starting Zotonic.
* This PR adds a default zotonic.config that is copied before make. Bonus: less sed’ing necessary.
=> docker: Fix duplicate zotonic.config file

doc/Makefile
We used to hide the doc todo blocks, but I agree with the [Producing OSS book](http://producingoss.com/en/getting-started.html#documentation) that encourages to 
> Label the areas where the documentation is known to be incomplete.
=> doc: Show todos on website

priv/sites/zotonic_status/modules/mod_zotonic_site_management/support/zotonic_status_addsite.erl, src/db/z_db_pgsql.erl, src/db/z_db_pool.erl, src/support/z_edge_log_server.erl, src/support/z_pivot_rsc.erl
Fix #465 
This fixes a problem where a site crashes hard during a postgresql database restart.
On an `econnrefused` the db pool entry will try to reconnect for a couple of times.
The periodic queue pollers now gracefully handle timeout and econnrefused errors.
This also fixes a problem with merging config keys.
No documentation changes needed.
Tests were done manually by stopping and starting the db.
=> Retry db connections on econnrefused.

modules/mod_acl_user_groups/tests/mod_acl_user_groups_tests.erl, modules/mod_search/tests/mod_search_db_tests.erl, priv/sites/zotonic_status/modules/mod_zotonic_site_management/mod_zotonic_site_management.erl, src/models/tests/m_identity_tests.erl, src/models/tests/m_rsc_db_tests.erl, src/models/tests/m_rsc_import_db_tests.erl, src/support/z_module_manager.erl, src/support/z_sites_manager.erl, src/support/z_sitetest.erl
Fixes a problem with tests and site installation where the site was not started properly before using it.
Adds z_sites_manager:await_startup/1 and/or z_module_manager:await_upgrade/1
=> Added function to wait for site startup.

modules/mod_translation/mod_translation.erl, modules/mod_translation/templates/admin_translation.tpl, priv/translations/nl.po
Fix #1462.
Show a user-facing warning and create a log entry when ‘Generate .pot files’ while gettext is unavailable.
=> mod_translation: Show error when gettext is not installed

doc/ref/modules/mod_filestore.rst, modules/mod_filestore/mod_filestore.erl, modules/mod_filestore/model/m_filestore.erl, modules/mod_filestore/support/filestore_admin.erl, modules/mod_filestore/templates/admin_filestore.tpl
Fix #1488.
- Helps in recovering accidentally deleted files.
- Make deletion optional: useful for read-only setups such as
non-production environments. Fixes `[error] <0.3542.31>@mod_filestore:delete_ready:302 Could not delete remote file. Path <<"archive/2016/10/16/XXXXXXX.XXX">> (XXX) error {error,forbidden}`
This covers our use cases:
- We have one S3 bucket per site, which is shared between (dev, acc, prod) environments. This makes for easy database imports (for testing and debugging) without the need to shuffle files around.
- Non-production environments (dev, acc) should only read S3 files, never delete them, because they may still be referenced in production. 
- On the (AWS) S3-side, we can re-enable the delete permission on our buckets as long as non-production is configured not …
=> mod_filestore: Add delete interval

modules/mod_filestore/mod_filestore.erl, modules/mod_filestore/model/m_filestore.erl
Following #1493, raise mod_filestore’s schema to actually create the `deleted` column.
=> Filestore schema

doc/developer-guide/access-control.rst, doc/ref/modules/mod_acl_user_groups.rst, doc/ref/modules/mod_admin_category.rst, doc/ref/modules/mod_admin_predicate.rst, modules/mod_admin_category/mod_admin_category.erl, modules/mod_admin_category/templates/_admin_category_sorter.tpl, modules/mod_admin_category/templates/admin_category_sorter.tpl, modules/mod_admin_predicate/dispatch/dispatch, modules/mod_admin_predicate/mod_admin_predicate.erl, modules/mod_admin_predicate/templates/admin_predicate.tpl, modules/mod_menu/templates/_menu_edit_item.tpl
Fix #1001.
* In dispatch rules and admin menu items, only check module use permissions.
* On category and predicate admin screens, check for insert, update and delete permissions to decide which buttons to show.
* Add ACL checks where there weren’t any.
=> admin: Fix access checks

rebar.config, rebar.config.lock, src/support/z_sanitize.erl, src/tests/z_sanitize_tests.erl
Fix #1524
Fix a problem where the sanitizer crashes on filtering non Mso classes.
=> core: fix a problem with sanitizing classes in html.

doc/ref/modules/mod_search.rst, modules/mod_search/mod_search.erl, modules/mod_search/support/search_query.erl
Allow configuration of rank weight.
The default '{0.05, 0.25, 0.5, 1.0}' is a bit too fussy for some clients.
Searches with a rank configured like '{0.05, 0.10, 0.25, 1.0}' will have results with more emphasis on the title text.
=> Search weight config

modules/mod_editor_tinymce/templates/_tinymce_dialog_zmedia_props.tpl
Due to the the use of {_ Middle _} in person's middle name field we often get that translation in the image size property. Anyway this small fix will be more inline with common usages of Small/Medium/Large for sizes.
=> mod_editor_tinymce - translation for middle size changed to medium size

src/support/z_template.erl
- Fix `lager:error` calls throwing a `FORMAT ERROR` due to invalid number of parameters.
- Remove site name from log messages (see also #1510).
=> core: Fix template render error logging

doc/developer-guide/upgrading.rst, doc/ref/tags/tag_image.rst, doc/ref/tags/tag_lib.rst, doc/ref/tags/tag_url.rst, modules/mod_acl_user_groups/templates/_dialog_acl_rules_try.tpl, modules/mod_admin_identity/templates/email_admin_new_user.tpl, modules/mod_admin_identity/templates/email_identity_verify.tpl, modules/mod_authentication/templates/email_password_reset.tpl, modules/mod_facebook/templates/_logon_extra_email_reset.tpl, modules/mod_instagram/templates/_logon_extra_email_reset.tpl, modules/mod_linkedin/templates/_logon_extra_email_reset.tpl, modules/mod_mailinglist/templates/email_mailinglist_confirm.tpl, modules/mod_mailinglist/templates/email_mailinglist_welcome.tpl, modules/mod_search/services/service_search_search.erl, modules/mod_signup/templates/email_verify.tpl, modules/mod_survey/templates/email_survey_result.tpl, modules/mod_twitter/templates/_logon_extra_email_reset.tpl, src/models/m_rsc.erl, src/models/m_rsc_export.erl, src/support/z_dispatcher.erl, src/support/z_lib_include.erl, src/support/z_media_tag.erl
=> core: Rename use_absolute_url to absolute_url

src/support/z_search.erl
The total number of search results was hardcoded. This PR changes that so custom searches can return a total number of results. This is useful e.g. with Elasticsearch, which can return a reliable total without having to query a large set (the 30.000 `OFFSET_PAGING` in `z_search`).
=> core: Support custom search total

modules/mod_base/lib/js/modules/livevalidation-1.3.js
Add a verification to guarantee that this.insertAfterWhatNode is not null when an invalid id is used through the message_after parameter of the validate tag.
Fix #1542
=> mod_base: fix livevalidation message_after error when invalid id

modules/mod_translation/support/translation_scan.erl, priv/translations/ar.po, priv/translations/de.po, priv/translations/en.po, priv/translations/fr.po, priv/translations/nl.po, priv/translations/pt.po, priv/translations/ru.po, priv/translations/th.po, src/support/z_module_indexer.erl
* Make sure all modules are included (not just active ones).
* Add missing translations from 0.x
Add run this shell script to update the translations from 0.x:
```bash
#!/usr/bin/env bash
langs=(ar de en es et fr nl pl pt ru th tr zh)
for lang in "${langs[@]}"; do
files=`find ../zotonic/modules -name ${lang}.po`
cmd="msgmerge -U priv/translations/${lang}.po priv/translations/zotonic.pot"
for file in $files; do
cmd="${cmd} -C $file "
done
$cmd
done
```
=> core: Fix generation of core translations

README.md
Fixes a broken link to the installation chapter on read the docs
=> doc: fixed installation url in readme

src/support/z_transport.erl
Fix #1575
This fix makes zotonic accept push_queue names as binaries. Javascript doesn't really have atoms. Only undefined, true and false are transformed.
=> core: Accept push queue names as binaries. Fixes #1575

modules/mod_oauth/models/m_oauth_perms.erl
Fix #[1581]
Checks for empty/unselected permissions when calling m_oauth_perms:insert_all/3 and skips them.
=> Fixes #1581 mo_oauth: problem with m_oauth_perms inserting empty permissions into db

doc/ref/templates/template_base.rst, doc/ref/templates/template_base_noscript.rst, modules/mod_base/templates/base.tpl, modules/mod_base/templates/base_noscript.tpl, modules/mod_base/templates/base_simple.tpl, modules/mod_base/templates/connection_test.tpl, modules/mod_base/templates/error_websocket.tpl
Fix #1586
Introduce a new `base_noscript.tpl` template in mod_base.
This fixes a problem where people extending from base.tpl do not have a working site due to missing scripts.
=> Add scipts to the mod_base base.tpl.

doc/ref/filters/filter_embedded_media.rst, doc/ref/filters/filter_show_media.rst, doc/ref/filters/filter_without_embedded_media.rst, doc/ref/filters/html/index.rst, modules/mod_base/filters/filter_embedded_media.erl, modules/mod_base/filters/filter_without_embedded_media.erl
Fix #1566
Add filter embedded_media.
Let filter without_embedded_media also consider the text blocks and `body_extra`.
=> mod_base: let filter without_embedded_media also consider text blocks.

doc/ref/modules/mod_acl_user_groups.rst, modules/mod_acl_user_groups/mod_acl_user_groups.erl, modules/mod_acl_user_groups/support/acl_user_groups.hrl, modules/mod_acl_user_groups/support/acl_user_groups_checks.erl, modules/mod_acl_user_groups/templates/_admin_edit_content_acl.tpl, modules/mod_admin/templates/_admin_edit_content_address.tpl, src/models/m_category.erl, src/models/m_rsc.erl, src/models/m_rsc_update.erl
Fix #1211 
Add ACL checks on some privacy sensitive properties.
The restrictions are regulated using the `privacy` property.
The `privacy` property can have the following values:
- 0 public
- 10 members
- 20 member of same user group (except default members group)
- 30 collaboration group members
- 40 collaboration group managers
- 50 private
The default for *person* is 30, for other categories 0.
We use increments of 10 so that more refined options can be added later.
The protected properties are:
- email
- phone
- phone_mobile
- phone_alt
- address_street_1
- address_street_2
- address_postcode
- address_city
- date_start
- date_end
- location_lat
- location_lng
- pivot_location_lat
- pivot_location_lng
- pivot_geocode
- pivot_geocode_qhash
=> Add ACL checks on some properties

Dockerfile, Dockerfile.dev, docker-compose.yml
=> docker: Install openssl to support TLS

modules/mod_base/filters/filter_show_media.erl, modules/mod_base/lib/js/apps/zotonic-1.0.js, modules/mod_editor_tinymce/lib/js/tinymce-4.3.7/tinymce/plugins/zmedia/plugin.min.js, src/support/z_sanitize.erl, src/tests/z_sanitize_tests.erl
Add support for special (unsafe html characters) in z-media caption.
Fixes #1620
=> Add support for special characters in the z-media caption.

src/scripts/helpers/zotonic_setup
This PR expands on #1082 to also use the adminstrator-defined config file in places where rather than find_config_arg, find_config is used. Notably, this is done in rebar. The logic is identical to that earlier occurrence.
=> Allow admin to override default config location also for rebar and such

include/zotonic.hrl, modules/mod_acl_user_groups/support/acl_user_groups_checks.erl, modules/mod_acl_user_groups/tests/mod_acl_user_groups_tests.erl, src/models/m_media.erl, src/models/m_rsc_update.erl
Fix #1639
* Add properties in a acl insert check. This allows acl modules to check properties of newly to be added resources.
* Adapted acl_user_groups to use the added properties to check if the current user is allowed to add a resource of a specific category to the content or collaboration group.
=> Issue 1639

src/support/z_sanitize.erl
Currently the javascript of a tweet embed is removed.
See issue: https://github.com/zotonic/zotonic/issues/1646
Fix #1646
=> Add platform.twitter.com to whitelist

modules/mod_seo/templates/_html_head.tpl
mod_seo: Rename shorturl to shortlink  
shorturl is not accepted by https://validator.w3.org/. Probably shortlink (http://microformats.org/wiki/rel-shortlink) was meant instead of shorturl.
=> mod_seo: Rename shorturl to shortlink

src/support/z_media_preview.erl
Fix #1650 
Remove assertions on image size, return errors instead.
=> Do not crash if resulting image is too big

modules/mod_email_status/templates/_email_status_flag.tpl, modules/mod_email_status/templates/_email_status_view.tpl, rebar.lock, src/smtp/z_email_server.erl
Fix #1655
This shows non final errors as a warning instead of an error.
Also set a higher timeout for smtp connect (which defaults to 5 seconds, which in practice is too low).
=> Better handling for smtp timeout and closed errors.

src/support/z_sites_dispatcher.erl
This is a small fix for missing request data when observing #dispatch_host.
=> Retain reqdata for use in #dispatch_host notification

modules/mod_admin/actions/action_admin_dialog_media_upload.erl
Fix https://github.com/driebit/ginger/issues/283.
#1640 introduced a bug: non-admins no longer have permission to insert files. This is because `Props` can contain `content_group_id` (with value `undefined`) when coming from `action_admin_dialog_media_upload`, so `proplists:lookup` is [not none](https://github.com/zotonic/zotonic/pull/1640/files#diff-2b13477af6ebbdd6a5dba710dbdbc463R203).
=> mod_acl_user_groups: Fix non-admins denied permission to insert file

src/scripts/zotonic-debug, src/scripts/zotonic-start, src/scripts/zotonic-start-nodaemon
This is a temporary workaround for #1673, until #1674 has been tested and merged. This PR is only relevant for 0.x (on master #1673 does not occur).
Ref #1673.
=> scripts: Raise maximum number of atoms

src/erlydtl/erlydtl_runtime.erl
Though only applicable to 0.x, as ErlyDTL has been replaced on master, still useful for us now.
=> Add ErlyDTL maps support

src/scripts/zotonic-sitetest
The `zotonic sitetest` command didn’t read `erlang.config`. This PR adds `erlang.config` to the sitetest arguments. This solves configuration differences between live and test, which caused some of our tests to fail. 
@arjan Did you ignore `erlang.config` on purpose? It seems that we can add it without problems.
=> core: Read erlang.config in sitetest command

include/zotonic.hrl, src/install/z_install.erl, src/install/z_installer.erl, src/models/m_rsc.erl
Fix #1633
Core changes to support older ACL modules again.
Changes to those modules are also needed, and being worked on.
The `mod_acl_adminonly` module is now compatible with this branch.
The `mod_acl_simple_roles` is a bit more complicated as it is also used for 0.x sites.
Maybe it is an idea (going forward) to make a function that maps the simple-roles model to a user-groups model?  Depending on the visible_for flag we can move content to different content groups.
=> Compatibility with older ACL modules.

rebar.config.lock, src/support/z_depcache.erl, src/support/z_stats.erl
Depends on https://github.com/zotonic/depcache/pull/4.
Fix #1677.
=> core: Record depcache evictions in exometer

doc/developer-guide/upgrading.rst, modules/mod_acl_user_groups/mod_acl_user_groups.erl, modules/mod_admin/actions/action_admin_dialog_new_rsc.erl, modules/mod_search/mod_search.erl, modules/mod_twitter/mod_twitter.erl, src/models/m_category.erl, src/models/m_edge.erl, src/models/m_predicate.erl, src/models/m_rsc.erl, src/models/m_rsc_import.erl, src/models/m_rsc_update.erl, src/support/z_datamodel.erl
- Make m_rsc:name_to_id/2 stricter by removing implicit conversion from
textual name to resource id integer.
- Remove digital name conversion from m_rsc:name/2:
- Remove name_to_id_check/2 from m_category, m_predicate and m_rsc to
reduce confusion.
Fix #440.
=> core: Untangle name_to_id and rid

modules/mod_base/filters/filter_slice.erl
Hi!
while trying to slice binary variable (call["caller_id_number"]|slice:[-1,]), got an error: Stack: [{lists,nthtail,[-1,[<<"user_ec34e4">>]],[{file,"lists.erl"},{line,180}]} 
It appears that template_compiler_runtime:to_list/2 just wraps binary var into brackets instead of converting it.
Provided patch solved the problem, do you think there could be any drawbacks?
Regards,
Kirill
=> slice filter: convert binary

.travis.yml
Only use Python packages from requirements.txt, not the Debian (outdated) ones.
=> doc: Move all doc build dependencies to one place 

doc/ref/filters/filter_slice.rst, modules/mod_base/filters/filter_slice.erl
Add *native* binary support to the `slice` filter.
This also changes the behavior of a negative start argument.
Previously the following was documented:
```
{{ [1,2,3,4,5,6,7,8,9,0]|slice:[-7,] }} -> [3,4,5,6,7,8,9,0]
```
But I think it should have been:
```
{{ [1,2,3,4,5,6,7,8,9,0]|slice:[-7,] }} -> [4,5,6,7,8,9,0]
```
As `"1234567890"|slice:[-1,]` should return a string with the last character (`"0"`)
=> mod_base: extended support for binary input to the slice filter.

doc/ref/models/model_rsc.rst, modules/mod_admin/support/admin_rsc_diff.erl, modules/mod_admin/templates/_admin_edit_content_seo.tpl, modules/mod_base/templates/pivot/_main_text.tpl, modules/mod_seo/templates/_html_head.tpl, modules/mod_seo/templates/admin_seo.tpl, src/models/m_rsc.erl
* Remove seo_title, which wasn't used at all.
* Remove seo_keywords, which was used for meta keywords. Google simply ignores those (https://support.google.com/webmasters/answer/79812 and https://webmasters.googleblog.com/2009/09/google-does-not-use-keywords-meta-tag.html), so it makes no sense to bother editors with them.
=> mod_seo: Remove meta title and keywords

src/db/z_db.erl, src/support/z_notifier.erl
Fix #497. 
Among other issues, this fixes the following error during manage_schema (and because of this, random z_sitetest failures):
```{'EXIT',{{case_clause,{rollback,{{badmatch,notfound},[{m_category,move_below,3,[{file,"/opt/zotonic/src/models/m_category.erl"},{line,704}]},{z_datamodel,'-manage/4-lc$^0/1-0-',4,[{file,"/opt/zotonic/src/support/z_datamodel.erl"},{line,65}]},{z_datamodel,manage,4,[{file,"/opt/zotonic/src/support/z_datamodel.erl"},{line,65}]},…,{z_db,'-transaction1/2-fun-0-',3,[{file,"/opt/zotonic/src/db/z_db.erl"},{line,135}]},{timer,tc,2,[{file,"timer.erl"},{line,181}]},{z_db,with_connection,3,[{file,"/opt/zotonic/src/db/z_db.erl"},{line,200}]},{z_db,transaction,3,[{file,"/opt/zotonic/src/db/z_db.erl"},{line,95}]}]}}},[{z_module_manager,manage_schema,4,[{file,"src/suppor …
```
=> core: Delay notifications during database transactions

.editorconfig, GNUmakefile, doc/developer-guide/deployment/env.rst, doc/developer-guide/deployment/privilegedports.rst, docker-compose.yml, priv/zotonic.config.in, src/scripts/zotonic-runtests, src/support/z_config.erl
And environment variables for the HTTP and HTTPS ports that Zotonic receives requests on.
**BC break**: for consistency with `listen_port` and `ssl_listen_port`, I renamed `ZOTONIC_PORT` and `ZOTONIC_SSL_PORT` to `ZOTONIC_LISTEN_PORT` and `ZOTONIC_SSL_LISTEN_PORT` respectively. The old `ZOTONIC_PORT` and `ZOTONIC_SSL_PORT` now refer to `port` and `ssl_port`.
=> core: Add env vars for HTTP and HTTPS ports

src/zotonic_compile.erl
Compiling new files (when adding a site) crashed because of a `no function clause matching`.
=> core: Fix compile options pattern match

rebar.config
Don't check out user sites in `_checkouts`, but add `user/` as an app dir. (This only works for sites and modules that are OTP apps.)
Issue #1743.
=> core: Compile the user/ dir for user sites and modules

doc/ref/actions/action_overlay_open.rst, modules/mod_base/lib/js/apps/zotonic-1.0.js, src/support/z_render.erl
Add an optional `class` argument to the `overlay_open` action.
This class is added to the overlay div.
=> mod_base: add optional class argument to overlay_open action.

src/models/m_rsc_update.erl, src/support/z_datetime.erl
Fix #1766
This fixes an issue where the `-` of negative dates was lost during date conversion.
It exposed a problem with TZ conversion for dates < 0.
=> Fix a problem with entering negative dates in the admin.

modules/mod_signup/translations/nl.po
Adds missing punctuation to translated sentence "in het invoerveld"
=> Signup email translation missing punctuation

docker/docker-entrypoint.sh
Fix #1777
Updates docker entrypoint script so it works with the zotonic/zotonic:latest and zotonic/zotonic-heavy:latest images.
=> Update docker entrypoint script to work with latest zotonic

apps/zotonic_core/src/models/m_category.erl, apps/zotonic_mod_base/src/mod_base.erl, apps/zotonic_mod_seo/priv/templates/_html_head_seo.tpl, apps/zotonic_mod_seo/priv/templates/mediaclass.config, apps/zotonic_mod_seo/priv/templates/schema_org/schema.article.tpl, apps/zotonic_mod_seo/priv/templates/schema_org/schema.collection.tpl, apps/zotonic_mod_seo/priv/templates/schema_org/schema.event.tpl, apps/zotonic_mod_seo/priv/templates/schema_org/schema.news.tpl, apps/zotonic_mod_seo/priv/templates/schema_org/schema.organization.tpl, apps/zotonic_mod_seo/priv/templates/schema_org/schema.query.tpl, apps/zotonic_mod_seo/priv/templates/schema_org/schema.video.tpl, apps/zotonic_mod_seo/priv/templates/schema_org/types/_organization.tpl, apps/zotonic_mod_seo/priv/templates/schema_org/types/article.tpl, apps/zotonic_mod_seo/priv/templates/schema_org/types/event.tpl, apps/zotonic_mod_seo/priv/templates/schema_org/types/item_list.tpl, apps/zotonic_mod_seo/priv/templates/schema_org/types/organization.tpl, apps/zotonic_mod_seo/priv/templates/schema_org/types/video.tpl, apps/zotonic_mod_seo/priv/templates/schema_org/types/website.tpl, apps/zotonic_mod_seo/src/mod_seo.erl, doc/ref/controllers/controller_page.rst, doc/ref/modules/mod_seo.rst
* Add structured metadata for most content types.
* Add documentation for the new features.
* Add documentation for some existing features, such as the `noindex` flag.
=> mod_seo: Add Schema.org structured metadata

apps/zotonic_core/src/support/z_validation.erl
Fix #1784
This is the master pull request for #1785
=> zotonic_core: fix a problem where validation crashes on inputs with a ':' in their name

src/support/z_validation.erl
Fix #1784
This fixes a crash when validating form elements with a `:` in their name.
This pull request is for the 0.x branch.
=> core: fix a problem where validation crashes on inputs with a ':' in their name

modules/mod_admin/templates/_admin_menu.tpl, modules/mod_admin/templates/admin_overview.tpl
Fix a problem where the full text search in the admin is not sorted by relevance.
This changes the sorting of the full text queries in the admin to be on relevance, unless a sort column is clicked *after* the search has been done.
=> mod_admin: ensure that text search results are sorted on relevance

apps/zotonic_mod_admin/priv/templates/_action_dialog_connect.tpl, apps/zotonic_mod_admin/priv/templates/_action_dialog_connect_tab_find.tpl, apps/zotonic_mod_admin/priv/templates/_action_dialog_connect_tab_find_results.tpl, apps/zotonic_mod_admin/priv/templates/_action_dialog_connect_tab_find_results_loop.tpl, apps/zotonic_mod_admin/src/mod_admin.erl, apps/zotonic_mod_search/src/support/search_query.erl, doc/developer-guide/search.rst
Manual merge of 1d0c78a80216ca23d01b05e728c97cc8e884c72c
Adds a select box in the admin connect dialog to filter on the content-group of the data.
Also add `asort` and `zsort` search terms.
=> mod_admin: in connect dialog, add filter on content group.

src/scripts/zotonic-runtests
Not pretty, but seems to be the only way to get the tests running reliable again.
=> tests: Raise timeout to fix build failures

apps/zotonic_core/src/models/m_edge.erl, apps/zotonic_mod_acl_user_groups/src/mod_acl_user_groups.erl, doc/developer-guide/upgrading.rst
core: Pivot subject/object when edge is changed
Fix #1722.
=> core: Pivot subject/object when edge is changed

apps/zotonic_core/src/support/z_config.erl, apps/zotonic_core/src/support/z_sites_dispatcher.erl, apps/zotonic_launcher/priv/config/zotonic.config.in, apps/zotonic_listen_http/src/zotonic_listen_http.erl
Fix #1821
Make server header configurable.
Defaults to `Zotonic` (without version number).
=> Make server header configurable. Fixes #1821

apps/zotonic_core/include/zotonic.hrl, apps/zotonic_core/src/smtp/z_email_server.erl, apps/zotonic_core/src/support/z_site_startup.erl, apps/zotonic_core/src/support/z_template_compiler_runtime.erl, apps/zotonic_mod_admin/priv/templates/_name.tpl, apps/zotonic_mod_base/priv/templates/_name.tpl, apps/zotonic_mod_base/src/services/service_base_info.erl
Fix #1842 
Remove the include of zotonic_version.hrl from zotonic.hrl.
This prevents recompiling all files if the version changes.
Also fixes in service_base_info.
=> Remove include of zotonic_version.hrl from zotonic.hrl.

include/zotonic_notifications.hrl, modules/mod_export/controllers/controller_export_resource.erl, modules/mod_export/mod_export.erl, modules/mod_export/support/export_encoder_atom.erl
Rss feeds are currently handled by browsers as a download while the Rss reader plugins want Content-Disposition inline.
This PR allows Content-Disposition to be inline instead of attachment.
It also fixes a problem with unpublished resources to show up in feeds.
=> [mod_export] Observe content disposition

rebar.config.lock
This PR fixes the error thrown when displaying BC dates:
```erlang
[{calendar,last_day_of_the_month,[-2000,1],[{file,"calendar.erl"},{line,240}]},{calendar,date_to_gregorian_days,3,[{file,"calendar.erl"},{line,116}]},{calendar,datetime_to_gregorian_seconds,1,[{file,"calendar.erl"},{line,138}]},{z_dateformat,tzoffset_1,2,[{file,"src/z_dateformat.erl"},{line,387}]},{z_dateformat,tag_to_value,4,[{file,"src/z_dateformat.erl"},{line,171}]},{z_dateformat,replace_tags,6,[{file,"src/z_dateformat.erl"},{line,86}]},{z_dateformat,format,3,[{file,"src/z_dateformat.erl"},{line,68}]},{z_convert,to_json_struct,1,[{file,"src/z_convert.erl"},{line,335}]}]
```
=> deps: Fix BC date handling

modules/mod_search/support/search_parse_list.erl, modules/mod_search/support/search_query.erl
Fix a problem where custom filters terms in query texts give parse errors.
Fix #1854
=> Fix parsing custom-filter values in query texts

doc/ref/filters/filter_date.rst, modules/mod_l10n/support/l10n_date.erl, modules/mod_l10n/translations/fr.po, modules/mod_l10n/translations/nl.po, rebar.config.lock
* Add era notation ('e').
* Add ISO 8601 year notation ('x').
* Fix error when displaying BCE dates.
* Fix ISO 8601 representation for years with fewer than 4 digits.
* Add translations.
=> docs: Incorporate changes from z_stdlib to improve date handling

Dockerfile, Dockerfile.base, Dockerfile.dev, docker-compose.yml
* Run as user zotonic to fix erlexec error "Not allowed to run as root".
* Use official Erlang (Alpine) image instead of our own.
=> docker: Simplify Docker setup by introducing a base image

apps/zotonic_core/src/db/z_db_pgsql.erl, apps/zotonic_core/src/db/z_db_pool.erl, apps/zotonic_core/src/install/z_installer.erl
Copied from #1815, now on master instead of 0.x
This doesn’t fully work yet, as introducing error handling causes changes downstream, such as the status site not working properly. Submitting as a PR as a reference for future work on the issue.
Fix #1776.
=> Add more psql connect error handling and better connect retries.

apps/zotonic_core/src/support/z_dispatcher.erl, apps/zotonic_core/src/support/z_module_indexer.erl, apps/zotonic_core/src/support/z_module_manager.erl, apps/zotonic_filehandler/src/zotonic_filehandler_mapper.erl, apps/zotonic_fileindexer/include/zotonic_fileindexer.hrl, apps/zotonic_fileindexer/rebar.config, apps/zotonic_fileindexer/src/zotonic_fileindexer.app.src, apps/zotonic_fileindexer/src/zotonic_fileindexer.erl, apps/zotonic_fileindexer/src/zotonic_fileindexer_cache.erl, apps/zotonic_fileindexer/src/zotonic_fileindexer_scan.erl, apps/zotonic_fileindexer/src/zotonic_fileindexer_sup.erl, apps/zotonic_filewatcher/src/zotonic_filewatcher_fswatch.erl, apps/zotonic_launcher/src/zotonic_launcher.app.src
The `zotonic_fileindexer` caches directory scans needed by `z_module_indexer`.
This greatly speeds up startup when there are many sites.
The `zotonic_fileindexer` observes `zotonic_filehandler` notifications to flush cached indexes.
=> Add zotonic_fileindexer.

apps/zotonic_core/src/zotonic_core.erl
This fixes a problem where the nodename was not added to the mnesia directory if the directory was configured.
This prevented running multiple nodes or syncing between machines.
Now the `node()` name is always appended to the configured mnesia directory.
=> core: always add the nodename to the mnesia dir.

src/support/z_session_manager.erl
Fix #1889
Set `secure` option for session cookie if the `site.protocol` is `https`
=> Set session cookie to secure if site protocol is https. Fixes #1889

apps/zotonic_core/src/models/m_config.erl
Hi,
While was trying to use Zotonic with file configs instead of running db, got a problem with i18n language_list variable.
m_config:get/3 returns it with key "value" instead of "list".
Here is a quick workaround. Could it be accepted?
My file config looks like this:
[zotonic@beta priv]$ cat ~/zotonic/user/sites/phiz/priv/config.d/translation 
[
{i18n, [{language, "ru"}
,{language_list, [{ru,[{is_enabled,true}
,{fallback,<<"ru">>}
,{language,<<"ru">>}
,{direction,undefined}
,{name,<<"Rus">>}
,{name_en,<<"Russian">>}
,{region,undefined}
,{script,<<"Cyrl">>}
]
}
,{en,[{is_enabled,true}
,{fallback,<<"en">>}
,{language,<<"en">>}
,{direction,undefined}
,{name,<<"English">>}
,{name_en,<<"English">>}
,{region,undefined}
,{script,undefined}
]
}
]
}
]
}
].
[zotonic@beta priv]$ 
Regards,
Kirill
=> i18n language_list variable in text config file

.gitignore, apps/zotonic_core/src/support/z_filehandler.erl, apps/zotonic_filehandler/src/zotonic_filehandler_compile.erl, apps/zotonic_filehandler/src/zotonic_filehandler_handler.erl, apps/zotonic_filehandler/src/zotonic_filehandler_mapper.erl, apps/zotonic_filehandler/src/zotonic_filehandler_mappers.erl, apps/zotonic_filewatcher/src/zotonic_filewatcher_beam_reloader.erl, apps/zotonic_filewatcher/src/zotonic_filewatcher_fswatch.erl, apps/zotonic_filewatcher/src/zotonic_filewatcher_handler.erl, apps/zotonic_filewatcher/src/zotonic_filewatcher_inotify.erl, apps/zotonic_filewatcher/src/zotonic_filewatcher_monitor.erl, apps/zotonic_filewatcher/src/zotonic_filewatcher_sup.erl
Fix filewatch for symlinked priv/src/include directories.
To do:
~~If a new app is found (in user/modules and/or user/sites):~~
1. ~~Wait till no further updates during a couple of seconds~~
2. **Manually** Run rebar3 (`z:compile()`)
If a new directory (application) is found in `_build/default/lib`:
1. Wait till no further updates during a couple of seconds
2. Ensure that the code load path includes the new app
3. Restart the running file watcher so that it adds the new app
4. Reindex the sites and modules (do not automatically start the new application)
In this way checking out a module or site in the user directory, manually compiling it will automatically add all the new code paths to the running Zotonic node.
=> Add filewatcher support for symlinks & added sites/modules

apps/zotonic_mod_translation/include/mod_translation.hrl, apps/zotonic_mod_translation/src/mod_translation.erl
In conjunction with https://github.com/zotonic/zotonic/pull/1888 mod_translation could be used while running Zotonic without mod_admin+Postgres
=> decouple mod_translation

modules/mod_search/support/search_query.erl
From query pages, `hassubject=123` yields `{hassubject, <<"123">>}`.
From templates, however, `hassubject=123` yields `{hassubject, 123}`.
Consequently, we have to split both binaries and integers.
Ref #1894
Fix #1895.
=> mod_search: Fix #1895 by also splitting non-binaries

doc/ref/modules/mod_seo.rst, modules/mod_seo/templates/_ga_params.tpl
Fix #1804
Remove user_id param and update the documentation.
=> remove user_id from google analytics params

modules/mod_admin/controllers/controller_admin_edit.erl, modules/mod_admin/templates/_admin_edit_content_seo.tpl, src/models/m_rsc.erl, src/models/m_rsc_update.erl
Issue #1095
Makes the slug and seo fields translatable.
No BC breaks, afaik. Unless the fields are exported in JSON, as the values are now `{trans, ...}` records.
=> Make slug and seo fields translatable

modules/mod_authentication/controllers/controller_logon.erl, modules/mod_authentication/templates/_logon_reminder_form_fields.tpl, modules/mod_authentication/templates/_logon_stage.tpl, modules/mod_authentication/templates/email_password_reset.tpl, modules/mod_authentication/translations/es.po, modules/mod_authentication/translations/et.po, modules/mod_authentication/translations/fr.po, modules/mod_authentication/translations/nl.po, modules/mod_authentication/translations/pl.po, modules/mod_authentication/translations/ru.po, modules/mod_authentication/translations/tr.po, modules/mod_authentication/translations/zh.po
Fix #1802 
If a password reset is requested, then always send the email to the account(s) associated with the email address. If there is no associated account, then send an email telling there is no account.
**Discussion**
Currently we send the email to both the primary email address and the entered email address.
This allows for the use case where the user lost control of one of the email addresses and forgot the other email address.
Is this wanted behavior?
**Todo**
=> mod_authentication: don't tell if an email address is registered.

include/zotonic_notifications.hrl, modules/mod_admin/support/admin_rsc_diff.erl, modules/mod_admin_merge/mod_admin_merge.erl, modules/mod_admin_merge/templates/_confirm_merge.tpl, src/models/m_rsc.erl, src/models/m_rsc_update.erl
In a *merge & delete* add translations from the *loser* missing in the *winner* to the updated winner.
For example, if winner has languages `[de, en]` and loser has `[en, de, nl]`, then the all `nl` texts from loser should be copied to winner.
TODO:
=> mod_admin_merge: add option to add missing translations to the winner.

src/models/m_rsc_update.erl, src/support/z_datetime.erl, src/support/z_pivot_rsc.erl
Fix #1536.
Anything I’m missing here? Why actually would we want to default start date to now if an end date is given? Why not just leave the start date as entered (i.e., empty)? Or does this also involve searches/pivots?
=> core: Don't default start date to now

src/filewatcher/z_filewatcher_handler.erl
When switching to a Git branch that does not contain some .erl file, the filewatcher still tried to compile that file, crashing with:
`gen_server z_filewatcher_inotify terminated with reason: no match of right hand value {error,enoent} in make:recompilep1/5 line 232`
This change prevents the crash by not compiling deleted files.
Question: is ignoring deletes sufficient or should we add a `code:delete/1` and `code:purge/1` instead?
=> core: Don't crash when files have been deleted

modules/mod_admin_identity/validators/validator_admin_identity_email_unique.erl
Currently the failure_message property for this validator is ignored. This adds this message instead of the current message which it now defaults to, "please correct" is the default message. If no failure_message defined then it still uses "please correct".
=> Support failure_message in email_unique validator

src/support/z_datamodel.erl
c0a89926678de3786ee946f0ec2b99c5e11b2038 introduced a bug where a site
initialization from an empty database (with edges defined) throws:
```erlang
z_db error {error,error,<<"23505">>,
<<"duplicate key value violates unique constraint \"rsc_pivot_queue_pkey\"">>,
[{detail,<<"Key (rsc_id)=(382) already exists.">>}]} in query
"insert into rsc_pivot_queue (rsc_id, due, is_update) values ($1, current_timestamp, true)" with [382]
```
This change fixes that by disabling the automatic object pivot when
m_edge:insert/5 is called from z_datamodel:manage_edge/4.
=> core: Fix pivot failure during manage_data

modules/mod_admin/templates/_action_dialog_media_upload_tab_upload.tpl, modules/mod_admin/templates/_action_dialog_media_upload_tab_url.tpl, modules/mod_oembed/templates/_media_upload_panel.tpl
The callbacks check for content_group_id, but this was never passed to
them.
=> mod_admin: Pass content group id when inserting a resource

apps/zotonic_mod_base/src/filters/filter_format_price.erl
Small refactor: it's possible to use a more concise infix append in `filter_format_price.erl`
=> refactor: simpler infix append

src/support/z_pivot_rsc.erl
This reduces confusion with pivot/2.
- **BC break**
=> core: Remove pivot_resource/2 export

src/support/z_sites_manager.erl, src/zotonic.erl
Place all mnesia files in a directory per node.
Instead of `priv/mnesia` we will now use something like `priv/mnesia/zotonic001@localhost`
On first creation any mnesia files in priv/mnesia will be moved to the new directory.
This solves a problem where a Zotonic node can't be started after the node name changed or if mnesia files from another node are placed in the `priv/mnesia` directory.
This is also compatible with the changes in master.
=> Move mnesia files to a directory per node.

modules/mod_authentication/controllers/controller_logon.erl
m_identity:get_username does not return {ok, Username} but only Username itself or undefined. Currently gives an badmatch error since it cannot be matched on {ok, Username}
=> Badmatch in expired logon on get_username value

apps/zotonic_mod_authentication/priv/templates/_logon_expired_form.tpl
The validation is linked to a field with element id password1, the input field's id is password_reset1. This results in a growl error message.
=> Error message on expired password page

modules/mod_base/controllers/controller_websocket.erl, modules/mod_base/support/z_websocket.erl
Fix #1981
Allow one to send binary data (e.g. video) over a websocket to a webpage.
=> Allow sending binary data over a websocket

Dockerfile, Dockerfile.base, apps/zotonic_launcher/bin/zotonic-start-nodaemon, doc/developer-guide/docker.rst, docker/erlang.config.sed
* Don't mount /opt/zotonic as volume, as it causes files placed in that
directory during build to be lost.
* Disable DEBUG when making for more efficient build output.
=> docker: Fix Docker build by removing volume

src/support/z_sanitize.erl, src/tests/z_sanitize_tests.erl
When embedding YouTube, https:// is currently stripped and replaced
with //. It seems to be we always want to load YouTube (and possibly
other services) over HTTPS, no matter whether the current Zotonic site
is being served over HTTPS or not.
=> core: Embed YouTube over HTTPS

doc/ref/modules/mod_clamav.rst, modules/mod_admin/actions/action_admin_dialog_media_upload.erl, modules/mod_admin/mod_admin.erl, modules/mod_admin/translations/nl.po, modules/mod_base/controllers/controller_file.erl, modules/mod_clamav/docs/notes.md, modules/mod_clamav/mod_clamav.erl, modules/mod_clamav/support/z_clamav.erl, priv/zotonic.config.in, src/models/m_media.erl, src/support/z_media_sanitize.erl
Add `mod_clamav` to enable virus scanning of uploaded files.
This implementation is a first rough implementation. @ddeboer and I agreed to have a fresh look for the 1.0 where we could add sanitization using quarantine states on the medium record.
Also use the HTML sanitizer on uploaded html files.
(Which people rarely have permission to upload anyway).
/cc @mmzeeman
=> mod_clamav: Scan for viruses in uploaded files with ClamAV

modules/mod_admin_identity/templates/_action_dialog_set_username_password.tpl, modules/mod_admin_identity/templates/_action_dialog_user_add.tpl, modules/mod_admin_identity/templates/_identity_password.tpl, modules/mod_admin_identity/translations/nl.po
Passwords for new users were not validated against the `password_regex` config param.
* Refactor duplicated templates.
* Add password failure message.
=> mod_admin_identity: Check password regex for new users

modules/mod_admin/actions/action_admin_admin_tasks.erl
Fix #1995 
Preserve current functionality in admin_task action `flush_all_sites` and edit task `flush` to pass the context to the flush call, causing it to only flush the site at hand.
=> [mod_admin] Don't let flush button in admin interface flush all sites

src/models/m_rsc_update.erl
Duplicate page does not work when the page has a title_slug, even though it is added as undefined to the SafeDupProps
Problem 1. the prop title_slug is added as undefined, then in props filter if the title_slug is empty it is added as a empty slug and title_slug. slug is not allowed as a empty value. Resulting in an empty slug and a database error.
Problem 2. checks for slugs are done by checking custom_slug boolean, this is currently not reset to false. For the slug the value is then not reset to default using the title of the resource for the slug. Resulting in an empty slug and a database error.
=> When duplicate page reset custom_slug boolean

modules/mod_admin_predicate/templates/_admin_edit_content.predicate.tpl, src/models/m_edge.erl
Add an option to insert new edges _before_ existing edges.
Normally edges were inserted after all existing edges.
This option makes it possible to invert that behavior.
Two places:
- `is_insert_before` property on the predicate
- `is_insert_before` option to `m_edge:insert/4`
=> core: Edge insert top

modules/mod_authentication/controllers/controller_logon.erl, modules/mod_authentication/templates/__template_structure.txt, modules/mod_authentication/templates/_logon_error.tpl, modules/mod_authentication/templates/_logon_expired_form.tpl, modules/mod_authentication/templates/_logon_expired_form_title.tpl, modules/mod_authentication/templates/_logon_login_form.tpl, modules/mod_authentication/templates/_logon_login_form_fields.tpl, modules/mod_authentication/templates/_logon_reset_form_fields.tpl, modules/mod_authentication/templates/_logon_stage.tpl, modules/mod_authentication/templates/_logon_tos_agree_form.tpl, modules/mod_authentication/templates/_logon_tos_agree_form_fields.tpl, modules/mod_authentication/templates/_logon_tos_agree_title.tpl, modules/mod_authentication/templates/logon_error/action.tpl, modules/mod_authentication/templates/logon_error/message.need_passcode.tpl, modules/mod_authentication/templates/logon_error/message.passcode.tpl, modules/mod_authentication/templates/logon_error/message.pw.tpl, modules/mod_authentication/templates/logon_error/message.ratelimit.tpl, modules/mod_authentication/templates/logon_error/message.reminder.tpl, modules/mod_authentication/templates/logon_error/message.tooshort.tpl, modules/mod_authentication/templates/logon_error/message.tpl, modules/mod_authentication/templates/logon_error/message.unequal.tpl, modules/mod_authentication/translations/de.po, modules/mod_authentication/translations/es.po, modules/mod_authentication/translations/et.po, modules/mod_authentication/translations/fr.po, modules/mod_authentication/translations/nl.po, modules/mod_authentication/translations/pl.po, modules/mod_authentication/translations/ru.po, modules/mod_authentication/translations/tr.po
Add option to force the user to re-agree with the T&C after authentication.
This is regulated by the config `mod_authentication.tos_update_agree`
The user's property `tos_agreed` (or the user's creation date) is checked against the publication dates of the resources `signup_tos` and `signup_privacy`.
If either publication date is newer than the user's agree date then the user is forced to agree with the T&C after authentication (and before actual logon).
This also restructures the error messages and actions for the logon templates.
There is a separate template for every error message, so that it is easier to change these without resorting to copying the authentication dialogs.
=> Let user re-agree to T&C.  Restructure logon errors.

modules/mod_admin/templates/_action_dialog_edit_basics.tpl
Add block around modal footer in dialog edit basics, so there is less need to overwrite the whole template.
=> Add block around modal footer

modules/mod_authentication/controllers/controller_logon.erl, modules/mod_signup/mod_signup.erl
This adds a configuration option `mod_authentication.tos_agreed_on_create`. When set to a *false* value then creation date of a person is not assumed to be the date the person agreed to the T&C.  If not defined or set to a *true* value then the creation date is assumed to be the date the user agreed to the T&C.
This also sets the `tos_agreed` date in the person record iff the person was added via the signup module.
=> Tos agree on create

modules/mod_acl_user_groups/templates/_admin_catcg.tpl, modules/mod_acl_user_groups/templates/_admin_category_dropdown.tpl, modules/mod_admin/lib/css/zotonic-admin.css, modules/mod_admin/lib/less/base.less, modules/mod_admin/lib/less/dialog-new-connect.less, modules/mod_admin/lib/less/form.less, modules/mod_admin/mod_admin.erl, modules/mod_admin/templates/_action_dialog_connect.tpl, modules/mod_admin/templates/_action_dialog_connect_tab_findnew.tpl, modules/mod_admin/templates/_action_dialog_new_rsc.tpl, modules/mod_admin/templates/_action_dialog_new_rsc_tab.tpl, modules/mod_admin/templates/_action_dialog_new_rsc_tab_find_description.tpl, modules/mod_admin/templates/_action_dialog_new_rsc_tab_find_results.tpl, modules/mod_admin/templates/_action_dialog_new_rsc_tab_find_results_item.tpl, modules/mod_admin/templates/_action_dialog_new_rsc_tab_preview.tpl, modules/mod_admin/templates/_admin_category_dropdown.tpl, modules/mod_admin/templates/_admin_edit_depiction.tpl, modules/mod_admin/templates/_rsc_preview_panel.tpl, modules/mod_admin/translations/nl.po, modules/mod_editor_tinymce/templates/_editor.tpl
Fix #2027 
Redesign of the new connect/new tab.
* Opens preview of items over the "new" form
* Remove filter "valid for <predicate>", category id from form is now leading
* Helper text above search result
To do:
=> Redesign of connect/new tab.

modules/mod_admin/templates/_admin_edit_media.tpl, modules/mod_clamav/mod_clamav.erl, modules/mod_clamav/support/z_clamav.erl, modules/mod_video/templates/_video_viewer.tpl, src/models/m_media.erl
Fix #2030
Set the following flags in the medium record:
* `is_av_scanned` if there is an antivirus module active during medium upload
* `is_av_sizelimit` if an antivirus module reported a file that is too large to scan
Also:
* Fix an issue with replacing the temp video image during re-render (mod_video)
* Add a *View* button in the admin medium panel
=> clamav: set medium flags 'is_av_scanned' and 'is_av_sizelimit'

modules/mod_linkedin/controllers/controller_linkedin_redirect.erl, modules/mod_linkedin/mod_linkedin.erl
Migrate mod_linkedin to LinkedIn v2 API.
This API returns a lot less information, so now only email, first- and last name are stored.
=> Linkedin v2

modules/mod_admin_identity/translations/nl.po, modules/mod_authentication/controllers/controller_logon.erl, modules/mod_authentication/templates/_logon_error.tpl, modules/mod_authentication/templates/logon_error/message.password_change_match.tpl, modules/mod_authentication/translations/nl.po, src/models/m_identity.erl
Adds config option `site.password_force_different` to force a different password on password resets.
=> Add config option to force new password on password reset

modules/mod_acl_user_groups/mod_acl_user_groups.erl, modules/mod_base/filters/filter_match.erl, modules/mod_clamav/mod_clamav.erl, modules/mod_logging/actions/action_logging_addlog.erl, modules/mod_logging/mod_logging.erl, modules/mod_logging/templates/_admin_log_row.tpl, modules/mod_logging/templates/admin_log.tpl, modules/mod_menu/mod_menu.erl, modules/mod_ratelimit/mod_ratelimit.erl, modules/mod_video/support/z_video_convert.erl, priv/sites/testsandbox/config, src/models/m_config.erl, src/models/m_identity.erl, src/support/z.erl, src/support/z_auth.erl, src/support/z_datamodel.erl, src/support/z_module_manager.erl, src/support/z_site_startup.erl
This re-uses mod_logging to log more system related events:
* We don't know the user who removed a user-group member (as this is signaled via the edge update log, which is filled via a trigger)
* Message if a MS-Office file is refused due to linked files. This can be added as a log entry after merging, as this logging branch does not have the office-filtering code yet.
=> Logging of system/acl events in mod_logging

modules/mod_seo/templates/admin_seo.tpl, modules/mod_seo/translations/nl.po
* Never store the value in the database when the value is in the site
config, because the database value will override the site config.
* Improve unclear UI message.
=> mod_seo: Don't store noindex value in db when read from site config

src/support/z_media_identify.erl
This fixes an issue where ImageMagick identify result parsing would fail if the input filename had a space in it.
This only happens if identify is called directly with a file that is not uploaded via Zotonic, as Zotonic ensures filenames do not have spaces in them.
=> Fix identification of files with a space in the name

modules/mod_ratelimit/mod_ratelimit.erl, src/models/m_identity.erl
Change log levels for identity/password modifications and rate limit events.
Also tighten ACL checks in username/pw changes.
=> Log levels and extra checks for identity changes / ratelimit

modules/mod_acl_user_groups/templates/_admin_category_dropdown.tpl, modules/mod_admin/templates/_action_dialog_new_rsc_tab.tpl
Fix #2083
This fixes an issue where in the admin-link dialog the category drop down is empty if it is opened with a subject or object id, but no predicate.
=> Allow all categories if no predicate is defined. Fixes #2083

modules/mod_admin/mod_admin.erl
When using the find dialog (not the new_find dialog) there was an error on the matching of predicate. The predicate was not a binary as assumed in the case.
=> mod_admin: Convert predicate to binary to fix matching

doc/ref/controllers/controller_log_client.rst, doc/ref/filters/filter_log_format_stack.rst, doc/ref/filters/strings/index.rst, doc/ref/modules/mod_logging.rst, modules/mod_base/lib/js/apps/zotonic-1.0.js, modules/mod_logging/controllers/controller_log_client.erl, modules/mod_logging/dispatch/dispatch, modules/mod_logging/filters/filter_log_format_stack.erl, modules/mod_logging/mod_logging.erl, modules/mod_logging/models/m_log_ui.erl, modules/mod_logging/templates/_admin_log_ui_row.tpl, modules/mod_logging/templates/admin_log_base.tpl, modules/mod_logging/templates/admin_log_ui.tpl, modules/mod_logging/translations/nl.po, src/support/z_module_manager.erl
This adds a tab in the `admin/log` where you can see client-side Javascript errors.
The errors are caught in an `onerror` handler and sent with a xhr request to a custom controller in `mod_logging`. The error is then inserted in the ui-log database table and in the info lager log.
To prevent spamming of the database table there is a rate limit of 1 error per second.
The database log is also pruned after a week.
To do:
=> Log client ui errors

modules/mod_auth2fa/mod_auth2fa.erl, modules/mod_auth2fa/models/m_auth2fa.erl, modules/mod_auth2fa/templates/_auth2fa_user_actions.tpl, modules/mod_auth2fa/templates/_dialog_auth2fa_passcode.tpl, modules/mod_auth2fa/translations/nl.po
Only allow the admin (user 1) to change the 2FA settings of the admin.
=> Only allow admin to change admin 2fa settings

modules/mod_search/support/search_query.erl
It is possible to define `sort` terms with queries.
If there are table joins then there might be ambiguity for terms like `created` or `id`.
This prefixes `sort` columns with `rsc.` if there is no table reference in the sort definition.
=> WIP: Ensure 'rsc' table ref on search sort terms

modules/mod_admin/templates/_action_dialog_media_upload_tab_url.tpl, modules/mod_search/mod_search.erl, modules/mod_search/support/search_query.erl
Fix #2089 
Fix some problems with the link/create dialog:
* Enable searching on `id:...`
* Searching on `id:...` now also returns the list of resources with a matching prefix
=> Fix a problem with searching on 'id:..' in the create/link dialog

modules/mod_admin/templates/_action_dialog_edit_basics.tpl
Replaces #1989 
Show the `name` field for all `meta` categories.
Make it required for `category` and `predicate`.
=> admin: show 'unique name' field in quick edit for all meta resources.

src/models/m_rsc_update.erl, src/models/tests/m_rsc_db_tests.erl
Replaces #1963 
Support `dmy` as a date formatter in the properties normalization routines.
=> Support 'dmy' input format for dates.

.travis.yml
Travis is making some changes, which needs modification of the `.travis.yml` file.
See:
https://github.com/gen-smtp/gen_smtp/pull/179
And (original issue):
https://github.com/for-GET/jesse/pull/83
=> Use ubuntu trusty for OTP 18 on Travis 

rebar.config, rebar.config.lock, src/db/z_db.erl, src/db/z_db_pgsql.erl, src/db/z_db_worker.erl, src/install/z_install.erl, src/install/z_installer.erl, src/support/z_sitetest.erl, src/tests/pgsql_perf_db_tests.erl
Fix #2096
Upgrades the epgsql driver we use to version 3.4.0. Please note that this is not the latest version of the driver. But there are slight incompatibilities in 4.x which require more work.
=> Renamed all pgsql references to epgsql

modules/mod_atom_feed/controllers/controller_atom_feed_search.erl, modules/mod_email_receive/models/m_email_receive_recipient.erl, modules/mod_mailinglist/mod_mailinglist.erl, modules/mod_search/services/service_search_search.erl, src/db/z_db.erl, src/db/z_db_pgsql.erl, src/models/m_rsc_gone.erl, src/support/z_sitetest.erl
Use the epgsql `#error{}` record instead of the `{error, ...}` tuple.
=> Use epgsql error record

apps/zotonic_core/src/db/z_db.erl, apps/zotonic_core/src/db/z_db_pgsql.erl, apps/zotonic_core/src/models/m_rsc_gone.erl, apps/zotonic_core/src/support/z_pivot_rsc.erl, apps/zotonic_core/src/support/z_sitetest.erl, apps/zotonic_mod_email_receive/src/models/m_email_receive_recipient.erl, apps/zotonic_mod_mailinglist/src/mod_mailinglist.erl
Instead of a tuple and error codes, use the epgsql error record and the codename.
=> Use the epgsql #error record instead of the tuple.

apps/zotonic_core/src/support/z_sites_manager.erl, apps/zotonic_mod_zotonic_site_management/src/zotonic_status_addsite.erl, priv/skel/nodb/priv/zotonic_site.config.in, rebar.lock
=> Misc fixes (elm support)

apps/zotonic_core/src/support/z_ssl_certs.erl
Fix #2135 
Provide a list of ciphers for the http2 and ssl protocols.
Do not list ciphers that are considered broken.
TODO:
- ~make this more robust between Erlang versions?~ Not for now.
-  ~only hard code the list for the http2 protocol?~ Not for now.
=> WIP: Hardcode a list of ciphers for tls (http2)

doc/developer-guide/deployment/nginx.rst
Fix #[2140]
Add documentation for proxying MQTT transport on websocket with nginx.
=> doc: nginx websocket config (#2140)

apps/zotonic_core/src/zotonic_core.erl, apps/zotonic_launcher/bin/zotonic-debug, apps/zotonic_launcher/bin/zotonic-start, apps/zotonic_launcher/bin/zotonic-start-nodaemon
Fix #2113
Adds a check on the number of schedulers (must be > 1).
Also adds ERLOPTS env var to add options to the ERL command on `debug` or `start`.
=> Check schedulers on startup, add ERLOPTS env var. Fixes #2113

apps/zotonic_mod_admin/src/support/z_admin_media_discover.erl, apps/zotonic_mod_oembed/src/mod_oembed.erl, apps/zotonic_mod_oembed/src/support/oembed_client.erl, apps/zotonic_mod_video_embed/src/mod_video_embed.erl
The JSON decoder now returns a map.
Also: keep the keys in the oembed info as binaries, to prevent creating random atoms.
=> OEmbed fixes

doc/ref/configuration/port-ssl-configuration.rst
Remove references to `ssl_only` from the docs.
See also issue #2147
=> docs: remove reference to 'ssl_only' from the docs.

apps/zotonic_core/src/models/m_media.erl, apps/zotonic_core/src/support/z_media_identify.erl
Better code for insert of `#upload{}` with data but no tmpfile.
=> More robust media identify of uploaded files.

doc/developer-guide/deployment/nginx.rst
Fix #1738
Rewrote the nginx proxy documentation taking into account that Zotonic always
redirects to SSL. Tested the configuration on a live server.
=> docs: updated nginx proxy description

modules/mod_admin/templates/_action_dialog_connect.tpl
Fix #2106
Show the tab with connected media when selecting media from the tinymce editor
=> Show connected media in tinymce select media dialog.

doc/ref/scomps/scomp_pager.rst, modules/mod_base/scomps/scomp_base_pager.erl
Fix #2124
This allows a list to be the `result` argument of the pager scomp.
Also pass the `page` and `pagelen` as arguments if they are not default or not included in the request query arguments.
=> Allow pager to accept a list for the 'result' arg.

apps/zotonic_mod_base/src/scomps/scomp_base_pager.erl, doc/ref/scomps/scomp_pager.rst
Fix #2125
Fix #2124
Merged pager changes.
Now also accepts a list of items or a list of chunks.
=> scomp pager: allow result to be a list. Merge from #2125

modules/mod_admin/templates/_admin_edit_media.tpl
Add a button to copy paste the direct download link of a media item. This will help editors link to downloadable content in the RTE.
=> Download link

modules/mod_admin/templates/admin_base.tpl, modules/mod_base/templates/base.tpl, modules/mod_base/templates/base_simple.tpl, modules/mod_base_site/templates/phone/base.tpl, modules/mod_base_site/templates/phone/base_fullscreen.tpl, modules/mod_base_site/templates/tablet/base.tpl, modules/mod_base_site/templates/text/base.tpl, priv/sites/zotonic_status/templates/base.tpl, priv/skel/blog/templates/base.tpl, priv/zotonic.config.in, src/models/m_site.erl, src/support/z.erl, src/support/z_config.erl, src/support/z_context.erl
Fix #2120
Add a `environment` config reflecting the current DTAP status of a site (or system).
Possible values:
* development
* test
* acceptance
* production
* education
* backup
The DTAP environment is reflected in the `X-DTAP-Environment` headed and in the `environment-...` class on the `<html>` tag (in the default and admin templates).
=> Add support for DTAP environment [clean branch]

rebar.config, rebar.config.lock
gen_smtp 0.14.0 fixes a problem with mime encoding on OTP21
=> Upgrade gen_smtp to 0.14

apps/zotonic_core/src/support/z_mqtt_sessions_runtime.erl, apps/zotonic_mod_admin/src/mod_admin.erl, rebar.lock
Also remove some information disclosure during failed connnections.
Fix #2186
This fixes a problem where the MQTT session could crash during a connect with an existing session.
Also removes an issue where the MQTT session disclosed some session related information in non-successful connack responses.
Also fix an unrelated issue where clicking the 'Visit full edit page' button on the connect/new dialog didn't have any effect.
=> Fix a problem with MQTT reconnects.

src/support/z_media_identify.erl
Fix #2191
This fixes a problem with identifying PDF files where the file starts with a '\t' character.
The magic number is in this case `\t%PDF`, which is not recognized by `file`.
=> Fix PDF identification for some special PDFs

src/i18n/z_trans.erl
Fix #2193
This problem was introduced when a fix was added to prevent `#m{}` values to be passed as templates filter inputs.
That fix didn't work, and the correct fix for the `#m{}` problems would be to add an extra filter in the templates.
=> Fix a problem with map values in templates

modules/mod_logging/controllers/controller_log_client.erl, modules/mod_logging/mod_logging.erl
Fix #2202
No lager info logging if is_ui_ratelimit_check returns false.
Also fixes the mod_logging.ui_log_disabled config check
=> Less noisy UI logging

src/support/z_session_manager.erl
Fix #2205
Adds an option which makes it possible to configurable per dispatch rule to not set a session cookie.
There is currently no place where settings which influence sessions are documented, so something should be added to the release notes.
=> core: Implemented option to make setting the session cookie optional.

apps/zotonic_fileindexer/src/zotonic_fileindexer_cache.erl, apps/zotonic_fileindexer/src/zotonic_fileindexer_scan.erl
Fix #2209
Fixes a problem with indexing filenames and directories that contain unicode characters.
=> fileindexer: fix a problem with indexing unicode filenames.

apps/zotonic_mod_auth2fa/src/mod_auth2fa.erl, doc/developer-guide/upgrading.rst
Fix #2211 
Fix `admin_menu` observe, in master it is now a tuple `#admin_menu{}`
=> mod_auth2fa: Fix admin_menu observe. Fixes #2211

src/support/z_template.erl
Fix #2118
Fix problem where the template path in the template debug was truncated if the template was not "below" the Zotonic directory.
=> Show full filepath in template debug. Fix #2118

modules/mod_editor_tinymce/lib/js/tinymce-4.3.7/tinymce/plugins/zmedia/plugin.min.js, modules/mod_editor_tinymce/lib/js/tinymce-4.9.3/tinymce/plugins/zmedia/plugin.min.js, modules/mod_editor_tinymce/templates/_tinymce_dialog_zmedia_props.tpl
Fix #2105
Add 'delete' button on tinymce zmedia properties dialog
=> mod_editor_tinymce: add zmedia 'delete' button. Fixes #2105

apps/zotonic_mod_editor_tinymce/priv/lib/js/tinymce-4.5.5/tinymce/plugins/zmedia/plugin.min.js, apps/zotonic_mod_editor_tinymce/priv/lib/js/tinymce-4.9.3/tinymce/plugins/zmedia/plugin.min.js, apps/zotonic_mod_editor_tinymce/priv/templates/_tinymce_dialog_zmedia_props.tpl
Fix #2105
Add 'delete' button in zmedia tinymce dialog.
(Also fix line-ending in one of the js plugins)
=> mod_editor_tinymce: add zmedia delete button. Fix #2105

rebar.config, rebar.config.lock, src/smtp/z_email_server.erl
Fix #2229 
In an older change in gen_smtp some exceptions during delivery were not caught anymore.
This leads to crashes in the smtp routines.
Fixed with an update to gen_smtp and improved error handling in the zotonic smtp routines.
=> Fix a problem with smtp exceptions not caught

modules/mod_base/controllers/controller_nocontent.erl, modules/mod_base/dispatch/dispatch
Fix #2226
A controller was added which returns 204 on every request it receives. A dispatch rule was added to mod_base to the `log-client-event` dispatch found in `mod_logging`. When the module is not enabled, the client errors are ignored.
=> Wip blackhole controller

Dockerfile, Dockerfile.heavy, apps/zotonic_launcher/bin/zotonic, docker/docker-entrypoint.sh, docker/s6-service/zotonic/run
Fix #2242 
This PR changes references to start-nodaemon to start_nodaemon, but also allows start-nodaemon in the event someone accidentally uses that.  Also addresses the '-x'(executable) vs '-e'(existing) check.
- [-] documentation updated
- [-] tests added
- [?] no BC breaks
=> start-nodaemon vs start_nodaemon fixes

apps/zotonic_launcher/src/command/zotonic_command.erl
Fix #2240
Adds `_checkouts` to the path, so compiled modules are found.
=> Add _checkouts to the code paths

apps/zotonic_core/src/support/z_config.erl, apps/zotonic_core/src/support/z_config_files.erl, apps/zotonic_core/src/support/z_ssl_certs.erl, apps/zotonic_core/src/zotonic_core_sup.erl, apps/zotonic_launcher/priv/config/zotonic.config.in, apps/zotonic_listen_http/src/zotonic_listen_http.erl, apps/zotonic_listen_mqtt/src/zotonic_listen_mqtt.erl, apps/zotonic_mod_admin_config/priv/templates/_admin_config_ssl.tpl, apps/zotonic_mod_admin_config/priv/templates/admin_config_ssl.tpl, apps/zotonic_mod_admin_config/src/models/m_admin_config.erl, apps/zotonic_mod_authentication/priv/templates/admin_authentication_services.tpl, apps/zotonic_mod_export/priv/templates/_admin_edit_sidebar.tpl, apps/zotonic_mod_ssl_ca/src/mod_ssl_ca.erl, apps/zotonic_mod_ssl_letsencrypt/src/mod_ssl_letsencrypt.erl, doc/ref/configuration/port-ssl-configuration.rst, doc/ref/configuration/zotonic-configuration.rst, doc/ref/directory-structure.rst, doc/ref/modules/mod_ssl_ca.rst, doc/ref/modules/mod_ssl_letsencrypt.rst
Fix #2131
The security directory will be:
* config key `security_dir`
* `/etc/zotonic/security` (created if missing and `/etc/zotonic` exists)
* `~/.zotonic/security` (created if missing)
* Zotonic `priv/security` (if all the above could not be created)
=> Add special security_dir for dhfile and ssl certs.

apps/zotonic_core/src/models/m_edge.erl, apps/zotonic_mod_base/src/mod_base.erl
Fix #2238
Remove the manual re-pivots and add an edge insert/delete observer to `mod_base` to always re-pivot the subject if an edge is inserted or deleted.
This removes the (undocumented) `no_pivot` option and also removes the pivot of the object. If an object needs to be pivoted then a separate observer must be added.
=> Repivot subject on edge changes

apps/zotonic_core/src/support/z_config.erl, apps/zotonic_core/src/support/z_context.erl
Fix #2261 
If the `ssl_listen_port` was set to `none` and `ssl_port` was not configured, then `ssl_port` would be set to `none` as well.
This fixes this problem by defaulting `ssl_port` to 443 if `ssl_listen_port` is set to `none`.
The same is done for `port` and `listen_port`, defaulting to 80.
=> Default ssl_port to 443 if ssl_listen_port is set to 'none'. Fixes #2261

modules/mod_admin/lib/js/apps/admin-common.js, modules/mod_base/lib/js/apps/zotonic-1.0.js
Fix #1838  
Suppress JS console message.
The list of connections is now updated lazily so we don't need to emit the event
=> Do not emit the link-... event if an edge changes

modules/mod_translation/templates/_translation_edit_languages.tpl
Add block around language options so it is possible to overwrite/extend this template in modules/sites with inherit possibilities.
=> Add block around language options

modules/mod_backup/models/m_backup_revision.erl, modules/mod_backup/templates/_admin_edit_sidebar.tpl, modules/mod_backup/templates/admin_backup_revision.tpl
Fix #2266 
Only show the revisions list to users having update permission on the resource.
=> Only show revisions list if user has edit permissions.

apps/zotonic_mod_wires/priv/lib/js/apps/zotonic-wired.js
Fix #2276
Access the error object more carefully it is optional.
=> mod_wires: The error object is optional, carefully access it. Fixes #2276

apps/zotonic_mod_backup/priv/templates/_admin_edit_sidebar.tpl, apps/zotonic_mod_backup/priv/templates/admin_backup_revision.tpl, apps/zotonic_mod_backup/src/models/m_backup_revision.erl
Fix #2266
Only show revisions list if user has edit permissions.
Master merge of #2273
=> Only show revisions list if user has edit permissions. Fix #2266

apps/zotonic_core/src/support/z_config.erl, apps/zotonic_launcher/priv/config/config.d/http-ports.yml, apps/zotonic_launcher/priv/config/zotonic-cloudinit.yml, apps/zotonic_launcher/priv/config/zotonic.config.in, apps/zotonic_launcher/src/zotonic_launcher_config.erl, doc/developer-guide/deployment/zotonic-cloudinit.yml, doc/developer-guide/getting-started.rst
This adds a cloud-init example file, useful for initializing a Zotonic VPS.
Hetzner.de is one of the VPS providers that accept this kind of initialization files.
=> cloud-init example (as accepted by Hetzner)

apps/zotonic_mod_base/priv/dispatch/dispatch, apps/zotonic_mod_base/src/controllers/controller_nocontent.erl
Fix #2226
Add blackhole controller and default client-ui event dispatch to blackhole.
This catches UI error events in case the `mod_logging` is disabled.
=> mod_base: add blackhole controller and dispatch for client-events.

apps/zotonic_mod_zotonic_site_management/priv/skel/blog/priv/templates/_sidebar.tpl
Fix #2235
Do not convert archive months to local timezone when displaying.
This fixes a problem where the wrong months are displayed if the timezone is at negative UTC.
=> blog skel: show archive in UTC. Fix #2235

Dockerfile.base, apps/zotonic_launcher/priv/config/erlang.config.docker, docker/docker-entrypoint.sh, docker/erlang.config.sed
Fix #2166 
For Docker, use the `erlang.config.in` file as-is without modification.
If we need an adapted configuration for Docker then we should make a separate config file.
=> For docker use erlang.config.in as-is. Fixes #2166

modules/mod_ssl_self_signed/mod_ssl_self_signed.erl
Fix #2293 
This PR removes the code which generates DHE key exchange parameters. This process can take a long time, and it is not recommended. Some automated tools check for the usage of
published DHE parameters.
I added the published RFC7919 parameters to the source. When zotonic starts it checks if it 
needs to write a new parameter file to the `ssl` directory. If it does not find find it it saves 
the parameters published as `ffdhe3072`. It is possible to specify which parameter to use by
configuring this as a site setting `default_dh_param_name`. It can be set to `ffdhe2048`, `ffdhe3072` or `ffdhe4096`. Note that it is still possible to supply your own parameter set
by simply store them in the file named `dh-params.pem` in the `ssl` directory.
I tested the parameters with …
=> mod_ssl: Use rfc7919 dhe parameters

modules/mod_admin/lib/css/zotonic-admin.css, modules/mod_admin/lib/less/edit.less, modules/mod_admin/templates/_admin_overview_list.tpl, modules/mod_admin/templates/_admin_system_content_warning.tpl, modules/mod_admin/templates/admin_edit.tpl, modules/mod_admin/translations/nl.po, modules/mod_admin_category/templates/admin_category_sorter.tpl, modules/mod_admin_predicate/templates/admin_predicate.tpl, modules/mod_menu/templates/admin_menu_hierarchy.tpl
Fix #2309
Show warninhg on edit page if editing system content.
Adds classes `cg-...` and `cat-...` to the body tag for the content group and the (inherited) category of the page.
The warning is shown or hidden depending on the classes on the body page.
=> mod_admin: Show warning on edit page if editing system content.

src/support/z.erl, src/support/z_config.erl
Add `z:load_confg()` function to reload the zotonic.config file.
This makes it possible to change some zotonic.config settings without restarting Zotonic.
(Especially the smtp configs and the password).
Note that IP addresses and port numbers are reloaded, but services are not restarted, so any changes to these settings are not effectuated.
=> core: add z:load_config() to reload the zotonic.config file.

modules/mod_admin/lib/css/zotonic-admin.css, modules/mod_admin/lib/less/base.less, modules/mod_admin/lib/less/dialog-new-connect.less, modules/mod_admin/lib/less/environment.less, modules/mod_admin/templates/_action_dialog_new_rsc_tab.tpl
Fix #2305
Fix a problem with the connect/new dialog where the file-upload stays visible if the dialog is opened with a preselected non-media category.
This also moves the title/filter input field above the two columns to make it clearer that the input is affecting both columns.
=> Hide the 'file upload' on initial show with preselected non-media category.

modules/mod_admin/models/m_admin_status.erl, modules/mod_admin/templates/_admin_status_alert.tpl, modules/mod_admin/templates/_admin_system_status.tpl, modules/mod_admin/templates/admin_status.tpl, priv/erlang.config.in, src/zotonic_sup.erl
Fix #1335 
- Adds better config values to erlang.config.in
- Add a warning to the console when zotonic starts with when ssl application is not configured.
- Add a warning to the admin status page (`admin/status`) when not configured.
=> 1337 ssl application configuration

apps/zotonic_core/src/zotonic_core_sup.erl, apps/zotonic_launcher/priv/config/erlang.config.in, apps/zotonic_mod_admin/priv/templates/_admin_status_alert.tpl, apps/zotonic_mod_admin/priv/templates/admin_status.tpl, apps/zotonic_mod_admin/src/models/m_admin_status.erl
Fix #1335
* Add ACL check on m_admin_status
* Adds better config values to erlang.config.in
* Add a warning to the console when zotonic starts with when ssl application is not configured.
* Add a warning to the admin status page (admin/status) when not configured.
Master version of #2304
=> Add better SSL config to erlang.config.in, show status/error if ssl config is default

modules/mod_base/scomps/scomp_base_catinclude.erl, src/support/z_template.erl
Fix #2315
To prevent confusion with using the `name` and the category for catinclude we will move to a system where the name will be prefixed with `name.` (e.g, `foo.name.bar.tpl`) instead of using the name directly (e.g. `foo.bar.tpl`).
In the 0.x both the `bar` and `name.bar` will be supported. 
In the master (1.x) we will only support `name.bar`.
Documentation will be updated in the master branch.
=> Add 'name.<name>' as selector for catincludes

apps/zotonic_core/src/support/z_template_compiler_runtime.erl, doc/developer-guide/templates.rst, doc/developer-guide/upgrading.rst, doc/ref/tags/tag_catinclude.rst
Fix #2315 
To prevent confusion with using the name and the category for catinclude we will move to a system where the name will be prefixed with name. (e.g, foo.name.bar.tpl) instead of using the name directly (e.g. foo.bar.tpl).
In the 0.x both the bar and name.bar will be supported.
In the master (1.x) we will only support name.bar.
Documentation will be updated in the master branch.
=> Add "name.<name>" as selector for catincludes

apps/zotonic_core/src/support/z_config.erl, apps/zotonic_core/src/support/z_ssl_certs.erl, apps/zotonic_core/src/support/z_ssl_dhfile.erl, apps/zotonic_core/src/zotonic_core_sup.erl, apps/zotonic_listen_http/src/zotonic_listen_http.erl, apps/zotonic_listen_mqtt/src/zotonic_listen_mqtt.erl, apps/zotonic_mod_ssl_ca/src/mod_ssl_ca.erl, apps/zotonic_mod_ssl_letsencrypt/src/mod_ssl_letsencrypt.erl
Fix #2293
Use rfc7919 dhe parameters
=> ssl: Use rfc7919 dhe parameters

apps/zotonic_core/src/support/z_media_tag.erl, apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/less/image.less, apps/zotonic_mod_admin/priv/lib/css/zotonic-admin.css, apps/zotonic_mod_admin/priv/templates/mediaclass.config, doc/ref/tags/tag_image.rst
Fix #2306
Add width/height attributes to the `img` tag.
This prevent _jenk_ when the initial page loads and the images are not loaded yet.
=> Add width/height attributes to the img tag

apps/zotonic_filewatcher/src/zotonic_filewatcher_fswatch.erl, apps/zotonic_mod_wires/priv/lib/js/apps/zotonic-wired.js
Issue #2076
Do not change the MQTT client-id when navigating between pages on the same session/tab.
Also fix a problem in fswatch where a filename could be split over two stdout packages.
=> Fixate mqtt client-id using sessionStorage.

apps/zotonic_mod_admin/priv/templates/admin_base.tpl, apps/zotonic_mod_base/priv/lib-src/less/Makefile, apps/zotonic_mod_base/priv/lib-src/less/z.bridge.less, apps/zotonic_mod_base/priv/lib/css/z.bridge.css, apps/zotonic_mod_base/priv/templates/_bridge_warning.tpl
Fix #2076
Show  a warning if the bridge is down.
This displays an alert in the lower right corner if the bridge is disconnected.
=> Show warning in admin if bridge is down. Fixes #2076

apps/zotonic_launcher/src/command/zotonic_cmd_debug.erl, apps/zotonic_launcher/src/command/zotonic_cmd_start.erl, apps/zotonic_launcher/src/command/zotonic_cmd_start_nodaemon.erl, apps/zotonic_launcher/src/command/zotonic_command.erl, apps/zotonic_launcher/src/zotonic_launcher_app.erl
Fix #2279 
Refuse to perform the `start`, `start_nodaemon` and `debug` commands as _root_ user.
=> Refuse to run as root. Fixes #2279

apps/zotonic_core/include/zotonic.hrl, apps/zotonic_core/src/support/z_context.erl, doc/ref/models/model_site.rst
Fix #1329
Add options to set the HSTS headers.
Merges the 0.x changes from #2297 into master.
=> Add HSTS options. Fix #1329

doc/ref/notifications/includes/meta-tick.rst, doc/ref/notifications/includes/tick.rst, doc/ref/notifications/other.rst
Fix #1918
Document `tick` notifications.
=> Document tick notifications. Fix #1918

apps/zotonic_core/src/models/m_identity.erl, apps/zotonic_mod_admin_identity/priv/templates/_identity_password.tpl, apps/zotonic_mod_admin_identity/priv/templates/email_admin_new_user.tpl, apps/zotonic_mod_admin_identity/priv/templates/email_identity_verify.tpl, apps/zotonic_mod_authentication/priv/dispatch/dispatch, apps/zotonic_mod_authentication/priv/lib/js/zotonic.auth.worker.js, apps/zotonic_mod_authentication/priv/templates/_logon_box.tpl, apps/zotonic_mod_authentication/priv/templates/_logon_error.tpl, apps/zotonic_mod_authentication/priv/templates/_logon_expired_form.tpl, apps/zotonic_mod_authentication/priv/templates/_logon_login_form.tpl, apps/zotonic_mod_authentication/priv/templates/_logon_login_form_fields.tpl, apps/zotonic_mod_authentication/priv/templates/_logon_reset_form_fields.tpl, apps/zotonic_mod_authentication/src/controllers/controller_authentication.erl, apps/zotonic_mod_authentication/src/models/m_authentication.erl
Fix #2062
Misc fixes for authentication:
- _rememberme_ checkbox
- passcode handling and field display
- auth logon error display
=> Fix auth 'rememberme' and passcode handling. Fix #2062

apps/zotonic_mod_zotonic_site_management/src/mod_zotonic_site_management.erl
Fix #2343
In `mod_zotonic_site_management` there is a race condition where a starting site could start so fast that the next call waiting for the site to start would return the error that the site is already started.
This fixes this problem by better waiting for the site starting and logging any start error condition.
=> Fix a race condition when starting a new site. Fix #2343

doc/ref/tags/tag_image.rst, modules/mod_admin/lib/css/zotonic-admin.css, modules/mod_admin/lib/less/image.less, modules/mod_admin/templates/mediaclass.config, src/support/z_media_tag.erl
Issue #2306
Add `width` and `height` attributes to the generated `img` tags. This enables the browser to calculate the aspect ratio of the image before it is loaded, thus removing any jenk when loading a page with (non cached) images.
=> core: generate image width and height attributes. Issue #2306

apps/zotonic_core/src/support/z_file_entry.erl, apps/zotonic_core/src/support/z_file_locate.erl, apps/zotonic_core/src/support/z_file_sup.erl, apps/zotonic_core/src/support/z_lib_include.erl, apps/zotonic_core/src/support/z_module_indexer.erl
Fix #2346
Let z_file_locate skip files that cannot be read (access `none` and `write`).
Also cleanup lib code to make it more binary only.
=> Skip lib files that cannot be read. Fixes #2346

apps/zotonic_mod_clamav/src/mod_clamav.erl, apps/zotonic_mod_logging/src/mod_logging.erl, apps/zotonic_mod_ratelimit/src/mod_ratelimit.erl, apps/zotonic_mod_twitter/src/mod_twitter.erl, apps/zotonic_mod_zotonic_site_management/priv/skel/basesite/priv/zotonic_site.config.in, apps/zotonic_mod_zotonic_site_management/priv/skel/blog/priv/zotonic_site.config.in, apps/zotonic_mod_zotonic_site_management/priv/skel/empty/priv/zotonic_site.config.in, apps/zotonic_mod_zotonic_site_management/priv/skel/nodb/priv/zotonic_site.config.in, doc/ref/modules/mod_cron.rst, doc/ref/notifications/includes/meta-tick.rst
Modules implementing `tick_...` should have a dependency on `cron` (as provided by `mod_cron`
=> Add module dependencies for cron, as provided by mod_cron

apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/less/base.less, apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/less/edit.less, apps/zotonic_mod_admin/priv/lib/css/zotonic-admin.css, apps/zotonic_mod_admin/priv/templates/_admin_media_import_list.tpl, apps/zotonic_mod_base_site/priv/templates/page.video.tpl, apps/zotonic_mod_oembed/priv/templates/_oembed_embeddable.tpl, apps/zotonic_mod_oembed/priv/templates/_oembed_embeddable_vimeo.tpl, apps/zotonic_mod_oembed/priv/templates/_oembed_embeddable_youtube.tpl, apps/zotonic_mod_oembed/src/mod_oembed.erl, apps/zotonic_mod_video_embed/priv/templates/_video_embed.tpl, apps/zotonic_mod_video_embed/src/mod_video_embed.erl
Fix a problem where videos where not always resized correctly with the layout.
This adds a wrapper `div.embed-responsive` around iframes of which we know the width and height.
=> mod_video_embed/mod_oembed: Use 'embed-responsive' wrappers in the embed templates.

apps/zotonic_core/src/models/m_identity.erl, apps/zotonic_mod_admin_identity/priv/templates/_action_dialog_set_username_password.tpl, apps/zotonic_mod_admin_identity/priv/templates/_admin_edit_basics_user.tpl, apps/zotonic_mod_admin_identity/priv/templates/_admin_edit_sidebar.person.tpl, apps/zotonic_mod_admin_identity/priv/templates/_admin_edit_sidebar_person_live.tpl, apps/zotonic_mod_admin_identity/priv/templates/_identity_password.tpl, apps/zotonic_mod_admin_identity/priv/templates/admin_users.tpl, apps/zotonic_mod_admin_identity/src/actions/action_admin_identity_dialog_set_username_password.erl, apps/zotonic_mod_authentication/priv/lib/js/zotonic.auth-ui.worker.js, apps/zotonic_mod_authentication/priv/lib/js/zotonic.auth.worker.js, apps/zotonic_mod_authentication/priv/templates/_logon_box.tpl, apps/zotonic_mod_authentication/priv/templates/_logon_expired_form.tpl, apps/zotonic_mod_authentication/priv/templates/_logon_reset_form_fields.tpl, apps/zotonic_mod_authentication/priv/templates/_logon_reset_title.tpl, apps/zotonic_mod_authentication/src/controllers/controller_authentication.erl, apps/zotonic_mod_authentication/src/mod_authentication.erl, apps/zotonic_mod_authentication/src/models/m_authentication.erl
Fix #2061 
Add support for expired passwords.
Passwords are now marked as expired using the `m_identity:set_expired/3` function.
=> Add 'password expired' support. Fixes #2061

doc/ref/actions/action_redirect_incat.rst, doc/ref/actions/admin/index.rst, modules/mod_admin/actions/action_admin_redirect_incat.erl, modules/mod_admin/templates/_admin_edit_content_publish.tpl
Fix #2375
On the admin edit page, only search for the next/prev resource if the next/prev page is requested.
=> mod_admin: replace next/prev on admin with lazy search. Issue #2375

modules/mod_translation/mod_translation.erl, modules/mod_translation/templates/_admin_headeritem.tpl
(cherry picked from commit f9c08b1c4a1bf43911604b71e18ad9c1560486a5)
Fix #2374
Use the `z.lang` cookie to remember language preference, instead of the persistent storage.
=> Use z.lang cookie to store the language preference. Fix #2374

modules/mod_base/controllers/controller_static_pages.erl, src/erlydtl/erlydtl_compiler.erl, src/filewatcher/z_filewatcher_handler.erl, src/support/z_config.erl, src/support/z_file_mtime.erl, src/support/z_lib_include.erl, src/support/z_mediaclass.erl, src/support/z_template.erl, src/zotonic_sup.erl
Cache the `filelib:last_modified/1` lookups.
This is code from the master, slightly adapted for the 0.x
=> Cache file modification time lookups

modules/mod_admin/lib/css/zotonic-admin.css, modules/mod_admin/lib/less/tree-list.less, modules/mod_admin/templates/_admin_edit_content_page_connections.tpl, modules/mod_admin/templates/_admin_edit_content_page_connections_list.tpl, modules/mod_admin/templates/_rsc_edge.tpl, modules/mod_admin/templates/_rsc_edge_list.tpl, modules/mod_admin_predicate/mod_admin_predicate.erl, modules/mod_admin_predicate/templates/_admin_edges_list.tpl, modules/mod_admin_predicate/templates/admin_edges.tpl
Issue #2387 
Truncate long connections lists in the admin page edit.
=> Truncate long connections lists in the admin. Issue #2387 (0.x)

src/support/z_pivot_rsc.erl, src/support/z_site_services_sup.erl, src/support/z_site_sup.erl
Reorganize the site supervisor.
This places the services like pivot and edge-log underneath their own one-for-one supervisor.
These services are allowed to crash and restart without affecting the rest of the running site.
This reorg is done because of a crash autopsy where the pivot server crashed due to a slow database.
=> Reorg site supervisor (0.x)

modules/mod_admin/mod_admin.erl, modules/mod_logging/mod_logging.erl, src/db/z_db_pool.erl, src/support/z_stats.erl
Whenever a database connection is checked back into the pool, a check is done. When the check finds that the pool usage is high, it will log a message.
=> core: Add a database pool usage warning

apps/zotonic_core/rebar.config, apps/zotonic_core/src/support/z_keyserver_callback.erl, apps/zotonic_core/src/support/z_pivot_rsc.erl, apps/zotonic_core/src/support/z_site_services_sup.erl, apps/zotonic_core/src/support/z_site_sup.erl
Fix #2392
Reorganize the site supervisor.
Places some processes underneath a separate one-for-one supervisor, so that when those fail they get restarted and don't take down the site.
=> Reorganize the site supervisor. Fixes #2392

modules/mod_admin/actions/action_admin_dialog_new_rsc.erl, modules/mod_admin_predicate/actions/action_admin_predicate_dialog_predicate_new.erl, modules/mod_admin_predicate/templates/admin_predicate.tpl, modules/mod_base/mod_base.erl, src/models/m_category.erl, src/models/m_hierarchy.erl
* Force category_nr to be reindexed on category hierarchy changes
* Catch error throws on page creation and show a growl error.
=> Catch throw on creation of pages or predicates.

apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_core/src/behaviours/zotonic_model.erl, apps/zotonic_core/src/models/m_modules.erl, apps/zotonic_core/src/support/z_model.erl, apps/zotonic_core/src/support/z_module_manager.erl, apps/zotonic_core/src/support/z_mqtt_sessions_runtime.erl, apps/zotonic_core/src/support/z_proc.erl, apps/zotonic_mod_authentication/src/controllers/controller_authentication.erl, apps/zotonic_mod_authentication/src/support/z_authentication_tokens.erl, apps/zotonic_mod_server_storage/rebar.config, apps/zotonic_mod_server_storage/src/mod_server_storage.erl, apps/zotonic_mod_server_storage/src/models/m_server_storage.erl, apps/zotonic_mod_server_storage/src/z_server_storage.erl, apps/zotonic_mod_server_storage/src/zotonic_mod_server_storage.app.src, doc/ref/models/model_server_storage.rst, doc/ref/modules/mod_mqtt.rst, doc/ref/modules/mod_server_storage.rst
Fix #2064 
Add server side storage.
Uses an unique sid in the z.auth cookie to identify the client.
To do:
=> Secure server side storage

apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_core/src/db/z_db.erl, apps/zotonic_core/src/db/z_db_pgsql.erl, apps/zotonic_core/src/models/m_predicate.erl, apps/zotonic_core/src/support/z_context.erl, apps/zotonic_core/src/support/z_mqtt_sessions_runtime.erl, apps/zotonic_mod_admin/src/actions/action_admin_zmedia_choose.erl, apps/zotonic_mod_authentication/src/controllers/controller_authentication.erl, apps/zotonic_mod_authentication/src/mod_authentication.erl, apps/zotonic_mod_development/priv/templates/admin_development.tpl, apps/zotonic_mod_development/src/mod_development.erl, apps/zotonic_mod_development/src/models/m_development.erl, apps/zotonic_mod_development/src/support/z_development_dbtrace.erl, apps/zotonic_mod_server_storage/src/mod_server_storage.erl, apps/zotonic_mod_server_storage/src/models/m_server_storage.erl, apps/zotonic_mod_server_storage/src/z_server_storage.erl
Fix #2390
Trace slow database queries and better timeout handling.
Todo:
=> Add db query tracing.

apps/zotonic_core/src/support/z_template_compiler_runtime.erl, apps/zotonic_mod_development/priv/templates/admin_development.tpl, apps/zotonic_mod_development/src/models/m_development.erl, doc/ref/tags/tag_cache.rst
Fix #2408
Add option to disable the cache tag to mod_development.
=> Add 'mod_development.nocache' option to disable the cache tag

modules/mod_filestore/mod_filestore.erl, modules/mod_filestore/model/m_filestore.erl, modules/mod_filestore/support/filestore_uploader.erl
Fix #2187
In mod_filestore, retry upload and download errors after 10 minutes.
This fixes a problem where downloads would not be retried after a transient error happened.
=> mod_filestore: retry upload / download errors

modules/mod_filestore/mod_filestore.erl, modules/mod_filestore/support/filestore_uploader.erl, src/support/z_file_entry.erl, src/support/z_file_request.erl, src/support/z_file_sup.erl
There was a race condition at the moment a file was moved to s3.
After the file entry was marked _stale_ it was racing against the
caching system moving the file to the cache.
If the file entry found the file still on disk then it could assume it
was serving a disk file and wouldn't check the filestore or caching
system for s3 files.
If the caching system then moved the file away, the file entry
could not find the file anymore. Either serving an empty file or
re-generating a preview of the original file.
This fixes this scenario by _pausing_ the file entry for the duration
of the hand-off of the file to the caching system.
=> mod_filestore: fix race condition.

apps/zotonic_core/rebar.config, apps/zotonic_core/src/support/z_config.erl, apps/zotonic_core/src/support/z_ssl_certs.erl, apps/zotonic_core/src/support/z_ssl_dhfile.erl, apps/zotonic_mod_admin_config/src/models/m_admin_config.erl, apps/zotonic_mod_ssl_letsencrypt/src/mod_ssl_letsencrypt.erl, apps/zotonic_site_status/priv/zotonic_site.config, rebar.lock
Fix #2435 
Use the `zotonic_ssl` library for cert parsing and DH file generation.
Also restrict ssl connections to tlsv1.2
=> Use zotonic_ssl lib, remove tlsv1.1 and tlsv1

apps/zotonic_core/src/support/z_model.erl
Assume only atoms and binaries are used to match on the path elements.
All other strings could also be non-unicode strings.
Fix #2438
=> z_model: do not map strings to binary in the search path.

apps/zotonic_core/src/models/m_category.erl, apps/zotonic_core/src/support/z_edge_log_server.erl, apps/zotonic_core/src/support/z_pivot_rsc.erl, apps/zotonic_core/src/support/z_pivot_rsc_task_job.erl, apps/zotonic_core/src/support/z_utils.erl, apps/zotonic_mod_filestore/src/support/filestore_admin.erl
=> Pivot tasks as sidejob 

apps/zotonic_mod_seo/priv/templates/_html_head_seo.tpl
While both Shortlink and Canonical links _can_ be relative, it is both
common practice and expected by search engines to use full URLs,
especially when no <base> tag is used.
=> Shortlink and Canonical links should be full URLs

apps/zotonic_launcher/bin/zotonic, bin/zotonic, doc/developer-guide/deployment/env.rst, start.sh
Enhance zotonic security.
- Update shell scripts with usual good practices.
- Let PATH and ZOTONIC variables be readonly before started.
- Add variable ZOTONIC_WAIT_VM to wait for total stop of Erlang VM if required.
This can be needed when all resources have to be release before a new start.
Document ZOTONIC_PIDFILE.
=> System security

apps/zotonic_launcher/bin/zotonic, bin/zotonic
- Protect shell command of path with dash and space with --
- rewrite variables from $VAR to ${VAR}
- update missing brackets surrounding some variables
=> Update system security for shell scripts

apps/zotonic_core/src/models/m_config.erl, apps/zotonic_mod_translation/priv/templates/_translation_edit_languages.tpl, apps/zotonic_mod_translation/src/mod_translation.erl, apps/zotonic_mod_translation/src/models/m_translation.erl
Fix #2487 
- If a default language is set, force it to be enabled
- On admin edit page, ensure a language tab is selected
=> Fix a problem where setting default language could not enable the language

apps/zotonic_launcher/src/command/zotonic_cmd_config.erl
Add # comment on titles
Add dynamic underlining depending node name length
Let output valid YAML for config. This allow external tools to validate or use Zotonic YAML config.
=> Let output valid YAML for config

apps/zotonic_mod_logging/src/models/m_log_ui.erl
This fixes an issue where the YandexBot is logging many errors due to their erroneous WebSocket connection attempts.
=> Drop UI events coming from the Yandex Bots

apps/zotonic_mod_facebook/priv/templates/_html_head_facebook.tpl, apps/zotonic_mod_facebook/priv/templates/mediaclass.config, apps/zotonic_mod_seo/priv/templates/mediaclass.config, apps/zotonic_mod_twitter/priv/templates/_html_head_twitter.tpl
Fix #2495
Use the same mediaclass for Twitter and Facebook meta tags.
=> New mediaclasses for head meta tags. Fixes #2495

modules/mod_base/lib/js/apps/zotonic-1.0.js
Fix #2508
Changing the language could add an extra `?` in the front of the search path.
=> Fix a problem where changing language via javascript added an extra '?' to the url. Issue #2508

modules/mod_base/lib/js/modules/livevalidation-1.3.js
=> Allow custom validator to show errors on empty input

apps/zotonic_mod_wires/priv/lib/js/modules/livevalidation-1.3.js
Fix #2514
Allow error messages on empty input with Custom validators.
=> Allow error on empty input with Custom validator. Fix #2514

src/models/m_rsc_update.erl
Prevents silent failures if throw is never caught,
which happens in controllers.
=> Log errors on resource update

apps/zotonic_mod_translation/priv/templates/_language_switch.tpl, apps/zotonic_mod_translation/priv/templates/language_switch.tpl, apps/zotonic_mod_translation/src/mod_translation.erl
Change the language switch to generate URLs with the correct slug if an id is known.
This prevents the use of URLs with slugs belonging to another language.
Especially Google is prone to find those "wrong" URLs as it is using Javascript to crawl sites.
=> Generate lang switch URLs with the correct slug

apps/zotonic_core/rebar.config, apps/zotonic_core/src/support/z_ssl_certs.erl, rebar.lock
Push collecting the save tls socket options to `zotonic_ssl`. This library knows which options are safe to use for the OTP release the user is using.
=> Use zotonic_ssl 1.0.3

rebar.config.lock
Upgrade to mochiweb, which creates a safer TLS cipher suite based on the available algorithms in OTP and OpenSSL.
See: https://github.com/zotonic/mochiweb/pull/12 for details.
=> Bump mochiweb version to use better TLS cipher suite.

apps/zotonic_core/src/smtp/z_email_server.erl, apps/zotonic_mod_video/src/mod_video.erl, apps/zotonic_mod_video/src/support/z_video_convert.erl, apps/zotonic_mod_video/src/support/z_video_info.erl, apps/zotonic_mod_video/src/support/z_video_preview.erl
Optimizes mod_video by not converting correctly orientated h264/aac video files.
=> Refactor mod_video, do not rerender h264/aac files.

apps/zotonic_mod_zotonic_site_management/priv/skel/blog/priv/dispatch/dispatch
The controller_page will return a 404 for home page in the base setup.
Fix #2546
The default dispatch rules for the blog homepage should be controller_template instead of controller_page as the home page is not a resource.
I'm unsure if there are any tests for the skel sites as the default.
=> Fix default blog generator.

src/models/m_rsc_export.erl
Privacy filtering on person resources looks into proplist values
recursively, because export data is nested. Also fixes the list
fold parameter ordering.
=> core: Fix m_rsc_export for person resources

apps/zotonic_mod_base/src/controllers/controller_redirect.erl, doc/ref/controllers/controller_redirect.rst
Remove dispatch args from generated redirect url.
Document ACL options for controller_redirect.
=> controller_redirect: filter arguments, document acl option.

apps/zotonic_core/src/db/z_db.erl, apps/zotonic_core/src/db/z_db_pool.erl, apps/zotonic_core/src/support/z_access_syslog.erl, apps/zotonic_core/src/support/z_cowmachine_middleware.erl, apps/zotonic_core/src/support/z_file_request.erl, apps/zotonic_core/src/support/z_mqtt_sessions_runtime.erl, apps/zotonic_core/src/support/z_sites_dispatcher.erl, apps/zotonic_core/src/support/z_stats.erl
This allows serializing db pool requests during peak load, without emitting warnings.
If the db connection-pool takes more than 10msec to return a connection there will be a warning about the pool being close to full.
If the db connection-pool returns `full` then the warning about the pool exhaustion is raised.
Also a statistic `zotonic.[site].db.connection_wait` is added.
This is a histogram with the µsec wait time needed to get a connection from the pool.
=> Only warn about db pool when waiting period increases.

apps/zotonic_core/src/db/z_db.erl
Fix #2369
Support `"schema.table"` for the `z_db` routines that accept a table name.
This makes it possible to query between different schemas (in the same database).
=> Support 'schema.table' for the z_db routines with a table name.

apps/zotonic_core/src/support/z_lib_include.erl
Fix #2530
Allow both `css/sites.css` and `lib/css/site.css` paths for the lib tag.
Also add more type specs and small cleanup of `z_lib_include.erl`
=> Allow 'lib/' prefix for lib-tag files. Fix #2530

apps/zotonic_core/priv/translations/zotonic.pot, apps/zotonic_mod_admin/priv/templates/_admin_edit_content_page_connections_list.tpl, apps/zotonic_mod_admin/priv/templates/_rsc_edge_list.tpl, doc/ref/modules/mod_admin.rst
Fix #2580
Make max edge list length in the admin configurable, defaults to 100 connections.
Adds the configuration key mod_admin.edge_list_max_length
=> Make max edge list length configurable. Fixes #2580

modules/mod_oembed/support/oembed_providers.erl
This PR adds an oembed provider for links to SoundCloud audio.
Zotonic will accept them as document resources (type: rich).
=> Add SoundCloud oembed provider

apps/zotonic_mod_survey/src/models/m_survey.erl, apps/zotonic_mod_survey/src/support/survey_test_results.erl
Fix #2589
Some maps should have been a proplist.
As the proplists are used for storage of the answers in the database.
=> Fix a problem with counting points on survey submission. 

apps/zotonic_core/src/i18n/z_language_data.erl, apps/zotonic_core/src/support/z_module_indexer.erl, crowdin.yml
In the language data there is a distinction between `zh-hans` and `zh-hant`.
External systems, like crowdin don't use `zh-hant` but `zh-TW` for the language code.
So we need to use `zh-TW`.
As Zotonic uses lower cased language code we also need to map the `zh-TW` in the po file to `zh-tw`.
=> Only make distinction between zh and zh-tw

apps/zotonic_core/src/i18n/z_language.erl, apps/zotonic_core/src/i18n/z_language_data.erl, apps/zotonic_mod_menu/priv/templates/_menu_edit_scripts.tpl, apps/zotonic_mod_translation/priv/templates/_dialog_language_delete.tpl, apps/zotonic_mod_translation/priv/templates/_dialog_language_edit_detail.tpl, apps/zotonic_mod_translation/priv/templates/_dialog_language_edit_detail_item.tpl, apps/zotonic_mod_translation/src/mod_translation.erl, apps/zotonic_mod_wires/src/support/z_render.erl, crowdin.yml
Map crowdin zh-TW to zh-hant.
Add aliases for languages.
This fixes an issue with selecting traditional Chinese for languages like zh-HK and zh-TW.
Traditional Chinese will be stored as `zh-hant`.
Simplified Chinese will be stored as `zh`
Also add catinclude for dialogs and menu editor.
=> Fix traditional/simplified chinese fallbacks.

apps/zotonic_core/include/zotonic_file.hrl, apps/zotonic_core/src/support/z_file_entry.erl, apps/zotonic_core/src/support/z_file_locate.erl
If a file with a medium record is served, then use the mime type of the medium and do not derive it from the file extension.
=> Use the mime type of the medium, if available.

apps/zotonic_mod_admin/priv/templates/_admin_status_update_pivot_count.tpl, apps/zotonic_mod_base/priv/templates/_html_head.tpl, apps/zotonic_mod_base/priv/templates/_html_head_cotonic.tpl, apps/zotonic_mod_base/src/controllers/controller_mqtt_transport.erl, apps/zotonic_mod_base/src/scomps/scomp_base_worker.erl, apps/zotonic_mod_wires/priv/lib/js/apps/zotonic-wired.js
This fixes a problem with lost messages during startup.
Also, by pre-connecting the mqtt connection the bridge is started earlier.
* Use cotonic.ready promise
* Use / topics
* Pre-connect the websocket
* Catch early topic clicks and submits, replay on cotonic.ready
See also the companion pull request https://github.com/cotonic/cotonic/pull/45
=> Cotonic startup improvements.

apps/zotonic_mod_admin_frontend/priv/lib/js/modules/admin-frontend.js, apps/zotonic_mod_admin_frontend/priv/templates/page_admin_frontend_edit.tpl, apps/zotonic_mod_menu/priv/templates/_menu_edit_scripts.tpl
Fixes an issue where on a slow connection the edit-form would not be loaded,
The frontend edit page in general needs to be restructured so that it is more compatibel with layouts other than with a top-menu bar.  Also the includes are not fully compatible with other base templates.
=> Fix race condition in init of /edit pages.

apps/zotonic_mod_admin/priv/templates/_admin_edit_main_parts.tpl, apps/zotonic_mod_admin/priv/templates/_admin_features.category.tpl
Fix #2613
This PR removes a couple of default values:
- one default which makes the address widget always visible in admin
- another default which makes the `show address` feature always checked in the category edit page
=> fix address widget everywhere (#2613)

modules/mod_logging/mod_logging.erl
Refactor ACL check `is_admin` to check permission of use of the mod_logging module.
=> Refactor permissions to check use of mod_logging

apps/zotonic_mod_admin/priv/templates/_admin_edit_main_parts.tpl, apps/zotonic_mod_admin/priv/templates/_admin_features.category.tpl, apps/zotonic_mod_admin_frontend/priv/templates/_admin_frontend_edit.tpl, doc/developer-guide/upgrading.rst
Fix #2613
Rename the feature flags of the categories to "is_..." as then a proper boolean value is
=> Rename 'feature_..' to 'is_feature_..'

modules/mod_seo/templates/_html_head_seo.tpl
Fix #1628
Use summary filter for the meta description tag
=> Fix #1628: Use summary filter for meta description

apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_core/src/support/z_auth.erl, apps/zotonic_core/src/support/z_context.erl, apps/zotonic_mod_authentication/priv/templates/logon.tpl, apps/zotonic_mod_authentication/src/mod_authentication.erl
Add support routines for logon and signup during MQTT posts.
TODO:
=> Add support for auth switching.

apps/zotonic_mod_base/priv/lib-src/less/z.icons/icon-buttons.less, apps/zotonic_mod_base/priv/lib/css/z.icons.css, apps/zotonic_mod_signup/priv/templates/signup_confirm.tpl, apps/zotonic_mod_signup/src/controllers/controller_signup_confirm.erl, apps/zotonic_mod_signup/src/mod_signup.erl
Automatically post the signup confirm page if a key is known.
Also fix masking/unmasking the form and page.
=> Fix signup confirm. Change position of social icons in social login buttons.

apps/zotonic_mod_admin_frontend/priv/dispatch/dispatch, apps/zotonic_mod_base/src/controllers/controller_page.erl, apps/zotonic_mod_base/src/controllers/controller_template.erl, doc/ref/controllers/controller_page.rst, doc/ref/controllers/controller_template.rst
This fixes a problem where the browser is caching old versions of edit pages.
=> Add option 'nocache' to page and template controllers.

apps/zotonic_core/src/db/z_db_pgsql.erl, apps/zotonic_mod_authentication/priv/dispatch/dispatch, apps/zotonic_mod_authentication/priv/lib/js/zotonic.auth.worker.js, apps/zotonic_mod_authentication/src/mod_authentication.erl, apps/zotonic_mod_authentication/src/models/m_authentication.erl, apps/zotonic_mod_authentication/src/support/z_authentication_tokens.erl, apps/zotonic_mod_base/src/controllers/controller_http_error.erl, apps/zotonic_mod_oauth2/priv/lib/js/zotonic.oauth.worker.js, apps/zotonic_mod_oauth2/src/models/m_oauth2_service.erl, apps/zotonic_mod_signup/src/controllers/controller_signup.erl, rebar.lock
This fixes a problem where when running behind a proxy cluster the onetime token was dependent on the peer ip address of the proxy. The IP address could vary, and with that the onetime-token could be rejected.
Now the token is dependent on the unique sid of the client.
=> Fix a problem where OAuth2 login didn't work if peer ip address changes.

apps/zotonic_core/src/support/z_context.erl, apps/zotonic_core/src/support/z_cowmachine_middleware.erl, apps/zotonic_core/src/support/z_datamodel.erl, apps/zotonic_core/src/support/z_mqtt_sessions_runtime.erl, apps/zotonic_mod_admin/src/support/admin_rsc_diff.erl, apps/zotonic_mod_authentication/priv/lib/js/zotonic.auth.worker.js, apps/zotonic_mod_authentication/src/controllers/controller_authentication.erl, apps/zotonic_mod_authentication/src/support/z_authentication_tokens.erl, apps/zotonic_mod_base/src/controllers/controller_mqtt_transport.erl, apps/zotonic_mod_mqtt/src/models/m_client_local_storage.erl
Replace the `sid` as generated by the authentication code with the `cotonic-sid` as managed by Cotonic.
This fixes an issue where the `sid` could not be synchronized between MQTT and HTTP requests.
=> Removed server generated sid, replace with cotonic-sid.

.github/workflows/test.yml, doc/cookbook/justenough-otp1.rst, doc/developer-guide/getting-started.rst, doc/developer-guide/upgrading.rst, doc/ref/installation/requirements.rst, rebar.config
This because some dependencies set their mininmum OTP version to 22 now.
=> Set minimum OTP version to 22.

apps/zotonic_launcher/src/command/zotonic_cmd_stop.erl, apps/zotonic_launcher/src/zotonic.erl
Fix #2668 
Only stops our own essential processes, and then kills all ports by halting the VM with status 0.
This fixes a problem where the `beam.smp` stays running with high CPU after being requested to stop using `init:stop()`
=> Quicker shutdown

apps/zotonic_core/rebar.config, apps/zotonic_core/src/smtp/z_email_server.erl, erlang_ls.config, rebar.lock
Fix #2672
Mailgun gives spurious authentication failed errors when sending.
As that is a permanent error the mail would be dropped.
This makes the `auth_failed` error a temporary error so that the email will be retried.
=> Fix an issue where email could be dropped on authentication failures by email relays.

apps/zotonic_mod_auth2fa/priv/templates/_dialog_auth2fa_passcode.tpl, apps/zotonic_mod_auth2fa/src/mod_auth2fa.erl, apps/zotonic_mod_auth2fa/src/models/m_auth2fa.erl, apps/zotonic_mod_authentication/priv/templates/logon_error/message.need_passcode.tpl, apps/zotonic_mod_authentication/priv/templates/logon_error/message.passcode.tpl, apps/zotonic_mod_authentication/priv/templates/logon_error/message.pw.tpl, apps/zotonic_mod_authentication/priv/templates/logon_error/message.ratelimit.tpl
Make it clearer who the issuer of a TOTP 2FA QR code is by using the site's title as the issuer.
=> Use the site title as the issuer for 2FA totp urls.

apps/zotonic_core/src/support/z_sanitize.erl, apps/zotonic_mod_oembed/src/mod_oembed.erl, apps/zotonic_mod_oembed/src/support/oembed_client.erl, apps/zotonic_mod_oembed/src/support/oembed_providers.erl
Embed prezi video and issuu docs.
GIve oembed video a higher priority, so that it displays before images.
=> Add prezi video and issuu oembed providers.

apps/zotonic_mod_signup/priv/templates/_signup.tpl, apps/zotonic_mod_signup/src/controllers/controller_signup.erl, apps/zotonic_mod_signup/src/models/m_signup.erl, doc/ref/models/model_signup.rst
Fix a problem where users authenticating via 3rd parties always redirect to their home page, whereas users authenticating via username/password signup are redirected depending on the result of the `#signup_confirm_redirect{}` notification.
=> Signup redirect for users authenticating via 3rd parties

apps/zotonic_mod_admin/priv/templates/_admin_js_include.tpl, apps/zotonic_mod_base/cotonic-fetch.sh, apps/zotonic_mod_base/priv/dispatch/dispatch-cotonic, apps/zotonic_mod_base/priv/templates/_js_include.tpl, apps/zotonic_mod_base/priv/templates/tests/initial_postback_test.tpl, apps/zotonic_mod_base/src/scomps/scomp_base_worker.erl, apps/zotonic_mod_base_site/priv/templates/_js_include.tpl, apps/zotonic_mod_zotonic_site_management/priv/skel/blog/priv/templates/base.tpl
- Use the standard cotonic release instead of building a zotonic specific version.
- Make it possible to download a specific cotonic branch or tag. This makes it easier to test new features and pin the version of the cotonic library for releases.
=> Wip pin cotonic

apps/zotonic_launcher/src/command/zotonic_cmd_config.erl
Fix #2492
Fixes a problem with YAML output not being legal YAML.
This needs a real fix by using a generic YAML output application.
=> Bit better YAML output for erlang terms. Fixes #2492

Dockerfile.dev, doc/developer-guide/directory-structure.rst, doc/developer-guide/docker.rst, doc/developer-guide/upgrading.rst, docker-compose.yml, docker/docker-entrypoint.sh, docker/erlang.config
Fix #2709
This fixes permission issues in mounted directories.
* Change the Docker file to use the UID and GID of the host's Zotonic directory.
* Upgrade to OTP-24
* Place all docker files in the docker-data directory
Changes the location of the configuration files and security directory to:
* `docker-data/config`
* `docker-data/security`
* `docker-data/logs`
* `docker-data/data`
=> Set docker user-id to the host user-id

apps/zotonic_mod_search/src/support/search_query.erl
The time was not used in the query. This caused events which just finished to disappear from the results.
=> Use current_timestamp instead of current_date so the time is also used in the query.

.github/workflows/test.yml
Issue #2721 
Upgrade Erlang to 24.0.5 to check issue #2721
=> Upgrade CI Test to OTP 24.0.5

apps/zotonic_core/src/support/z_edge_log_server.erl
This makes sure the edge log check will be done after the transaction finishes.
The edge log check was done inside a transaction, however when edges are inserted by the user in a transaction the edge log information was not visible yet because it was set in a nested transaction. This caused edge notifications to be fired much later. Using zotonic's notification mechanism makes sure the check is done after the transaction is committed.
=> Do the edge log check via a notification 

src/models/m_predicate.erl
Fix #2737
Fixed a typo, so the `predicate_for_subject` information cache will be flushed when a predicate changes.
=> Fixed typo

apps/zotonic_core/src/support/z_mqtt_sessions_runtime.erl, apps/zotonic_listen_mqtt/src/zotonic_listen_mqtt_handler.erl
Fix #2742
Add language, timezone and peer_ip to the mqtt context.
=> Add language, tz and peer_ip to mqtt context

apps/zotonic_core/src/support/z_module_manager.erl, doc/developer-guide/modules.rst
This makes it possible to return multiple data models to be installed.
Which is useful to install extra (test) data, depending on the current site environment.
=> Allow the manage_schema/2 function return a list of datamodels.

apps/zotonic_core/src/support/z_context.erl, apps/zotonic_mod_authentication/priv/templates/logon.tpl, apps/zotonic_mod_authentication/src/controllers/controller_logoff.erl, apps/zotonic_mod_authentication/src/controllers/controller_logon_done.erl, apps/zotonic_mod_base/src/filters/filter_is_site_url.erl, apps/zotonic_mod_base/test/base_filter_tests.erl, apps/zotonic_mod_translation/priv/templates/language_switch.tpl, apps/zotonic_mod_translation/src/controllers/controller_language_set.erl, apps/zotonic_mod_translation/src/mod_translation.erl, apps/zotonic_site_testsandbox/priv/zotonic_site.config, doc/ref/filters/filter_is_site_url.rst, doc/ref/filters/filter_url.rst, doc/ref/filters/filter_url_abs.rst, doc/ref/filters/filter_urlencode.rst, doc/ref/filters/miscellaneous/index.rst, doc/ref/filters/urls/index.rst
Add the filter `is_site_url`.
This filter can be used to check if an URL is local to the current site.
It is used for testing redirects on authentication pages.
Move all URL related filters together in a doc section
=> Add is_site_url filter.

apps/zotonic_mod_wires/priv/lib/js/apps/zotonic-wired.js
Fix #2787
Make sure wire messages are sent after the auth worker is stable and running. This makes sure auth redirect happen after the worker is ready
=> Make sure wire transport messages are sent when the auth worker is ready

apps/zotonic_core/src/support/z_media_preview.erl, apps/zotonic_core/test/z_media_preview_tests.erl
Fix #2784
The width and height of portrait oriented images must be swapped when calculating its preview size.
=> Swap the width and height of portrait oriented images

apps/zotonic_core/include/zotonic.hrl, apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_core/src/db/z_db.erl, apps/zotonic_core/src/models/m_category.erl, apps/zotonic_core/src/models/m_search.erl, apps/zotonic_core/src/support/z_search.erl, apps/zotonic_core/src/support/z_template_compiler_runtime.erl, apps/zotonic_mod_admin/src/controllers/controller_admin_edit.erl, apps/zotonic_mod_admin/src/mod_admin.erl, apps/zotonic_mod_admin_identity/src/mod_admin_identity.erl, apps/zotonic_mod_admin_predicate/src/mod_admin_predicate.erl, apps/zotonic_mod_base/src/scomps/scomp_base_pager.erl, apps/zotonic_mod_export/src/support/export_encoder.erl, apps/zotonic_mod_facebook/src/mod_facebook.erl, apps/zotonic_mod_logging/src/mod_logging.erl, apps/zotonic_mod_logging/src/models/m_log.erl, apps/zotonic_mod_logging/src/models/m_log_email.erl, apps/zotonic_mod_logging/src/models/m_log_ui.erl, apps/zotonic_mod_mailinglist/src/mod_mailinglist.erl, apps/zotonic_mod_mailinglist/src/support/z_mailinglist_recipients.erl, apps/zotonic_mod_search/src/mod_search.erl, apps/zotonic_mod_search/src/support/search_all_bytitle.erl, apps/zotonic_mod_search/src/support/search_query.erl, apps/zotonic_mod_search/test/mod_search_db_tests.erl, apps/zotonic_mod_survey/src/questions/survey_q_category.erl, apps/zotonic_mod_wires/src/actions/action_wires_moreresults.erl, apps/zotonic_mod_wires/src/actions/action_wires_typeselect.erl, doc/developer-guide/shell.rst, doc/ref/scomps/scomp_pager.rst
Fix #2729
Change the (internal) search methods, allow the use of a binary search name a map for search options.
Also:
- use the PostgreSQL query planner to get an estimate of the number of rows
- remove `#m_search_result{}`
- add a simpler paging search api to z_search
- connect the (MQTT) API to the search
- use new erlang search api in the erlang code
- add function `z_db:estimate_rows/3` to estimate the number of rows a query returns.
Open:
- Use new search api in templates
- Change documentation where template search code is used
=> Move the search from {atom, list} to binary name and options maps.

apps/zotonic_mod_search/src/support/search_query.erl, apps/zotonic_mod_search/test/mod_search_db_tests.erl
Fix #2794 
Also take query arguments into consideration which are lists instead of tuples.
This works for query arguments like this: `[[718,chat_subject],[333,has_requestor]]`
=> Arguments can also be lists when hasobject or hassubject are used

apps/zotonic_core/src/models/m_media.erl, apps/zotonic_core/src/models/m_rsc.erl, apps/zotonic_mod_admin/priv/templates/_admin_edit_media.tpl, apps/zotonic_mod_admin/src/controllers/controller_admin_edit.erl
This adds a button to the admin with which the associated medium record can be deleted.
Also:
- Changed some texts
- Changed m_rsc:touch/2 to also flush the cache and send an update event
- Changed m_medium:delete/2 to also touch the resource
=> Add button in admin to delete a medium from a resource.

apps/zotonic_mod_authentication/priv/lib/js/zotonic.auth-ui.worker.js, apps/zotonic_mod_authentication/priv/lib/js/zotonic.auth.worker.js, apps/zotonic_mod_authentication/priv/templates/_logon_box.tpl, apps/zotonic_mod_authentication/src/controllers/controller_authentication.erl, apps/zotonic_mod_authentication/src/models/m_authentication.erl
Re-sent the verification email when somebody tries to logon, but the account is not activated.
This was not implemented yet. 
During logon a token is now generated and added to the logon error. This token can be used to (re) send the verification message.
=> Fix sending verification mail for accounts which are not validated during logon

apps/zotonic_mod_search/src/mod_search.erl, apps/zotonic_mod_search/src/support/search_facet.erl, doc/ref/modules/mod_search.rst
This adds a search to return all possible facet values.
The facet values are returned in the `facets` field, the `result` is empty.
The query
```erlang
z_search:search(<<"facet_values">>, #{}, 1, 100, z:c(sitename)).
```
returns:
```erlang
#search_result{search_name = <<"facet_values">>,
search_args = #{},result = [],page = 1,pagelen = 20,
total = 0,pages = 0,next = false,prev = 1,
facets = #{<<"category">> =>
#{<<"type">> => <<"value">>,
<<"values">> =>
[101,102,104,111,116,117,120,312,313,315,318,328,329,330|...]},
<<"created_year">> =>
#{<<"type">> => <<"value">>,<<"values">> => [2011,2021]},
<<"org_pubdate">> =>
#{<<"max">> => {{2021,11,12},{10,29,31}},
<<"min">> => {{2005,3,10},{21,42,0}},
<<"type">> => <<"range">>},
<<"org_pubyear">> =>
#{<<"type">> => <<"value">>,<<"values">> => …
```
=> Add 'facet_values' search

apps/zotonic_core/src/support/z_search.erl, apps/zotonic_mod_search/src/support/search_facet.erl, apps/zotonic_mod_search/src/support/search_query.erl
Add an _or_ option to search for facet values.
```erlang
z_search:search(<<"query">>, #{ <<"facet.category">> => [102,104] }, 1, 100, z:c(atlas)).
```
Which return rows for resources with either category `102` or `104`.
And:
```erlang
z_search:search(<<"query">>, #{ <<"facet.category">> => #{ <<"all">> => [ 102, 104 ] } }, 1, 100, z:c(atlas)).
```
Is an _and_ query, which returns nothing as the category facet can't be two values at once.
Also add the option to pass a list of ids to `id_exclude` (issue #2180)
=> Add 'or' query to the facet query terms.

apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_core/src/models/m_rsc_import.erl, apps/zotonic_mod_admin/priv/templates/_admin_authoritative_info.tpl, apps/zotonic_mod_admin/src/support/z_admin_rsc_import.erl
This adds an additional import format:
```erlang
#{
<<"uri">> => <<"....">>,
<<"rdf_triples">> => [ zotonic_rdf:rdf_triple() ]
}
```
Also allows modules to resolve URIs for fetching import data.
=> Add support for importing RDF triples.

apps/zotonic_mod_survey/priv/templates/_dialog_survey_editor.tpl, apps/zotonic_mod_survey/priv/templates/_survey_end.tpl, apps/zotonic_mod_survey/priv/templates/_survey_end_edit.tpl, apps/zotonic_mod_survey/priv/templates/_survey_question_page.tpl, apps/zotonic_mod_survey/priv/templates/_survey_start.tpl, apps/zotonic_mod_survey/priv/templates/_survey_start_button.tpl, apps/zotonic_mod_survey/src/mod_survey.erl
This replaces the `is_overlay` and `is_dialog` flags with `viewer`.
The viewer can have values `overlay`, `dialog` or empty (for a page).
=> survey: change is_overlay/is_dialog to more generic 'viewer' variable

apps/zotonic_mod_ssl_letsencrypt/src/mod_ssl_letsencrypt.erl, apps/zotonic_mod_ssl_letsencrypt/src/support/z_letsencrypt.erl, apps/zotonic_mod_ssl_letsencrypt/src/support/z_letsencrypt_api.erl
Fix several problems with LetsEncrypt cert requests:
* Crash on status `"invalid"`
* No logging on errors
Fix #2803
=> Add extra logging to LetsEncrypt requests.

apps/zotonic_core/src/support/z_stats.erl, apps/zotonic_mod_admin_statistics/priv/templates/stat_panel/database.tpl
The db-pool usage field in the stats panel was not implemented yet. 
Added the pool status to the collected statistics, and added the ui for mod_admin_statistics so it is possible to get a little bit more insight into what zotonic is doing.
=> The db-pool-usage stat field in the mod_admin_statistics was not working

apps/zotonic_mod_authentication/priv/templates/_logon_login_form_fields.tpl, apps/zotonic_mod_authentication/priv/templates/_logon_reminder_admin_form_fields.tpl, apps/zotonic_mod_signup/priv/templates/_signup_form_fields_email.tpl
Use input = email for username and the email field in the password reminder form.
=> Use type='email' input box for usernames

apps/zotonic_mod_authentication/priv/templates/_logon_login_form_fields.tpl, apps/zotonic_mod_authentication/priv/templates/_logon_reminder_admin_form_fields.tpl, apps/zotonic_mod_signup/priv/templates/_signup_form_fields_email.tpl
Reverts zotonic/zotonic#2826
It was not possible to logon as admin with these values on the input box.
=> Revert "Use type='email' input box for usernames"

apps/zotonic_core/src/support/z_mqtt.erl, apps/zotonic_mod_mqtt/src/scomps/scomp_mqtt_live.erl
The topics for the wires should be seen from the client, for server topics add a 'origin/bridge/'.
=> Fix an issue where the live scomp could not use client topics.

apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/less/edit.less, apps/zotonic_mod_admin/priv/lib/css/zotonic-admin.css, apps/zotonic_mod_admin/priv/templates/_admin_edit_content_date_range.tpl, apps/zotonic_mod_admin/priv/templates/_edit_date.tpl, apps/zotonic_mod_admin/priv/templates/admin_base.tpl, apps/zotonic_mod_admin_frontend/priv/templates/page_admin_frontend_edit.tpl
This removes the jQuery date/time pickers and replaces them with native HTML5 date and time inputs.
Problem: when an input is empty the current date or time is displayed in light gray. I would prefer it to be empty in those cases.
=> Use native date/time pickers in the admin.

apps/zotonic_mod_search/priv/templates/pivot/facet.tpl, apps/zotonic_mod_search/src/support/search_facet.erl
Add labels to the output of faceted search.
This is useful when the facet value and facet presentation are different.
=> Faceted search: add translatable labels.

apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_core/src/smtp/z_email_server.erl, apps/zotonic_core/src/support/z_context.erl, apps/zotonic_core/src/support/z_multipart_encode.erl, apps/zotonic_core/src/support/z_multipart_parse.erl, apps/zotonic_mod_email_dkim/src/mod_email_dkim.erl, apps/zotonic_mod_email_dkim/src/support/z_email_dkim.erl
This enables modules like `mod_mailgun` to use APIs or other methods to send emails.
Also move DKIM routines from core to `mod_email_dkim`.
=> Add option to send emails via modules instead of SMTP.

bin/zotonic
The [init script](http://docs.zotonic.com/en/latest/developer-guide/deployment/startup.html) does not work when it runs from another user home (e.g. root user). The `cd` command gives a "not found".
By making the path absolute - by prefixing it with `ZOTONIC` path - the path conflict is removed.
=> Prefix local zotonic_launcher path with ZOTONIC path

apps/zotonic_core/priv/translations/zotonic.pot, apps/zotonic_core/src/db/z_db.erl, apps/zotonic_mod_admin/priv/templates/admin_status.tpl, apps/zotonic_mod_admin/src/models/m_admin_status.erl, apps/zotonic_mod_admin_statistics/priv/templates/admin_statistics.tpl
Show the descriptive version string of the database on the admin/status page.
This helps in debugging issues where the prod database version was not clear.
=> mod_admin: show database version on admin/status

apps/zotonic_core/src/db/z_db.erl, apps/zotonic_core/src/db/z_db_pgsql.erl, apps/zotonic_mod_filestore/src/mod_filestore.erl, apps/zotonic_mod_filestore/src/support/filestore_uploader.erl
The filestore is querying the database during the start of the uploader.
If the database is slow then the supervisor might experience a timeout during start_link.
Somehow the database connection is reused and the exact same query is retried on the 
same connection process. Why is still unclear to me and needs further investigation.
=> mod_filestore: fix a problem with 'busy' sql connections

apps/zotonic_core/src/i18n/z_trans_server.erl, apps/zotonic_core/src/support/z_module_indexer.erl, apps/zotonic_core/src/support/z_module_manager.erl, apps/zotonic_core/src/support/z_module_sup.erl, apps/zotonic_core/src/support/z_sites_dispatcher.erl, apps/zotonic_core/src/support/z_sites_manager.erl, apps/zotonic_launcher/src/command/zotonic_command.erl, apps/zotonic_mod_search/src/mod_search.erl, doc/developer-guide/deployment/env.rst
Fix #2848
Lower memory use.
Points are added below depending on the results of observer and code review.
=> core: optimize memory usage

apps/zotonic_core/src/db/z_db_pgsql.erl, apps/zotonic_core/src/install/z_install.erl, apps/zotonic_core/src/install/z_install_update.erl, apps/zotonic_core/src/support/z_pivot_rsc.erl, apps/zotonic_core/src/support/z_pivot_rsc_task_job.erl, apps/zotonic_mod_admin/priv/templates/_admin_status_update_pivot_count.tpl, apps/zotonic_mod_admin/priv/templates/_admin_system_status.tpl, apps/zotonic_mod_admin/priv/templates/admin_status.tpl, apps/zotonic_mod_admin/src/models/m_admin_status.erl
This also moves the error_count column from the task props to a database column.
=> mod_admin: add task queue status to admin/status

apps/zotonic_core/src/models/m_edge.erl, apps/zotonic_core/src/support/z_edge_log_server.erl, apps/zotonic_mod_menu/src/filters/filter_menu_expand.erl
Also add extra dependency key {predicate, PredId} which is flushed when edges with this predicate are changed.
=> core: add memo caching to filter menu_expand.

GNUmakefile, apps/zotonic_core/src/support/z_pivot_rsc.erl, apps/zotonic_core/src/support/z_site_services_sup.erl, apps/zotonic_core/src/support/z_site_startup.erl, apps/zotonic_core/src/support/z_sites_sup.erl, apps/zotonic_mod_admin/src/zotonic_mod_admin.app.src
Fix an issue with site init where the modules did not start on initial run.
Add '--all' to 'make upgrade-deps'
Fix an issue with pivot_rsc starting when site is not yet running.
Minor (textual) fixes.
=> core: fixes for initial site startup.

apps/zotonic_core/src/support/z_logger_formatter.erl
This allows passing the `stack` with structured logs.
=> core: z_logger_formatter: pretty print the stack in the msg.

apps/zotonic_core/src/support/z_logger_formatter.erl
=> core: fix a problem where the log formatter could crash on ssl errors

apps/zotonic_core/include/zotonic_log.hrl, apps/zotonic_core/src/support/z.erl
The fatal log level was supported, but without mapping to logger.
=> core: map zotonic (lager) log fatal to logger alert.

apps/zotonic_launcher/src/zotonic_launcher_app.erl, apps/zotonic_listen_http/src/zotonic_listen_http.erl, apps/zotonic_listen_mqtt/src/zotonic_listen_mqtt.erl, apps/zotonic_listen_mqtt/src/zotonic_listen_mqtt_handler.erl, apps/zotonic_listen_smtp/src/zotonic_listen_smtp.erl
Set SSL loglevel to warning.
Add structured logging to smtp, http and MQTT listeners.
=> Set SSL log level

apps/zotonic_core/src/support/z_media_tag.erl, doc/developer-guide/media.rst, doc/ref/tags/tag_image.rst
Adding `decoding="async"` makes the page load faster, as sync img decoding is disabled.
This also solves an issue with some Safari versions where only the top part of an image is shown.
More changes:
- Add prefix `mediaclass-` to the mediaclass when added the img class attribute
- Add `rotate` to the list of known img options
- Fix a problem where the mediaclass was not added as a css class if there was an alt attribute defined
=> core: add support for img decoding attribute.

apps/zotonic_core/src/support/z_media_preview.erl, apps/zotonic_core/test/z_media_preview_tests.erl, doc/ref/tags/tag_image.rst
Issue #2884 
If the generated image is a jpeg, then add the `-interlace plane` option to make the image progressive.
Also make log statements in z_media_preview structured.
=> core: make generated jpeg images progressive

apps/zotonic_core/src/support/z_pivot_rsc.erl, apps/zotonic_mod_search/src/support/search_facet.erl
Fix #2862
Fix a problem with unique key violations during task insert by serializing the task queue updates via the pivot process.
=> core: fix a problem with unique key violations on task insert.

apps/zotonic_core/src/support/z_config.erl
Add a default for `log_http_buffer_size`, the ringbuffer which protects the process writing the access logs.
=> Add default for the log buffer size

modules/mod_seo_sitemap/mod_seo_sitemap.erl
This PR adds a notify `seo_sitemap_rebuild` to allow sites to start custom sitemap indexing jobs when sitemap indexing is triggered from the admin sitemap rebuild button.
=> seo_sitemap: add notification at sitemap rebuild for custom indexing

apps/zotonic_core/src/i18n/z_language.erl, apps/zotonic_core/src/smtp/z_email_server.erl, apps/zotonic_core/src/support/z_context.erl, apps/zotonic_core/src/support/z_logger_formatter.erl, apps/zotonic_core/src/support/z_pivot_rsc.erl, apps/zotonic_core/src/support/z_pivot_rsc_job.erl, apps/zotonic_core/src/support/z_pivot_rsc_task_job.erl, apps/zotonic_filehandler/src/zotonic_filehandler_compile.erl, apps/zotonic_listen_http/src/zotonic_listen_http_metrics.erl, apps/zotonic_mod_base/priv/lib/js/modules/z.clickable.js
This fixes an issue where a pivot could deadlock if it would try to add a task job.
Also added:
- more structured logging
- timeout handling for tasks
- timeout handling for pivot jobs
=> zotonic-core: handle pivots in separate job process

apps/zotonic_core/src/models/m_rsc.erl, apps/zotonic_core/src/models/m_rsc_update.erl
Add options to omit edges and/or medium when duplicating a resource.
=> core: add options to m_rsc:duplicate

apps/zotonic_core/src/models/m_req.erl, apps/zotonic_core/src/support/z_context.erl, apps/zotonic_core/src/support/z_cowmachine_middleware.erl, apps/zotonic_core/src/support/z_lib_include.erl, apps/zotonic_core/src/support/z_render.erl, apps/zotonic_mod_admin/priv/templates/_admin_js_include.tpl, apps/zotonic_mod_base/priv/templates/_html_head_cotonic.tpl, apps/zotonic_mod_base/priv/templates/tests/_initial_postback_test.tpl, apps/zotonic_mod_base/priv/templates/tests/initial_postback_test.tpl, apps/zotonic_mod_base/src/scomps/scomp_base_worker.erl, apps/zotonic_mod_development/priv/templates/_html_head.tpl, apps/zotonic_mod_editor_tinymce/priv/templates/tinymce-4.9.3/_editor.tpl, apps/zotonic_mod_editor_tinymce/priv/templates/tinymce-5.10.2/_editor.tpl, apps/zotonic_mod_seo/priv/templates/_html_head_seo.tpl, apps/zotonic_mod_wires/priv/lib/js/apps/zotonic-wired.js, apps/zotonic_mod_zotonic_site_management/priv/skel/blog/priv/templates/base.tpl, doc/ref/notifications/notification/security_headers.rst
This adds support for the `Content-Security-Policy: script-src 'nonce-.'` header.
If a `content-security-policy` header is added, then the string `'nonce-'` (including quotes) is
replaced with the nonce for the request.
The request nonce is set in the cowmachine middleware, it is in the context under the key `csp_nonce`.
The value can be accessed via `z_context:csp_nonce(Context)` or `m.req.csp_nonce`.
Separate issue:
* remove `eval`, use injected script tag (with correct nonce)? See #2883
=> core: add support for Content-Security-Policy script-src nonce-

apps/zotonic_core/src/db/z_db.erl
This fixes an issue with making the db schema for sites with a `_` character in their name.
=> core: allow underscore character in schema names.

apps/zotonic_core/src/models/m_media.erl, apps/zotonic_core/src/support/z_datamodel.erl, apps/zotonic_core/src/support/z_media_import.erl, apps/zotonic_core/src/support/z_module_manager.erl
This adds support to directly define the URL for a medium import in the media section of a `#datamodel`.
Example:
```erlang
#datamodel{
media = [
{page_youtube,
"https://www.youtube.com/watch?v=dQw4w9WgXcQ",
#{ <<"title">> => <<"Rolling along">> }}
]
}.
```
=> core: support direct media-URLs as source for datamodel media imports.

apps/zotonic_core/src/support/z_logger_formatter.erl, apps/zotonic_core/src/support/z_module_manager.erl, apps/zotonic_mod_filestore/src/support/filestore_uploader.erl
If a (temporary) file upload worker crashed due to a missing filezcache ets table, then nog log entry was made.
This adds log entries when terminate is called with something else than `normal`.
Also fix an issue where a module could not be started if that module was stopped during a module restart backoff period.
=> mod_filestore: log errors when filestore uploader terminates.

README.md, apps/zotonic_core/priv/translations/zotonic.pot, apps/zotonic_mod_admin/priv/templates/_admin_edit_content.query.tpl, apps/zotonic_mod_mailinglist/priv/templates/_admin_edit_content.mailinglist.tpl, apps/zotonic_mod_translation/priv/templates/admin_translation.tpl
Issue: N/A
The link https://docs.zotonic.com/docs/latest/developer-guide/search.html#query-model-arguments is not working.
=> Fix links to documentation stuff

apps/zotonic_mod_filestore/src/mod_filestore.erl
mod_filestore: use records for supervisor definition.
=> mod_filestore: use records for supervisor definition.

apps/zotonic_core/src/support/z_context.erl, apps/zotonic_core/src/support/z_controller_helper.erl, apps/zotonic_mod_base/src/controllers/controller_api.erl
On HTTP GET API calls, pass the Qs args as props in the payload.
Also suppress the "zotonic" arguments when parsing POST forms as payload.
Fixes #2947
API Calls like `curl -i -k 'https://zotonicwww2.test:8443/api/model/search/get/query?text=rationale'` now work.
=> mod_base: on API GET call, pass query args as the payload. 

priv/zotonic.config.in
Fix syntax error in `zotonic.config.in`.
=> Fix syntax error in zotonic.config.in

apps/zotonic_mod_survey/priv/templates/email_survey_result.tpl, apps/zotonic_mod_survey/src/mod_survey.erl
This fixes a problem where a dialog with the survey result editor was not closed after submit.
Also fix the right/wrong feedback in the result email for non-test thurstone questions.
=> mod_survey: close dialog/viewer after editing submit.

apps/zotonic_mod_search/src/support/search_query.erl, doc/developer-guide/search.rst
This completes the `id_exclude` with a search term `id`.
Useful when mapping textual searches like `"id:1234" to query terms.
=> mod_search: add the search term 'id', to limit result to one or more ids

apps/zotonic_core/include/zotonic.hrl, apps/zotonic_core/src/models/m_rsc.erl, apps/zotonic_core/src/models/m_search.erl, apps/zotonic_core/src/smtp/z_email_server.erl, apps/zotonic_core/src/support/z_search.erl, apps/zotonic_core/src/support/z_template_compiler_runtime.erl, apps/zotonic_mod_admin/priv/templates/mediaclass.config, apps/zotonic_mod_base/priv/templates/mediaclass.config, apps/zotonic_mod_search/src/support/search_query.erl, apps/zotonic_mod_search/test/mod_search_db_tests.erl, apps/zotonic_mod_wires/src/actions/action_wires_moreresults.erl, doc/ref/models/model_rsc.rst
Also:
- Add rsc properties`image_url` and `thumbnail_url` 
- Add mod_base mediaclasses `image` and `thumbnail`
- Make some errors more structured
TODO:
- ~Docs for API~ **Must be part of a complete API doc**
Example API calls:
For the default properties:
`https://zotonicwww2.test:8443/api/model/search/get/query?cat=image&options.properties`
For specific properties:
`https://zotonicwww2.test:8443/api/model/search/get/query?cat=image&options.properties[]=title,image_url`
=> core: add option 'properties' to search

apps/zotonic_core/src/support/z_context.erl, apps/zotonic_core/src/support/z_controller_helper.erl, apps/zotonic_core/src/support/z_file_locate.erl, apps/zotonic_core/src/support/z_sites_dispatcher.erl, apps/zotonic_mod_base/src/controllers/controller_api.erl, apps/zotonic_mod_wires/src/support/z_transport.erl
This fixes an issue where postbacks via the controller_mqtt_transport lost their `z_` arguments. Which are needed by the transport routines.
Also fix some logging and error handling of invalid URLs and dispatches.
=> Fix a problem where the z_postback was filtered on controller_mqtt_transport postbacks.

apps/zotonic_launcher/src/command/zotonic_cmd_addsite.erl
-p option was setting dbhost instead of dbport
=> FIX: Corrected -p option on addsite

apps/zotonic_launcher/src/command/zotonic_cmd_addsite.erl, doc/ref/cli/cli-addsite.rst
The docs says "Skeleton site (one of ‘blog’, ‘empty’, ‘nodb’; default: blog)", but when a site is created with no options the default one is "empty". This PR fixes this using the already defined ?SKEL macro, but changed from atom to string.
So with this PR, running addsite command without options the site skel will be blog.
Also fixed the addsite docs. The doc says that the default schema is "public", but running the addsite command the default one is <site_name>.
=> Fix addsite default skel and docs

doc/cookbook/custom-model.rst
Looking at `zotonic_model` and docs, I found some mismatches.
Maybe `Keys` should be `[atom() | binary()]` instead of just `list()`? Or what's the best type? Maybe [pos_integer() | binary()]? Or can be [term()]?
=> Update cookbook-custom-model docs

apps/zotonic_mod_zotonic_site_management/priv/skel/blog/priv/zotonic_site.config.in, apps/zotonic_mod_zotonic_site_management/priv/skel/empty/priv/zotonic_site.config.in, apps/zotonic_site_testsandbox/priv/zotonic_site.config
Using the `addsite` command, I got an error about OAuth for Facebook. Checking the active modules, the OAuth was disabled. These changes fix this by changing the OAuth module name in the `zotonic_site.config` from `mod_oauth` to `mod_oauth2`, according to the [zotonic_mod_oauth2](https://github.com/zotonic/zotonic/tree/master/apps/zotonic_mod_oauth2).
=> Fix OAuth module name in site config

apps/zotonic_mod_acl_user_groups/src/support/acl_default_rules.erl, apps/zotonic_mod_signup/src/mod_signup.erl
This fixes an issue where users added via the signup module could not set their username/password
Fix #2964
=> mod_acl_user_groups: add default rule that members can update their own content.

modules/mod_signup/mod_signup.erl, src/smtp/z_email_server.erl
Also add name of signup user to To for emails.
This fixes an issue with improperly formatted `To` addresses in verify emails.
=> core: ensure To email is properly formatted.

apps/zotonic_core/include/zotonic.hrl, apps/zotonic_core/src/smtp/z_email.erl, apps/zotonic_mod_signup/src/mod_signup.erl
This for a lower spam score and a nicer recipient in the received email.
If an email to an resource `Id` and then let the z_email routines add the name and email address of the recipient to the email.
=> mod_signup: use the name of the person for the To in the verify email.

.gitignore, GNUmakefile, apps/zotonic_launcher/bin/zotonic, apps/zotonic_launcher/bin/zotonic.escript
Adds completion to `bin/zotonic`.
Running `make` or `bin/zotonic completion` a file named `zotonic-completion.bash` is created in `/etc/bash_completion.d`.
No completion for options, just for the `zotonic_cmd_*` commands.
Working in Ubuntu 21.10. Would this work in other OS?
The generated file `zotonic-completion.bash` content:
```bash
#/usr/bin/env bash
_zotonic_completions()
{
if [ "${#COMP_WORDS[@]}" != "2" ]; then
return
fi
COMPREPLY=($(compgen -W "addsite compile compilefile config configfiles configtest connectdb createdb debug dispatch etop flush load logtail restart restartsite rpc runtests shell siteconfig siteconfigfiles sitedir sitetest start start_nodaemon startsite status stop stopsite update wait" "${COMP_WORDS[1]}"))
}
complete -F _zotonic_completions zotonic
```
=> Script completion proposal

apps/zotonic_launcher/src/command/zotonic_cmd_addsite.erl, apps/zotonic_mod_zotonic_site_management/priv/skel/blog/src/SITE.app.src, apps/zotonic_mod_zotonic_site_management/priv/skel/blog/src/SITE_app.erl, apps/zotonic_mod_zotonic_site_management/priv/skel/blog/src/SITE_sup.erl, apps/zotonic_mod_zotonic_site_management/priv/skel/empty/src/SITE.app.src, apps/zotonic_mod_zotonic_site_management/priv/skel/empty/src/SITE_app.erl, apps/zotonic_mod_zotonic_site_management/priv/skel/empty/src/SITE_sup.erl, apps/zotonic_mod_zotonic_site_management/priv/skel/nodb/src/SITE.app.src, apps/zotonic_mod_zotonic_site_management/priv/skel/nodb/src/SITE_app.erl, apps/zotonic_mod_zotonic_site_management/priv/skel/nodb/src/SITE_sup.erl, apps/zotonic_mod_zotonic_site_management/src/zotonic_status_addsite.erl, doc/ref/cli/cli-addsite.rst
Add "-S" as a boolean option to the `addsite` command (default false). If true, `<site>_app.erl` (application behaviour) and `<site>_sup.erl` (supervisor behaviour) files are included in the site dir, and, when the site starts, the application and root supervisor starts to.
e.g. 
```
bin/zotonic addsite -S true foo
```
Running `observer:start()` in the zotonic shell the site appears in the applications list:
=> Site application proposal

apps/zotonic_mod_authentication/src/controllers/controller_logoff.erl
Fix #2978
Notify about the logoff when via `controller_logoff`.
No notification currently is emitted.
=> Fix #2978 No logoff notification

apps/zotonic_core/src/models/m_acl.erl, apps/zotonic_core/src/support/z_controller_helper.erl, apps/zotonic_mod_acl_user_groups/src/controllers/controller_admin_acl_rules_export.erl, apps/zotonic_mod_admin/src/controllers/controller_admin_edit.erl, apps/zotonic_mod_base/src/controllers/controller_file.erl, apps/zotonic_mod_base/src/controllers/controller_page.erl, apps/zotonic_mod_base/src/controllers/controller_redirect.erl, apps/zotonic_mod_base/src/controllers/controller_template.erl
* Remove from controller_template the implicit check for view-permission on any id in the query args.
* Allow `m_acl` to use any action, removes the check on known actions. This allows to perform ACL checks on project specific actions.
=> mod_base/core: make id explicit for the z_controller_helper:is_authorized calls.

apps/zotonic_launcher/src/command/zotonic_cmd_chrome.erl, apps/zotonic_launcher/src/command/zotonic_cmd_chromium.erl, apps/zotonic_mod_development/src/mod_development.erl
I'm facing issues getting the Cotonic to work in localhost over HTTPS.
In the browser console, I receive these messages:
```
Could not start serviceWorker due to a SecurityError.
See https://cotonic.org/#model.serviceWorker for more information.
```
The [Cotonic docs](https://cotonic.org/#model.serviceWorker) say to me this:
> A Note on Security
The serviceWorker needs https to work correctly. The Chrome browser does not accept self-signed certificates for running serviceWorkers. Either run from localhost, use a real certificate, or follow the instructions [on this page by Dean Hume](https://deanhume.com/testing-service-workers-locally-with-self-signed-certificates/). <br>
Safari and Firefox accept self-signed certificates for running the serviceWorker.
But I don't want to generate a …
=> Adds a function to open site as safe in Chrome for development

apps/zotonic_core/src/models/m_acl.erl, apps/zotonic_core/src/support/z_acl.erl, apps/zotonic_mod_acl_user_groups/priv/templates/_admin_edit_content_acl.tpl, apps/zotonic_mod_acl_user_groups/src/support/acl_user_groups_checks.erl, apps/zotonic_mod_admin_config/src/actions/action_admin_config_config_delete.erl, apps/zotonic_mod_admin_config/src/actions/action_admin_config_config_toggle.erl, apps/zotonic_mod_admin_config/src/actions/action_admin_config_dialog_config_delete.erl, apps/zotonic_mod_admin_config/src/actions/action_admin_config_dialog_config_edit.erl, apps/zotonic_mod_admin_config/src/actions/action_admin_config_dialog_config_new.erl, apps/zotonic_mod_admin_config/src/mod_admin_config.erl, apps/zotonic_mod_admin_identity/priv/templates/_admin_edit_sidebar_person_live.tpl, apps/zotonic_mod_admin_identity/src/actions/action_admin_identity_delete_username.erl, apps/zotonic_mod_admin_identity/src/actions/action_admin_identity_dialog_delete_username.erl, apps/zotonic_mod_admin_identity/src/actions/action_admin_identity_dialog_set_username_password.erl, apps/zotonic_mod_admin_identity/src/actions/action_admin_identity_dialog_user_add.erl, apps/zotonic_mod_admin_modules/src/actions/action_admin_modules_module_toggle.erl, apps/zotonic_mod_backup/src/actions/action_backup_backup_start.erl, apps/zotonic_mod_backup/src/controllers/controller_admin_backup.erl, apps/zotonic_mod_logging/src/models/m_log.erl, apps/zotonic_mod_oauth2/src/models/m_oauth2.erl, apps/zotonic_mod_oauth2/src/models/m_oauth2_consumer.erl, apps/zotonic_mod_search/src/mod_search.erl, apps/zotonic_mod_ssl_letsencrypt/src/mod_ssl_letsencrypt.erl
In the `z_acl` module it was hard coded that an user can always update their self.
This should be decided by the ACL module, as not all use cases allow an user to fully edit their own person resource.
=> core: let the ACL decide if an user can edit their own person record

apps/zotonic_mod_base/priv/templates/error.tpl
On the error page we hide the stack trace on production sites.
This shows the stack trace  on production sites if the current user is an admin.
An explanation why the stack trace is show is added.
=> On error page, show stack trace if site is not production or user is an admin.

apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_core/src/support/z_cowmachine_middleware.erl, doc/ref/notifications/notification/meta-middleware.rst, doc/ref/notifications/notification/middleware.rst, doc/ref/notifications/other.rst
Gives control over how requests are to be processed by a middleware notification.
Handling the request in a module:
```erlang
observe_middleware(#middleware{ on = welformed }, Context, _Context) ->
io:format("on welformed middleware~n"),
Context;
observe_middleware(#middleware{ }, Context, _Context) ->
Context.
```
So custom headers and other stuff can be made during the request.
=> Adds middleware notifier

apps/zotonic_launcher/src/command/zotonic_cmd_addsite.erl, apps/zotonic_mod_zotonic_site_management/src/zotonic_status_addsite.erl, doc/ref/cli/cli-addsite.rst, rebar.config
Provides a multi-app project structure to the site, like [`rebar3 new umbrella`](https://rebar3.readme.io/docs/basic-usage) command.
The site dir will become, e.g.
```
foo
|-- apps
|   |-- foo
|   |   |-- priv
|   |   |   |-- dispatch
|   |   |   |-- templates
|   |   |   |-- ...
|   |   |   |-- zotonic_site.config
|   |   |   `-- zotonic_site.config.in
|   |   `-- src
|   |       |-- foo.app.src
|   |       `-- foo.erl
|   |-- zotonic_mod_foo
|   |   |-- priv
|   |   |   `-- dispatch
|   |   |-- src
|   |   |   |-- zotonic_mod_foo.app.src
|   |   |   `-- mod_foo.erl
|   |   `--rebar.config
|   `-- *more apps*
`-- .gitignore
```
For new projects, `-U` option was added to `addsite` command:
```
bin/zotonic addsite -U true <site>
```
Tested creating a new site with and without the new …
=> Umbrella proposal

apps/zotonic_core/priv/translations/zotonic.pot, apps/zotonic_core/src/support/z_datetime.erl, apps/zotonic_core/test/z_datetime_tests.erl, apps/zotonic_mod_base/src/filters/filter_add_month.erl
This fixes an issue where adding (or substracting)  multiple months to a date could shift the day.
Mentioned by @loetie
=> core: add z_datetime:next_month/2 and z_datetime:prev_month/2.

modules/mod_seo_sitemap/mod_seo_sitemap.erl, modules/mod_seo_sitemap/models/m_seo_sitemap.erl
Fix an issue where resources with pro 0.0 were still included in the sitemap.
Also update the sitemap on pivot, this is better as _on update_ will give more frequent updates of the sitemap (after every edit).
=> mod_seo_sitemap: update sitemap on pivot, remove prio 0 resources from urlsets (0.x)

apps/zotonic_core/src/smtp/z_email.erl, apps/zotonic_core/test/z_email_tests.erl
Example of such an address:  `Jan Janssen <jan.janssen>`
After this patch this will split successfully into a name and an email address (without domain).
=> core: fix a problem where the split of an email did not work if the email address did not have a domain.

apps/zotonic_core/src/smtp/z_email.erl, apps/zotonic_core/test/z_email_tests.erl
Previously the `to_binary` mapped to latin1 binary names.
This crashes on email addresses like: `Klønhammer <test@example.com>`
=> core: fix a problem with splitting email addresses containing extended utf8 characters.

apps/zotonic_core/src/models/m_search.erl, apps/zotonic_core/src/support/z_search.erl, apps/zotonic_core/src/support/z_template_compiler_runtime.erl, apps/zotonic_mod_admin/priv/templates/_admin_sort_header.tpl, apps/zotonic_mod_admin/priv/templates/admin_media.tpl, apps/zotonic_mod_admin/priv/templates/admin_overview.tpl, apps/zotonic_mod_admin/priv/templates/admin_referrers.tpl, apps/zotonic_mod_admin_predicate/priv/templates/admin_edges.tpl, apps/zotonic_mod_base/src/scomps/scomp_base_pager.erl, apps/zotonic_mod_survey/priv/templates/email_survey_result.tpl
Under the pager, show the (estimated) number of items found.
Also:
- refactor the pager to show nice page ranges.
- fix a problem in the admin lists where clicking on a header removed the selected page length
=> mod_admin: show estimated row count.

apps/zotonic_core/src/support/z_search.erl, apps/zotonic_mod_admin/priv/templates/admin_media.tpl, apps/zotonic_mod_admin/priv/templates/admin_overview.tpl, apps/zotonic_mod_admin/priv/templates/admin_referrers.tpl, apps/zotonic_mod_admin_predicate/priv/templates/admin_edges.tpl
Better lookahead for nicer pager.
=> core: define min lookahead for searches (for correct pagination)

include/zotonic.hrl, modules/mod_admin/templates/_admin_sort_header.tpl, modules/mod_admin/templates/admin_media.tpl, modules/mod_admin/templates/admin_overview.tpl, modules/mod_admin/templates/admin_referrers.tpl, modules/mod_admin/translations/nl.po, modules/mod_admin_predicate/templates/admin_edges.tpl, modules/mod_base/actions/action_base_moreresults.erl, modules/mod_base/scomps/scomp_base_pager.erl, modules/mod_search/support/search_all_bytitle.erl, modules/mod_twitter/support/twitter_poller.erl, src/db/z_db.erl, src/erlydtl/erlydtl_runtime.erl, src/models/m_search.erl, src/support/z_search.erl
For queries the total row count was calculated precisely up to 30K rows.
This was done by fetching those rows and then counting.
For some queries this is too slow and taxing on the database.
This PR copies the query row estimation from the master branch.
The rows are estimated by checking the query planner for the estimated number of rows.
In the `#search_result{}` record the `all` field has been removed and the `is_total_estimated` field has been added.
Also fix an issue with the admin where changing the sort removed the selected page length.
=> core: add estimated row counts to search results.

apps/zotonic_mod_l10n/src/support/l10n_country2iso.erl, apps/zotonic_mod_l10n/src/support/l10n_iso2country.erl
The official name of Turkey is now Türkiye
Adds a mapping of Turkey to tr for the country2iso lookup.
The zotonic-country.pot file should be done separately on the master branch.
There is a problem with the translations, as the name `Türkiye` doesn't seem to translate well automatically with Google Translate.
So maybe we need to wait a bit with merging this till the translation engines have picked up the new name of Türkiye.
Note: seems that the Türkiye is officially Türkiye in all languages, so maybe the translations _do_ work... this needs to be checked.
At least in Ukrainian it is not correctly translated: https://translate.google.com/?sl=en&tl=uk&text=Türkiye&op=translate
(Latin characters, instead of Cyrillic)
=> mod_l10n: Turkey is now called Türkiye

apps/zotonic_mod_admin/priv/templates/_action_dialog_duplicate_rsc.tpl, apps/zotonic_mod_admin/src/actions/action_admin_dialog_duplicate_rsc.erl
In the confirm dialog a new title was requested.
This title was not multi-lingual.
Now the page is duplicated as-is, except for the 'published' flag, which is reset.
=> mod_admin: fix a problem where the multi-lingual title of a page was lost on duplication.

modules/mod_base/scomps/scomp_base_pager.erl, src/support/z_search.erl
Also change the z_search handling so that if a list is returned then let z_search apply the paging.
Returning a list is for search handlers that do not use the OffsetLimit
=> mod_base: make next/prev pager is page count is undefined.

modules/mod_base/lib/js/apps/zotonic-1.0.js
Also suppress errors if the page is unloading.
On FireFox in-flight Ajax requests are canceled with an error if the page is unloading (navigating away).
This results in "FAIL: error" messages.
By suppressing the messages if the page is unloading we can prevent those errors from appearing.
Also "FAIL: error" is not very helpful, so only show the error text if it is not "error" and replace the "FAIL" with something more descriptive about _what_ is failing.
=> core: show more descriptive error on Ajax errors.

modules/mod_signup/controllers/controller_signup_confirm.erl, modules/mod_signup/templates/signup_confirm.tpl, modules/mod_signup/translations/es.po, modules/mod_signup/translations/nl.po, modules/mod_signup/translations/pl.po
This prevents the code being consumed by accidental double clicking or other proceses fetching the confirm URL.
=> mod_signup: always press a button to confirm.

apps/zotonic_mod_base/src/controllers/controller_static_pages.erl
Unicode filenames were not correctly handled.
Also add a check against misconfiguration where the root was not defined.
=> mod_base: fix a problem where controller_static_pages could not handle unicode filenames

apps/zotonic_mod_admin/src/filters/filter_temporary_rsc.erl
Fix #3057
When the user has no server_storage_session, nothing could have been stored, so return not_found instead of no_session. The storage session will be created when an id is stored.
=> Return not_found instead of no_session. Fixes #3057

priv/zotonic.config.in, src/filewatcher/z_filewatcher_handler.erl, src/support/z_config.erl
=> core: add config 'filewatcher_terminal_notifier' to enable or disable file update growl messages.

apps/zotonic_core/src/support/z_config.erl, apps/zotonic_filehandler/src/zotonic_filehandler_terminal.erl, apps/zotonic_launcher/priv/config/zotonic.config.in
=> core: add config 'filewatcher_terminal_notifier' to optionally disable terminal messages on file updates.

apps/zotonic_mod_translation/priv/templates/_dialog_language_edit_list.tpl, apps/zotonic_mod_translation/priv/templates/_html_head_admin.tpl, apps/zotonic_mod_translation/priv/templates/_html_head_translation.tpl
Apparently to the (new?) hreflang documentation we should add the link to the current language version in the list of alternative language versions.
Also suppress the list if the `rewrite_url` config is not set.
https://developers.google.com/search/docs/advanced/crawling/localized-versions?hl=en&visit_id=637902158000412765-571714860&rd=1
=> mod_translation: include hreflang link to current translation

modules/mod_seo/templates/_html_head_seo.tpl, modules/mod_translation/mod_translation.erl, modules/mod_translation/templates/_html_head_translation.tpl
See also #3006
This adds in the head section a _hreflang_ link to all language versions and a _x-default_ link to the url without language code.  Previously only the hreflang links to translations other than the current one were added.
=> mod_seo: add all available hreflang and x-default links to html head

apps/zotonic_core/src/models/m_rsc_update.erl, apps/zotonic_core/src/support/z_acl.erl
Edges insertions on rsc-update can change subjects and also add ACL rights (like membership of user groups). Using admin rights for such updates (like when signing up) can have unwanted changes to normally not user-editable resources or predicates.
This is a proposal to not allow inserting edges during a sudo. This change makes it safe(r) to use sudo on insertion of resources using non-checked user-supplied forms.
=> core: on rsc update, as sudo, do not allow to add edges.

apps/zotonic_core/src/support/z_datetime.erl, apps/zotonic_core/test/z_datetime_tests.erl, apps/zotonic_mod_base/src/filters/filter_add_day.erl, apps/zotonic_mod_base/src/filters/filter_add_hour.erl, apps/zotonic_mod_base/src/filters/filter_add_week.erl, apps/zotonic_mod_base/src/filters/filter_add_year.erl, apps/zotonic_mod_base/src/filters/filter_sub_day.erl, apps/zotonic_mod_base/src/filters/filter_sub_hour.erl, apps/zotonic_mod_base/src/filters/filter_sub_week.erl, apps/zotonic_mod_base/src/filters/filter_sub_year.erl
Previously it was necessary to repeat adding one unit to the date time.
Also fix some edge cases in the date manipulations.
=> core: add functions to add/sub N second/minute/hour/week/month/year to datetimes.

modules/mod_search/support/search_query.erl
So it does not get propagated as filter
Text search query parameters with an empty binary string are now ignored, so all results are returned instead of none. This is now in line with the behavior of normal empty strings, when the parameter is missing and the 1.0 version.
=> Check for empty search string

src/smtp/z_email_embed.erl, src/smtp/z_email_server.erl
Also:
* limit the number of outgoing emails to 30 in parallel.
* add a config `site.email_images_noembed` to disable embedding images in emails.
=> core: in emails, only embed images < 1MB.

apps/zotonic_core/src/smtp/z_email_embed.erl, apps/zotonic_mod_admin_config/priv/templates/admin_config_email.tpl, doc/developer-guide/email.rst
Also add a config to enable/disable the embedding of images.
This fixes an issue where using overly large images (like animated gifs) in mailings could result in the server using too much memory.
=> smtp: do not embed images > 1MB

apps/zotonic_core/src/support/z_search.erl
For certain queries the calculated page number was off by 1.
=> core: fix an issue where the search_result page count could be off by one for certain searches.

apps/zotonic_core/src/support/z_search.erl
This could happen if a query without any search arguments was used and a clause was added to restrict results for certain users.
=> core: fix a problem where a search could result in illegal SQL

.github/workflows/docs.yml, doc/requirements.txt
Ubuntu 18.04 is removed from GH Actions.
Update the docs actions to work with a newer Ubuntu version.
=> GH Actions: upgrade ubuntu version for Docs action

.github/workflows/docs.yml, doc/requirements.txt, modules/mod_admin/templates/_admin_edit_content_seo.tpl, modules/mod_admin/translations/de.po, modules/mod_admin/translations/es.po, modules/mod_admin/translations/et.po, modules/mod_admin/translations/fr.po, modules/mod_admin/translations/nl.po, modules/mod_admin/translations/ru.po, modules/mod_admin/translations/tr.po, modules/mod_admin/translations/zh.po, modules/mod_admin_identity/translations/es.po, modules/mod_admin_identity/translations/nl.po, modules/mod_admin_identity/translations/pl.po, modules/mod_base/controllers/controller_file.erl, modules/mod_base/controllers/controller_page.erl, modules/mod_seo/templates/_html_head_seo.tpl, modules/mod_seo/translations/nl.po, modules/mod_seo_sitemap/models/m_seo_sitemap.erl, modules/mod_seo_sitemap/support/seo_sitemap.erl
This adds an option to exclude all pages in a category from indexing by a search engine.
For this the property `is_seo_noindex_cat` is set 
Also update the Docs GH Action to keep working with a newer Ubuntu version as GH is removing 18.04 support.
=> core: add option to exclude categories from the SEO indexing (0.x)

apps/zotonic_mod_admin/priv/templates/_admin_edit_content_seo.tpl, apps/zotonic_mod_base/src/controllers/controller_file.erl, apps/zotonic_mod_base/src/controllers/controller_page.erl, apps/zotonic_mod_seo/priv/templates/_html_head_seo.tpl, apps/zotonic_mod_seo_sitemap/src/models/m_seo_sitemap.erl, apps/zotonic_mod_seo_sitemap/src/support/seo_sitemap.erl
This adds an option to exclude all pages in a category from indexing by a search engine.
For this the property `is_seo_noindex_cat` is set.
=> core: add option to exclude categories from the SEO indexing

doc/ref/controllers/controller_template.rst, modules/mod_base/controllers/controller_template.erl
Add the option `http_status` to the `controller_template` to set the HTTP status code of the response.
This defaults to 200.
=> mod_base: add option to controller_template to set the http status code (0.x)

apps/zotonic_mod_base/src/controllers/controller_template.erl, doc/ref/controllers/controller_template.rst
This adds the option `http_status` to controller_template to set the HTTP response status on successful render of a template.
=> mod_base: add option to controller_template to set the http status code

apps/zotonic_core/src/support/z_context.erl
This filters URLs to ensure that they are local to the current site.
This function is added for compatibility with the 0.x
See also #3096
=> core: add z_context:site_url/2

apps/zotonic_core/src/support/z_dispatcher.erl, apps/zotonic_mod_base/src/controllers/controller_file_id.erl
This prevents adding csp_nonce to urls in controller_file_id.
=> mod_base: add csp_nonce to standard dispatcher args.

apps/zotonic_mod_menu/src/filters/filter_menu_is_visible.erl, doc/ref/filters/filter_menu_is_visible.rst
This makes it easier and more expected when the filter is applied on menu resources where some id has been deleted.
=> mod_menu: filter menu_is_visible now also checks for exists.

apps/zotonic_mod_translation/src/controllers/controller_language_set.erl
This ensures that an illegal URL is cleaned up before being used for the Location header.
=> mod_translation: sanitize URI for controller_set_language
