modules/mod_survey/templates/blocks/_block_view_survey_thurstone.tpl
=> Fix typo in _block_view_survey_thurstone.tpl

modules/mod_authentication/templates/_logon_box.tpl
Pass page param (for custom post-logon redirect URL) to reload delegate.
=> Support custom redirect page after social media logon

doc/manuals/templates/actions.rst
this would have saved me a lot of time :)
=> Added reference to scomps-script

src/scripts/zotonic-modules
=> Fixes zotonic/zotonic#1027 issue with zotonic-module script

include/zotonic.hrl, src/db/z_db.erl
The variable for the unique constraint was not used in column_spec in the previous pull request. Fixed.
=> Added support for UNIQUE constraint in psql column definitions

rebar.config, src/db/z_db.erl, src/db/z_db_pgsql.erl, src/db/z_db_worker.erl, src/install/z_install.erl, src/install/z_installer.erl, src/tests/pgsql_perf_db_tests.erl
Changed epgsql to version 3.0 and renamed all calls to pgsql to epgsql.
=> Upgrade epgsql to version 3.0.0

modules/mod_admin/templates/_action_dialog_connect.tpl
The bug was introduced in c1ffffc6709c5b6b44490796b951ca8e65120bfb (0.13.6).
=> Fix category preselection

modules/mod_base/filters/filter_make_value.erl, modules/mod_base/filters/filter_stringify.erl
I have added the to_value conversion to several places so that the examples
from issue #1084 work correctly. In addition to that I have added a make_value
filter so that you can not only print the value but also use it in a more
elaborate expression.
=> mod_base: Issue #1084: Force model queries into values more often

doc/ref/actions/action_moreresults.rst
=> Document catinclude argument for moreresults

.travis.yml, README.md, doc/cookbook/admin-a-custom-widget.rst, doc/cookbook/admin-datetime.rst, doc/cookbook/frontend-custom-content-block.rst, doc/dev/releasenotes/rel_0.09.0.rst, doc/dev/releasenotes/rel_0.12.4.rst, doc/dev/releasenotes/rel_0.13.0.rst, doc/dev/releasenotes/rel_0.13.4.rst, doc/dev/releasenotes/rel_0.13.5.rst, doc/dev/translations.rst, doc/index-tex.rst, doc/installation/_make_common.rst, doc/manuals/dispatch.rst, doc/manuals/user/admin.rst, doc/ref/actions/action_confirm.rst, doc/ref/actions/predicates/index.rst, doc/ref/dispatch/.generate, doc/ref/dispatch/index.rst, doc/ref/filters/html/index.rst, doc/ref/filters/resources/index.rst, doc/ref/filters/variables/index.rst, doc/ref/models/model_acl.rst, doc/ref/models/model_edge.rst, doc/ref/modules/mod_artwork.rst, doc/ref/modules/mod_base.rst, doc/ref/modules/mod_base_site.rst, doc/ref/tags/tag_image.rst, doc/ref/tags/tag_url.rst, doc/ref/templates/index.rst
=> Build docs on Travis

doc/dev/index.rst, doc/dev/releasing.rst
As decided today with @arjan @mmzeeman and @mworrell. 
/cc @CyBeRoni
=> doc: Document release schedule

modules/mod_import_csv/support/parse_csv.erl
=> mod_import_csv: Fix CSV import for CR files

doc/ref/modules/mod_admin_identity.rst, doc/user-guide/index.rst, doc/user-guide/user-management.rst, modules/mod_admin_identity/actions/action_admin_identity_dialog_user_add.erl, modules/mod_admin_identity/templates/_action_dialog_user_add.tpl
=> mod_admin_identity: Add config param for new user category

src/install/z_install.erl
Fix #1156. This of course works only for newly created sites, but that seems sufficient for now.
See also http://stackoverflow.com/a/417184.
=> Increase resource URI length

doc/developer-guide/modules.rst, include/zotonic.hrl, include/zotonic_notifications.hrl, src/support/z_datamodel.erl
=> Add data model notification

modules/mod_acl_user_groups/support/admin_acl_rules.erl, modules/mod_acl_user_groups/templates/_action_dialog_delete_rsc.acl_user_group.tpl, modules/mod_acl_user_groups/templates/_admin_acl_rule_header.tpl, modules/mod_acl_user_groups/templates/_admin_acl_rule_row.tpl, modules/mod_acl_user_groups/templates/_admin_acl_rules_publish_buttons.tpl, modules/mod_acl_user_groups/templates/_admin_catcg.tpl, modules/mod_acl_user_groups/templates/_admin_edit_content_acl.tpl, modules/mod_acl_user_groups/templates/_admin_edit_visible_for.tpl, modules/mod_acl_user_groups/templates/_dialog_acl_rules_import.tpl, modules/mod_acl_user_groups/templates/admin_acl_rules.tpl, modules/mod_acl_user_groups/templates/page_acl_user_group_try.tpl, modules/mod_acl_user_groups/translations/nl.po
=> mod_acl_user_groups: Improve wording and add missing Dutch translations 

doc/developer-guide/modules.rst, doc/ref/modules/mod_acl_user_groups.rst, modules/mod_acl_user_groups/mod_acl_user_groups.erl, modules/mod_acl_user_groups/models/m_acl_rule.erl, modules/mod_acl_user_groups/templates/_admin_acl_rule_row.tpl, modules/mod_acl_user_groups/translations/nl.po
Fix #1146.
* Disable managed ACL rule editing in admin
* Support both module and rsc rules
* Add documentation
=> Support managed ACL rules

modules/mod_base/controllers/controller_file.erl
Fix the leap year error during static files request.
=> Fix the leap year error(issue : #1202)

doc/developer-guide/releasenotes/rel_0.14.0.rst
@mworrell Any [main changes](https://github.com/zotonic/zotonic/compare/0.13.8...release-0.14.0) that I failed to mention?
=> Add 0.14.0 release notes

include/zotonic_notifications.hrl, modules/mod_acl_user_groups/templates/admin_acl_rules.tpl, modules/mod_acl_user_groups/translations/nl.po, modules/mod_admin/templates/_action_dialog_connect.tpl, modules/mod_admin/templates/_edit_date.tpl, modules/mod_media_exif/mod_media_exif.erl, rebar.config, rebar.config.lock, src/models/m_media.erl, src/support/z_media_identify.erl
core: use Erlang 'exif' module and add mod_media_exif to extract reso…urce properties (gps, orientation, crop, date)
=> Better exif support (works together with mod_admin_multiupload)

modules/mod_admin_statistics/templates/admin_statistics.tpl, priv/sites/zotonic_status/modules/mod_zotonic_statistics/mod_zotonic_statistics.erl
Added metric to display the number of open TCP connections in the mod_admin_statistics module.
=> Added Metric: Number of Open TCP Connections.

modules/mod_acl_user_groups/support/acl_user_groups_checks.erl
=> Fix a problem where an user can't update their own 'person' resource.

src/support/z_media_identify.erl, src/support/z_media_sanitize.erl, src/tests/z_sanitize_test.erl
This adds sanitization of SVG files and a place to add sanitization of other uploaded files.
See issue #1265
=> core: add sanitization on the contents of uploaded SVG files.

doc/ref/modules/mod_seo.rst
=> doc: Document Google Analytics

src/erlydtl/erlydtl_compiler.erl
=> core: fix problem with identifiers in templates

modules/mod_acl_user_groups/mod_acl_user_groups.erl, modules/mod_acl_user_groups/support/acl_default_rules.erl
=> mod_acl_user_groups: Insert default ACL rules

modules/mod_acl_user_groups/models/m_acl_rule.erl
=> mod_acl_user_groups: Be less verbose when editing and publishing ACL rules

doc/developer-guide/access-control.rst, doc/ref/modules/mod_acl_user_groups.rst
=> doc: Document mod_acl_user_groups

.travis.yml, doc/ref/directory-structure.rst, modules/mod_acl_user_groups/tests/mod_acl_user_groups_tests.erl, priv/sites/.gitignore, priv/sites/testsandboxdb/config, priv/sites/testsandboxdb/testsandboxdb.erl, src/scripts/zotonic-runtests, src/support/z_sites_manager.erl
* Run tests against the database
TODO:
Fix #1234.
=> tests: Add testsandboxdb site

src/zotonic.erl
=> tests: Make build fail if Zotonic fails to start

.travis.yml, modules/mod_oauth/models/m_oauth_app.erl, rebar.lock, src/support/z_ids.erl, src/support/z_utils.erl, src/zotonic_sup.erl
=> Add 19.0 as CI target. New mochiweb

doc/ref/modules/mod_ssl.rst, priv/erlang.config.in
=> mod_ssl: Added documentation on important ssl app settings

Dockerfile, Dockerfile.full, README.md, doc/developer-guide/docker.rst, doc/developer-guide/index.rst, doc/developer-guide/installation.rst, docker/docker-entrypoint.sh
=> docker: Create lite Zotonic container

doc/developer-guide/deployment/https.rst, doc/developer-guide/deployment/nginx.rst
Also mention SNI in the https-support section.
Example config was supplied by @maltejk (Thanks!)
https://gist.github.com/maltejk/b7e1739b07f1bd5eb79d59146ea3c1dc
=> docs: add example configuration for SSL termination using nginx.

doc/developer-guide/templates.rst
=> doc: Document page template names

doc/developer-guide/search.rst, doc/ref/models/model_search.rst
Please have a look. Improved formatting and some mistakes about incoming/outgoing edges.
=> doc: Improve search docs

doc/ref/filters/filter_twitter.rst, doc/ref/modules/mod_twitter.rst
=> doc: Add a note that only unprotected Tweets will be imported

include/zotonic.hrl, modules/mod_acl_user_groups/support/acl_user_group_rebuilder.erl, modules/mod_acl_user_groups/support/acl_user_groups_checks.erl, modules/mod_acl_user_groups/tests/mod_acl_user_groups_tests.erl, modules/mod_base/support/z_list_of_ids_filter.erl, modules/mod_comment/models/m_comment.erl, src/models/m_category.erl, src/models/m_edge.erl, src/models/m_identity.erl, src/models/m_media.erl, src/models/m_rsc.erl, src/models/m_rsc_update.erl, src/models/tests/m_rsc_db_tests.erl, src/support/z_acl.erl, src/tests/support/z_acl_tests.erl
* Solved by calling rid/2
Fix #1357.
=> core: For every resource id argument, allow resource name as well

src/support/z_datamodel.erl
=> core: Remove datamodel list fallback

Dockerfile
=> docker: Upgrade to Erlang 19

src/models/m_rsc.erl
Fix #acl_props{} record and login.
=> Fix acl_props

src/db/z_db.erl
=> Attempt to get rid of some dialyzer issues.

doc/conf.py
=> Build stubs rtd

Dockerfile, rebar.config.lock
Following 131b75405102f0840cd06ed9bd08d2506098b8e4
=> core: Fix bcrypt dep on 0.x

modules/mod_admin/templates/admin_widget_dashboard_latest.tpl
=> Remove TD from admin dashboard

modules/mod_admin/templates/_admin_edit_content_page_connections_list.tpl
Fix for #1476 
Show 'add connection' button in admin if linkable.
please cherry pick to 0.x after merge
=> Fix #1476 show add connection buttons if linkable

doc/ref/notifications/includes/edge_delete.rst, src/install/z_install.erl, src/install/z_installer.erl
=> core: Add edge creation timestamp to edge_log

doc/ref/modules/mod_acl_user_groups.rst, modules/mod_acl_user_groups/models/m_acl_rule.erl
=> mod_acl_user_groups: Add managed collab rules support

doc/ref/modules/mod_seo.rst, modules/mod_seo/templates/_ga_params.tpl, modules/mod_seo/templates/_html_head.tpl
=> mod_seo: Support custom Analytics params

modules/mod_admin_category/templates/_admin_category_sorter.tpl, modules/mod_menu/mod_menu.erl, modules/mod_menu/templates/_admin_menu_hierarchy_sorter.tpl, modules/mod_menu/templates/_admin_menu_menu_view.tpl, modules/mod_menu/templates/_menu_edit_item.tpl, modules/mod_menu/templates/admin_menu_hierarchy.tpl
Broken in b835ee708e9b346c7833fde07179208f2e051fc3.
=> mod_menu: Fix menu and user groups not editable

doc/ref/validators/validator_name_unique.rst, doc/ref/validators/validator_username_unique.rst, modules/mod_admin/templates/_admin_edit_content_advanced.tpl, modules/mod_admin/translations/nl.po, modules/mod_base/validators/validator_base_name_unique.erl
Fix #1412.
* Add name_unique validator.
* Add documentation.
* Add Dutch translation.
=> mod_base: Validate resource name

doc/developer-guide/search.rst, doc/developer-guide/upgrading.rst, modules/mod_admin/templates/admin_overview.tpl, modules/mod_search/support/search_query.erl
=> mod_search: Rename authoritative to is_authoritative

doc/developer-guide/index.rst, doc/developer-guide/logging.rst, doc/ref/configuration/zotonic-configuration.rst, doc/ref/modules/mod_logging.rst, include/zotonic_log.hrl, modules/mod_menu/mod_menu.erl, modules/mod_translation/mod_translation.erl, modules/mod_video/support/z_video_convert.erl, src/support/z.erl, src/support/z_datamodel.erl
=> core: Remove deprecated log functions

modules/mod_filestore/mod_filestore.erl, modules/mod_filestore/templates/admin_filestore.tpl
=> mod_filestore: Fix an issue with setting deletion to 'never'

doc/index.rst
=> doc: Link to 0.x docs

doc/cookbook/custom-controller.rst, doc/cookbook/index.rst, doc/developer-guide/controllers.rst, doc/developer-guide/dispatch-rules.rst
Document how to create a custom controller.
=> doc: Add custom controllers cookbook chapter

doc/developer-guide/notifications.rst, doc/ref/validators/validator_postback.rst
The delegate option is buggy, so remove it for now.
=> doc: Fix postback validator documentation

doc/ref/validators/validator_postback.rst
{{ok, Value, Context}; to {{ok, Value}, Context};
=> Minor typo in syntax fixed

doc/cookbook/index.rst, doc/cookbook/logstash.rst, doc/developer-guide/logging.rst
=> doc: Document Logstash configuration

src/support/z_pivot_rsc.erl
=> core: Make pivot index name unique

modules/mod_base/templates/_pager.tpl
=> base: Remove empty pager CSS

include/zotonic.hrl, src/models/m_search.erl
=> core: Add facets property to search_result

priv/erlang.config.in
=> core: Move filezcache data dir outside dep dir

src/models/m_rsc_update.erl
Fix #1642 
Fix problems when updating publication and event start and end dates
=> core: Fix problems when updating dates. (#1642)

modules/mod_video_embed/mod_video_embed.erl
=> replaced iframeborder with style border none

modules/mod_email_status/mod_email_status.erl, modules/mod_email_status/models/m_email_status.erl, modules/mod_email_status/templates/_email_status_view.tpl
Better email status administration, give up sending email to an address if sending failed 5 times over distinct days (without any success in between)
Work being done:
=> Email status handling and mailing list integration

priv/translations/nl.po
This fixes NL translations.
Some are taken from the 0.11/0.x and some are new.
We should also check the other languages.
=> Some nl translation fixes.

src/erlydtl/erlydtl_compiler.erl
Fix #1673
This replaces dynamic atom generation with predictable enumerated atoms, such limiting the number of different atoms to be generated.
=> core: fix a problem where compilation of templates generates random atoms

doc/cookbook/exometer.rst, doc/cookbook/index.rst
A cookbook for using Exometer with Zotonic. See https://github.com/zotonic/zotonic/issues/1670#issuecomment-298607044
=> Exometer cookbook

priv/translations/nl.po
=> [Translation] Changed 'bedank' to 'bedankt'

modules/mod_base/actions/action_base_moreresults.erl
=> mod_base: Support maps result in moreresults filter

doc/developer-guide/deployment/index.rst, doc/developer-guide/deployment/server-configuration.rst, doc/ref/troubleshooting.rst
=> doc: Add server configuration chapter

.travis.yml
=> tests: Re-enable Dialyzer on Travis

priv/translations/fr.po
Translation of branch 1.x to French
=> Translation to French

elvis.config, src/filewatcher/z_filewatcher_handler.erl, src/zotonic_compile.erl
=> core: Override ebin output directory (fix #1706)

modules/mod_base/filters/filter_date.erl
=> mod_base: Support ISO 8601 dates in filter_date

modules/mod_editor_tinymce/templates/_admin_tinymce_overrides_js.tpl
Ref. https://github.com/driebit/ginger/pull/294.
=> mod_editor_tinymce: Don't override language if already set

doc/developer-guide/modules.rst, doc/developer-guide/notifications.rst
=> doc: Document pid_observe_

apps/zotonic_mod_acl_user_groups/src/mod_acl_user_groups.erl, apps/zotonic_mod_acl_user_groups/test/mod_acl_user_groups_tests.erl
=> core: Fix race condition in replace_managed ACL rules during tests

.travis.yml, doc/Makefile, doc/conf.py, doc/ref/actions/index.rst
=> doc: Fix stubs build

modules/mod_admin/mod_admin.erl, modules/mod_admin/templates/_action_dialog_connect.tpl, modules/mod_admin/templates/_action_dialog_connect_tab_find.tpl, modules/mod_admin/templates/_action_dialog_connect_tab_find_results.tpl, modules/mod_admin/templates/_action_dialog_connect_tab_find_results_loop.tpl, modules/mod_search/support/search_query.erl
Add option to the admin connect dialog to filter on content group or on user-generated content.
=> In admin connect dialog, add option to filter on content group

README.md
Quick README fix, now linking correctly to a travisCI badge
=> doc: fixed broken image from TravisCI

Dockerfile.heavy, hooks/build
=> build: Base zotonic-heavy image on specified Zotonic version

apps/zotonic_mod_twitter/priv/templates/_html_head.tpl, apps/zotonic_mod_twitter/priv/templates/_html_head_twitter.tpl
=> mod_twitter: Add Twitter metadata

Dockerfile
We need open ssl on development environments and 0.x
=> Added open ssl to docker config

.gitignore, doc/ref/.gitignore
=> core: Fix gitignores

src/models/m_rsc_update.erl
=> Pass is_import to normalize

doc/ref/tags/tag_include.rst
=> doc: Document anondo include parameter

apps/zotonic_mod_admin_identity/priv/templates/_identity_verify_table.tpl, apps/zotonic_mod_email_status/priv/templates/_email_status_view.tpl, apps/zotonic_mod_email_status/src/mod_email_status.erl, apps/zotonic_mod_email_status/src/models/m_email_status.erl
Manual merge of 027cf2550c6be76d725161fcef7cce9c440b7bdf
Adds option to mod_email_status to block email addresses
=> Add option to block email addresses

doc/ref/tags/tag_image.rst
=> doc: Improve image documentation

docker/docker-entrypoint.sh
=> Docker: Fix unknown command error; add SHELL env var.

modules/mod_oauth/controllers/controller_oauth_access_token.erl, modules/mod_oauth/controllers/controller_oauth_request_token.erl, modules/mod_oauth/mod_oauth.erl
Add POST support of OAuth signature check on API calls.
=> mod_oauth: support OAuth signature check on POST to controller_api.

apps/zotonic_mod_base/src/controllers/controller_http_error.erl
Conversation here: https://groups.google.com/forum/#!topic/zotonic-developers/AlCy9NB2aq4
=> Zotonic returns 200 instead of 404 on "Not Found"

modules/mod_search/support/search_query.erl
`hassubject` and `hasobject` parsing was broken in #1866, throwing:
`webmachine_mochiweb:119 stop_request 500 (reason {badarg,[{erlang,iolist_to_binary,[[33437,<<"blogposting">>]],[]},{z_string,to_name1,1,[{file,"src/z_string.erl"},{line,482}]},{z_string,to_name,1,[{file,"src/z_string.erl"},{line,459}]},{m_rsc,name_lookup,2,[{file,"src/models/m_rsc.erl"},{line,707}]},{search_query,parse_query,3,[{file,"modules/mod_search/support/search_query.erl"},{line,260}]},{search_query,search,2,[{file,"modules/mod_search/support/search_query.erl"},{line,44}]},{z_notifier,first1,3,[{file,"src/support/z_notifier.erl"},{line,206}]},{z_search,search,3,[{file,"src/support/z_search.erl"},{line,102}]}]})
`
=> mod_search: Fix hassubject and hasobject query term parsing

modules/mod_search/support/search_query.erl
This fixes an infinite recursion introduced in c67ebcda68eb1fcdffec5c8fdabb731a437cbb6b.
=> mod_search: Fix regression in search query term parsing

modules/mod_search/support/search_query.erl, modules/mod_search/tests/search_query_tests.erl
mod_search: Fix hassubject/hasobject argument parsing
=> mod_search: Fix hassubject/hasobject argument parsing

modules/mod_seo/templates/_html_head.tpl
Fix #1800
Anonymises the ip address of the user
=> Anonymize ip address google analytics

modules/mod_atom/tests/atom_convert_tests.erl, priv/sites/testsandboxdb/config, src/db/z_db.erl, src/db/z_db_pool.erl, src/install/z_installer.erl
Fix #1701
Drop schema on starting testsandboxdb site
Also fix a timezone issue in mod_atom tests.
=> Drop schema before running tests

modules/mod_signup/templates/_signup_box.tpl
Fix #1755 
Show error on duplicate username..
=> mod_signup: show error on duplicate username. Fixes #1755

modules/mod_admin_identity/actions/action_admin_identity_dialog_user_add.erl, modules/mod_admin_identity/templates/_action_dialog_user_add.tpl, modules/mod_signup/controllers/controller_signup.erl, modules/mod_signup/mod_signup.erl, modules/mod_signup/templates/_signup_form_fields_email.tpl, modules/mod_signup/templates/_signup_form_fields_username.tpl
Fix #1879
Fix a problem where the surname prefix was not saved during signup.
Also fix a problem with autofill in relation with the surname prefix.
=> mod_signup: fix a problem with surname prefix on signup.

include/zotonic_notifications.hrl, modules/mod_development/lib/js/livereload.js, modules/mod_development/mod_development.erl, modules/mod_development/templates/_html_head.tpl, modules/mod_development/templates/admin_development.tpl, modules/mod_search/support/search_query.erl, src/filewatcher/z_filewatcher_handler.erl, src/support/z_mqtt_acl.erl
Live reload of css files.
Uses patched version of livereload.js, see https://github.com/zotonic/livereload-zotonic-js
Issue #1793 
This is only for the 0.x, an adapted version for master needs to be made.
Documentation update will come with the master version.
=> mod_development: add livereload of css and js. Issue #1793

apps/zotonic_core/include/zotonic_notifications.hrl
=> doc: Document user missing from edge notifications

src/support/z_script.erl
Please note that I did not "fix" the indentation: this gives a confusing diff.
=> Remove unnecessary call to internal function

Dockerfile, Dockerfile.dev
=> docker: Build on Erlang 19.3

src/support/z_pivot_rsc.erl
Fix #1965
Always trigger pivot_done, also on manual pivot.
=> Trigger pivot_done on manual rsc pivot

src/models/m_edge.erl, src/support/z_pivot_rsc.erl
Fix #1965 
Also delay the pivot due to edge inserts.
=> Pivot done

doc/developer-guide/releasenotes/rel_0.45.0.rst
=> Release 0.45.0

doc/ref/configuration/zotonic-configuration.rst, priv/sites/zotonic_status/controllers/controller_zotonic_status.erl, priv/sites/zotonic_status/templates/logon.tpl, priv/zotonic.config.in, src/support/z_config.erl
Add ip whitelist configuration to restrict access to the zotonic_status site.
=> zotonic_status: add optional ip whitelist

modules/mod_twitter/mod_twitter.erl, modules/mod_twitter/support/twitter_poller.erl, modules/mod_twitter/templates/_admin_authentication_service.tpl, modules/mod_twitter/translations/nl.po
Fix #1985
Add configuration to set a minimum delay for the configured feeds.
=> mod_twitter: Add configurable poll delay. Issue #1985

modules/mod_authentication/controllers/controller_logon.erl
=> mod_authentication: Fix config check

doc/cookbook/task-queue.rst
=> doc: Explain anonymous context in task queue callback

modules/mod_editor_tinymce/lib/js/tinymce-4.9.3/tiny-init.js
Fix #2009
Add tinymce plugin `lists` to support numlist and bullist to new tinymce editor 4.9.3
=> Fix #2009: Add lists to plugins to support lists in editor

src/models/m_rsc_update.erl
=> core: Fix publication_start default

.travis.yml, doc/ref/dispatch/dispatch_mod_auth2fa-dispatch.rst, doc/ref/filters/filter_ip2country.rst, doc/ref/filters/miscellaneous/index.rst, modules/mod_admin/templates/_admin_system_status.tpl, modules/mod_auth2fa/models/m_auth2fa.erl, modules/mod_auth2fa/support/z_auth2fa_qrcode_demo.erl, modules/mod_base/filters/filter_member.erl, modules/mod_geoip/filters/filter_ip2country.erl, modules/mod_geoip/mod_geoip.erl, modules/mod_twitter/models/m_twitter.erl, rebar.config, rebar.config.lock
New module to map IP addresses to countries.
=> mod_geoip: new module to map IP addresses to country names.

modules/mod_acl_user_groups/mod_acl_user_groups.erl, src/support/z_session_page.erl
Fix #2028
If the user's ACL groups change, then force all active websocket connections to reconnect.
This refreshes the permissions used by the websocket connection.
=> Reconnect ws connections on user permission change

modules/mod_authentication/controllers/controller_logon.erl, src/models/m_identity.erl
=> Add password reset token expiration

modules/mod_authentication/controllers/controller_logon.erl, modules/mod_authentication/templates/_logon_expired_form.tpl
Fix some problem with resetting expired passwords.
- Show errors
- Show passcode field if needed
- Correct handling of unchanged password error
=> mod_authentication: fix a problem with resetting expired passwords.

src/models/m_rsc_gone.erl, src/models/m_rsc_update.erl
Fix a problem where a race condition in rsc_gone might end up canceling the delete transaction.
=> Fix race condition in rsc_gone

modules/mod_admin/mod_admin.erl, modules/mod_admin/templates/_action_dialog_new_rsc_tab.tpl
Fix a problem where a connected depiction was disconnected if it was added to the text using tinyMCE.
=> mod_admin: do not toggle 'depiction' if image is embedded in tinymce

apps/zotonic_listen_http/src/zotonic_listen_http.erl, apps/zotonic_listen_mqtt/src/zotonic_listen_mqtt.erl
Fix #2129
Make the ranch options a map.
=> Make ranch options a map. Fixes #2129

apps/zotonic_launcher/bin/helpers/zotonic_setup, doc/ref/configuration/port-ssl-configuration.rst
Fix #1144
Fix #1143
Rebased version of #1144 by @pguyot 
(diff also contains ssl docs commit that has been merged already)
=> Pguyot patch 3

apps/zotonic_core/priv/translations/nl.po, apps/zotonic_core/priv/translations/zotonic.pot, apps/zotonic_mod_admin/priv/templates/_admin_edit_media.tpl, apps/zotonic_mod_authentication/priv/templates/email_password_reset.tpl
Merge copy-download-link from issue #2163 
Also small NL translation fixes.
=> 2163 download link

apps/zotonic_core/rebar.config, apps/zotonic_core/src/support/z_sites_dispatcher.erl, rebar.lock
Fix for a problem where the `hostalias` was not working after the Dialyzer changes.
With thanks to @karlsson 
Also remove twerl, as we don't need it anymore.
=> Fix for hostalias

apps/zotonic_core/src/models/m_site.erl, apps/zotonic_core/src/support/z.erl, apps/zotonic_core/src/support/z_config.erl, apps/zotonic_core/src/support/z_context.erl, apps/zotonic_launcher/priv/config/zotonic.config.in, apps/zotonic_mod_admin/priv/templates/admin_base.tpl, apps/zotonic_mod_base/priv/templates/base_noscript.tpl, apps/zotonic_mod_base_site/priv/templates/base_fullscreen.tpl, apps/zotonic_site_status/priv/templates/base.tpl, priv/skel/blog/priv/templates/base.tpl
Fix #2120 
Merge 0.x changes for DTAP environment setting into master.
=> DTAP environment (merged from #2151)

apps/zotonic_core/src/support/z_media_identify.erl
Fix #2191
Merge into master the changes from #2192
=> Fix PDF identification for some special PDFs. Fix #2191

modules/mod_base/scomps/scomp_base_pager.erl
Add dispatch so the pager template can use this information.
=> Add dispatch so pager tpl can use this

doc/ref/services/service_language_list.rst, modules/mod_base/lib/js/apps/z.widgetmanager.js, modules/mod_translation/services/service_translation_language_list.erl, src/support/z_search.erl
Adds an api to fetch the list of enabled languages.
=> Add api to fetch language list

src/models/m_edge.erl
This ensures correct notifications of all subjects and objects.
Fix #2204
Ensure that edge  notifications are emitted when merging two resources.
This is done by inserting new edges instead of patching subject/object ids of the existing edges.
=> core: merge edges by inserting new ones.

apps/zotonic_core/src/smtp/z_email_server.erl
Issue #2215
Make the smtp server more robust against mnesia aborts.
=> Make smtp server more robust agaist mnesia errors. Issue #2215

modules/mod_logging/mod_logging.erl
Fix #2232
Fix a problem where the log email could not be inserted when sending pages using the `{cat, ..}` templates.
=> Fix problem with logging emails using cat templates

apps/zotonic_core/src/support/z_ssl_certs.erl
Fixes an issue where self-signed certificates were generated for non-matching host names.
If we are serving the fallback site (after no site matched the hostname) then the self-signed cert for the current server will be used.
=> core: serve self-signed server cert for fallback site.

apps/zotonic_core/src/support/z_ssl_certs.erl
Change error code in ssl self-signed handling
=> Change error code in ssl self-signed handling

modules/mod_base/mod_base.erl, src/support/z_edge_log_server.erl, src/support/z_pivot_rsc.erl
Fix #2238
Fix a problem where the subject of a relation is not pivoted on an edge insert or delete.
=> Repivot subject on edge delete/insert

modules/mod_admin/templates/_rsc_edge_media.tpl
Fix #2269
Fix crop-center preview in depiction list on admin edit page.
=> mod_admin: Fix crop center view in rsc_edge_media.tpl  Fix #2269

apps/zotonic_core/src/db/z_db_pgsql.erl, apps/zotonic_core/src/db/z_db_pool.erl, apps/zotonic_core/src/install/z_installer.erl, apps/zotonic_core/src/support/z_sites_config.erl, apps/zotonic_core/src/support/z_sitetest.erl, apps/zotonic_launcher/src/command/zotonic_cmd_siteconfig.erl, apps/zotonic_mod_backup/priv/templates/_admin_backup_list.tpl, apps/zotonic_mod_backup/src/mod_backup.erl
Fix #2165 
Fix a problem where the wrong schema name was used if the default schema name is initialized (using `""`) in the site's config file.
=> [WIP] mod_backup: fix a problem with the default schema name

doc/developer-guide/getting-started.rst
Fix #2174
Add docs for the install on FreeBSD.
=> docs: Add package list for FreeBSD install. Fix #2174

modules/mod_base/lib/js/apps/zotonic-1.0.js
Don't close the connection in a beforeunload, but later in an unnload
Fix #2294
This PR keeps the connection open after a `pageunload` and makes sure all ajax
requests are asynchronous. This prevents the browser from sending synchronous
ajax requests after a `pageunload` and prevents the throw/deprecation warning
in Chrome.
Note: The connection will not be automatically restarted when the page is unloading
state after a `pageunload`.
=> core: Don't close the connection in a beforeunload, but later in an unload. Make sure all ajax requests are async

src/support/z_context.erl
=> Remove X-DTAP-Environment header

apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/less/environment.less, apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/less/zotonic-admin.less, apps/zotonic_mod_admin/priv/lib/css/zotonic-admin.css
Fix #2319
Change the color of the admin menu and sidebar to match the current DTAP environment setting.
=> mod_admin: reflect the environment in the admin colors. Fixes #2319

modules/mod_admin/lib/css/zotonic-admin.css, modules/mod_admin/lib/less/environment.less, modules/mod_admin/lib/less/zotonic-admin.less, modules/mod_admin/templates/admin_base.tpl
Issue #2319
Change the color of the admin menu and sidebar to match the current DTAP environment setting.
=> mod_admin: reflect the environment in the admin colors. Issue #2319

apps/zotonic_core/src/models/m_predicate.erl, apps/zotonic_mod_acl_user_groups/priv/templates/_admin_category_dropdown.tpl, apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/less/base.less, apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/less/dialog-new-connect.less, apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/less/environment.less, apps/zotonic_mod_admin/priv/lib/css/zotonic-admin.css, apps/zotonic_mod_admin/priv/templates/_action_dialog_new_rsc_tab.tpl
Fix #2305
Master version of merge request #2322
=> Hide the 'file upload' on initial show with preselected non-media category.

apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_core/src/models/m_identity.erl, apps/zotonic_core/src/smtp/z_email_server.erl, apps/zotonic_filehandler/src/zotonic_filehandler_mappers.erl, apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/less/table.less, apps/zotonic_mod_admin/priv/lib/css/zotonic-admin.css, apps/zotonic_mod_email_status/priv/templates/_email_status_view.tpl, apps/zotonic_mod_email_status/src/mod_email_status.erl, apps/zotonic_mod_logging/priv/templates/_admin_log_email_row.tpl, apps/zotonic_mod_logging/priv/templates/admin_log_email.tpl
Merge email changes from LearningStone
- low level drop of email to blocked addresses
- show email status panel on email log when searching for an email address
=> Email status on log; drop email for blocked addresses

src/support/z_pivot_rsc.erl
The table `rsc_pivot_queue` will be locked in row share exclusive mode to prevent race
conditions when updating a resource, or adding edges to the resource.
Removed the catch clause. It looks like it was there to prevent race condition errors from propagating. These kind of errors can no longer happen because of the lock.
=> Add a lock to the pivot table to prevent race conditions

doc/ref/filters/filter_flatten_value.rst, doc/ref/filters/lists/index.rst, modules/mod_admin/lib/css/zotonic-admin.css, modules/mod_admin/lib/less/dialog-new-connect.less, modules/mod_admin/lib/less/environment.less, modules/mod_admin/mod_admin.erl, modules/mod_admin/templates/_action_dialog_new_rsc_tab.tpl, modules/mod_admin/templates/_action_dialog_new_rsc_tab_find_results.tpl, modules/mod_admin/translations/nl.po, modules/mod_base/filters/filter_flatten_value.erl, modules/mod_search/support/search_query.erl
Modifications to the new page dialog.
- Swap columns
- For consistency, use _page_ instead of _content_
=> mod_admin: new page dialog, swap columns and small changes

apps/zotonic_core/src/support/z_media_tag.erl, apps/zotonic_core/src/support/z_mediaclass.erl, apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/less/dialog-new-connect.less, apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/less/image.less, apps/zotonic_mod_admin/priv/lib/css/zotonic-admin.css, apps/zotonic_mod_admin/priv/templates/_action_dialog_new_rsc_tab.tpl, apps/zotonic_mod_admin/priv/templates/_action_dialog_new_rsc_tab_find_results.tpl, apps/zotonic_mod_base/src/filters/filter_flatten_value.erl, apps/zotonic_mod_search/src/support/search_query.erl, doc/ref/filters/filter_flatten_value.rst, doc/ref/filters/lists/index.rst
Merge changes from 0.55.0 into the master.
Mainly changes to the admin connect/new dialog.
=> Merge changes from 0.55.0

rebar.config.lock, src/smtp/z_email.erl, src/smtp/z_email_receive.erl, src/smtp/z_email_server.erl
Fix a problem with sending emails due to a sting/binary conversion in z_string:trim/1
=> Email patch 0.55

apps/zotonic_mod_admin_config/priv/templates/_admin_config_ssl.tpl, apps/zotonic_mod_admin_config/priv/templates/_admin_config_ssl_certinfo.tpl, apps/zotonic_mod_admin_config/priv/templates/admin_config_ssl.tpl, apps/zotonic_mod_admin_config/src/models/m_admin_config.erl, apps/zotonic_mod_ssl_ca/priv/templates/_admin_config_ssl.mod_ssl_ca.tpl, apps/zotonic_mod_ssl_ca/src/mod_ssl_ca.erl, apps/zotonic_mod_ssl_letsencrypt/priv/templates/_admin_config_ssl.mod_ssl_letsencrypt.tpl, apps/zotonic_mod_ssl_letsencrypt/priv/templates/_ssl_letsencrypt_status.tpl, doc/ref/modules/mod_ssl_ca.rst
* Allow any filename in mod_ssl_ca (as long the extensions are ok)
* Don't require .pem for mod_ssl_ca
* Better display of certificates and their dates
=> Improve SSL handling

apps/zotonic_filehandler/src/zotonic_filehandler_compile.erl, apps/zotonic_listen_mqtt/src/zotonic_listen_mqtt_handler.erl, apps/zotonic_mod_base/src/controllers/controller_mqtt_transport.erl, doc/ref/validators/validator_postback.rst, rebar.lock
Add timeouts for limit the time till receiving the first complete connect package.
Also add limit to the size of the connect package.
=> Mqtt connect timeout

src/support/z_pivot_rsc.erl
Fix a problem where a flood of edge changes caused a spike in transactions to schedule pivot requests.
=> core: Let the pivot queue server insert new edges into the db

apps/zotonic_core/src/support/z_pivot_rsc.erl
From merge request  #2379 
Fix a problem where a flood of edge changes caused a spike in transactions to schedule pivot requests.
=> Deduplicate pivot requests. Issue #2379

modules/mod_development/mod_development.erl, modules/mod_development/models/m_development.erl, modules/mod_development/support/z_development_dbtrace.erl, modules/mod_development/templates/admin_development.tpl, src/db/z_db_pgsql.erl, src/models/m_predicate.erl, src/support/z_transport.erl
Issue #2390
* Add per session database query tracing.
* Cancel queries on timeout or crash of query process.
=> Trace database queries. Issue #2390

modules/mod_admin/templates/_action_dialog_change_category.tpl, modules/mod_admin/templates/_admin_edit_header.tpl
Issue #2360
Allow change of category if category does not exist.
Also cleanup `_admin_edit_header.tpl`
=> Allow to change category if category does not exist. Issue #2360 (0.x)

apps/zotonic_core/src/db/z_db_pool.erl, apps/zotonic_core/src/support/z_stats.erl, apps/zotonic_mod_logging/src/mod_logging.erl
Fix #2392
Add warning for exhaustion of the db pool.
Changes by @mmzeeman, manually copied to master branch.
=> core: Add a database pool usage warning. Fixes #2392

apps/zotonic_core/src/models/m_category.erl, apps/zotonic_core/src/models/m_hierarchy.erl, apps/zotonic_mod_admin/src/actions/action_admin_dialog_new_rsc.erl, apps/zotonic_mod_admin_predicate/priv/templates/admin_predicate.tpl, apps/zotonic_mod_admin_predicate/src/actions/action_admin_predicate_dialog_predicate_new.erl, apps/zotonic_mod_base/src/mod_base.erl
* Resync category after hierarchy changes.
* Better error messages on page/predicate creation errors.
=> Resync category after hierarchy changes.

apps/zotonic_core/src/support/z_mqtt_sessions_runtime.erl, apps/zotonic_core/src/support/z_template_compiler_runtime.erl, apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/less/tree-list.less, apps/zotonic_mod_admin/priv/lib/css/zotonic-admin.css, apps/zotonic_mod_admin/priv/templates/_admin_edit_content_page_connections.tpl, apps/zotonic_mod_admin/priv/templates/_admin_edit_content_page_connections_list.tpl, apps/zotonic_mod_admin/priv/templates/_rsc_edge.tpl, apps/zotonic_mod_admin/priv/templates/_rsc_edge_list.tpl, apps/zotonic_mod_admin_predicate/priv/templates/_admin_edges_list.tpl, apps/zotonic_mod_admin_predicate/priv/templates/admin_edges.tpl, apps/zotonic_mod_admin_predicate/src/mod_admin_predicate.erl, apps/zotonic_mod_wires/src/actions/action_wires_confirm.erl
Fix #2387 
Truncate long lists of edges in the admin.
Add 'disconnect' button to connections list screen.
=> mod_admin: truncate long edge lists in the admin.

apps/zotonic_core/src/support/z_template_compiler_runtime.erl, apps/zotonic_mod_acl_user_groups/priv/templates/_action_dialog_change_category.tpl, apps/zotonic_mod_admin/priv/templates/_action_dialog_change_category.tpl, apps/zotonic_mod_admin/priv/templates/_admin_edit_header.tpl
Fix #2360 
Allow to change category if the category does not exist.
Also cleanup category change dialog.
=> Allow to change category if it does not exist.

apps/zotonic_core/src/install/z_install.erl, apps/zotonic_core/src/install/z_installer.erl, apps/zotonic_core/src/models/m_identity.erl
Fix #2264
Change indices on `rsc` table for better query performance.
=> Add extra indices for better queries

apps/zotonic_core/src/install/z_install.erl, apps/zotonic_mod_zotonic_site_management/priv/skel/basesite/priv/zotonic_site.config.in, apps/zotonic_mod_zotonic_site_management/priv/skel/blog/priv/zotonic_site.config.in, apps/zotonic_mod_zotonic_site_management/priv/skel/empty/priv/zotonic_site.config.in, apps/zotonic_mod_zotonic_site_management/priv/skel/nodb/priv/zotonic_site.config.in
Fix #2410 
Fix create index for some psql versions.
=> Fix SQL for site creation.

apps/zotonic_core/src/models/m_media.erl, apps/zotonic_core/src/models/m_rsc.erl, apps/zotonic_core/src/models/m_rsc_update.erl, apps/zotonic_core/src/smtp/z_email_server.erl, apps/zotonic_mod_mailinglist/src/mod_mailinglist.erl
Misc fixes and code cleanup.
Fix #2416
=> Fixes for attachment handling. Code cleanup.

apps/zotonic_core/src/db/z_db.erl, apps/zotonic_core/src/models/m_config.erl, apps/zotonic_core/src/support/z_pivot_rsc.erl, apps/zotonic_mod_filestore/src/mod_filestore.erl, apps/zotonic_mod_twitter/src/mod_twitter.erl, apps/zotonic_mod_twitter/src/models/m_twitter.erl
Fix #2412
Also fix a problem with setting db props now that props are maps.
=> Fix config props and error level for unique key violations

.travis.yml, rebar.config, rebar.config.lock
Fix #2301 
Fix problem with OTP-22
=> Make compatible with OTP-22

modules/mod_base/controllers/controller_api.erl, modules/mod_filestore/mod_filestore.erl, modules/mod_filestore/model/m_filestore.erl, modules/mod_filestore/support/filestore_admin.erl, modules/mod_filestore/support/filestore_uploader.erl, modules/mod_filestore/templates/admin_filestore.tpl, rebar.config.lock
S3 - option to create bucket and fixes.
API - allow service modules to return a map, will be encoded using jsx.
=> Allow to create s3 bucket when not present.

apps/zotonic_mod_admin/priv/templates/admin_referrers.tpl, apps/zotonic_mod_survey/priv/templates/_admin_survey_editor_results.tpl, apps/zotonic_mod_survey/priv/templates/_survey_question_page.tpl, apps/zotonic_mod_survey/priv/templates/blocks/_block_view_survey_short_answer.tpl
Master version of #2429 
Excluding the translations, that must be done for all translations at once.
=> mod_survey fixes from #2429

modules/mod_survey/questions/survey_q_category.erl, modules/mod_survey/questions/survey_q_multiple_choice.erl, modules/mod_survey/questions/survey_q_short_answer.erl, modules/mod_survey/templates/_admin_edit_content_survey_settings.tpl, modules/mod_survey/templates/survey.tpl, modules/mod_survey/translations/nl.po
Handy for cases where the survey needs to be (temporarily) closed
=> mod_survey - option to hide survey form

apps/zotonic_core/src/support/z_model.erl, apps/zotonic_core/src/support/z_search.erl, apps/zotonic_mod_import_wordpress/rebar.config, apps/zotonic_mod_import_wordpress/src/mod_import_wordpress.erl, apps/zotonic_mod_instagram/rebar.config, apps/zotonic_mod_instagram/src/mod_instagram.erl, apps/zotonic_mod_twitter/rebar.config, apps/zotonic_mod_twitter/src/support/twitter_poller.erl, apps/zotonic_mod_wires/rebar.config, apps/zotonic_mod_wires/src/scomps/scomp_wires_droppable.erl, apps/zotonic_mod_wires/src/scomps/scomp_wires_sorter.erl, apps/zotonic_notifier/src/zotonic_notifier_worker.erl
Remove calls to erlang:get_stacktrace/0
=> Remove calls to erlang:get_stacktrace/0

apps/zotonic_core/src/support/z_model.erl, apps/zotonic_mod_base/src/controllers/controller_api.erl
Better checks on missing model paths or methods.
=> Better error returns for faulty API calls

doc/developer-guide/directory-structure.rst, doc/developer-guide/index.rst, doc/ref/index.rst
Moving pages in docs for better maintenance.
=> Move directory-structure to developer-guide.

apps/zotonic_core/src/support/z_lib_include.erl, apps/zotonic_mod_base/priv/lib/js/apps/z.widgetmanager.js, apps/zotonic_mod_translation/priv/lib-src/Makefile, apps/zotonic_mod_translation/priv/lib-src/mod_translation.less, apps/zotonic_mod_translation/priv/lib/less/config, apps/zotonic_mod_translation/priv/lib/less/less_to_css, doc/ref/tags/tag_lib.rst
Add lib tag options 'async' and 'minify'.
Also make jquery ui optional for simple zotonic widgets.
=> Add lib tag options 'async' and 'minify'.

apps/zotonic_core/priv/translations/zotonic.pot, apps/zotonic_core/src/support/z_media_tag.erl, apps/zotonic_core/src/support/z_template.erl, apps/zotonic_mod_acl_user_groups/src/support/acl_user_group_rebuilder.erl, apps/zotonic_mod_acl_user_groups/src/support/acl_user_groups_rules.erl, apps/zotonic_mod_base/src/controllers/controller_page.erl, apps/zotonic_mod_base/src/filters/filter_randomize.erl, apps/zotonic_mod_survey/src/filters/filter_survey_any_correct_answer.erl, apps/zotonic_mod_survey/src/filters/filter_survey_any_wrong_answer.erl, apps/zotonic_mod_translation/priv/templates/language_switch.tpl, apps/zotonic_mod_video/priv/templates/_video_viewer.tpl, apps/zotonic_mod_wires/priv/lib/js/modules/livevalidation-1.3.js
=> Fixes 20200610

apps/zotonic_core/priv/translations/fr.po
Give some love to French language. File fr.po updated.
=> Un peu d'amour

GNUmakefile
GNUMakefile doesn't work if the host is behind an https proxy
This PR adds calls to 'httpc:set_options()' before calls to 'httpc:request()' in case env var $https_proxy is set.
=> Added support for https_proxy in GNUMakefile

apps/zotonic_core/src/i18n/z_language_data.erl, apps/zotonic_core/src/models/m_rsc_export.erl
Misc problems encountered in production.
=> Fixes 20200613

apps/zotonic_core/src/i18n/z_language_data.erl, apps/zotonic_mod_acl_user_groups/priv/templates/_admin_edit_basics_user_extra.tpl, apps/zotonic_mod_acl_user_groups/src/mod_acl_user_groups.erl, apps/zotonic_mod_admin/src/actions/action_admin_dialog_edit_basics.erl
Misc fixes from production.
1. Added languages:
* ku: Kurdish
* su: Sundanese
* sw: Swahili
* yo: Yoruba
2. Fixed a problem with adding users to user-groups in the quick edit dialog.
=> Misc fixes

apps/zotonic_core/src/smtp/z_email_dkim.erl, apps/zotonic_mod_email_dkim/priv/templates/admin_email_dkim.tpl, apps/zotonic_mod_email_dkim/src/mod_email_dkim.erl, apps/zotonic_mod_email_dkim/src/models/m_email_dkim.erl
Fix #2470
Also place the DKIM keys in the security folder.
=> Fix dkim admin screen.

apps/zotonic_mod_admin/priv/templates/_admin_edit_header.tpl
Fix #2473
Show full category path in admin header.
=> Show full category path in admin header.

apps/zotonic_core/src/support/z_parse_multipart.erl, apps/zotonic_mod_admin/src/actions/action_admin_dialog_media_upload.erl, apps/zotonic_mod_base/src/controllers/controller_mqtt_transport.erl, apps/zotonic_mod_wires/priv/lib/js/apps/zotonic-wired.js
=> Fix a problem with routing responses to mqtt-transport form posts.

apps/zotonic_mod_wires/src/mod_wires.erl, doc/ref/modules/mod_wires.rst
=> Add minimal mod_wires documentation.

apps/zotonic_core/priv/translations/ar.po, apps/zotonic_core/priv/translations/de.po, apps/zotonic_core/priv/translations/en.po, apps/zotonic_core/priv/translations/es.po, apps/zotonic_core/priv/translations/et.po, apps/zotonic_core/priv/translations/fr.po, apps/zotonic_core/priv/translations/nl.po, apps/zotonic_core/priv/translations/pl.po, apps/zotonic_core/priv/translations/pt.po, apps/zotonic_core/priv/translations/ru.po, apps/zotonic_core/priv/translations/th.po, apps/zotonic_core/priv/translations/tr.po, apps/zotonic_core/priv/translations/zh.po, apps/zotonic_core/priv/translations/zotonic.pot
=> New pot file, merged into po files

apps/zotonic_core/priv/translations/ar.po, apps/zotonic_core/priv/translations/de.po, apps/zotonic_core/priv/translations/en.po, apps/zotonic_core/priv/translations/es.po, apps/zotonic_core/priv/translations/et.po, apps/zotonic_core/priv/translations/fr.po, apps/zotonic_core/priv/translations/nl.po, apps/zotonic_core/priv/translations/pl.po, apps/zotonic_core/priv/translations/pt.po, apps/zotonic_core/priv/translations/ru.po, apps/zotonic_core/priv/translations/th.po, apps/zotonic_core/priv/translations/tr.po, apps/zotonic_core/priv/translations/zh.po, apps/zotonic_core/priv/translations/zotonic.pot, apps/zotonic_mod_survey/priv/templates/_admin_edit_content_survey_settings.tpl, apps/zotonic_mod_survey/priv/templates/survey.tpl, apps/zotonic_mod_survey/src/questions/survey_q_multiple_choice.erl, apps/zotonic_mod_survey/src/questions/survey_q_short_answer.erl
Fix #2434
Add option to disable a survey.
=> Merge survey changes from #2432. Fixes #2434

src/filewatcher/z_filewatcher_handler.erl
Fix #2029
It calls `sassc` instead of the old, now deprecated, `ruby-sass`.
The package sassc is now a dependency.
MacOS install
```
brew install sassc
```
Ubuntu install
```
apt-get install sassc
```
There could be BC breaks when sassc compiles the sass files differently. This will surface only when changes are made to the scss files themselves as the css files are usually added to the repository.
=> Use sassc instead of ruby-sass

apps/zotonic_core/src/support/z_config.erl, apps/zotonic_core/src/zotonic_core_sup.erl, apps/zotonic_filehandler/src/zotonic_filehandler_compile.erl, apps/zotonic_filehandler/src/zotonic_filehandler_mappers.erl, apps/zotonic_filewatcher/src/zotonic_filewatcher_handler.erl, apps/zotonic_filewatcher/src/zotonic_filewatcher_sup.erl, apps/zotonic_launcher/priv/config/zotonic.config.in, apps/zotonic_listen_http/src/zotonic_listen_http.erl, doc/ref/modules/mod_development.rst
Also better https listener errors.
Fix #2500
=> Use sassc for .sass compilation.

apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_core/src/models/m_media.erl, apps/zotonic_core/src/support/z_media_identify.erl, apps/zotonic_core/src/support/z_media_preview.erl, apps/zotonic_mod_admin/priv/templates/_action_dialog_new_rsc_tab.tpl, apps/zotonic_mod_admin/priv/templates/_admin_edit_media.tpl, apps/zotonic_mod_audio/priv/templates/_admin_edit_content.audio.tpl, apps/zotonic_mod_audio/priv/templates/_audio_viewer.tpl, apps/zotonic_mod_audio/src/mod_audio.erl, apps/zotonic_mod_audio/src/zotonic_mod_audio.app.src, apps/zotonic_mod_base/src/filters/filter_format_duration.erl, apps/zotonic_mod_video/src/mod_video.erl, doc/ref/controllers/controller_oauth2_service_authorize.rst, doc/ref/controllers/controller_oauth2_service_redirect.rst, doc/ref/dispatch/dispatch_mod_oauth2-dispatch.rst, doc/ref/filters/filter_format_duration.rst, doc/ref/filters/filter_format_integer.rst, doc/ref/filters/filter_format_number.rst, doc/ref/filters/filter_format_price.rst, doc/ref/filters/numbers/index.rst, doc/ref/filters/strings/index.rst, doc/ref/models/model_email_dkim.rst, doc/ref/models/model_oauth2_service.rst, doc/ref/modules/mod_instagram.rst, doc/ref/templates/template_logon_service_oauth.rst, doc/ref/templates/template_logon_service_oauth_done.rst
=> Add mod_audio

apps/zotonic_mod_audio/priv/templates/_audio_viewer.tpl, apps/zotonic_mod_video/priv/templates/_video_viewer.tpl, doc/ref/modules/mod_audio.rst, doc/ref/modules/mod_oembed.rst, doc/ref/modules/mod_video.rst, doc/ref/modules/mod_video_embed.rst
Extra documentation for mod_audio
=> Docs mod audio

apps/zotonic_core/src/models/m_rsc.erl, apps/zotonic_core/test/models/m_rsc_db_tests.erl, apps/zotonic_core/test/support/z_lib_include_tests.erl, apps/zotonic_core/test/support/z_media_preview_tests.erl, apps/zotonic_launcher/bin/zotonic, apps/zotonic_mod_search/src/support/search_query_notify.erl
=> Misc test fixes

apps/zotonic_core/src/support/z_dropbox.erl
Fix an issue where dropbox files would not import if the site directory contains a relative path.
=> Fix an issue where dropbox files would not import

apps/zotonic_core/priv/translations/ar.po, apps/zotonic_core/priv/translations/de.po, apps/zotonic_core/priv/translations/en.po, apps/zotonic_core/priv/translations/es.po, apps/zotonic_core/priv/translations/et.po, apps/zotonic_core/priv/translations/fr.po, apps/zotonic_core/priv/translations/nl.po, apps/zotonic_core/priv/translations/pl.po, apps/zotonic_core/priv/translations/pt.po, apps/zotonic_core/priv/translations/ru.po, apps/zotonic_core/priv/translations/th.po, apps/zotonic_core/priv/translations/tr.po, apps/zotonic_core/priv/translations/zh.po, apps/zotonic_core/priv/translations/zotonic.pot, apps/zotonic_core/src/support/z_file_locate.erl, apps/zotonic_mod_base/priv/templates/base_noscript.tpl, apps/zotonic_mod_base_site/priv/templates/base.tpl, apps/zotonic_mod_mailinglist/priv/templates/mailinglist_confirm.tpl, apps/zotonic_mod_mailinglist/priv/templates/mailinglist_unsubscribe.tpl, apps/zotonic_mod_mailinglist/src/scomps/scomp_mailinglist_mailinglist_subscribe.erl, apps/zotonic_mod_seo/priv/templates/_html_head_seo.tpl, apps/zotonic_mod_translation/priv/templates/_html_head_translation.tpl, apps/zotonic_mod_video/priv/templates/_video_viewer.tpl, apps/zotonic_mod_video/src/mod_video.erl, apps/zotonic_mod_video/src/support/z_video_convert.erl, doc/cookbook/justenough-otp1.rst, doc/cookbook/justenough-postgres.rst, doc/developer-guide/getting-started.rst, doc/ref/installation/requirements.rst
Misc fixes, most too small for separate merge requests.
=> Fixes 20201023

modules/mod_authentication/templates/logon_service_done.tpl, modules/mod_facebook/controllers/controller_facebook_authorize.erl, modules/mod_facebook/controllers/controller_facebook_redirect.erl, modules/mod_linkedin/controllers/controller_linkedin_redirect.erl, modules/mod_twitter/controllers/controller_twitter_redirect.erl
Fix #2536
Fix a problem with Safari 14 and the OAuth authentication flow.
=> Fix a problem with OAuth flow on Safari 14. Issue #2536

apps/zotonic_mod_ssl_letsencrypt/src/mod_ssl_letsencrypt.erl, doc/developer-guide/sites.rst
Fix a problem where the intermediate certificates of LetsEncrypt were not saved.
=> Letsencrypt ca chain

apps/zotonic_core/src/models/m_config.erl, apps/zotonic_core/src/support/z_acl.erl, apps/zotonic_core/src/support/z_search.erl, apps/zotonic_mod_acl_user_groups/src/models/m_acl_rule.erl, apps/zotonic_mod_linkedin/priv/templates/_logon_extra_email_reset.tpl, apps/zotonic_mod_search/src/mod_search.erl, apps/zotonic_mod_survey/priv/templates/blocks/_block_view_survey_narrative.tpl, apps/zotonic_mod_survey/priv/templates/email_survey_result.tpl
* import/export of ACL rules
* error on m.config access without permission
* better survey result email
* extra search term for match_objects with content_group filtering
=> Misc fixes dec 2020

README.md, apps/zotonic_core/src/db/z_db.erl, apps/zotonic_mod_authentication/src/controllers/controller_authentication.erl, apps/zotonic_mod_l10n/src/mod_l10n.erl, apps/zotonic_mod_mailinglist/src/mod_mailinglist.erl, apps/zotonic_mod_mailinglist/src/support/z_mailinglist_recipients.erl, apps/zotonic_mod_twitter/src/support/oauth_twitter_client.erl
* Twitter poller no tokens
* List recipients of mailing list
=> Misc fixed 2020-dec

apps/zotonic_core/src/models/m_media.erl, apps/zotonic_mod_video/src/mod_video.erl, apps/zotonic_mod_video/src/support/z_video_info.erl
Misc fixes, batch 1 for jan 2021
=> Fix to file upload mime checks and video mp1 processing.

apps/zotonic_core/src/support/z.erl, apps/zotonic_core/src/support/z_sites_dispatcher.erl, apps/zotonic_launcher/src/command/zotonic_cmd_dispatch.erl, apps/zotonic_mod_development/priv/templates/_development_dispatch_trace.tpl, apps/zotonic_mod_development/src/support/z_development_dispatch.erl, doc/ref/cli/index.rst
Fix #2407
Add CLI command to show dispatch information.
=> Command line option to show dispatch information

apps/zotonic_core/src/support/z_dispatcher.erl, apps/zotonic_launcher/src/command/zotonic_cmd_dispatch.erl, apps/zotonic_mod_development/priv/templates/_development_dispatch_trace.tpl
Issue #2407
Also add the module and dispatch file to the dispatch information.
=> Add module and dispatch file to controller options and dispatch information

.github/workflows/docs.yml, apps/zotonic_core/src/support/z_lib_include.erl
Fix a problem where the lib files where combined in reverse order.
=> Fix a problem where the lib files where combined in reverse order.

doc/developer-guide/deployment/nginx.rst
See discussion at:
https://github.com/zotonic/zotonic/commit/9b328ed1d48d9990f73a225ae432ce459462f4a5#commitcomment-46969607
=> Re-add the mqtt-transport location to the nginx example.

apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/less/edit-blocks.less, apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/less/edit.less, apps/zotonic_mod_admin/priv/lib/css/zotonic-admin.css, apps/zotonic_mod_admin/priv/templates/_admin_edit_block_li.tpl, apps/zotonic_mod_admin/priv/templates/_admin_edit_blocks.tpl, apps/zotonic_mod_backup/src/backup_rsc_upload.erl, apps/zotonic_mod_backup/src/controllers/controller_admin_backup.erl, apps/zotonic_mod_survey/priv/lib-src/css/admin_survey.scss, apps/zotonic_mod_survey/priv/lib/css/admin_survey.css, apps/zotonic_mod_survey/priv/lib/js/admin_survey_question_editor.js, apps/zotonic_mod_survey/priv/templates/_admin_edit_content_survey_settings.tpl, apps/zotonic_mod_survey/priv/templates/_admin_survey_question_j.tpl, apps/zotonic_mod_survey/priv/templates/_admin_survey_question_page.tpl, apps/zotonic_mod_survey/priv/templates/_admin_survey_question_q.tpl, apps/zotonic_mod_survey/priv/templates/_admin_survey_settings_tab.tpl, apps/zotonic_mod_survey/priv/templates/blocks/_admin_edit_block_li_survey_button.tpl, apps/zotonic_mod_survey/priv/templates/blocks/_admin_edit_block_li_survey_page_break.tpl, apps/zotonic_mod_wires/src/support/z_render.erl
* Fix render_iframe and restore of backup file.
* Better dragging of blocks in admin editors
* Add label-floating to survey settings
=> Misc. updates and fixes

apps/zotonic_mod_base/priv/templates/base.tpl
The cotonic init code which is loaded with a all include head, was not present in base.tpl. This PR adds an include in _base.tpl.
=> Add cotonic head init in base

apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_core/src/support/z.erl, apps/zotonic_core/src/support/z_context.erl, apps/zotonic_core/src/support/z_controller_helper.erl, apps/zotonic_core/src/support/z_validation.erl, apps/zotonic_mod_admin/priv/templates/admin_base.tpl, apps/zotonic_mod_fileuploader/include/fileuploader.hrl, apps/zotonic_mod_fileuploader/priv/dispatch/dispatch, apps/zotonic_mod_fileuploader/priv/lib/js/z.fileuploader.js, apps/zotonic_mod_fileuploader/priv/lib/js/zotonic.fileuploader.worker.js, apps/zotonic_mod_fileuploader/priv/templates/_fileuploader_worker.tpl, apps/zotonic_mod_fileuploader/rebar.config, apps/zotonic_mod_fileuploader/src/controllers/controller_fileuploader.erl, apps/zotonic_mod_fileuploader/src/mod_fileuploader.erl, apps/zotonic_mod_fileuploader/src/models/m_fileuploader.erl, apps/zotonic_mod_fileuploader/src/support/z_fileuploader.erl, apps/zotonic_mod_fileuploader/src/support/z_fileuploader_recorddefs.erl, apps/zotonic_mod_fileuploader/src/zotonic_mod_fileuploader.app.src, apps/zotonic_mod_video/src/support/z_video_preview.erl, apps/zotonic_mod_wires/priv/lib/js/apps/zotonic-wired.js, doc/ref/controllers/controller_fileuploader.rst, doc/ref/dispatch/dispatch_mod_fileuploader-dispatch.rst, doc/ref/models/model_fileuploader.rst, doc/ref/modules/mod_fileuploader.rst
This adds module `mod_fileuploader`.
This adds file uploading using a web worker.
The `zotonic-wired.js` will use this webworker if it is present.
=> mod_fileuploader: use a web worker to upload files.

doc/cookbook/custom-model.rst, doc/developer-guide/controllers.rst, doc/developer-guide/directory-structure.rst, doc/developer-guide/getting-started.rst, doc/developer-guide/templates.rst
This PR fixes some documentation typos and outdated stuff.
=> Docs: minor fixes

apps/zotonic_core/src/smtp/z_email_server.erl
Fixes an issue where empty emails could be sent during site startup.
=> Change z_email_server polling, check on presence of templates.

apps/zotonic_mod_survey/src/models/m_survey.erl
Fixes #2589 
This PR changes the row update method in `replace_survey_submission/4`, from
`z_db:q()` plus SQL `UPDATE` commands
to
`z_db:update()`
=> fix badmap on editable surveys (#2589)

apps/zotonic_core/priv/translations/zotonic.pot, apps/zotonic_mod_survey/priv/templates/_admin_edit_content_survey_settings.tpl, apps/zotonic_mod_survey/priv/templates/_dialog_survey_email_addresses.tpl, apps/zotonic_mod_survey/src/mod_survey.erl, apps/zotonic_mod_survey/src/models/m_survey.erl, apps/zotonic_mod_survey/src/questions/survey_q_narrative.erl, apps/zotonic_mod_survey/src/support/survey_answer_prep.erl, apps/zotonic_mod_survey/src/support/survey_test_results.erl, apps/zotonic_mod_twitter/src/support/twitter_poller.erl
Misc fixed for survey results and editing.
Mainly:
- template changes for floating-label
- changes to maps in result storage
=> Fixes for survey results and editing

apps/zotonic_core/src/models/m_identity.erl, apps/zotonic_mod_admin/priv/templates/_admin_edit_js.tpl
Add m_identity:is_email_verified/1 and /2 to check if an email identity is verified.
=> Changes from LS branch

apps/zotonic_core/src/models/m_site.erl, apps/zotonic_core/src/smtp/z_email.erl, apps/zotonic_core/src/smtp/z_email_server.erl, apps/zotonic_mod_admin/priv/templates/_admin_edit_content_page_connections_list.tpl, apps/zotonic_mod_admin/priv/templates/_admin_media_import_list.tpl, apps/zotonic_mod_admin/src/models/m_admin.erl, apps/zotonic_mod_base/priv/lib-src/less/z.icons/icon-buttons.less, apps/zotonic_mod_base/priv/lib/css/z.icons.css, apps/zotonic_mod_signup/priv/templates/signup_confirm.tpl, apps/zotonic_mod_signup/src/controllers/controller_signup_confirm.erl, apps/zotonic_mod_signup/src/mod_signup.erl
Replace some occurrences of m.config in the templates.
=> Config keys 20210312

apps/zotonic_core/src/support/z_mqtt_sessions_runtime.erl
Better and more fine grained ACL checks for model event topics.
=> Topic acl model event

apps/zotonic_mod_authentication/priv/templates/_logon_service_error.tpl, apps/zotonic_mod_base/priv/templates/base_simple.tpl, apps/zotonic_mod_facebook/priv/templates/_admin_authentication_service.tpl, apps/zotonic_mod_microsoft/priv/dispatch/dispatch, apps/zotonic_mod_microsoft/priv/templates/_admin_authentication_service.tpl, apps/zotonic_mod_microsoft/priv/templates/_logon_extra.tpl, apps/zotonic_mod_microsoft/priv/templates/_logon_extra_email_reset.tpl, apps/zotonic_mod_microsoft/priv/templates/_logon_service.microsoft.tpl, apps/zotonic_mod_microsoft/priv/templates/_microsoft_login_link.tpl, apps/zotonic_mod_microsoft/rebar.config, apps/zotonic_mod_microsoft/src/mod_microsoft.erl, apps/zotonic_mod_microsoft/src/models/m_microsoft.erl, apps/zotonic_mod_microsoft/src/support/z_microsoft_oauth_service.erl, apps/zotonic_mod_microsoft/src/zotonic_mod_microsoft.app.src, apps/zotonic_mod_oauth2/priv/lib/js/zotonic.oauth.worker.js, doc/ref/dispatch/dispatch_mod_microsoft-dispatch.rst, doc/ref/models/model_microsoft.rst, doc/ref/modules/mod_microsoft.rst
Add logon and signup using the Microsoft identity platform
=> Logon and signup using Microsoft identity platform

apps/zotonic_core/src/support/z_render.erl, apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/less/dragdrop.less, apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/less/zotonic-admin.less, apps/zotonic_mod_admin/priv/lib/css/zotonic-admin.css, apps/zotonic_mod_admin/priv/templates/_action_dialog_delete_rsc.tpl, apps/zotonic_mod_admin/priv/templates/admin_base.tpl, apps/zotonic_mod_admin/priv/templates/admin_edit.tpl, apps/zotonic_mod_fileuploader/priv/lib/js/z.fileuploader-admin.js, apps/zotonic_mod_fileuploader/priv/lib/js/zotonic.fileuploader.worker.js, apps/zotonic_mod_fileuploader/priv/templates/_html_body_admin.tpl, apps/zotonic_mod_fileuploader/src/mod_fileuploader.erl
Add simple upload of files using drag & drop.
=> First version of drag&drop to upload files in the admin.

apps/zotonic_mod_admin/priv/templates/_action_dialog_connect.tpl, apps/zotonic_mod_admin/priv/templates/_action_dialog_media_upload_tab_upload.tpl, apps/zotonic_mod_admin/priv/templates/_action_dialog_new_rsc_tab.tpl, apps/zotonic_mod_admin/priv/templates/_admin_media_import_list.tpl, apps/zotonic_mod_admin/src/actions/action_admin_dialog_media_upload.erl, apps/zotonic_mod_admin/src/models/m_admin.erl, apps/zotonic_mod_admin_frontend/priv/templates/_admin_frontend_edit.tpl, doc/cookbook/custom-model.rst, doc/ref/actions/action_alert.rst, doc/ref/filters/filter_if_undefined.rst, doc/ref/modules/mod_admin.rst, doc/ref/tags/tag_image.rst, doc/ref/validators/validator_numericality.rst
Add options for handling the 'is_dependent' flag in the connect dialog.
=> Add configs mod_admin.rsc_dialog_is_dependent and mod_admin.rsc_dialog_hide_dependent

.github/workflows/docs.yml, modules/mod_seo/templates/_html_head_seo.tpl, modules/mod_seo/templates/admin_seo.tpl, modules/mod_twitter/filters/filter_twitter.erl, src/smtp/z_email_server.erl
- Add support for GTM
- Add support for G- GA tracking
- Fix link to Bing webmasters
- Fix crash in tweet importer for illegal URLs
- Fix logging problem in email server for unexpected errors
=> SEO GTM support and misc fixes

modules/mod_authentication/controllers/controller_logon.erl, modules/mod_authentication/dispatch/dispatch, modules/mod_authentication/templates/_logon.tpl, modules/mod_authentication/templates/_logon_login_form_fields.tpl, modules/mod_authentication/templates/_logon_reset_form.tpl, modules/mod_authentication/templates/_logon_reset_form_fields.tpl, modules/mod_authentication/templates/_logon_reset_support.tpl, modules/mod_authentication/translations/nl.po
This adds an interface on `/logon/change` to change the password of the current user.
=> Add password change for current user

apps/zotonic_core/src/support/z_media_identify.erl, apps/zotonic_filehandler/src/zotonic_filehandler_terminal.erl, apps/zotonic_mod_admin_identity/src/validators/validator_admin_identity_username_unique.erl, apps/zotonic_mod_base/src/validators/validator_base_date.erl, apps/zotonic_mod_base/src/validators/validator_base_email.erl, apps/zotonic_mod_base/src/validators/validator_base_numericality.erl, apps/zotonic_mod_base/src/validators/validator_base_presence.erl, apps/zotonic_mod_search/src/support/search_query.erl, apps/zotonic_mod_survey/src/filters/filter_survey_prepare_thurstone.erl, apps/zotonic_mod_survey/src/questions/survey_q_long_answer.erl, apps/zotonic_mod_survey/src/questions/survey_q_narrative.erl, apps/zotonic_mod_survey/src/questions/survey_q_short_answer.erl
Fix typing issues with trim returning binaries.
=> Dialyzer fixes for trim binary result.

doc/cookbook/custom-controller.rst, doc/cookbook/index.rst, doc/developer-guide/modules.rst
=> Document lib-src

apps/zotonic_core/src/models/m_media.erl, apps/zotonic_mod_acl_user_groups/src/support/acl_user_groups_checks.erl, apps/zotonic_mod_signup/priv/templates/_signup.tpl, apps/zotonic_mod_signup/priv/templates/_signup_config.tpl, apps/zotonic_mod_signup/priv/templates/_signup_form_fields_email.tpl, apps/zotonic_mod_signup/src/mod_signup.erl, apps/zotonic_mod_twitter/src/support/z_twitter_oauth_service.erl, doc/ref/modules/mod_signup.rst
Also add an option mod_signup.depiction_as_medium to add the depiction_url as a medium to the person resource.
=> On signup with twitter, set the name_first and name_surname.

apps/zotonic_core/src/db/z_db_pgsql.erl
This fixes a problem where connections could stay in idle state, within a transaction, if there was a timeout during one of the statements in the transaction.
This problem is solved by hard-closing the connection, which lets the database rollback the transaction.
=> Fix a problem where db connections could stay open after timeouts.

apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_core/src/models/m_identity.erl, apps/zotonic_mod_admin_statistics/priv/templates/admin_statistics.tpl, apps/zotonic_mod_admin_statistics/priv/templates/stat_panel/broker.tpl, apps/zotonic_mod_auth2fa/src/mod_auth2fa.erl, apps/zotonic_mod_authentication/priv/templates/_logon_login_form_fields.tpl, apps/zotonic_mod_authentication/src/controllers/controller_authentication.erl, apps/zotonic_mod_authentication/src/mod_authentication.erl, apps/zotonic_mod_signup/priv/templates/_signup_form_fields_email.tpl, apps/zotonic_mod_signup/priv/templates/_signup_form_fields_username.tpl
Now the query_args in #auth_postcheck is a map.
=> Fixes for 2FA.

apps/zotonic_core/src/models/m_media.erl
Uploading a file with a root name longer than 100 characters would result in an SQL error as the `rootname` column is 100 characters wide.
=> Fix a problem where files could not be uploaded if their rootname was longer than 100 characters.

apps/zotonic_core/src/db/z_db_pgsql.erl
Also make message if busy process down an info message.
=> Cleanup db connection process.

apps/zotonic_core/src/support/z_media_preview.erl, apps/zotonic_core/src/support/z_media_tag.erl
Fix a problem where the 'autoplay' filter could give a runtime error.
=> Fix a problem where the 'autoplay' filter could give a runtime error.

apps/zotonic_mod_authentication/priv/templates/_logon_login_form_fields.tpl, apps/zotonic_mod_authentication/src/controllers/controller_authentication.erl, apps/zotonic_mod_authentication/src/mod_authentication.erl, apps/zotonic_mod_authentication/src/models/m_authentication.erl, doc/cookbook/frontend-signup-logon-form.rst, doc/ref/controllers/controller_authentication.rst, doc/ref/modules/mod_authentication.rst
* Add mod_authentication.is_rememberme config
* Add password field for auto-fill by password managers
* Document authentication configs
=> Add mod_authentication.is_rememberme config.

apps/zotonic_core/src/support/z_media_preview.erl, apps/zotonic_core/src/support/z_media_tag.erl, apps/zotonic_mod_admin/priv/templates/mediaclass.config, doc/developer-guide/media.rst
Fix #1213
Add support srcset for images.
=> Add srcset support from #1213

cloud-init/zotonic-cloudinit.yml, doc/cookbook/admin-user-group.rst, doc/cookbook/justenough-postgres.rst, doc/cookbook/shell-debuggingdatabase.rst, doc/developer-guide/getting-started.rst, doc/developer-guide/sites.rst, doc/ref/configuration/site-configuration.rst, doc/ref/installation/requirements.rst, doc/ref/notifications/notification/rsc_update.rst
=> Update psql version. Fix site config docs.

apps/zotonic_mod_base/src/filters/filter_escape_check.erl, doc/developer-guide/contributing.rst, doc/glossary.rst, doc/ref/filters/escaping/index.rst, doc/ref/filters/filter_escape_check.rst, doc/ref/filters/filter_force_escape.rst
This filter is used for checking html content used in embeds.
=> Add filter escape_check

apps/zotonic_mod_authentication/priv/lib-src/logon.less, apps/zotonic_mod_authentication/priv/lib/css/logon.css
Fix #2793 
The selector in the css file was wrong.
=> The css to show the error messages did not have the right selector

apps/zotonic_mod_survey/priv/templates/_survey_end.tpl, apps/zotonic_mod_survey/priv/templates/_survey_end_edit.tpl, apps/zotonic_mod_survey/priv/templates/_survey_question_page.tpl, apps/zotonic_mod_survey/priv/templates/_survey_start.tpl, apps/zotonic_mod_survey/priv/templates/_survey_start_button.tpl, apps/zotonic_mod_survey/src/mod_survey.erl, apps/zotonic_mod_survey/src/scomps/scomp_survey_poll.erl
Adds an option to open surveys in an overlay.
Needs additional templates from the site to show the survey overlay.
=> Support for opening surveys in an overlay.

apps/zotonic_mod_acl_user_groups/src/support/acl_user_groups_checks.erl
Fix #2814
Added a special check for persons to see if they have overlapping collaboration groups
=> Let users who have overlapping collaboration groups see each other

apps/zotonic_mod_admin/priv/templates/_admin_footer.tpl, apps/zotonic_mod_admin/priv/templates/admin_base.tpl, apps/zotonic_mod_base/priv/templates/_powered_by_zotonic.tpl, apps/zotonic_mod_development/priv/templates/admin_development.tpl, apps/zotonic_mod_translation/priv/templates/_language_attrs.tpl, apps/zotonic_mod_translation/src/filters/filter_language_dir.erl, doc/ref/filters/filter_is_rtl.rst, doc/ref/filters/filter_language.rst, doc/ref/filters/filter_language_dir.rst, doc/ref/filters/translation/index.rst
Better support for RTL languages in the admin.
=> RTL language support support for the admin [part 1 of N]

apps/zotonic_mod_menu/priv/lib/js/jquery.ui.nestedSortable.js
Fix a problem with nestedSortable and the new jQuery ui.
This comes from https://github.com/ilikenwf/nestedSortable/blob/master/jquery.mjs.nestedSortable.js
=> mod_menu: Update nestedSortable for changes in jquery ui.

apps/zotonic_core/src/db/z_db.erl
=> Use map to log error

apps/zotonic_core/src/support/z_cowmachine_middleware.erl, apps/zotonic_listen_http/src/zotonic_listen_http.erl, apps/zotonic_listen_http/src/zotonic_listen_http_metrics.erl
- Added the session-id to the http log
- Filter response and request headers.
=> Add the session-id to the http log

apps/zotonic_mod_seo_sitemap/src/mod_seo_sitemap.erl
Fixes #2897
Changes from 0.x #2894
=> mod_seo_sitemap: add seo site map rebuild notification.

apps/zotonic_mod_backup/priv/templates/admin_backup.tpl, apps/zotonic_mod_backup/src/mod_backup.erl, apps/zotonic_mod_backup/src/models/m_backup.erl
=> mod_backup: show backup directory on admin backup page.

apps/zotonic_mod_survey/priv/templates/blocks/_admin_edit_block_li_survey_thurstone.tpl, apps/zotonic_mod_survey/src/models/m_survey.erl, apps/zotonic_mod_survey/src/support/survey_answer_prep.erl
Also use maps instead of proplists.
=> mod_survey: normalize answers in survey_prep_readable.

apps/zotonic_mod_admin_identity/priv/templates/_identity_verify_table.tpl
=> Fix typo 'Verfied'

apps/zotonic_core/priv/translations/zotonic.pot, apps/zotonic_mod_backup/src/controllers/controller_admin_backup.erl
=> Fix typo 'mudule'

apps/zotonic_mod_import_wordpress/priv/templates/_admin_status.tpl, apps/zotonic_mod_import_wordpress/priv/templates/_dialog_import_wordpress.tpl, apps/zotonic_mod_import_wordpress/src/mod_import_wordpress.erl, apps/zotonic_mod_import_wordpress/src/support/import_wordpress.erl, doc/developer-guide/releasenotes/rel_0.07.0.rst, doc/ref/modules/mod_import_wordpress.rst
Start use/fix camel style for `WordPress`.
**N/A**
=> Start use/fix camel style for WordPress

apps/zotonic_core/src/support/z_sites_dispatcher.erl
If the a request for a `hostalias` is received then we redirect to the main `hostname`.
This is done by requesting the absolute URL for the original request path.
If thus path starts with `//` then the `z_context:abs_url/2` routine just prepends `https:`
If the original request was something like `https://foo.bar//example.com` then the server
would redirect to `https://example.com`.
This patch fixes this by removing superfluous slashes in front of the path.
=> core: fix an issue with redirecting to main site if path starts with two slashes

apps/zotonic_mod_base/src/controllers/controller_template.erl
This removes the functionality that controller_template checks the query args for an id.
An optional resource id is now only fetched from the dispatch options.
Fix #2958
=> Let controller_template only check for an id in the dispatch options

apps/zotonic_core/src/support/z_sanitize.erl, apps/zotonic_core/test/z_sanitize_tests.erl, apps/zotonic_mod_video_embed/src/mod_video_embed.erl
This adds the `sandbox` attribute to iframes.
=> Let the sanitizer add a sandbox parameter to iframes.

apps/zotonic_core/src/support/z_pivot_rsc_job.erl
This fixes an issue where the pivot_title, as used for sorting, is in a random language.
As we have only a single pivot_title field, it is best to use the default language for setting that field.
(Least surprises)
=> core: ensure that the default language is used for the pivot title.

apps/zotonic_launcher/bin/zotonic
Fix #2971
An improved version of the completion proposal for the `bin/zotonic` command.
@mworrell could you check if it works on your Mac?
=> Fix #2971 Script completion proposal

apps/zotonic_launcher/bin/zotonic
Added BSD to bin/zotonic launcher
=> add BSD to bin/zotonic launcher

apps/zotonic_core/src/zotonic_core_sup.erl
This removes, on startup, a log entry per site with the site's status.
The status changes are already logged by the site supervisor, so this is not needed.
=> zotonic_core: remove delayed site status logging.

apps/zotonic_mod_admin/priv/dispatch/dispatch, apps/zotonic_mod_admin/priv/templates/_admin_js_include.tpl, apps/zotonic_mod_admin/priv/templates/_admin_menu.tpl, apps/zotonic_mod_admin/priv/templates/admin_base.tpl, apps/zotonic_mod_search/priv/lib-src/zotonic-search-view-admin/Makefile, apps/zotonic_mod_search/priv/lib-src/zotonic-search-view-admin/less/base.less, apps/zotonic_mod_search/priv/lib-src/zotonic-search-view-admin/less/zotonic-search-view-admin.less, apps/zotonic_mod_search/priv/lib-src/zotonic-search-view/Makefile, apps/zotonic_mod_search/priv/lib-src/zotonic-search-view/less/base.less, apps/zotonic_mod_search/priv/lib-src/zotonic-search-view/less/zotonic-search-view.less, apps/zotonic_mod_search/priv/lib/css/zotonic-search-view-admin.css, apps/zotonic_mod_search/priv/lib/css/zotonic-search-view.css, apps/zotonic_mod_search/priv/lib/js/zotonic-search-view.js, apps/zotonic_mod_search/priv/templates/_search_view_list_item.media.tpl, apps/zotonic_mod_search/priv/templates/_search_view_list_item.tpl, apps/zotonic_mod_search/priv/templates/search_view.tpl
Quick search view implementation
=> Search view

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/other_issues.md
=> Add issues templates

apps/zotonic_mod_search/priv/templates/_search_view_list_item.tpl
=> mod_search: add depiction to the quick search results.

modules/mod_base/filters/filter_add_month.erl, src/support/z_datetime.erl
=> core: add z_datetime:next_month/2 and z_datetime:prev_month/2. (0.x)

apps/zotonic_mod_admin_identity/src/validators/validator_admin_identity_username_unique.erl, doc/ref/validators/validator_username_unique.rst
Fix #3020
Updated the documentation, and made the code a little bit more readable so you can easily see what argument is checked.
=> Fix username_unique documentation

apps/zotonic_mod_admin/priv/templates/_admin_edit_blocks.tpl, apps/zotonic_mod_admin/priv/templates/_rsc_block_item.tpl, apps/zotonic_mod_admin/priv/templates/blocks/_admin_edit_block_li_page.tpl
Add a disconnect button to remove the connection in a page block.
=> mod_admin: Add disconnect btn for page blocks

apps/zotonic_mod_admin/priv/templates/_admin_sort_header.tpl
=> mod_admin: Fix a problem where the pagelen was reset if the sort was changed

apps/zotonic_mod_base/src/support/z_list_of_ids_filter.erl
Fix the spec of these functions. The spec was not matching the use and the functions.
=> mod_base: fix spec of z_list_of_ids_filter:filter functions.

apps/zotonic_core/src/models/m_identity.erl
Also stricter access permission checks for identity queries.
Only administrators are now allowed to perform such queries.
This filters all _prop_ and verify keys from the identities.
=> core: filter identities returned via the m.identity api.

modules/mod_admin_identity/templates/_action_dialog_delete_username.tpl, modules/mod_admin_identity/templates/_action_dialog_set_username_password.tpl, modules/mod_admin_identity/templates/_admin_edit_basics_user.tpl, modules/mod_admin_identity/templates/_identity_password.tpl, modules/mod_admin_identity/templates/admin_users.tpl, modules/mod_admin_identity/translations/es.po, modules/mod_admin_identity/translations/et.po, modules/mod_admin_identity/translations/nl.po, modules/mod_admin_identity/translations/pl.po, modules/mod_admin_identity/translations/ru.po, modules/mod_admin_identity/translations/tr.po, modules/mod_admin_identity/translations/zh.po, modules/mod_auth2fa/templates/_admin_user_info.tpl
Also add 'delete username' to the change-password dialog.
=> mod_admin_identity: show 2FA status on user overview page.

apps/zotonic_core/priv/translations/zotonic.pot, apps/zotonic_mod_microsoft/priv/templates/_admin_authentication_service.tpl, apps/zotonic_mod_microsoft/src/mod_microsoft.erl
This fixes a problem where it was unclear which scopes should be added.
Also a possible problem with how Azure checks the scopes against the `/me` API.
=> mod_microsoft: change default scope, add comments.

apps/zotonic_core/src/db/z_db.erl, apps/zotonic_mod_search/priv/templates/pivot/facet.tpl, apps/zotonic_mod_search/src/support/search_facet.erl
This adds support for lists of terms or ids in the search facets.
=> mod_search: add array support to the search facets

modules/mod_menu/lib/js/jquery.ui.nestedSortable.js
Fix #3131
This fixes a problem with the newer jQuery code where the drag&drop in the menu editor stopped working.
=> mod_menu: update nestedSortable.js

apps/zotonic_core/src/support/z_fetch.erl, apps/zotonic_mod_base/src/validators/validator_base_format.erl, apps/zotonic_mod_oauth2/priv/lib/js/zotonic.oauth.worker.js, apps/zotonic_mod_oauth2/priv/templates/admin_oauth2_consumers.tpl, apps/zotonic_mod_oauth2/src/models/m_oauth2_consumer.erl, apps/zotonic_mod_survey/priv/templates/blocks/_admin_edit_block_li_survey_thurstone.tpl
Also small fixes in oauth worker, format validator and survey thurstone editing.
Add an option {authorization, none} to disable authorization on z_fetch requests.
=> mod_oauth2: fixes for fetching new certificates.

apps/zotonic_core/src/support/z_datamodel.erl, apps/zotonic_mod_base/priv/templates/pivot/_main_text.tpl
Also fix an issue where the pivot did not index text of blocks.
=> Schema medium import

apps/zotonic_mod_facebook/priv/templates/_html_head_facebook.tpl, apps/zotonic_mod_seo/priv/templates/_html_head_seo.tpl, apps/zotonic_mod_twitter/priv/templates/_html_head_twitter.tpl
Show longer descriptions for the meta description tag.
Also set noindex for search result pages past the first page.
Do let the crawler index all search result pages.
=> mod_seo: longer seo descriptions, noindex for q.page > 1

apps/zotonic_mod_search/src/support/search_query.erl
This fixes a problem where it was not possible to search for example `nl` OR `en`.
=> mod_search: support OR query for language search term

apps/zotonic_core/src/support/z_search.erl
This fixes a problem where passing `undefined` for the page length crashed the search.
=> core: in search, allow pagelen to be undefined. Fixes #3171

apps/zotonic_core/src/support/z_path.erl
This fixes a problem with non-umbrella setups where the "site update" would not work because the app src directory could not be found.
=> core: find site path for setup without umbrella apps

apps/zotonic_mod_base/src/filters/filter_toc.erl
The rest of the opening `h`-tag was not skipped, leaving a '>' in front of all header links.
=> mod_base: fix a problem with filter toc where a '>' was shown before the texts

apps/zotonic_mod_base/priv/templates/tests/initial_postback_test.tpl
It needed the auth notification before the postback can be made.
=> mod_base: fix postback test

apps/zotonic_mod_survey/src/mod_survey.erl
=> mod_survey: set answer_user_id to user if not editing existing answer

apps/zotonic_mod_admin/priv/templates/_admin_menu.tpl, apps/zotonic_mod_search/priv/lib-src/zotonic-search-view-admin/less/base.less, apps/zotonic_mod_search/priv/lib-src/zotonic-search-view/less/base.less, apps/zotonic_mod_search/priv/lib/css/zotonic-search-view-admin.css, apps/zotonic_mod_search/priv/lib/css/zotonic-search-view.css, apps/zotonic_mod_search/priv/lib/js/zotonic-search-view.js
Search view JS now listens to a `data-attribute` so it's a choice to use the search view
- Cleanup css a bit
=> [Search] Refactor search view

.github/workflows/docs.yml, modules/mod_cookie_consent/lib/css/cookie_consent.css, modules/mod_cookie_consent/lib/css/cookie_consent.scss, modules/mod_cookie_consent/lib/images/arrow-down-thick.svg
Direction of arrow for more options.
Prevent wrap of some text.
=> mod_cookie_consent: cosmetic changes

src/models/m_search.erl, src/support/z_search.erl
Also ensure that next is set for queries with a Limit < PageLen.
=> Fix an issue where the next was not set in m_search_result

modules/mod_cookie_consent/lib/css/cookie_consent.css, modules/mod_cookie_consent/lib/css/cookie_consent.scss
Small fixes for cookie consent banner on small screens.
=> mod_cookie_consent: small css changes

apps/zotonic_core/src/models/m_search.erl
Fix an issue where pagelen was set to page for certain queries.
=> core: fix paging in m_search with payload

apps/zotonic_mod_search/src/support/search_query.erl
=> mod_search: fix a problem with joining search_facet table

apps/zotonic_mod_mailinglist/priv/templates/_scomp_mailinglist_subscribe.tpl, apps/zotonic_mod_mailinglist/src/scomps/scomp_mailinglist_mailinglist_subscribe.erl
Make the element-id's unique for every form
Fix #3221
=> mod_mailinglist: allow multiple mailinglists subscribe forms on one page

modules/mod_admin_modules/templates/admin_modules.tpl, src/models/m_modules.erl, src/support/z_module_manager.erl
Try to show the version of modules in the admin/modules overview.
=> mod_admin_modules: show the version of modules in the admin/modules (0.x)

apps/zotonic_core/src/support/z_render.erl, apps/zotonic_mod_backup/priv/templates/admin_backup_revision.tpl
Fix a problem where the revision diff was not displayed correctly.
=> mod_backup: fix revision diff view

include/zotonic_notifications.hrl, modules/mod_authentication/templates/_logon_modal.tpl, modules/mod_signup/controllers/controller_signup.erl, modules/mod_signup/controllers/controller_signup_confirm.erl, modules/mod_signup/templates/_signup_form.tpl
Add option to redirect to a specific page, defined in the signup, after signup confirm.
=> Signup confirm redirect (0.x)

apps/zotonic_mod_translation/priv/templates/_html_head_translation.tpl
The title attribute is not needed and can be removed.
=> mod_translation: remove title attribute from hreflang link tags

apps/zotonic_core/src/support/z_module_manager.erl
=> core: after module schema error, flush caches

nix/nixpkgs.nix, shell.nix
This is the 0.x version of https://github.com/zotonic/zotonic/pull/3253.
=> Manage system dependencies with Nix (0.x version)

apps/zotonic_core/src/csv/z_csv_parser.erl, apps/zotonic_core/src/csv/z_csv_writer.erl
=> core: use type file:filename_all in z_csv_writer

modules/mod_admin/mod_admin.erl, modules/mod_admin/templates/_action_dialog_connect_tab_find.tpl, modules/mod_base/lib/js/apps/zotonic-1.0.js
Fix #3267
Fixes for:
- In admin dialog connect dialog the connections can not be toggled
- In the admin upload, if the 'is_published' is unchecked then it is not posted
- The 'mine' filter in the admin connect dialog does not work
=> mod_admin: misc fixes for the connect/disconnect dialog (0.x)

apps/zotonic_mod_admin/priv/templates/_action_dialog_connect_tab_find.tpl, apps/zotonic_mod_admin/src/mod_admin.erl, apps/zotonic_mod_wires/priv/lib/js/apps/zotonic-wired.js
Fix #3267
Fixes for:
- In admin dialog connect dialog the connections can not be toggled
- In the admin upload, if the 'is_published' is unchecked then it is not posted
- The 'mine' filter in the admin connect dialog does not work
=> mod_admin: misc fixes for the connect/disconnect dialog

apps/zotonic_mod_admin/priv/templates/_action_dialog_connect.tpl, apps/zotonic_mod_admin/priv/templates/_admin_edit_content_page_connections.tpl, apps/zotonic_mod_admin/priv/templates/_admin_edit_content_page_connections_list.tpl
=> Add nocatselect to the dialog

apps/zotonic_mod_admin/priv/lib/js/apps/admin-common.js, apps/zotonic_mod_admin/priv/templates/_action_dialog_connect.tpl, apps/zotonic_mod_admin/priv/templates/_action_dialog_media_upload_tab_upload.tpl, apps/zotonic_mod_admin/src/mod_admin.erl, apps/zotonic_mod_editor_tinymce/priv/lib/js/tinymce-5.10.2/tinymce/plugins/zmedia/plugin.min.js
Better support for zmedia insert without subject_id
=> mod_admin: in zmedia show documents as small

apps/zotonic_mod_admin/priv/templates/_action_dialog_edit_basics.tpl, apps/zotonic_mod_image_edit/priv/lib-src/css/image-edit.scss, apps/zotonic_mod_image_edit/priv/lib/css/image-edit.css
Also force bg color of image editor to (almost) black.
=> mod_admin: in quick edit, also show 'Visit full edit page' on use.mod_admin_frontend rights

apps/zotonic_mod_mailinglist/src/mod_mailinglist.erl, apps/zotonic_mod_survey/src/support/survey_admin.erl
In `mod_mailinglist` add an ACL check for allowing to add or remove subscriber edges to mailinglists.
A subscriber edge can be added if:
- The person (subscriber) is visible
- The mailinglist is editable
- The current user has `use` permission on `mod_mailinglist`
=> mod_mailinglist: add acl check for adding mailing subscriber edges

apps/zotonic_mod_admin/priv/templates/_action_dialog_edit_basics.tpl, apps/zotonic_mod_admin/priv/templates/_admin_edit_content_page_connections.tpl, apps/zotonic_mod_admin/priv/templates/_admin_edit_content_page_connections_list.tpl, apps/zotonic_mod_image_edit/priv/lib-src/css/image-edit.scss, apps/zotonic_mod_image_edit/priv/lib/css/image-edit.css, apps/zotonic_mod_image_edit/priv/templates/_overlay_image_edit.tpl
- Refactor dialog to overlay for better use of tools
- Add some blocks so on site level you can choose which settings you want to use
- Tweak the css a bit so its not like you are completely gone from the page
=> mod_image_edit: use overlay instead of dialog

apps/zotonic_mod_mailinglist/src/support/z_mailinglist_recipients.erl
Fix #3300 
Ignore mailinglist queries that contain errors.
=> mod_mailinglist: fix an issue where sending a mailing gives a 500 error if any mailinglist contains an illegal query.

apps/zotonic_mod_cookie_consent/priv/lib/js/z.cookie_consent.js
=> Make mod_cookie_consent selector slightly more general (PR #3308)

apps/zotonic_core/src/support/z_fetch.erl
This fixes an issue where it was not possible to send body content other than x-www-form-urlencoded.
=> Add option to set the content_type of z_fetch requests

apps/zotonic_core/src/support/z_fetch.erl
=> core: fix type for z_fetch to allow extra methods of z_url_fetch

doc/developer-guide/releasenotes/rel_0.75.0.rst
=> doc: add 0.75.0 release notes

apps/zotonic_core/include/zotonic_notifications.hrl, apps/zotonic_core/src/support/z_dropbox.erl, apps/zotonic_mod_admin/priv/templates/admin_status.tpl, apps/zotonic_mod_admin/src/mod_admin.erl, apps/zotonic_mod_mailinglist/src/mod_mailinglist.erl
This adds a panel to the status site where a file can be uploaded to the dropbox.
Fixes some binary/list issues in the dropbox and mailinglist routines.
=> mod_admin: add panel to upload dropbox files

apps/zotonic_mod_base/priv/lib/js/modules/z.listfilter.js
Usage:
```javascript
<input class="form-control do_listfilter"
id="country_filter"
type="search"
value=""
autofocus
placeholder="{_ Find country _}"
data-listfilter="list: '.countries__names', sort: true"
>
```
The div with class `countries__names` must be present as a child element of the containing form.
=> mod_base: add option to listfilter for sorting the filtered list

apps/zotonic_mod_logging/src/mod_logging.erl
This makes the db pool load less verbal in the database log.
The load can seem high on slow databases, but can also be an indication of slow queries or high query load so logging the message is important.
=> mod_logging: be less verbal about db pool load

shell.nix
Fix #[3318] for nix environment
=> Update Nix erlang version

apps/zotonic_core/src/models/m_identity.erl, apps/zotonic_mod_admin_identity/priv/templates/email_identity_verify.tpl, apps/zotonic_mod_admin_identity/priv/templates/identity_verify.tpl, apps/zotonic_mod_signup/priv/templates/email_verify.tpl
Better identity error handling of eexist error
Cleanup some identity templates
=> core: better identity error handling of eexist error

apps/zotonic_mod_admin_identity/src/mod_admin_identity.erl
This allows the user to directly send a confirm email for their primary email address.
=> mod_admin_identity: option to verify the primary email address

apps/zotonic_mod_survey/priv/templates/_admin_block_thurstone_answer.tpl, apps/zotonic_mod_survey/priv/templates/blocks/_admin_edit_block_li_survey_thurstone.tpl, apps/zotonic_mod_survey/priv/templates/blocks/_block_view_survey_thurstone.tpl
Fix a problem where the last prompt of a thurston question could be lost if the survey was edited.
Also fix a problem where a closing tag was missing in the view template of thurstone questions.
=> mod_survey: fix thurstone edit template

apps/zotonic_core/src/models/m_rsc_export.erl
=> core: add 'page_url' to the rsc_export model api

apps/zotonic_core/src/models/m_rsc_update.erl, apps/zotonic_mod_mailinglist/priv/templates/email_mailinglist_goodbye.tpl, apps/zotonic_mod_mailinglist/priv/templates/mailinglist_subscriptions.tpl, apps/zotonic_mod_mailinglist/priv/templates/mailinglist_unsubscribe.tpl, apps/zotonic_mod_mailinglist/src/filters/filter_mailinglist_recipient_key_decode.erl, apps/zotonic_mod_mailinglist/src/mod_mailinglist.erl, apps/zotonic_mod_mailinglist/src/models/m_mailinglist.erl, apps/zotonic_mod_mailinglist/src/support/z_mailinglist_recipients.erl
This fixes an issue where people were not able to unsubscribe using the link the mailing footer.
=> mod_mailinglist: rework the mailinglist unsubscribe flow

apps/zotonic_mod_admin_frontend/priv/templates/_admin_frontend_edit.tpl
Add block around title, so it can be overwritten.
=> [admin_frontend_edit] Add block around titlte

modules/mod_oembed/support/oembed_client.erl, modules/mod_oembed/support/oembed_providers.erl, src/support/z_sanitize.erl
Add OEmbed support for spotify.
=> mod_oembed: add oembed support for spotify (0.x)

apps/zotonic_core/src/support/z_mediaclass.erl
Validate mediaclasses have simple names.
This fixes a problem where invalid URLs for the file storage could be generated.
=> core: validate mediaclass names

apps/zotonic_core/src/support/z_media_preview.erl
This makes it possible to reference files in the site using image magick options:
```
{magick, " -gravity SouthEast priv/lib/images/logo-watermark.png -composite"}
```
=> core: cd to the site dir before doing a convert call

.github/workflows/test.yml, apps/zotonic_site_testsandbox/test/testsandbox_basic_tests.erl
=> OTP-26 compat

apps/zotonic_mod_admin/priv/templates/_admin_edit_main_parts.tpl, apps/zotonic_mod_mailinglist/priv/templates/_admin_edit_content_extra.tpl
This makes it easy to unsubscribe someone by email address and/or connections.
=> mod_mailinglist: add admin-content-extra template showing mailinglist subscriptions

apps/zotonic_mod_survey/priv/templates/_admin_block_test_feedback.tpl, apps/zotonic_mod_survey/priv/templates/_admin_block_thurstone_answer.tpl
Refactor input text fields for feedback to textarea for easier writing of feedback.
=> [Survey] refactor to textarea for easier writing of feedback

apps/zotonic_core/src/models/m_rsc_update.erl
On an update with arguments:
```
#{ <<"is_published">> => true }
```
the `publication_start` property would be overwritten with the current date and time.
=> Fix a problem where publication_start could be overwritten when is_published is updated

apps/zotonic_core/src/models/m_media.erl
Adds a `post` and `delete` API for the media model.
You can post a `file` or an `url` together with an optional map with `rsc` properties.
=> core: add post and delete API on media model

apps/zotonic_mod_seo/src/support/seo_jsonld_webpage.erl
Restructure according to Google's example at https://developers.google.com/search/docs/appearance/structured-data/breadcrumb
=> Breadcrumb item

apps/zotonic_core/src/models/m_rdf.erl, apps/zotonic_mod_seo/src/support/seo_jsonld_webpage.erl
This fixes:
* a problem where the site's title wasn't displayed; and
* a problem where the items category wasn't properly derived.
=> mod_seo: fix a problem with displaying the site title and deriving the best schema type

apps/zotonic_mod_admin_identity/priv/templates/_search_view.tpl, apps/zotonic_mod_search/priv/lib-src/zotonic-search-view-admin/less/base.less, apps/zotonic_mod_search/priv/lib-src/zotonic-search-view/less/base.less, apps/zotonic_mod_search/priv/lib/css/zotonic-search-view-admin.css, apps/zotonic_mod_search/priv/lib/css/zotonic-search-view.css, apps/zotonic_mod_search/priv/templates/search_view.tpl
Fixes an issue where it was not possible to do a quick search using the email address of a resource.
=> mod_search: add identity search to quick admin search

apps/zotonic_mod_base/src/controllers/controller_page.erl
This fixes a problem where a request like `/page/12/hallo?a=1` always redirects to `/page/12/hallo`
This also means that we have a less restrictive 'redirect to canonical' for resources.
=> zotonic_core: allow request args for canonical page urls

apps/zotonic_core/src/support/z_datamodel.erl
This allows a datamodel install to continue on errors like duplicate paths.
=> core: report & ignore datamodel install errors

apps/zotonic_mod_admin/priv/templates/_action_dialog_connect_tab_find_results.tpl, apps/zotonic_mod_survey/priv/templates/_admin_survey_question_q.tpl
This fixes an issue where in the admin interface we can search directly on id or name, but not in the connect dialog
=> mod_admin: in connect, if search text matches rsc id, show that id

apps/zotonic_core/src/support/z_site_startup.erl, apps/zotonic_filehandler/src/zotonic_filehandler_mappers.erl
* Taskfile should be `Taskfile.yml`
* Use upsert for module enable SQL
=> core: fix taskfile name; better module update function

apps/zotonic_mod_admin/priv/templates/_action_dialog_connect_tab_find_results.tpl, apps/zotonic_mod_admin/priv/templates/_admin_overview_list.tpl
Change the copy of the search results when finding the exact unique page.
=> mod_admin: Change copy

apps/zotonic_core/src/smtp/z_email_server.erl
This fixes an issue with some smtp relays, where the relay gives a permanent error when a temporary error was more appropriate.
Fix #3508
=> core: work around an issue with some email relays

apps/zotonic_mod_seo/priv/templates/admin_seo.tpl, apps/zotonic_mod_seo/src/controllers/controller_admin_seo.erl, apps/zotonic_mod_seo/src/support/seo_jsonld_webpage.erl
Adds better support for:
* Site organization
* Site description
* Search action (including config via /admin/seo
=> mod_seo: additions to generated JSON-LD

apps/zotonic_core/src/models/m_rdf.erl, apps/zotonic_mod_seo/src/support/seo_jsonld_webpage.erl
Google doesn't seem to be able to handle multiple languages.
Show the 'about' summary in a single language.
=> mod_seo: show 'about' in a single language

apps/zotonic_core/src/models/m_rdf.erl, apps/zotonic_mod_seo/src/support/seo_jsonld_webpage.erl
Try not repeating the primary image in the generated JSON-LD.
Also use the content language for the inLanguage of the language specific summary.
=> mod_seo: in json-ld tune handling of webpage primary image

apps/zotonic_mod_base/priv/lib/misc/robots.txt, apps/zotonic_mod_translation/src/controllers/controller_language_set.erl
Update the robots.txt to exclude the admin and language select/switch URLs.
Also make the language switch redirect a permanent redirect.
=> base: update robots.txt

apps/zotonic_mod_image_edit/priv/lib-src/css/image-edit.scss, apps/zotonic_mod_image_edit/priv/lib/css/image-edit.css, apps/zotonic_mod_image_edit/priv/templates/_overlay_image_edit.tpl
Remove alert, this was activated during each screen resize... 
And some css tweaks
=> Remove alert in image editor, and some css tweaks

apps/zotonic_mod_base/src/filters/filter_append.erl, apps/zotonic_mod_base/src/filters/filter_capfirst.erl, apps/zotonic_mod_base/src/filters/filter_truncate.erl, apps/zotonic_mod_base/src/filters/filter_truncate_html.erl, apps/zotonic_mod_base/src/filters/filter_truncatechars.erl, apps/zotonic_mod_base/src/filters/filter_unescape.erl, apps/zotonic_mod_base/src/filters/filter_upper.erl, apps/zotonic_mod_base/src/filters/filter_url.erl, apps/zotonic_mod_base/src/filters/filter_url_abs.erl, apps/zotonic_mod_base/src/filters/filter_urldecode.erl, apps/zotonic_mod_base/src/filters/filter_urlize.erl, apps/zotonic_mod_base/src/filters/filter_utc.erl, apps/zotonic_mod_base/src/filters/filter_vsplit_in.erl, apps/zotonic_mod_base/src/filters/filter_without.erl, apps/zotonic_mod_base/src/filters/filter_without_embedded_media.erl, apps/zotonic_mod_base/src/filters/filter_yesno.erl, apps/zotonic_mod_base/test/base_filter_tests.erl, doc/ref/filters/filter_truncate.rst, doc/ref/filters/filter_truncate_html.rst, doc/ref/filters/filter_truncatechars.rst, doc/ref/filters/strings/index.rst
Add filter `truncatechars`
Also update some other filters with copyright and `#trans{}`
=> mod_base: add filter truncatechars

apps/zotonic_core/src/models/m_identity.erl
Add function to ensure an user has a specific username.
=> core: add m_identity:ensure_username_pw/3

apps/zotonic_core/src/install/z_install_data.erl, apps/zotonic_core/src/models/m_predicate.erl, apps/zotonic_mod_admin/priv/templates/_action_dialog_connect_tab_find.tpl, apps/zotonic_mod_admin/priv/templates/_admin_js_include.tpl, apps/zotonic_mod_admin_predicate/priv/templates/_admin_edit_content.predicate.tpl, apps/zotonic_mod_base/priv/lib/js/modules/z.listfilter.js
Adds the option `is_connect_checkbox` to predicates.
When checked the connect dialog for this predicate will display possible objects in a checklist.
=> mod_admin: add predicate option to connect pages using a checkbox list

apps/zotonic_core/src/models/m_rsc_update.erl, apps/zotonic_mod_seo/priv/templates/_html_head_seo.tpl
Add extra SEO tags: `og:type`, `og:locale` and `og:updated_time`
The updated time is set to the modification date of the page.
=> mod_seo: add og:type and og:updated_time

apps/zotonic_mod_admin/priv/templates/_action_dialog_connect_tab_find.tpl, apps/zotonic_mod_admin/priv/templates/_action_dialog_connect_tab_find_results_item.tpl, apps/zotonic_mod_admin/priv/templates/_action_dialog_delete_rsc.tpl, apps/zotonic_mod_admin/priv/templates/_action_dialog_duplicate_rsc.tpl, apps/zotonic_mod_admin/priv/templates/_action_dialog_new_rsc_tab_find_results_item.tpl, apps/zotonic_mod_admin/priv/templates/_action_unlink_undo.tpl, apps/zotonic_mod_admin/priv/templates/_admin_edit_header.tpl, apps/zotonic_mod_admin/priv/templates/_admin_overview_list.tpl, apps/zotonic_mod_admin/priv/templates/_rsc_edge.tpl, apps/zotonic_mod_admin/priv/templates/_rsc_edge_item.tpl, apps/zotonic_mod_admin/priv/templates/_rsc_edge_media.tpl, apps/zotonic_mod_admin/priv/templates/_rsc_item.tpl, apps/zotonic_mod_admin/priv/templates/_rsc_preview.tpl, apps/zotonic_mod_admin/priv/templates/admin_edit.tpl, apps/zotonic_mod_admin/priv/templates/admin_media.tpl, apps/zotonic_mod_admin/priv/templates/admin_widget_dashboard_latest.tpl
Fix #3536 
Show the short title of pages if the title is not defined.
=> mod_admin: show short_title if title is not defined.

apps/zotonic_core/src/support/z.erl, apps/zotonic_core/src/support/z_exec_browser.erl, apps/zotonic_launcher/src/command/zotonic_cmd_chrome.erl, apps/zotonic_launcher/src/command/zotonic_cmd_chromium.erl, apps/zotonic_mod_development/src/mod_development.erl, apps/zotonic_mod_development/src/support/z_development_template_graph.erl
Adds:
* z:open/1
* z:open_secure/1
This opens a site in the Chrome browser.
Also make the "root" node in mod_development live tracing a hexagon.
=> core: move exec chrome / chromium to the core, add z:open/1 function

apps/zotonic_site_status/priv/lib-src/css/Makefile, apps/zotonic_site_status/priv/lib-src/css/zotonic-status.scss, apps/zotonic_site_status/priv/lib/css/zotonic-status.css
Refactor less to sass, remove 3L
=> mod_zotonic_status: refactor less to scss, remove 3l

apps/zotonic_mod_authentication/priv/lib-src/Makefile, apps/zotonic_mod_authentication/priv/lib-src/logon.scss, apps/zotonic_mod_authentication/priv/lib/css/logon.css
=> mod_zotonic_authentication: refactor less to sass

.github/workflows/docs.yml
Fix a problem with the Python version during docs build
=> Fix build of 0.x docs

src/support/z_sites_dispatcher.erl
=> Fix an issue with redirecting from hostalias to hostname

apps/zotonic_mod_oauth2/test/oauth2_tests.erl
=> mod_oauth2: add longer timeout to enunit test

apps/zotonic_core/src/support/z_datamodel.erl
If on datamodel install a resource was present, but the medium is not present, then insert the medium.
=> Core: on datamodel update insert medium if rsc present but medium absent

apps/zotonic_mod_base/src/filters/filter_is_a.erl, apps/zotonic_mod_base/src/filters/filter_is_not_a.erl, apps/zotonic_mod_base/test/base_filter_tests.erl
=> mod_base: ensure filter is_a on atom returns boolean

apps/zotonic_core/src/models/m_rsc_update.erl
This fixes an issue where the publication start was only set if the `is_published` flag changed to `true`.
If the `is_published` flag was already true, then it was possible to pass an undefined publication_start date. This could happen if:
* Edit a new unpublished page
* Check is_published
* Save the edit form, do not leave the edit page
* Edit the edit form again
* Save again
Now the `publication_start` date would be undefined.
This changes fixes this by checking that if a resource is published, that is also must have a publication start date.
=> core: ensure that publicaion_start date is set if a resource is published

apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/less/connections.less, apps/zotonic_mod_admin/priv/lib/css/zotonic-admin.css, apps/zotonic_mod_admin/priv/templates/_action_dialog_connect_tab_find.tpl
This fixes some layout issues with a mix of long and short keywords in the connection lists.
=> mod_admin: better css for keyword connect - add close button

apps/zotonic_mod_search/src/support/search_query.erl
=> mod_search: also filter empty searches with <<>> values

apps/zotonic_mod_logging/priv/templates/admin_log_email.tpl, apps/zotonic_mod_logging/src/models/m_log.erl, apps/zotonic_mod_logging/src/models/m_log_email.erl, apps/zotonic_mod_logging/src/models/m_log_ui.erl
Make the log search compatible with the new search format.
=> mod_logging: fix search for the new search format

apps/zotonic_core/src/support/z_sanitize.erl, apps/zotonic_mod_base/priv/lib/js/modules/z.clickable.js, apps/zotonic_mod_base/src/filters/filter_show_media.erl, apps/zotonic_mod_editor_tinymce/priv/lib/js/tinymce-5.10.2/tinymce/plugins/zmedia/plugin.min.js, apps/zotonic_mod_editor_tinymce/priv/templates/_tinymce_dialog_zmedia_props.tpl
Add option to open tinymce media in a new window.
=> mod_editor_tinymce: add 'link_new' option to embedded media.

apps/zotonic_mod_admin/priv/templates/_admin_edit_basics.tpl, apps/zotonic_mod_admin/src/models/m_admin_status.erl, apps/zotonic_mod_translation/priv/templates/_translation_edit_languages.tpl, apps/zotonic_mod_translation/priv/templates/_translation_status.tpl
This adds a property `translation_status` that contains:
- `1` if the translation needs review because it was automatically generated;
-  `0` or empty if no review needed
=> mod_translation: Show note if a translation is automatically generated.

apps/zotonic_filehandler/src/zotonic_filehandler_terminal.erl, apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/less/bootstrap-overrides.less, apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/less/dialog-new-connect.less, apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/less/edit.less, apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/less/image.less, apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/less/table.less, apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/less/thumbnails.less, apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/less/widget.less, apps/zotonic_mod_admin/priv/lib/css/zotonic-admin.css
Now it compiles without any warnings about inlined javascript.
=> mod_admin: remove some #3L usage in lessc files

apps/zotonic_mod_base/priv/templates/email_base.tpl
Exactly what the title says. Change default color to white.
=> Make default color white for emails

apps/zotonic_core/src/models/m_rsc_import.erl, apps/zotonic_core/src/support/z_media_import.erl, apps/zotonic_mod_image_edit/src/mod_image_edit.erl
Fix #3669
Also fix a problem with updating medium items using an external rsc page uri.
=> core: fix a problem where copying between servers the image edit settings were not copied

apps/zotonic_core/src/db/z_db.erl, apps/zotonic_core/src/support/z_search.erl, apps/zotonic_core/src/support/z_template_compiler_runtime.erl, apps/zotonic_mod_admin/priv/templates/_admin_edit_content_advanced.tpl, apps/zotonic_mod_search/src/mod_search.erl, apps/zotonic_mod_search/src/models/m_search_status.erl, apps/zotonic_mod_search/src/support/search_facet.erl, apps/zotonic_mod_search/src/support/search_query.erl, doc/ref/models/model_search_status.rst
* Let ft facet search for words.
* Allow search_query_term notification to map to query term maps.
* Fix an issue with facet template mappings for categories.
=> mod_search: facet and query term improvements

apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/scss/_thumbnails.scss, apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/scss/_tree-list.scss, apps/zotonic_mod_admin/priv/lib/css/zotonic-admin.css, apps/zotonic_mod_admin/priv/templates/_action_dialog_connect_tab_find_results_item.tpl, apps/zotonic_mod_admin/priv/templates/_action_dialog_new_rsc_tab_find_results_item.tpl
The category flag wasn't working well with the longer title thumbnails, so moved it back and fixed a bug where the summary would not be visible.
=> Add some tweaks to the thumbnail

apps/zotonic_core/src/models/m_identity.erl
No functional changes - only better docs and clearer specs.
=> core: add more comments and specs for m_identity

apps/zotonic_mod_admin/priv/templates/_admin_edit_main_parts.tpl, apps/zotonic_mod_survey/priv/templates/_admin_edit_main_parts.survey.tpl
This makes it possible to have variations for the panel for different categories.
=> mod_admin: use catinclude for the 'advanced' edit panel

doc/ref/filters/filter_format_duration.rst, doc/ref/filters/numbers/index.rst, doc/ref/filters/strings/index.rst, modules/mod_base/filters/filter_format_duration.erl
Add the duration filter - needed for quick edit view in admin of video resources.
=> mod_base: add duration filter

apps/zotonic_core/src/models/m_category.erl, apps/zotonic_core/src/models/m_media.erl, apps/zotonic_core/src/support/z_pivot_rsc.erl, apps/zotonic_core/src/support/z_sanitize.erl, apps/zotonic_core/src/support/z_template_compiler_runtime.erl, apps/zotonic_mod_admin/priv/templates/_action_dialog_connect_tab_find.tpl, apps/zotonic_mod_admin/priv/templates/_action_dialog_media_upload_tab_upload.tpl, apps/zotonic_mod_admin/priv/templates/_admin_menu.tpl, apps/zotonic_mod_admin/priv/templates/_admin_overview_filter_panel.tpl, apps/zotonic_mod_admin/src/actions/action_admin_dialog_media_upload.erl, apps/zotonic_mod_admin/src/controllers/controller_admin_edit.erl, apps/zotonic_mod_admin/src/mod_admin.erl, apps/zotonic_mod_admin_frontend/priv/templates/_admin_frontend_edit.tpl, apps/zotonic_mod_base/src/controllers/controller_template.erl, apps/zotonic_mod_mqtt/priv/lib/js/modules/z.live.js, apps/zotonic_mod_mqtt/src/scomps/scomp_mqtt_live.erl, apps/zotonic_mod_search/priv/templates/pivot/facet.tpl, apps/zotonic_mod_search/src/support/search_facet.erl, apps/zotonic_mod_server_storage/src/mod_server_storage.erl
Added a new facet index type 'fts' which is used for full text searches with the _fts_ sql index.
Extra `do_live` widget class for live elements without adding a `{% live ... %}` scomp.
Misc fixes, extra specs, etc.
=> Extra search facet type 'fts' and misc fixes

apps/zotonic_filewatcher/src/zotonic_filewatcher_fswatch.erl, apps/zotonic_filewatcher/src/zotonic_filewatcher_inotify.erl
This fixes an issue where the logs would be swamped when there are problems with inotify of fswatch.
=> zotonic_filewatcher: backoff inotify and fswatch on errors

apps/zotonic_core/src/db/z_db.erl, apps/zotonic_core/src/models/m_identity.erl, apps/zotonic_mod_filestore/src/models/m_filestore.erl
=> Add some specs and comments to often used z_db functions

apps/zotonic_mod_admin_frontend/priv/templates/_admin_frontend_edit.tpl
Add blocks around panels, so we can change it if needed.
=> [Frontend edit] Add blocks around panels

apps/zotonic_core/src/install/z_install_update.erl, apps/zotonic_mod_base/src/controllers/controller_api.erl
This key was missing in some 0.x installs.
=> Ensure a key on category_id exists

apps/zotonic_mod_admin_identity/priv/templates/_action_dialog_delete_username.tpl, apps/zotonic_mod_admin_identity/priv/templates/_action_dialog_set_username_password.tpl, apps/zotonic_mod_admin_identity/priv/templates/_admin_edit_basics_user.tpl, apps/zotonic_mod_admin_identity/priv/templates/admin_users.tpl, apps/zotonic_mod_auth2fa/priv/templates/_admin_user_info.tpl
=> mod_admin_identity: show 2FA status on users overview page.

apps/zotonic_mod_base/priv/lib/js/modules/z.forminit.js
Has bearing on #3305 but resolves TODO in z.forminit.js in zotonic_mod_base
Add support for multiple options in select elements in mod_base, z.forminit.js
=> mod_base: Add support for multiple options in select element

apps/zotonic_core/src/install/z_install.erl, apps/zotonic_core/src/models/m_rsc_gone.erl, apps/zotonic_core/src/models/m_rsc_import.erl, apps/zotonic_mod_admin/priv/templates/admin_status.tpl, apps/zotonic_mod_admin/src/actions/action_admin_admin_tasks.erl
Sometimes we see that in copying databases the triggers are not correctly installed.
Reinstalling the datamodel will fix such problems.
=> mod_admin: add option to reinstall zotonic datamodel to admin/status

modules/mod_admin/lib/css/zotonic-admin.css, modules/mod_admin/lib/less/bootstrap-overrides.less, modules/mod_admin/lib/less/dialog-new-connect.less, modules/mod_admin/lib/less/edit.less, modules/mod_admin/lib/less/image.less, modules/mod_admin/lib/less/menu.less, modules/mod_admin/lib/less/table.less, modules/mod_admin/lib/less/thumbnails.less, modules/mod_admin/lib/less/tree-list.less, modules/mod_admin/lib/less/variables.less, modules/mod_admin/lib/less/widget.less
Also ensure that the .less can be handled by newer lessc.
=> mod_admin: Fix a menu issue on Safari (0.x)

apps/zotonic_core/src/install/z_install.erl, apps/zotonic_core/src/install/z_install_update.erl
This fixes an issue where files > 2GB could not be uploaded.
=> core: allow medium file size > 2G

apps/zotonic_mod_search/src/support/search_query.erl
This PR includes support for content_group lists as search term values, to be able to search over multiple groups in one go.
=> mod_search: For content_group term, also support a list of groups

apps/zotonic_core/src/support/z_sites_manager.erl, apps/zotonic_core/src/support/z_utils.erl
=> core: add minor specs and docs for site config overrides

apps/zotonic_mod_wires/src/scomps/scomp_wires_button.erl
Fix related to https://github.com/zotonic/zotonic/pull/3786#discussion_r1647490501 comments
=> Change a year at copyright scomp_wires_button.erl

apps/zotonic_core/src/models/m_search.erl, apps/zotonic_mod_admin/priv/templates/_admin_edit_content_page_referrers.tpl
Also add more information in the referrers connection list.
=> core: fix a problem where the count query could not be called via m.search

apps/zotonic_mod_wires/priv/lib/js/apps/zotonic-wired.js
This makes it possible to write code like this:
```
<a href="#" data-onclick-topic="model/wires/post/event/hello">HELLO!</a>
{% wire name="hello" action={alert text="Hello World!"} %}
```
=> mod_wires: add 'model/wires/post/event/+name' topic to trigger named wires

apps/zotonic_core/src/models/m_rsc_import.erl, apps/zotonic_core/src/support/z_pivot_rsc_task_job.erl, apps/zotonic_core/src/support/z_sidejob.erl, apps/zotonic_core/src/zotonic_core_sup.erl, apps/zotonic_mod_development/src/mod_development.erl, apps/zotonic_mod_development/src/models/m_development.erl, apps/zotonic_mod_mailinglist/src/mod_mailinglist.erl, apps/zotonic_mod_ssl_letsencrypt/src/support/z_letsencrypt_job.erl
Add a small module to start side jobs,
Easier to call and less knowledge needed.
=> core: refactor sidejob start code

apps/zotonic_core/src/models/m_acl.erl, apps/zotonic_core/src/support/z_acl.erl, apps/zotonic_mod_admin/priv/templates/_action_dialog_connect_tab_find.tpl, apps/zotonic_mod_admin/priv/templates/_action_dialog_connect_tab_find_results.tpl, apps/zotonic_mod_admin/priv/templates/_action_dialog_connect_tab_find_results_loop.tpl
This fixes an issue where in the connect dialog resources were shown that the user was not allowed to connect to.
=> mod_admin: filter connect dialog results using the ACL

modules/mod_admin/support/z_admin_refers.erl
This fixes a problem where finding all embedded ids could crash on a property value that is a map.
=> mod_admin: fix a problem with refers tracking and embedded maps

apps/zotonic_mod_survey/priv/templates/blocks/_admin_edit_block_li_survey_button.tpl
Adds a preview so users know which type of button they choose.
=> Mod_survey: Add a preview of the button

apps/zotonic_mod_survey/priv/templates/blocks/_admin_edit_block_li_survey_button.tpl
Reverts zotonic/zotonic#3824
The included template is missing.
=> Revert "Mod_survey: Add a preview of the button"

apps/zotonic_mod_admin/src/actions/action_admin_dialog_media_upload.erl
This adds support for the `stay` parameter in media upload dialogs.
The reason for this MR is for retro-compatibility, as this parameter was available in the old Zotonic-0.x version of `action_admin_dialog_media_upload`.
=> Support the stay parameter in media upload dialog

apps/zotonic_core/src/support/z_context.erl
Allow
* mediastream for media
* blob for webworker
=> core: default csp for webworker and mediastream

apps/zotonic_mod_editor_tinymce/src/models/m_editor_tinymce.erl
_Note: this is a fix for the latest version of Zotonic, see #3866 for the Zotonic-0.x version_
Problem: It can happen that the configured version of the editor is not available and no template can be included.
This can happen with misconfigurations but also with time: a version that used to be available can become unsupported and updating the mod_editor_tinymce would break the editor on such a website.
Solution: Make selecting the template to include more robust and default to the newest version when the configured one can't be used. Additionally, log a warning when this happens.
=> Make tinymce default to newest when the configured version is unsupported

apps/zotonic_mod_export/src/support/export_helper.erl
This prevents filenames like `filename..xlsx`
=> mod_export: prevent double dot before file extensions

modules/mod_email_status/templates/_email_status_view.tpl
Bit better layout of the email status dialog.
=> mod_email_status: move block/unblock button

apps/zotonic_mod_email_status/src/mod_email_status.erl, apps/zotonic_mod_email_status/src/models/m_email_status.erl
Also:
* improve function typing and docs for m_email_status;
* add periodic cleanup, copied from the 0.x branch.
=> mod_email_status: better block check and periodic cleanup

apps/zotonic_core/src/models/m_config.erl
Make config set default more robust against accidental overwrite of existing config values.
=> core: improve config set default

doc/ref/modules/mod_backup.rst, modules/mod_backup/mod_backup.erl, modules/mod_backup/models/m_backup_revision.erl, modules/mod_backup/templates/admin_backup.tpl, modules/mod_backup/templates/admin_backup_revision.tpl, src/install/z_install.erl, src/install/z_installer.erl, src/models/m_rsc_gone.erl, src/support/z_datetime.erl
This is a porting to Zotonic 0.x of the changes in #3546 and #3881
=> mod_backup: periodic cleanup of revisions (0.x)

apps/zotonic_core/src/install/z_install.erl, apps/zotonic_core/src/install/z_install_update.erl
Check on site startup if the identity_log table needs to be installed.
=> core: add upgrade to install the identity_log table

apps/zotonic_mod_authentication/priv/lib/js/zotonic.auth.worker.js, apps/zotonic_mod_authentication/priv/templates/sessions.tpl, apps/zotonic_mod_authentication/src/controllers/controller_authentication.erl, apps/zotonic_mod_authentication/src/mod_authentication.erl, apps/zotonic_mod_base/priv/templates/base_simple.tpl
Use a retained topic, published to by the authentication controller, for the session overview.
Adds a max ping period for session checks (15 minutes).
=> mod_authentication: update the session overview

apps/zotonic_launcher/bin/zotonic
Better feedback if the completion has been installed.
=> zotonic_launcher: better texts for bash completion install feedback

apps/zotonic_core/src/models/m_config.erl
Fix #3854
This fixes a problem where if the site title contains unicode characters, and that title is fetched using `m_config:get_value/2` then those Unicode characters are causing problems with the iolist handling because iolists can only contain byte values.
=> Fix a problem where the site title could not contain unicode characters

apps/zotonic_core/src/support/z_pivot_rsc.erl, apps/zotonic_mod_search/src/support/search_facet.erl
This ensures that new content can be found in searches before the complete database has been re-indexed.
=> On repivot, ensure newer items are pivoted/indexed first

apps/zotonic_core/src/support/z_mqtt_sessions_runtime.erl
Let the mqtt-session runtime used in zotonic return the `cotonic-routing-id`. Currently this routing id is always set by mqtt_sessions, but some client implementations (EasyMQTT) crashes when Zotonic returns the routing id as property attached to the `connack`
With this change the mqtt runtime in zotonic is responsible for returning the `cotonic-routing-id`. The `routing-id` is only passed when the properties found in the `connack` message contains a `cotonic_sid`.
=> Set the cotonic-routing-id only when a cotonic_sid is set

apps/zotonic_core/src/smtp/z_email_server.erl
This should make it easier to find the cause of email encoding errors
=> core: log an error if email encoding fails

apps/zotonic_mod_translation/priv/templates/_language_switch.tpl
Add icon options on language switch template.
=> [Translation] Add icon options on the language switch toggle

apps/zotonic_mod_export/src/support/export_encoder_json.erl
Fix #2502 
This changes the JSON export format for mod_export from a m_rsc:get/1 dump to the output of m_rsc_export. This ensures that edges are included.
Also changes the output from a map to a list. This ensures that the order of the found resources stays the same.
Fixes an issue where the `,` was not inserted between items (rows) when there was more than one exported row.
If a resource can't be exported then it is skipped in the output.
=> mod_export: fix JSON export - use m_rsc_export format

cloud-init/zotonic-cloudinit.yml
Fix included packages (changed for Ubuntu 24)
=> Adapt cloud-init for Ubuntu 24

apps/zotonic_core/src/markdown/markdown.erl, apps/zotonic_core/src/markdown/z_html2markdown.erl, apps/zotonic_core/test/z_markdown_tests.erl
Adds table support to markdown.
=> core: markdown table support

apps/zotonic_mod_zotonic_site_management/priv/templates/addsite.tpl
See discussion #3953
With thanks to @geoidesic for the clear text suggestions.
=> site_management: better explanations when adding sites

apps/zotonic_mod_base/src/filters/filter_to_integer.erl, apps/zotonic_mod_survey/priv/templates/blocks/_admin_edit_block_li_survey_short_answer.tpl, apps/zotonic_mod_survey/priv/templates/blocks/_block_view_survey_short_answer.tpl, apps/zotonic_mod_survey/priv/templates/blocks/_block_view_survey_short_answer_date.tpl
This makes it easier to enter a date.
=> mod_survey: use the date input for dates

apps/zotonic_mod_admin/priv/templates/_admin_overview_filter_panel.tpl, apps/zotonic_mod_mailinglist/priv/templates/mailinglist.tpl, apps/zotonic_mod_survey/priv/templates/blocks/_block_view_survey_category.tpl
Unlike what the name suggests, `all_bytitle` does need a pagelen.
=> admin: fix a problem where not all predicates were listed

apps/zotonic_core/src/models/m_identity.erl
This fixes the deletion of an identity through the admin interface.
=> Update db query to delete identity

apps/zotonic_mod_search/src/mod_search.erl, apps/zotonic_mod_search/src/support/search_query.erl
Defaults to the returned search ranking.
=> mod_search: add optional sort term to autocomplete search

apps/zotonic_filehandler/src/zotonic_filehandler_mappers.erl, docker/Dockerfile.dev
Update docker images for easier dev work
=> docker: use otp27 add sassc

apps/zotonic_core/src/support/z_config.erl, docker/zotonic-docker.config
Fix a problem where the fallback for some db configs was not done.
=> core: fix fallback for db configs

apps/zotonic_core/src/support/z_crypto.erl
Do not echo the whole payload, cleaning up logs.
=> core: cleanup z_crypto:depickle errors

apps/zotonic_mod_cookie_consent/priv/lib-src/cookie-consent.scss, apps/zotonic_mod_cookie_consent/priv/lib/css/cookie-consent.css, apps/zotonic_mod_cookie_consent/priv/templates/_cookie_consent.tpl
Add a _Reject All_ button for quick reject of non-functional cookies.
=> mod_cookie_consent: add 'reject all' button

apps/zotonic_mod_auth2fa/priv/templates/admin_auth2fa_config.tpl
This changes the admin configuration page for `zotonic_mod_auth2fa` to allow picking different options per Usergroup (as opposed to only "force", which was already available).
=> Allow picking different 2FA options per User Group

apps/zotonic_mod_acl_user_groups/src/mod_acl_user_groups.erl, apps/zotonic_mod_admin/src/mod_admin.erl
Start of spec'ing all observers.
=> Add some observer specs

apps/zotonic_listen_http/src/zotonic_listen_http_metrics.erl
Adds the query string to the log request, so it is possible to include it in access log metrics.
=> core: Add qs to the log request

apps/zotonic_core/src/i18n/z_trans.erl, apps/zotonic_mod_l10n/src/support/l10n_date.erl
This fixes a problem in the translation of date parts, like days and month names.
=> Fix a problem where days were not translated

apps/zotonic_core/src/models/m_identity.erl
Function to check is what is entered as username does match with a local user.
Either by username or email address.
=> core: add m_identity:is_username_local/2

apps/zotonic_core/src/markdown/z_html2markdown.erl, apps/zotonic_core/src/models/m_rsc.erl, apps/zotonic_core/src/models/m_site.erl, apps/zotonic_core/src/support/z_model.erl, apps/zotonic_mod_backup/src/mod_backup.erl, apps/zotonic_mod_logging/priv/templates/_admin_log_email_row.tpl, apps/zotonic_mod_logging/src/mod_logging.erl, apps/zotonic_mod_oauth2/src/models/m_oauth2_consumer.erl, apps/zotonic_mod_survey/priv/templates/blocks/_block_view_survey_thurstone.tpl
Small fixes and changes, as discovered during development.
=> Misc fixes March 2025

apps/zotonic_core/src/support/z_expression.erl, apps/zotonic_core/src/support/z_module_indexer.erl
This makes it possible to check if filters exist.
=> core: add filters to the module index

apps/zotonic_mod_export/priv/templates/_vevent.tpl
This will fix the ics file so importing works again.
=> Fix vevent issue

apps/zotonic_core/src/smtp/z_email_server.erl, apps/zotonic_mod_email_status/src/models/m_email_status.erl
Fixes #4085
Recognize spamcop blocking list errors. Retry the email after 12 hours.
=> core: retry messages blocked by spamcop after 12 hours.

apps/zotonic_core/src/db/z_db.erl, apps/zotonic_core/src/models/m_search.erl, apps/zotonic_mod_search/src/mod_search.erl, apps/zotonic_mod_search/src/support/search_facet.erl, apps/zotonic_mod_search/src/support/search_query.erl, doc/developer-guide/search.rst
Fix #4104
Fixes some rough edges in the facet search code.
=> Fix some rough facet search edges.

apps/zotonic_mod_export/src/controllers/controller_export.erl, apps/zotonic_mod_export/src/controllers/controller_export_resource.erl
Removed acl checks, this should be done in the helper.
=> Mod_export: remove acl checks

apps/zotonic_mod_seo/src/support/seo_jsonld_webpage.erl
Google complains loudly about empty names in the breadcrumbs, so force the presence of _some_ name (aka title).
First take one of the non-empty languages.
If still no title, then take the translation of "Untitled".
=> mod_seo: Fix an issue where the SEO JSON-LD could have an empty name in the breadcrumbs

apps/zotonic_core/src/models/m_rsc_update.erl
If no timezone is specified with a rsc insert or update, then use the context's timezone.
=> core: use the context tz as fallback when inserting resources

src/i18n/z_gettext_compile.erl
This makes diffs of pot files generated on different machines smaller.
=> core: shorten the paths in the generated pot files (0.x)

modules/mod_admin/controllers/controller_admin_edit.erl, modules/mod_admin/templates/_admin_edit_content_advanced.tpl, modules/mod_base/controllers/controller_page.erl, modules/mod_base/validators/validator_base_page_path_unique.erl, modules/mod_translation/models/m_translation.erl, src/install/z_install.erl, src/install/z_installer.erl, src/models/m_rsc.erl, src/models/m_rsc_gone.erl, src/models/m_rsc_update.erl, src/models/tests/m_rsc_db_tests.erl, src/support/z_pivot_rsc.erl
Copy (and adapt) the translatable page paths from the 1.x (master) branch to 0.x
=> Make page_path translatable (0.x)

apps/zotonic_mod_menu/priv/templates/_menu_edit_scripts.tpl
Make the selector more specific - remove any _danger_ or other texts.
Also make the selectors for finding the `data-page-id` less specific.
=> mod_menu: fix an issue where the title could not be found for the menu remove dialog

apps/zotonic_mod_ssl_letsencrypt/src/support/z_letsencrypt.erl
The timeout of 15 seconds on LE requests is sometimes too short. Up it to 60 seconds, also make it a `-define` for easier adjustment in the future.
=> mod_ssl_letsencrypt: higher timeout on LE requests

apps/zotonic_core/src/models/m_rsc.erl, apps/zotonic_core/src/support/z_expression.erl, apps/zotonic_mod_admin/priv/lib-src/zotonic-admin/scss/_base.scss, apps/zotonic_mod_admin/priv/lib/css/zotonic-admin.css, apps/zotonic_mod_admin/priv/templates/_admin_edit_content.query.tpl, apps/zotonic_mod_export/priv/templates/_admin_edit_sidebar.tpl, apps/zotonic_mod_export/src/mod_export.erl, apps/zotonic_mod_export/src/support/export_encoder.erl, apps/zotonic_mod_export/src/support/export_encoder_csv.erl, apps/zotonic_mod_export/src/support/export_encoder_json.erl, apps/zotonic_mod_export/src/support/export_encoder_xlsx.erl, apps/zotonic_mod_export/src/support/export_helper.erl, apps/zotonic_mod_export/src/support/export_value.erl
Adds admin option to edit the fields to be exported.
These fields can be expressions, enabling model and filter data to be exported.
=> mod_export: editable export columns with value expressions

modules/mod_admin/templates/_admin_translation_tabs.tpl, modules/mod_translation/mod_translation.erl, modules/mod_translation/models/m_translation.erl, src/i18n/z_trans.erl
Also accept language codes like `pap-aw`
=> Accept country and region codes for iso639-2 three letter languages

apps/zotonic_core/src/i18n/z_language_data.erl
This adds Papiamento and Papiamentu to the language data.
On different islands people use different dialects, the most important are added.
=> Add Papiamento to the language data

apps/zotonic_core/src/behaviours/zotonic_observer.erl
Add missing notification to behaviour file.
=> core: add behaviour for email_is_recipient_ok notification.

apps/zotonic_core/src/markdown/markdown.erl
Markdown code blocks containing other (HTML) code would not have their contents properly escaped.
This is fixed by moving the backtick-code blocks to a higher level of the parser, so that it will properly contain any other markup.
=> core: fix an issue with markdown code blocks

.github/copilot-instructions.md
This is according to the information on https://docs.github.com/en/copilot/how-tos/configure-custom-instructions/add-repository-instructions
We should modify and extend this text as needed.
=> Add draft version of Copilot instructions

apps/zotonic_core/src/support/z_utils.erl, apps/zotonic_core/test/z_utils_tests.erl, apps/zotonic_mod_base/src/filters/filter_group_by.erl
=> 4212 z utilsgroup by2 should also work on lists with maps
